### ISSUE TITLE
Conda badges

### ISSUE THREAD

**Issue by epruesse** [badges/shields#1000]
It would be neat to have badges (version, downloads, platforms) for packages available through the [conda](https://conda.io) channels, e.g. [bioconda](https://github.com/bioconda) or [conda-forge](https://github.com/conda-forge).

**Comment by paulmelnikow** [comment]
Thanks! Seems to be closed via #1001. If there's more to do, please open a new issue.

**Comment by epruesse** [comment]
@paulmelnikow Yes, it's fixed. Thanks!

Do I need to open issue for fixes/updates, or does a PR suffice? (May want to add 2-3 logos for the major channels to be displayed optionally to make platform/downloads badges more informative without becoming a mile wide)

**Comment by paulmelnikow** [comment]
Sometimes it's helpful to open an issue first, since once something is implemented it can be hard to discuss unemotionally. 😁  In general though, there's no need to open an issue first.

In terms of logos, we don't have a great way to optionally display them, though I'm hoping to add a better way in addressing #983. If you want to tackle that I'd be all for it, though I'd want to do that in a way that's global, rather than specific to a badge.
