### ISSUE TITLE
Chocolatey not found?

### ISSUE THREAD

**Issue by lin-ycv** [badges/shields#10045]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

seems unable to get information on chocolately packages

### 🔗 Link to the badge

https://img.shields.io/chocolatey/v/adobereader
https://img.shields.io/chocolatey/v/googlechrome
...etc

**Comment by chris48s** [comment]
Looks like all our requests to the chocolatey API are now returning zero results.

My guess would be that this is related to
https://github.com/chocolatey/choco/issues/3406
but I've not really looked into it.

We've been told before (in response to a previous issue - see https://github.com/badges/shields/issues/7931 and https://github.com/chocolatey/home/issues/159 ) that our use of the Chocolatey is unsupported and they may break/change it at any time.

Accepting that is our starting point: If someone can find a way to patch this up, I think we could review a PR to get this working again. Otherwise, it might be time to remove these badges.

Based on past experience, we will get zero help from the upstream on this one.

**Comment by jcs090218** [comment]
Same issue in my repo, see https://github.com/emacs-eask/packaging?tab=readme-ov-file#-chocolatey. (For record)
