### ISSUE TITLE
404 Badge Not Found

### ISSUE THREAD

**Issue by 0xSynapse** [badges/shields#10220]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Trying to make a custom logo badge for my [logo](https://drive.google.com/file/d/1j5XAef_OEJ09ZufRvJesIgmvxBP6SA-N/view?usp=sharing)

But it shows --

**404 Badge Not Found**

I have taken help from [this](https://medium.com/@perezlino/how-to-make-custom-logos-for-badges-using-shields-io-893a81129d8b) article.

Please help :)

### 🔗 Link to the badge

https://img.shields.io/badge/Blog?logo=data%253Aimage%252Fpng%253Bbase64%252CiVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D%252BPAAAALVBMVEX%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F6%252Bfn6%252Bvq3y%252BJ8rOFSne9Jm%252FQcOlr5DJ7GAAAAB3RSTlMAB2LM94H1yMxlvwAAADNJREFUCFtjZGAEAob%252FQMDIyAJl%252FmFkYmEGM%252F%252F%252BYWRmYWYCMv8BmSxYmUgKkLQhGYawAgApySgfFDPqowAAAABJRU5ErkJggg%253D%253D

**Comment by chris48s** [comment]
You're getting a 404 because `/badge/Blog` doesn't match any route. You'd need to supply at least a colour e.g:

![](https://img.shields.io/badge/Blog-blue?logo=data%253Aimage%252Fpng%253Bbase64%252CiVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D%252BPAAAALVBMVEX%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F6%252Bfn6%252Bvq3y%252BJ8rOFSne9Jm%252FQcOlr5DJ7GAAAAB3RSTlMAB2LM94H1yMxlvwAAADNJREFUCFtjZGAEAob%252FQMDIyAJl%252FmFkYmEGM%252F%252F%252BYWRmYWYCMv8BmSxYmUgKkLQhGYawAgApySgfFDPqowAAAABJRU5ErkJggg%253D%253D) - https://img.shields.io/badge/Blog-blue?logo=data%253Aimage%252Fpng%253Bbase64%252CiVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D%252BPAAAALVBMVEX%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F%252F6%252Bfn6%252Bvq3y%252BJ8rOFSne9Jm%252FQcOlr5DJ7GAAAAB3RSTlMAB2LM94H1yMxlvwAAADNJREFUCFtjZGAEAob%252FQMDIyAJl%252FmFkYmEGM%252F%252F%252BYWRmYWYCMv8BmSxYmUgKkLQhGYawAgApySgfFDPqowAAAABJRU5ErkJggg%253D%253D

also, your logo param seems to be double URL-encoded. I think what you're trying to do is:


![](
https://img.shields.io/badge/Blog-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D+PAAAALVBMVEX////////////////////////////////6+fn6+vq3y+J8rOFSne9Jm/QcOlr5DJ7GAAAAB3RSTlMAB2LM94H1yMxlvwAAADNJREFUCFtjZGAEAob/QMDIyAJl/mFkYmEGM//+YWRmYWYCMv8BmSxYmUgKkLQhGYawAgApySgfFDPqowAAAABJRU5ErkJggg==) - https://img.shields.io/badge/Blog-blue?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D+PAAAALVBMVEX////////////////////////////////6+fn6+vq3y+J8rOFSne9Jm/QcOlr5DJ7GAAAAB3RSTlMAB2LM94H1yMxlvwAAADNJREFUCFtjZGAEAob/QMDIyAJl/mFkYmEGM//+YWRmYWYCMv8BmSxYmUgKkLQhGYawAgApySgfFDPqowAAAABJRU5ErkJggg==

I have not read the medium article you posted so I can't really comment on whether it is right or not, but the docs on our own site cover this stuff:

- https://shields.io/badges/static-badge
- https://shields.io/docs/logos

**Comment by 0xSynapse** [comment]
thanks!!
