### ISSUE TITLE
Badge Request: Homebrew Cask Installs

### ISSUE THREAD

**Issue by MichaelHinrichs** [badges/shields#10288]
### 📋 Description

formulae.brew 
downloads|69k

### 🔗 Data

https://formulae.brew.sh/docs/api/

### 🎤 Motivation

Simple-icons assessing popularity rule 4.
https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#assessing-popularity

This badge would streamline pull requests for the simple icons project.

**Comment by MichaelHinrichs** [comment]
New problem: it doesn't work.
![homebrew downloads](https://img.shields.io/homebrew/installs/dm/freetube?logo=homebrew)
`https://img.shields.io/homebrew/installs/dm/freetube?logo=homebrew`

**Comment by chris48s** [comment]
I think you've just picked an example where the project is dead. The badge itself does work e.g:

![](https://img.shields.io/homebrew/installs/dm/cake) - https://img.shields.io/homebrew/installs/dm/cake

**Comment by MichaelHinrichs** [comment]
But it's right here. https://formulae.brew.sh/cask/freetube

**Comment by chris48s** [comment]
I don't use macs so I don't really know what I'm talking about here (someone who uses a mac, please save me) but.. it seems like there are 2 types of homebrew package:

- fomulas
- casks

Not 100% sure why/what the difference is.

![](https://img.shields.io/homebrew/installs/dm/freetube) https://img.shields.io/homebrew/installs/dm/freetube is not found because `freetube` is the name of a cask, not a formula.

We have got

- version badge for homebrew fomulas: https://shields.io/badges/homebrew-version
- downloads badge for homebrew formulas: https://shields.io/badges/homebrew-downloads
- version badge for homebrew cask: https://shields.io/badges/homebrew-cask

So the request here is for a **Homebrew Cask Installs** badge. We should also rename the titles of the existing 3 docs pages for clarity. It looks like the cask manifest does contain install stats for the last 30, 90 and 365 days e.g: https://formulae.brew.sh/api/cask/freetube.json

**Comment by chris48s** [comment]
https://github.com/badges/shields/pull/10595
