### ISSUE TITLE
NPM Download by tag

### ISSUE THREAD

**Issue by shinokada** [badges/shields#10644]
:clipboard: **Description**

I'd like to show NPM downloads by tag. 

```
// to show latest download
https://img.shields.io/npm/dw/flowbite-svelte-icons@latest
// to show @v1-latest download
https://img.shields.io/npm/dw/flowbite-svelte-icons@v1-latest
```

**Comment by chris48s** [comment]
The reason we don't do this for the npm downloads badge is because there isn't an API endpoint that exposes it.
We can call https://api.npmjs.org/downloads/point/last-week/flowbite-svelte-icons to get downloads for the package (which is what we do) but AFAIK there's no API call we can make to get downloads for a dist-tag.

**Comment by shinokada** [comment]
Thank you for your reply.
