### ISSUE TITLE
Badges don't show on Gitflic

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [badges/shields#10763]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Badges don't show when added into readme on gitflic.ru (Russian Github clone). From dev tools:

> GET https://img.shields.io/nuget/v/CilTools.BytecodeAnalysis  
> net::ERR_TIMED_OUT

The same badge works fine on Github. Previously badges were working for non-github repositories. Are they blocked now?

### 🔗 Link to the badge

https://img.shields.io/nuget/v/CilTools.BytecodeAnalysis

**Comment by chris48s** [comment]
We have not explicitly done anything to block traffic from gitflic. Tbh, I've never even heard of it until now.

If you're seeing

```
GET https://img.shields.io/nuget/v/CilTools.BytecodeAnalysis
net::ERR_TIMED_OUT
```

in your browser dev tools, that implies that it is your browser which is failing to fetch https://img.shields.io/nuget/v/CilTools.BytecodeAnalysis directly, rather than anything to do with the site where it is embedded. When you view badges on GitHub it is actually served through GitHub's image proxy, not from shields.io.

If you just try to visit https://img.shields.io/nuget/v/CilTools.BytecodeAnalysis directly in a browser (so completely independent of being embedded in a README on github or gitflic), do you see the image or get a timeout?

**Comment by MSDN-WhiteKnight** [comment]
It works now both in browser and on Gitflic. Looks like there was network issue that prevented badges from loading. On Github they are working more reliably exactly due to image proxy.
