### ISSUE TITLE
link query parameter for non social styles

### ISSUE THREAD

**Issue by alexanderrichards** [badges/shields#1079]
Hi, I've noticed that the link query parameter `?link=` only works for the social style `?style=social`. Is this an intended feature as it would be very useful to be able to have the regular looking shields act as a link?

**Comment by alexanderrichards** [comment]
Sorry, I should have provided examples of what I tried. Please see the examples below:

So the following social badge works as expected with a link on the left hand side.
[https://img.shields.io/badge/Test-OK-green.svg?style=social&link=https://www.google.com](https://img.shields.io/badge/Test-OK-green.svg?style=social&link=https://www.google.com)

However, the default style does not.
[https://img.shields.io/badge/Test-OK-green.svg?link=https://www.google.com](https://img.shields.io/badge/Test-OK-green.svg?link=https://www.google.com)

Indeed even if I include the style query parameter with a style other than social it doesn't work
[https://img.shields.io/badge/Test-OK-green.svg?style=flat&link=https://www.google.com](https://img.shields.io/badge/Test-OK-green.svg?style=flat&link=https://www.google.com)

It's true that the left/right definition of where the user clicks is not as well defined for the non-social badge styles however even the ability to specify a single link covering the entire bagde face would be useful.

**Comment by paulmelnikow** [comment]
Hi, thanks for those references. Seems to me that is probably a bug!

**Comment by paulmelnikow** [comment]
There's an old PR #598 that's addressing this.

**Comment by alexanderrichards** [comment]
Thanks for pointing me to that PR. It seems it has been open some time (it was first opened on 12 Dec 2015). Is there an ETA for this feature?

**Comment by paulmelnikow** [comment]
There are still quite a few PRs in the backlog, though we're getting much closer to clearing it.

I'm not able to review this without digging in a bit to the badge-template part of this project, an area I haven't learned too much about. Though, if you or someone would like to get it rebased and tested a bit, that would get the process started, and hopefully either @espadrine or I can take a look.

Since we stopped using SVGo and Google hopefully has fixed that bug, it seems like the old concerns no longer apply…

**Comment by espadrine** [comment]
Sadly, Google Chrome's SVG handling is still [broken](https://bugs.chromium.org/p/chromium/issues/detail?id=352912).

Shields.io started out in the pre-retina world where SVGs were not as prevalent, and we have hit dozens of bugs in various browsers, which we have carefully reported along the years.

As for SVGo, the change we made is that the SVGo transformation is performed during compilation (ie. when compiling the templates to JS functions) instead of at runtime (for every request). So we still hit the issue.

I have a rebased branch [here](https://github.com/espadrine/shields/tree/link) in case you have an idea.

**Comment by alexanderrichards** [comment]
Thanks for all your efforts on this. Can I ask when this feature will be deployed?

**Comment by paulmelnikow** [comment]
Sorry, I'm not sure. It's usually within 1–3 weeks. Thaddée is the only one with access, though we're aiming to add me sometime next month. You can monitor [the gh-pages branch](https://github.com/badges/shields/tree/gh-pages) which will update when it happens.
