### ISSUE TITLE
Bower badge shows void instead of alpha

### ISSUE THREAD

**Issue by limonte** [badges/shields#1098]
![](https://img.shields.io/bower/v/vaadin-checkbox.svg)

Actual result: `"void"`
Expected result: `"v1.0.0-alpha7"`

There's the `v1.0.0-alpha7` tag: https://github.com/vaadin/vaadin-checkbox/releases/tag/v1.0.0-alpha7

**Comment by ritwickdey** [comment]
Hi, this is for your package on pre-release version. (not stable version).

I've made a PR #1099 on it. 
You can access it through `/bower/vpre/vaadin-checkbox.svg`  (BTW, on Bower, it is `"v1.0.0-alpha6"`).
<br>
![image](https://user-images.githubusercontent.com/18099464/30875670-deb81eac-a311-11e7-9596-87dd7f316471.png)


<br><br><br>
![image](https://user-images.githubusercontent.com/18099464/30875382-f61ee8ce-a310-11e7-90a1-c21ba87b30f3.png)

**Comment by paulmelnikow** [comment]
Seems like there is also a usability issue here. Instead of displaying **void** when there are no releases, we should display something more user-friendly, like **no releases**. @ritwickdey Maybe you could test that case in your pull request, possibly using a mocked server response, and add a fix.

**Comment by ritwickdey** [comment]
Hi @paulmelnikow , I've made changes & added 9 tests (including for invalid packages). But Is it possible to test for this **'no releases'** label ? beacuse if I test it from any real package, soon or later that package may get official release. That time, it test will be failed.

**Comment by paulmelnikow** [comment]
The way to accomplish that is using the `intercept()` method in your test. It lets you intercept the request that would be made to the server, and provide a fake response. Then the test doesn't hit the server at all! It's not perfect, since the fake response can get out of skew with what the real server would return, though it helps you test that your code is working as intended. There's some commentary in the [service test readme](https://github.com/badges/shields/blob/master/service-tests/README.md) and a working example in [the cran tests](https://github.com/badges/shields/blob/master/service-tests/cran.js#L41-L46).

**Comment by ritwickdey** [comment]
Added 😄
