### ISSUE TITLE
Shield not displayed if repository contains "-"

### ISSUE THREAD

**Issue by offa** [badges/shields#1131]
I have a repository which contains a `-` in the path. Unfortunately this prevents shields from being displayed on Github.

### Example

Eg. following markdown from [shields.io](http://shields.io/) is not shown:

```
[![GitHub issues](https://img.shields.io/github/issues/offa/scope-guard.svg)](https://github.com/offa/scope-guard/issues)
```

Same happens for release or Travis shield. Replacing `-` with `--` has no effect. So this wont work either:

```
[![GitHub release](https://img.shields.io/github/release/offa/scope--guard.svg)](https://github.com/offa/scope-guard/releases)
```

Is there a way to get this working?

**Comment by paulmelnikow** [comment]
This is what I'm seeing:

https://img.shields.io/github/issues/offa/scope-guard.svg

<img width="115" alt="screen shot 2017-10-04 at 3 02 55 pm" src="https://user-images.githubusercontent.com/1487036/31194448-34626bb0-a915-11e7-86ce-989d07730930.png">

So I suspect this is an intermittent problem with the Github badge, due to Shields not having enough tokens for our API usage. Or possibly it could be due to #1119.

You can contribute some of your API quota to Shields, or ask other people interested in your project to do the same: https://img.shields.io/github-auth

It's also possible it was recently fixed and the busted image is cached on your machine, though usually with errors like this you'll see the wrong badge, not no badge, and if this is the first time you've tried to make the badge, it wouldn't be in your cache.

**Comment by offa** [comment]
If I open the url in the Browser I can see it too. However from Markdown it's not shown. The [Readme](https://github.com/offa/scope-guard/blob/master/README.md) should show 4 Shields, but I see only 2. I checked on another system and asked someone, both times all 4 are shown. Seem related to my system. I'll clean my browser and test again.

So from a general perspective, this should work (And I don't need the `--` for build / release)?

**Comment by paulmelnikow** [comment]
Yea, this markdown is working fine.

```md
[![GitHub issues](https://img.shields.io/github/issues/offa/scope-guard.svg)](https://github.com/offa/scope-guard/issues)
```

```md
[![GitHub release](https://img.shields.io/github/release/offa/scope-guard.svg)](https://github.com/offa/scope-guard/releases)
```

 I'm seeing four badges in your readme too.

**Comment by offa** [comment]
Finally figured out what caused the problem: The _UBlock_ plugin filtered those two. But only on this system (others with same settings work fine) and only on this project, all other projects, links and systems aren't affected. This also explains why it stopped working suddenly.

@paulmelnikow Thanks for having the time (and giving the final hint).
