### ISSUE TITLE
[Question] Acceptable types of badges

### ISSUE THREAD

**Issue by ice1000** [badges/shields#1169]
I know there's some repositories have something to do with music or video. I have some implementations of badges for a video website (https://www.bilibili.com) and a music site (https://music.163.com/). I wonder if you accept such kinds of badges. If so, I'll send pull request soon.

**Comment by paulmelnikow** [comment]
It's an interesting idea!

Where would a badge like this be used?

**Comment by ice1000** [comment]
Like, someone made a music generator, and he used the generator to generate a music, and uploaded it to music.163.cim, or made an introduction video on bilibili.

**Comment by ice1000** [comment]
Or some video tutorials

**Comment by ice1000** [comment]
And the badges will show the number of viewers or listeners, or other properties of the video/music.

**Comment by PyvesB** [comment]
Some interesting ideas around here! Rather then just tracking a unique song, would it be possible to track all the songs created with the generator, for instance using some sort of tag set by the author? Also, platforms such as SoundCloud have many more users and are available in a lot of languages, maybe it could benefit more Shields users?

**Comment by ice1000** [comment]
Supported:

+ Video website bilibili
    + video availability
    + danmaku count
    + share count
    + coin count
    + fav count
+ Music site netease music
    - Name of single song (DEPRECATED)
    - Name of specific album (UNDER ASSESSMENT)
    - Name of specific playlist (UNDER ASSESSMENT)
    - Comment count of single song
    - Comment count of specific album
    - Comment count of specific playlist
    - Play count of specific playlist
    - Share count of specific playlist
    - Subscribed count of specific playlist

And actually, I don't know much about SoundCloud...

**Comment by duoduoeeee** [comment]
SoundCloud has an official API. Here's the documentation

https://developers.soundcloud.com/docs/api/guide

**Comment by ice1000** [comment]
So what's your answer

> I wonder if you accept such kinds of badges.

If so, I'll close issue and soon send a pr

**Comment by paulmelnikow** [comment]
I'm on the fence. This seems like a good service to musicians, video producers, and content creators. While that can overlap with developers, it's on the fringe, and I'm not sure it makes sense to shift our focus of Shields-as-a-service from the developer community.

That said, I'm open to making the Shields codebase more modular, so that it's easy to build a shields-like service that serves a different audience while staying up to date with the main codebase. That's going to take some time, but it's underway… #1163 #948.

Forking Shields remains an option. It's easy to run on Heroku, for example, and while I know there's no Heroku in China, there must be good alternatives.

I'm also open to being convinced if there are a lot of developers that want this.

So I guess this is my answer to your question – which is a good question! Let's keep Shields.io focused on developers. Services should fall into one of these categories:
- Services which are **primarily used by developers**, like any artifact repository or CI company
- Services which are not primarily used by developers, but are **widely used by developers**, like Twitter

**Comment by ice1000** [comment]
OK. Closed.
