### ISSUE TITLE
Add server path to serve frontend

### ISSUE THREAD

**Issue by espadrine** [badges/shields#1220]
We lost a valuable production debugging tool with bde4d925f21fed2ddf87e9164e6c1ea7d3073d38.

Indeed, to determine if a problem was specific to a given server, or to put out a canari for a sensitive patch, I often deploy only with a single server (eg. `make deploy-s0`) and hit that server's frontend (eg. https://vps71670.vps.ovh.ca/try.html).

Because of the bde4d92 change, this is no longer possible, as `/try.html` no longer exists and `/` gets redirected to shields.io.
Indeed, infosite is not `/` in production (otherwise we would not be redirected to shields.io when hitting img.shields.io, which we want).

@paulmelnikow What do you think we can do?

**Comment by paulmelnikow** [comment]
Yea, that makes a lot of sense. I'll give it some thought, and either push a fix or leave a PR open for you to test.

**Comment by paulmelnikow** [comment]
I opened #1222 which I think should fix this. It creates a dev build of the frontend, which is like the old `try.html`. The badge URIs do not have hostnames nor a `maxAge` parameter. The deploy tasks will push this to the servers. I tested the output of `make website`, `npm run build`, and `npm run build:production` and they all seemed right. However I couldn't actually run the deploy tasks.

It also addresses a request you made offline, which is to enable local testing with production parity – i.e. with `maxAge`. To do that, run `npm run build:production` instead of `npm run build`. `npm run build:production` no longer puts `https://img.shields.io` in the generated frontend, so the badges will be generated by the local server.
