### ISSUE TITLE
[ReadTheDocs] Service not working

### ISSUE THREAD

**Issue by yonkornilov** [badges/shields#1224]
With #1150 , RTD was functioning up until today.

For instance, the following badge is the RTD example, but doesn't appear:

https://img.shields.io/readthedocs/pip.svg

![badge](https://img.shields.io/readthedocs/pip.svg)

**Comment by paulmelnikow** [comment]
Sorry the badge stopped working. Thaddée tried to deploy 05402ef yesterday but ran into a blocking bug in #1186 (fix: #1223).

Rather than roll back to the previously deployed version, he went with an even older version before the bug that caused #1198. It would have been better to cherry pick the fix (#1201) but he's not that familiar with the recent changes so perhaps couldn't do that confidently. I sent him my public encryption keys and I'm hoping to get access to deploy soon.

**Comment by paulmelnikow** [comment]
Thaddée deployed latest to production. Should be back up!

**Comment by yonkornilov** [comment]
Works, thanks!
