### ISSUE TITLE
"GitHub OAuth authentication failed to provide a code" when adding token

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#1243]
This is a recurrence of #1038 reported [here](https://github.com/badges/shields/issues/1038#issuecomment-341426222).

**Comment by paulmelnikow** [comment]
Possible causes: #1142 #1117 #1195 #1186 #1118.

I'll see if I can do some local testing.

**Comment by paulmelnikow** [comment]
It's #1118. Basically a merge conflict.

This line went out:

```
const baseUrl = process.env.BASE_URL || 'https://img.shields.io';
```

And this one went in:

```
const baseUrl = process.env.BASE_URL || 'https://shields.io';
```

**Comment by paulmelnikow** [comment]
Leaving open until deployed.

**Comment by tooomm** [comment]
I hope you get deploy access sooner than later.

**Comment by paulmelnikow** [comment]
Same. Thaddée gave me push access this week. It's not working yet – the server isn't accepting my SSH key. Deploy access would have helped in this case, where the fix was obvious.

He's also working this week on building a log drain I can connect to, which will make push access a lot more useful, because I'll be able to debug crashes and add logging output.

Giving me access is complicated because the hosting account (and maybe the servers as well?) are shared with other services he runs.

**Comment by waja** [comment]
> I hope you get deploy access sooner than later.

@tooomm I hope you are not building your business process on top of this project!

**Comment by tooomm** [comment]
For sure not! @waja :D
But there were a lot of mistakes and issues lately (besides all the great improvements).
Which most of them could have been solved with a simple re-deploy since the debug and fixes were there pretty fast. But he could just not do it himself.

Since @paulmelnikow is more or less the only active member right now, it would just help a lot.
Too bad the circumstances he described above makes it not as easy.

**Comment by paulmelnikow** [comment]
The fix is deployed. Could someone confirm it's fixed?
