### ISSUE TITLE
style examples not on point

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1264]
I realized this little confusion while trying to use a squared badge.
I typed `flat-squared` like it's written on the example badge... realized after several tries that the actual working URL extension is only `flat-square`
![flat-square](https://user-images.githubusercontent.com/9874850/32658941-9950361e-c61c-11e7-8784-ab19e0e3cfca.png)

All other examples and their label text in the badge match the correct parameters.

**Comment by paulmelnikow** [comment]
Hey @tooomm I know you're not a coder, and know that I really appreciate your catching and carefully reporting things like this!

Could open a PR for this? Since you have a fork you can edit `all-badge-examples.js` in the GitHub UI and it'll create a new branch in your fork and open a pull request for you.

https://github.com/badges/shields/edit/master/lib/all-badge-examples.js

Relative to the number of knowledgeable and active maintainers, there's a massive amount of change in this project. These small things really help!

**Comment by tooomm** [comment]
Are your sure it's `all-badge-examples.js` file?

To me it looks like here:
https://github.com/badges/shields/blob/master/frontend/fragments/try-footer.html#L89-L90

**Comment by paulmelnikow** [comment]
You're right, this one's not a badge example.

We can't change the parameter without breaking everyone's usage, so we just want to change the logo to match the parameter that works.

**Comment by tooomm** [comment]
>We can't change the parameter without breaking everyone's usage, so we just want to change the logo to match the parameter that works.

Exactly. Logo change is what I had in mind. https://github.com/badges/shields/pull/1265
