### ISSUE TITLE
Visual Studio Marketplace version badge should be blue like all the other version badges

### ISSUE THREAD

**Issue by felixfbecker** [badges/shields#1283]
A version does not have a "success" or "broken" state like builds, it is informational, like licenses. The only other state it can have is in v0.x.x or prereleases, it can be orange as a warning that it is unstable - but it will never be "broken" or "successful".

All version badges follow this pattern:

[![npm](https://img.shields.io/npm/v/npm.svg)]()
[![GitHub package version](https://img.shields.io/github/package-json/v/badges/shields.svg)]()
[![Maven Central](https://img.shields.io/maven-central/v/org.apache.maven/apache-maven.svg)]()
[![GitHub release](https://img.shields.io/github/release/qubyte/rubidium.svg)]()
[![NuGet](https://img.shields.io/nuget/v/Nuget.Core.svg)]()
[![PowerShell Gallery](https://img.shields.io/powershellgallery/v/Pester.svg)]()
[![Eclipse Marketplace](https://img.shields.io/eclipse-marketplace/v/notepad4e.svg)]()

Except vs marketplace:

[![Visual Studio Marketplace](https://img.shields.io/vscode-marketplace/v/ritwickdey.LiveServer.svg)]()

**Comment by paulmelnikow** [comment]
Agreed. These should be blue.

A bunch of the version badges were touched in #1246 which is pending deploy, though the problem is still observed in current master on the staging server. (The font width is off because we don't have the right font installed in staging.)

https://shields-staging.herokuapp.com/vscode-marketplace/v/ritwickdey.LiveServer.svg
![](https://shields-staging.herokuapp.com/vscode-marketplace/v/ritwickdey.LiveServer.svg)

A pull request is welcome!
