### ISSUE TITLE
Code Climate's 100% coverage shows red

### ISSUE THREAD

**Issue by jimmerioles** [badges/shields#1329]
I noticed Code Climate's coverage shows red even if i got 100% coverage, is this expected behavior? shouldn't it be green?

![image](https://user-images.githubusercontent.com/9766310/33609020-7188f532-da01-11e7-993a-c5fb3bac7d29.png)

**Comment by PyvesB** [comment]
Thanks for your report, I'll look into it. :wink:

**Comment by PyvesB** [comment]
The code in shields basically constructs the code coverage badge shown in your screenshot by retrieving the headers from Code Climate's own badges, in your case [this one](https://api.codeclimate.com/v1/badges/438413be3c404775866c/test_coverage). 

The information displayed by Code Climate seems to have changed recently, switching from showing a **score** (`A` for instance) to a **percentage** (`100%` for instance). Your badge would have previously shown as this: ![CodeClimate](https://img.shields.io/badge/coverage-A-brightgreen.svg)

Good news is that the service tests picked this up, and one test is now failing.

I am unsure how to approach this problem. As far as I can tell, most of their APIs seem to require authentication (see the [documentation](https://developer.codeclimate.com/#test-coverage)). We do seem to be able to publicly access `https://api.codeclimate.com/v1/repos?github_slug=XXX`. shields retrieves the `badge_token` from that endpoint, and uses it to fire off a second request to retrieve Code Climate's badges headers. I don't think we would be able to use the proper [test reports](https://developer.codeclimate.com/#test-coverage) endpoint to directly get the code coverage score without providing an authentication token. Now that the code coverage score is no longer retrievable, the only simple way to get our badge to display a score rather than a percentage might be to reproduce the percentage -> score mapping on our side, which is not ideal.

**Comment by paulmelnikow** [comment]
Does the work in #1236 shed any light on this?

**Comment by PyvesB** [comment]
Well the initial pull request comment is in line with my analysis above regarding the first API request and subsequent badge information retrieval, so at least we all agree on what the code was previously supposed to do. ^^

Unfortunately one of the two badges added by that pull request are no longer working as expected as a consequence of a recent Code Climate change and we have to come up with a different approach to retrieve the now missing information.

**Comment by paulmelnikow** [comment]
#1368 has been merged. Should this be closed?

**Comment by RedSparr0w** [comment]
It partially closes this,
`/c/user/repo.svg` will now show your score as `A-F`: ![](https://img.shields.io/badge/coverage-A-brightgreen.svg)
`/coverage/user/repo.svg` is still broken and shows ![](https://img.shields.io/badge/coverage-not%20found-lightgrey.svg) 
But _(i think)_ expected output is ![](https://img.shields.io/badge/coverage-100%25-brightgreen.svg) for `/coverage`

Not sure if `/coverage` is going to end up with the same output as `/c` or a percentage.

**Comment by PyvesB** [comment]
I believe this issue can be closed, as #1387 is now merged. 😉
