### ISSUE TITLE
Are you have any example of Dynamic badge?

### ISSUE THREAD

**Issue by kamontat** [badges/shields#1370]
I have found that <shield.io> has dynamic badge, but I don't know how to use it.

**Comment by MartinGonzalez** [comment]
I would like to know it too.
I'm trying to add a version badge, and the version is inside a .json.

**Comment by tooomm** [comment]
I highly advice you to read the PR implementing this feature (https://github.com/badges/shields/pull/820), it helped me to understand it.

I really think there should be a explanation and link to that *JSONpath expression evaluator*!

**Comment by MartinGonzalez** [comment]
@tooomm 

Just to understand how badges work. 
When we call for example a build pipeline using travis: `https://img.shields.io/travis/USER/REPO.svg`.
If i put my user and repo, how does it know which badge show?

A dynamic badge, when i put $.version, generates a new .svg or update someone?

Sorry about being a beginner but i would really like to learn to make my readme files more descriptive.

**Comment by tooomm** [comment]
>If i put my user and repo, how does it know which badge show?

Because of the services name (`travis`) in the link: https://img.shields.io/travis/USER/REPO.svg. :)
Other badges look like this "https://img.shields.io/appveyor/ci/USER/REPO.svg".
The travis one is the only one with this `user/repo` declaration in the example list, all others use real data there... that might confuses you and should get changed, yes.

>A dynamic badge, when i put $.version, generates a new .svg or update someone?

I don't know what you mean exactly. But a dynamic badge is a dedicated badge with its own .svg

**Comment by MartinGonzalez** [comment]
@tooomm Now i understood, it takes repository metadata. I tried with a gitlab project with it private token and worked.

Thanks!

**Comment by paulmelnikow** [comment]
Let us know if you have more questions!
