### ISSUE TITLE
Hosting own server with Docker have errors

### ISSUE THREAD

**Issue by MartinGonzalez** [badges/shields#1373]
Hi there! Amazing this service but i have a question about running shields on docker.
 I dont know if the Dockerfile its deprecated but it throws error saying that it does not have git.
After adding git in the dockerfile the image is built successfully but when i run the server the shield.io is being seen but without the badges

What did i do to make it run?
1. [x] Change npm version in dockerfile to 8.9.3-alpine
2. [x] Add git in RUN 
```
RUN apk add --no-cache gettext imagemagick librsvg ttf-dejavu git
```
3. [x] Build image
4. [x] Run image
5. [x] Enter localhost:port

Also, is not port 3000 that has to be exposed instead of 80?

Here is a log
```
[frontend] Client pings, but there's no entry for page: /discord/308323056592486420.svg
```

**Comment by MartinGonzalez** [comment]
Having this Dockerfile modified.

```
FROM node:8.9.3-alpine

RUN apk add --no-cache gettext imagemagick librsvg ttf-dejavu git
ENV FALLBACK_FONT_PATH /usr/share/fonts/ttf-dejavu/DejaVuSans.ttf

RUN mkdir -p /usr/src/app
RUN mkdir /usr/src/app/private
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY package.json /usr/src/app/
RUN npm install && \
    rm -rf /tmp/npm-* /root/.npm
COPY . /usr/src/app

CMD envsubst < secret.tpl.json > ./private/secret.json && npm start

EXPOSE 3000
```

then run

```
docker build -t shields .
```

then

```
docker run -rm -p 8080:3000 --name shields shields
```

i see the webpage like this

<img width="1390" alt="screen shot 2017-12-16 at 19 34 38" src="https://user-images.githubusercontent.com/4130008/34074974-a3a1f740-e298-11e7-901b-a1a93a72394f.png">

Any idea why?

**Comment by goozler** [comment]
Hi!

I tried to run the service on Docker and I did the same changes in `Dockerfile` like yours and everything looks fine. It's hard to guess why you see that question marks instead of badges. I suggest looking at Development console to figure out error messages.

**Comment by paulmelnikow** [comment]
Hi! Thanks for reporting this issue. We're glad to support Docker but don't have a lot of resources to test it, so we depend on reports like this. (Also: if you want to help us set up tests for it, that would be appreciated!)

```
[frontend] Client pings, but there's no entry for page: /discord/308323056592486420.svg
```

This is a message from the development server, which should not be running on a production machine. The fix is to replace `npm start` with `node server` and remove `EXPOSE 3000`.

To test it, try loading `/badge/foo-bar-blue.svg` on your server. The result should match https://img.shields.io/badge/foo-bar-blue.png.

The index page will be broken. The fix for that is to run `npm run build` before you start the server.

A nice refinement would be to run `npm prune --production && npm cache clean` at the end.

Let me know how you make out with that! And thanks for your patience!

**Comment by iamstarkov** [comment]
@MartinGonzalez @goozler look at this https://github.com/badges/shields/pull/1436

**Comment by iamstarkov** [comment]
and this #1439

**Comment by iamstarkov** [comment]
npm cache clean seems to be redundant:

```
Step 16/19 : RUN npm cache clean
 ---> Running in 95a6214c2ec2
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR! 
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

**Comment by iamstarkov** [comment]
@paulmelnikow
