### ISSUE TITLE
Logos from master branch aren't present in gh-pages branch

### ISSUE THREAD

**Issue by salaros** [badges/shields#1399]
I'm wondering when [my recent contribution](https://github.com/badges/shields/pull/1380) as well as some other logos (such as Travis CI etc) will make it to gh-pages branch, so the labels below will start working:

`[![Travis](https://img.shields.io/travis/rust-lang/rust.svg?logo=travis)]()`

[![Travis](https://img.shields.io/travis/rust-lang/rust.svg?logo=travis)]()

`[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg?logo=travis)]()`

[![Scrutinizer](https://img.shields.io/scrutinizer/g/filp/whoops.svg?logo=travis)]()

**Comment by paulmelnikow** [comment]
Deploys usually happen every 1–3 weeks. Thaddée, who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account (and maybe the servers too) are shared with other services he runs. This has been exacerbated recently by a release blocker (#1314). Sorry I can't give you a better estimate than that.

**Comment by RedSparr0w** [comment]
@salaros This should be deployed now! :tada: 
[![Travis](https://img.shields.io/travis/rust-lang/rust.svg?logo=travis)]()

**Comment by platan** [comment]
@paulmelnikow shouldn't we add a FAQ section in the README with information then changes are deployed? Is pretty common question in my opinion.
