### ISSUE TITLE
bower badge shows no releases

### ISSUE THREAD

**Issue by kyuwoo-choi** [badges/shields#1406]
Hi.

I recently published a project on npm and bower.
The badges for npm, license, github works great but not for bower.
And I have no idea why. `bower info tui-editor` works fine.
```markdown
![github](https://img.shields.io/github/release/nhnent/tui.editor.svg)
![bower](https://img.shields.io/bower/v/tui-editor.svg)
```
![github](https://img.shields.io/github/release/nhnent/tui.editor.svg)
![bower](https://img.shields.io/bower/v/tui-editor.svg)

Happy new year!

**Comment by chris48s** [comment]
The data for the bower badge comes from libraries.io.

If you look at the page for your package on there ( https://libraries.io/bower/tui-editor ) it reports zero tags so I think that's why the badge is reporting no releases.

The badge does appear to be reporting the data from the libraries API correctly.

**Comment by kyuwoo-choi** [comment]
ok. I'll leave a issue there and close this.
thank you :)

**Comment by chris48s** [comment]
I expect you have already noticed, but libraries is now showing all your tags: https://libraries.io/bower/tui-editor and the badge is reporting correct version: ![bower](https://img.shields.io/bower/v/tui-editor.svg)
