### ISSUE TITLE
Issues with style=for-the-badge

### ISSUE THREAD

**Issue by skyzyx** [badges/shields#1407]
#### Scrutinizer

I've seen "invalid" come up a couple more times for "for-the-badge", but now that I'm sitting down to file a ticket, Scrutinizer is the only service that comes to mind because I'm actually using it.

| Style | Badge |
| ----- | ----- |
| flat (default) | ![](https://img.shields.io/scrutinizer/g/simplepie/simplepie-ng.svg) |
| flat-square | ![](https://img.shields.io/scrutinizer/g/simplepie/simplepie-ng.svg?style=flat-square) |
| plastic | ![](https://img.shields.io/scrutinizer/g/simplepie/simplepie-ng.svg?style=plastic) |
| social | ![](https://img.shields.io/scrutinizer/g/simplepie/simplepie-ng.svg?style=social) |
| for-the-badge | ![](https://img.shields.io/scrutinizer/g/simplepie/simplepie-ng.svg?style=for-the-badge) |

**Comment by paulmelnikow** [comment]
Hi, thanks for this.

Interestingly this appears to be fixed in staging:

![](https://shields-staging.herokuapp.com/scrutinizer/g/simplepie/simplepie-ng.svg?style=for-the-badge)

https://shields-staging.herokuapp.com/scrutinizer/g/simplepie/simplepie-ng.svg?style=for-the-badge

Possibly that happened in #1405 which touched a couple lines of for-the-badge-specific code… though I'm not sure why that change would have affected it.

So, this is fixed pending deploy. Not exactly sure when that'll be as I don't have access.

**Comment by RedSparr0w** [comment]
Thanks for the issue report,
This was fixed in #1281 
As stated above by @paulmelnikow these changes are just awaiting deployment to the live server.

**Comment by paulmelnikow** [comment]
Oh gosh, I had no idea that was still pending!

**Comment by RedSparr0w** [comment]
Yeah i think it just missed out on the last deploy by a few days unfortunately.

**Comment by skyzyx** [comment]
Fantastic. Thanks!
