### ISSUE TITLE
Node version badge show wrong number

### ISSUE THREAD

**Issue by elvinn** [badges/shields#1447]
``` markdown
[![node](https://img.shields.io/node/v/passport.svg)](https://github.com/elvinn/git-master-merged)
```

I add a node version badge to [my project](https://github.com/elvinn/git-master-merged/blob/master/README.md). Although I set engines.node value as `>= 6.0.0` in package.json, the badge shows `>= 0.4.0`.

Is my usage wrong? Will shields.io parse `engines.node` to generate the badge?

Thanks a lot!

**Comment by chris48s** [comment]
The badge URL you've used is for someone else's project. It reports the [correct value for passport](https://github.com/jaredhanson/passport/blob/master/package.json#L46) :)

The badge URL for your project is https://img.shields.io/node/v/git-master-merged.svg

At the moment it will show 'not specified' because it gets the node compatibility info from NPM, not GitHub. The version of `git-master-merged` on NPM doesn't have`engines.node`. It will update when you next publish your package to NPM.

**Comment by elvinn** [comment]
It works out. Thanks for your reply 😺
