### ISSUE TITLE
Badges in footer have disappeared | Frontend not up to date

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#1458]
Badges in the footer have dissapeared:
![image](https://user-images.githubusercontent.com/7288322/35024569-15127696-fba5-11e7-957c-86dc9c54db19.png)
How it should look:
![image](https://user-images.githubusercontent.com/7288322/35024542-f1494bfe-fba4-11e7-99fc-b61762aa3146.png)

Looks like they are trying to load the badges from `https://shields.io/` instead of `https://img.shields.io/`

_Sidenote: what is the `:wq` for?_

**Edit:**
Looks like the frontend hasn't been rebuilt from master?
As it is still using the gratipay badge instead of opencollective:
![image](https://user-images.githubusercontent.com/7288322/35024814-822b9982-fba6-11e7-8290-009201a0bf14.png)

**Comment by CAD97** [comment]
> _Sidenote: what is the `:wq` for? this?_

How to exit vim: https://stackoverflow.com/q/11828270/3019990

**Comment by paulmelnikow** [comment]
I mentioned this to @espadrine on the 13th and just sent him a follow up email.

All the maintainers have deploy access to the frontend, though I don't know exactly which commit is deployed to the servers.

**Comment by paulmelnikow** [comment]
> Looks like they are trying to load the badges from `https://shields.io/` instead of `https://img.shields.io/`

This part is kind of puzzling. Since the old frontend is deployed, I'm wondering: did a change in the server cause these to stop working? ^^

**Comment by espadrine** [comment]
The reason for that is likely to be because this link points nowhere, perhaps because the new build process with next requires adding a new folder, the build folder, in the git project when doing `make gh-pages`?

**Comment by paulmelnikow** [comment]
Which links points nowhere?

Ah, right, if the folder doesn't exist, the build process creates it, however the deploy process doesn't ship it.

Would you like me to open a PR to fix the script, and test the (frontend) deploy in the process? If so, which commit?

**Comment by espadrine** [comment]
I tried simply adding build in `git add -f build index.html` in the Makefile in deploy-gh-pages, but it turns out that when doing `npm run build`, the index.html file is not at the root of the repository.

Without it at the root, it won't be shown as the main page of https://badges.github.io/shields, which means it won't show up as shields.io (since shields.io maps to GitHub Pages through the CNAME trick, which lets us rely on GitHub for webpage hosting).

@paulmelnikow How did you plan to make Next.js work in GitHub Pages? I see that its introduction was part of #1273, but I don't find much information about how it was meant to be handled in production, only how it affects developing the front-end locally.

**Comment by paulmelnikow** [comment]
Hmm, good question… Well, we definitely need to commit `build/`. Then to get Github to serve it from the root, perhaps the cleanest way would be to also add + commit symlinks to `build/_next`, `build/index.html`, and `build/static`. We could create + commit these symlinks at deploy time so they don't clutter up the project.

**Comment by espadrine** [comment]
Since there is uncertainty as to how it would behave, we should try it out first on a fork before doing it on shields.io.

**Comment by espadrine** [comment]
@paulmelnikow Small points related to the suggested solution:

- Jekyll does not support symlinks; they return 404. I relied on `cp` instead.
- gh-pages then loads the files fine, but next.js sets a number of critical files to be downloaded from `/_next/…` (NOT `_next/…`). Since the gh-pages website is meant to be at badges.github.io/shields/, it tries to load the file from badges.github.io/_next/… instead of badges.github.io/shields/_next/…
- Jekyll also ignores files starting with `.` or `_`, so it ignores `_next` and the underlying files result in a 404. The same goes for the `_error` folder. All I could find was to rename those folders and replace every occurrence of them being used in code. I needed bash-specific properties on the way, so I set the makefile to use bash. It also may not work on macOS, which I am uneasy about, because of the sudden complexity of the script in use.

This whole setup feels brittle and dangerous. Paul, could you look into having a proper setup? Hopefully not one that relies on anything Next.js in production.
