### ISSUE TITLE
dynamic json badges broken?

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1493]
I didn't change one of my dynamic json badges in a while... but now I realized that it started to show
`Syntax Error: Unexpected token in JSON at position 1520`...

If I check the json and my query at http://jsonpath.com/ the result is still working as expected!

**Comment by chris48s** [comment]
Can you post an example of a bade with this problem?

**Comment by tooomm** [comment]
![](https://img.shields.io/badge/dynamic/json.svg?query=$.modules[:2].sources[:1].branch&uri=https%3A%2F%2Fraw.githubusercontent.com%2Fflathub%2Fio.github.Cockatrice.cockatrice%2Fmaster%2Fio.github.Cockatrice.cockatrice.json)

```
![](https://img.shields.io/badge/dynamic/json.svg?query=$.modules[:2].sources[:1].branch&uri=https%3A%2F%2Fraw.githubusercontent.com%2Fflathub%2Fio.github.Cockatrice.cockatrice%2Fmaster%2Fio.github.Cockatrice.cockatrice.json)
```

**Comment by RedSparr0w** [comment]
Hey @tooomm, It looks like the JSON from the link is invalid due to the newlines @ line 60.

You could fix it by removing the newlines and formatting it all on 1 line:
[`https://img.shields.io/badge/dynamic/json.svg?query=$.modules[:2].sources[:1].branch&uri=http://shields.redsparr0w.com/1493/file.json`](http://shields.redsparr0w.com/1493/file.json)
[![](https://img.shields.io/badge/dynamic/json.svg?query=$.modules[:2].sources[:1].branch&uri=http://shields.redsparr0w.com/1493/file.json)](http://shields.redsparr0w.com/1493/file.json)

**Comment by tooomm** [comment]
So nothing in the shields code changed or got missed in deployment etc. 👍 
I'll review the changes made to the source file!

Too bad the error messages are mostly not helpful. At least to me... no clue where to look even. "position 1520"?!

**Comment by RedSparr0w** [comment]
Yeah unfortunately they are just the default error messages for `JSON.parse()`,
Still trying to figure something else out that may be more helpful.

Side note: looks like [this is the commit](https://github.com/flathub/io.github.Cockatrice.cockatrice/commit/7a635c704c5f5b4dfe183eab68cd1793f750266a#diff-ccb36c9ac2b092191d5ded4e851df837) that broke it
