### ISSUE TITLE
hackage-deps: incorrect `not found` check

### ISSUE THREAD

**Issue by jakubdaniel** [badges/shields#1498]
`hackage-deps` claims to check existence of package (say `3d-graphics-examples`)  by looking for packages that depend on it. If there are none then `not found` badge is returned, instead of checking the dependencies of `3d-graphics-examples`.

**Comment by chris48s** [comment]
Thanks for reporting this. I'm not haskell programmer but I did add this error handling.

We had to use a workaround to try and work out if a package is indexed due to https://github.com/snoyberg/packdeps/issues/35 - see https://github.com/badges/shields/pull/1416 (for discussion on adding the error handling).

My instinct is that we should change from using the  `/reverse` endpoint to the `/licenses` endpoint as a proxy:
http://packdeps.haskellers.com/reverse/3d-graphics-examples
http://packdeps.haskellers.com/licenses/3d-graphics-examples

As someone more familiar with the haskell community, does that seem reasonable @jakubdaniel ?

**Comment by jakubdaniel** [comment]
Is there a reason why not simply use `hackage.haskell.org/package/...`, which seems to return 404 too if the package is not known.

**Comment by chris48s** [comment]
> If the point is to avoid discrepancies between hackage.haskell.org and packdeps.haskellers.com,

Yes - this was the situation we're trying to guard against, although I'm unclear whether this is a likely condition. Given Hackage [requires all packages to be published under an open source license](https://hackage.haskell.org/upload) I've submitted PR #1506 proposing to change to the `/licenses` endpoint. Hopefully this will be a good solution.
