### ISSUE TITLE
Some of Code Climate badges are not working

### ISSUE THREAD

**Issue by ghost** [badges/shields#1518]
Hi, guys! It seems to be an issue again/still.
Badges with percentage are not working.
Any info on that?

**Comment by PyvesB** [comment]
Hello @voplex95!

I hopefully fixed all the badges in  #1387. Even though the pull request has been merged, it has not yet been pushed to production. 😉

**Comment by kachkaev** [comment]
@PyvesB thanks for the fix! Is it in production now? It could be me, but I can't make my coverage badge working.

repo: https://codeclimate.com/github/gicentre/prettier-plugin-elm
badge: ![coverage](https://img.shields.io/codeclimate/coverage/github/gicentre/prettier-plugin-elm.svg?style=flat-square)

Example badges on [shields.io](https://shields.io) are also grey.

**Comment by PyvesB** [comment]
@kachkaev unfortunately not. You can check out the fixed version on our [staging environment](https://shields-staging.herokuapp.com/), but we'll still have to wait a bit before getting it pushed to production. ^^

**Comment by kachkaev** [comment]
Thanks for this info @PyvesB! When about are you planning to push the fix into production? Just curious 🙂 

Meanwhile, will it be OK if use a staging badge at `https://shields-staging.herokuapp.com/codeclimate/coverage/gicentre/prettier-plugin-elm.svg?style=flat-square`?

**Comment by PyvesB** [comment]
I simply help maintaining the project, I'm afraid I'm not going to able to provide a more helpful answer. Let's ping @paulmelnikow and @espadrine , they may be able to shed some light on the next deployment plans. 😉

**Comment by paulmelnikow** [comment]
See #1538!

I'd request that the staging server be restricted to testing. Since we're on the free plan, Heroku limits the number of hours per month the server can be used. If we exceed those with production usage, the staging server becomes unusable for testing, which is why it's there. That said, you're welcome to host your own server on Heroku!

**Comment by PyvesB** [comment]
As far as I can tell, the Code Climate badges _should_ be working as expected. This is what I see when I visit the Shields homepage:

![codeclimate](https://user-images.githubusercontent.com/10694593/38572346-c78e92b0-3cea-11e8-8bc7-0574c80c0166.png)

I did submit a yet undeployed pull request to make our Code Climate code more reliable (#1613) and we are facing more general issues due to lack of capacity (see #1568), but I don't believe much else can be done right now.

**Comment by DannyBen** [comment]
This is what I see (at the time of this comment):
![image](https://user-images.githubusercontent.com/2405099/38573511-fc8a835c-3cfe-11e8-8df9-994b7ce9ac56.png)

**Comment by PyvesB** [comment]
As we've got three production servers, we might be hitting different ones when requesting the badges (or possibly different versions of cached badges).

**Comment by platan** [comment]
And now I get "not found" for all CodeClimate badges at "http://shields.io/". A moment ago they all were OK.

**Comment by DannyBen** [comment]
> And now I get "not found" for all CodeClimate badges at "http://shields.io/". A moment ago they all were OK.

... and the plot thickens ...

**Comment by RedSparr0w** [comment]
All currently showing ok for me, perhaps we are hitting CodeClimates rate limit?

**Comment by PyvesB** [comment]
@RedSparr0w yes, I was thinking that as well. We go back to the "more aggressive caching" mentioned in #1568. 😃

**Comment by RedSparr0w** [comment]
Did some tests overnight and im 99% certain we are hitting the API limit:
`#4bb2c5` Found
`#eaa228` Not Found
![chart](https://user-images.githubusercontent.com/7288322/38760298-9e13acd6-3fce-11e8-9982-2f80b6c65b4f.png)
On average after ~28 Minutes we start getting the `not found` badges.
And immediately after the hour rolls over, the badges start working again.

**Comment by PyvesB** [comment]
The [API documentation](https://developer.codeclimate.com/#rate-limit) states:

> The API enforces a limit of 5,000 requests per token per hour.

As we're not actually using tokens in our queries, I'm wondering whether we might be getting rate limited sooner. Also, these Code Climate badges systematically require two API calls to get the required information, which isn't helping us either.

**Comment by kachkaev** [comment]
Given that your project is so popular and important to people, WDYT of writing to Code Climate and asking them for a King Token that would not have the rate limits? They might be happy with providing you such token for free as it is also in their interests.

I would not know about Code Climate without stumbling across your badges and so would not create an account there. At the moment I only have one open-source project in Code Climate, which does not add any profits to them, but I'm already a half way through in becoming a paying customer. Guess this situation is not unique.

**Comment by citricsquid** [comment]
I have just recently started to use Code Climate for my open source project and ran into this rate limiting issue. Although I'm not associated with shields, I have sent an email to Code Climate pointing them to this issue asking that they provide some information here on whether or not they'll be able to grant an access token with higher rate limits.

**Comment by blackxored** [comment]
This is still not working to this day. Any way I can help?

**Comment by citricsquid** [comment]
I heard back from Code Climate support:

> Hey Samuel-
>
> Thanks for reaching out and sorry for the trouble with those badges. Happy to help with this.
>
> I'd like to run this by one of my dev colleagues here to help provide some guidance.
>
> Once I have an update on my end, I'll be back in touch. 👌 If you have any questions in the meantime, please feel free to shoot me an email.
>
> Thanks again,
>
> -Emily

**Comment by epistrephein** [comment]
I haven't got a single failure today, maybe Code Climate support really fixed something?

**Comment by RedSparr0w** [comment]
Think you may be right @epistrephein.
Today 100% have had the correct badge for me.
http://shields.redsparr0w.com/1518/
![image](https://user-images.githubusercontent.com/7288322/39091639-2e3a3b8a-464c-11e8-8e4b-a16c271a42ce.png)

**Comment by PyvesB** [comment]
Maybe they whitelisted our IPs, or generally increased the rate limit for everyone. Their API was in beta for a while, they might have loosened things up since then.

**Comment by RedSparr0w** [comment]
Will leave this open for a few days and close if results stay steady.

**Comment by RedSparr0w** [comment]
Looks like it was fine over the weekend (maybe due to reduced traffic), Heres a graph of the last 3 days:
![chart](https://user-images.githubusercontent.com/7288322/39152123-6727e028-479b-11e8-98f7-874f1bafd516.png)
>this is what I see on shields.io, but they seem to be working on the staging environment

I Assume they still work on the staging environment because we are not using an API key so should be based on IP, So the staging environment shouldn't be reaching that limit.

**Comment by citricsquid** [comment]
I think the hypothesis that there is reduced traffic over the weekend is most likely. I followed up with Code Climate support asking if there had been any changes and they said:

> HI Samuel -

> I haven't seen any activity on this internally, but I'll double-check and let you know.

> Thanks!

Haven't heard back since but I guess that means no changes were made.

**Comment by kachkaev** [comment]
@citricsquid did you get any updates from CodeClimate people?

**Comment by citricsquid** [comment]
I haven’t heard back. I’ll follow up again and share their response here.

**Comment by citricsquid** [comment]
> Hi Samuel -
>
>Thanks for checking back in! I do see that the investigation is still in progress, but I don't see any additional comments yet.
>
>I'll check in with the team today and will let you know what I find. 👍 
>
>Thanks again and I'll be in touch soon,
>
>Emily

That was sent 26 hours ago and I have not heard back since. I'll update here again if I do hear back.

**Comment by RedSparr0w** [comment]
@citricsquid Any new info from codeclimate?

Doesn't look like this is contained to only a weekday problem anymore, seems to be all the time (after ~30 past the hour)

**Comment by citricsquid** [comment]
Still nothing, last I heard was the [May 24th response](https://github.com/badges/shields/issues/1518#issuecomment-392097946). I just sent a follow up email again, I'll report back with any response I receive.

**Comment by citricsquid** [comment]
I have received a response:

“Hey Samuel,

Dave here, stepping in for Emily. Unfortunately, I don't yet have an update
on this rate limiting situation. I can tell you that we're a little backed
up on escalations at the moment, so it might be a few more weeks before we
can tackle this situation. I'm really sorry about the long wait here.

I've passed along your email to our dev team, and hopefully we can expedite
the resolution here. Please let me know if you have any questions about
this, or if there's anything else I can do for you in the meantime. I'll be
in touch as soon as I have more info.

Cheers,
Dave”

**Comment by paulmelnikow** [comment]
Would it be worth pinging them again? They seem open to solving the problem. Persistence may pay off!

**Comment by citricsquid** [comment]
`a few more weeks` have passed since the previous email, so I've followed up again -- will report back with any response.

**Comment by citricsquid** [comment]
> Hey Samuel, 
>
> Unfortunately I don't yet have an update here. For context, we're a little backed up on escalations as we prepare for Code Climate Summit, and it will likely be a couple more weeks before we're able to address this. I'm really sorry about the limitation here. 
>
> Please let me know if there's anything else I can do for you, and I'll be in touch as soon as I have more information. 
>
> Thanks,

**Comment by paulmelnikow** [comment]
Thanks for keeping on the case!

**Comment by efueger** [comment]
Hi @paulmelnikow @citricsquid -

Have you heard of any recent trouble with this? We've made some changes, so wondering if this is quiet now.

**Comment by efueger** [comment]
Thanks @RedSparr0w

**Comment by PyvesB** [comment]
@RedSparr0w I've got a feeling that it's timing out later in the hour because we have implemented better caching on our side and we are no longer systematically rendering on the homepage.

**Comment by RedSparr0w** [comment]
@PyvesB Good point 👍 , forgot about that 😅

**Comment by efueger** [comment]
Hi everyone -- Emily here from Code Climate Support. 

- Although we haven't officially deprecated our shields.io badges, our new badges are no longer hosted on shields.io, and have no rate limits.

---

To update your badges, 
- select the `Badges` option on your repo's Code Climate settings page.

![ea7b4028-50e7-40c0-a6eb-a2e143d3b013](https://user-images.githubusercontent.com/2053833/46162520-85a59f00-c256-11e8-9a88-de2af92e9dca.png)

---

Let me know if you have any questions! www.codeclimate.com/help

**Comment by AlexWayfer** [comment]
> Although we haven't officially deprecated our shields.io badges, our new badges are no longer hosted on shields.io, and have no rate limits.

And have no style options, like `flat-square`, right?

**Comment by kachkaev** [comment]
@efueger please do not deprecate shields.io badges – this is how you may aquire additional new customers. I personally knew about your service by just searching ‘coverage’ there.

The point of shields.io is to provide developers with a nice choice of styles, eg flat badges with rect corners. Even if your official badges mimic these styles (which will cost you money to develop), they won’t be 100% alike. Users won’t like the mismatch between the styles and will less likely add your badge to readme (which reduces audience reach for you).

Simply turning off rate limiting for shields.io agents looks like a solution that suits everyone.

**Comment by AlexWayfer** [comment]
> @efueger please do not deprecate shields.io badges – this is how you may aquire additional new customers. I personally knew about your service by just searching ‘coverage’ there.

I think I'll have to abandon this service for my projects if they deprecate shields.io, because I like consistency:

![image](https://user-images.githubusercontent.com/6510020/46165800-32edd680-c29a-11e8-8cc7-695d7f431703.png)

I do not understand why somebody want to drop shields.io support.

**Comment by PyvesB** [comment]
I've done a bit of work in #2201 to make the examples on our homepage static, therefore sparing some requests and hopefully helping us stay within the extremely tight boundaries of the public Code Climate API.

@efueger any news on the @codeclimate side of things? I'm hoping the above responses from our users will shed some light on the issue at hand.

**Comment by AlexWayfer** [comment]
@PyvesB, thank you. I hope that Code Climate will give us the ability to use their service with beautiful and customizable badges from shields.

**Comment by paulmelnikow** [comment]
Could we solve this by scraping their SVG badges (as in #2229)?

**Comment by PyvesB** [comment]
@paulmelnikow I'll briefly sum up some of the history around these badges so that we're all on the same page. Initially we had a coverage percentage badge that retrieved the content disposition header from a PNG image returned by Code Climate. Two score badges (i.e. with letters) which did do SVG scraping were later implemented in #1236. However, Code Climate changed the format of one of their SVG badges only a few weeks later, and replaced the score with a percentage. Therefore we ended up with broken badges on our side, and no means of retrieving the letter score by scraping anymore. To solve this, I submitted #1368 and switched to using the API which still returned the now missing information. Shortly afterwards, we had to carry out other fixes as Code Climate changed things again on their side (pertaining to the old content disposition header badge) and I overhauled the whole implementation in #1387. Unfortunately ever since we have been hitting rate limits.

Unless things have changed recently, the native Code Climate SVG badges are very limited and only provide two pieces of information:
* maintainability score.
* coverage percentage.

Our badges are much more diverse:
* number of issues.
* maintainability score.
* maintainability percentage.
* coverage score.
* coverage percentage.
* technical debt.

Only the full API allows to build all of them properly. Our many additional badges, alongside nicer and more consistent visuals, as well as amazing customisation options provided by Shields.io are some of the reasons why our users have been so passionate about getting this issue resolved. Unfortunately, after 6 months of following up, @codeclimate's only official message on this issue showcases a lack of understanding of the situation.

@RedSparr0w how often does your uptime robot refresh its data, I can only see until October 24th? I would be interested in knowing how much the recently deployed pull request #2201 has improved our performance.

**Comment by paulmelnikow** [comment]
Would using a pool of tokens be possible, or would the token need to correspond to the account that owns the project?

**Comment by PyvesB** [comment]
@paulmelnikow well we've mentioned solutions using tokens in some way or the other since the early days of this issue, and I believe @citricsquid contacted @codeclimate's support precisely on this matter back in April, with several follow ups in the meantime. This is where we have been hitting a wall.

**Comment by paulmelnikow** [comment]
It sounds like what we asked is for them to drop the rate limit, or give us a king token with a higher rate limit.

GitHub basically made the same call a while back, which is what led us to use the elaborate token rotation scheme we're using now. I'm wondering if either part of that solution could be used here.

For example:

1. If I signed up for my own code climate account, could I use my token to make queries against other users' public repos?
2. Would using a single token get us more requests than we're getting with no token?
3. Would a rotation of several tokens solve both problems?

Just trying to poke in the corners of our assumptions and see if there's anything we might have missed!

**Comment by efueger** [comment]
Hi @PyvesB ,

Thanks for the summary.

I really appreciate the effort you've put into this already. I've spoken to our Product and Engineering teams and it _does_ sound like we need to provide you a different rate limit. Unfortunately, I don't think we can prioritize this work in the near future.

I know this was not the answer you were looking for, and I'm really sorry about that.

-> To confirm for our devs notes: your users do **not** provide a Code Climate API key, correct?

**Comment by PyvesB** [comment]
@efueger thank you for your response. No, our users do not provide a Code Climate API key, we are currently relying on the unauthenticated API limits.

**Comment by kachkaev** [comment]
I found a personal solution for this rather long standing and irritating problem. Not sure if CodeClimate people will like it though, because it involves dropping their service as well as Travis/AppVeyor in favour of Azure DevOps! 😅 Check out the result here:  
https://github.com/gicentre/prettier-plugin-elm

No more `coverage: unknown` in a badge on NPM and no more clumsy integrations between a bunch of services, which are hard to make work together. Such a relief! ✨ 

Sorry for a slight off-topic, but hope it will help someone like me here and also give @efueger an important message to communicate to the CodeClimate management and devs.

**Comment by willstocks-tech** [comment]
Any movement on this at all? I came to add a CodeClimate badge to my repo today and the styling/font is just _nasty_ (apologies @efueger - but to be blunt about it, pretty much _all_ other badges seem to follow a standard format, not sure why CC is so far off and there are no customization options!) and the shields version isn't working for me 😞 

I know it's shallow - because CC works for me and works well as a product - but the simple fact that the **public facing** badge is so... 🤢 makes me want to _not_ use it in favour of having something "nicer".

**Comment by epistrephein** [comment]
I agree. I mean, if they don't want to provide a token for shields, they could give their users the choice between their normal badge design and the de-facto standard badge design of almost every service (Travis, Gemfury, Depfu to name a few).
But I suppose branding is important in this regard too 😕

**Comment by willstocks-tech** [comment]
I suppose in some way that makes sense... but imho, if anything, this
“branding” is an off putting as opposed to “a clever way to stand out”?

I’m by no means a “developer” - but a lot of people put a LOT of effort
into making _their_ products look good and want to prove to people that
their code is clean/maintainable/legit etc. - it’s a bit strange that a
third party would want to impede on that.

Like I said - I love CC, it’s great and works so well for me! But the
badge... oh man! :disappointed:

Anyway - that’s my two pennies. Hopefully something can be done! Sorry for
going slightly off topic!

**Comment by efueger** [comment]
Hi everyone - thanks again for all of the input here. I definitely understand why those badge formats are a pain for you. 

----

I don't have an ETA on changes, but we're actively collecting this feedback from you (and other internal and external users). 
- do any of you use these badges for private repos? 
- or, are you primarily oss?
- does this impact any other aspect of your repos? (other than your READMEs)

**Comment by AlexWayfer** [comment]
> do any of you use these badges for private repos?

No.

> or, are you primarily oss?

Yes.

> does this impact any other aspect of your repos? (other than your READMEs)

No.

**Comment by willstocks-tech** [comment]
I can second @AlexWayfer's responses:

>  do any of you use these badges for private repos?

No.

> or, are you primarily oss?

Yes.

> does this impact any other aspect of your repos? (other than your READMEs)

No - **HOWEVER**, please do not forget that a README is going to be the first thing that 99% of people see! I know I for one head straight to GitHub for OpenSource projects to review documentation, supportability etc. and the first thing I do is check the README! Whilst it seems "_insignificant_", first impressions matter... just my honest opinion :smile:

**Comment by epistrephein** [comment]
Did the rewrite address the usage limit issue discussed here?

**Comment by PikachuEXE** [comment]
I still see invalid badge most of the time
Only see it working yesterday...
Today = fail again

**Comment by paulmelnikow** [comment]
> Did the rewrite address the usage limit issue discussed here?

No, the rewrite was unrelated.

**Comment by PyvesB** [comment]
No issues with our Code Climate badges were reported recently. Over the years, we've improved caching on our side and we happen to be hitting the Code Climate API with five distinct IP addresses nowadays instead of three previously, which means that we'll hit the rate-limiting more slowly. I consider this as a workaround rather than a proper fix, if usage of our Code Climate badges increases significantly, the rate-limiting will likely kick in again.

Given that the fix mostly depends on Code Climate themselves and we haven't heard from them since early 2019, I don't think there's value in keeping this issue open forever, so I'm gonna go ahead and close it.
