### ISSUE TITLE
semantic colorschemes & color keywords

### ISSUE THREAD

**Issue by bkdotcom** [badges/shields#1522]
thoughts on adding a few new colorschemes?

semantic | color
---|---
error |  red
notice | orange
success | brightgreen
info | blue
default | lightgrey

currently, setting the color is completely non-semaantic

Also: is there a reason [color keywords](https://www.w3.org/TR/SVG/types.html#ColorKeywords) don't work?

[doc/gh-badges.md](https://github.com/badges/shields/blob/master/doc/gh-badges.md#defaults) ("CSS/SVG Color") links to  http://www.w3.org/TR/SVG/types.html#DataTypeColor
which in turn references the color keywords doc:  https://www.w3.org/TR/SVG/types.html#ColorKeywords

**Comment by chris48s** [comment]
Colour aliases are defined in https://github.com/badges/shields/blob/5dd58142cb7688203fad2d782abcdd0d9973271d/lib/colorscheme.json I think it would be useful to define that handful of semantic aliases you've suggested. Maybe @RedSparr0w has opinions on this?

**Comment by RedSparr0w** [comment]
Nice idea, Would be good to have a few more aliases.

I looked into why the css color names are not working,
And seems to be these lines:
https://github.com/badges/shields/blob/master/lib/make-badge.js#L130-L131
```javascript
  if (!cssColor.test(colorA)) { colorA = undefined; }
  if (!cssColor.test(colorB)) { colorB = undefined; }
```
Not quite sure why they are there, will look into it a bit further and see if there is a reason.

**Comment by RedSparr0w** [comment]
I've been down the rabbit hole:
(the file has been renamed a few times and history only show for current name)
https://github.com/badges/shields/commits/master/lib/make-badge.js
https://github.com/badges/shields/commits/master/lib/badge.js
https://github.com/badges/shields/commits/master/badge.js

And it seems they were added in this PR:
https://github.com/badges/shields/commit/29a4803e4b3d5fe4ecd7af947843a0444c198639#diff-b5697a9649db913d96811d1e9873e606

I **think** we should be able to do the following without causing any errors:
```diff
  if (colorscheme) {
    let pickedColorscheme = definedColorschemes[colorscheme];
    if (!pickedColorscheme) {
      pickedColorscheme = definedColorschemes.red;
    }
-    colorA = colorA || pickedColorscheme.colorA;
-    colorB = colorB || pickedColorscheme.colorB;
+    colorA = colorA || pickedColorscheme.colorA || undefined;
+    colorB = colorB || pickedColorscheme.colorB || undefined;
  }
-  if (!cssColor.test(colorA)) { colorA = undefined; }
-  if (!cssColor.test(colorB)) { colorB = undefined; }
```

**Comment by paulmelnikow** [comment]
I commented in #1525 about the semantic color scheme. This seems like a better place to discuss it, so I'll re-post my comment here.

I really like the way you formalized this! I think **severity** is the most descriptive name. Would be great to use this not just in `?colorA` but also in our code. It'll make it semantically clearer. I'm curious how well the colors correspond with what we're doing in the code!

In terms of the names, the one I'm not sure is clear is **notice**. I think of notice as being a pretty low severity. In PHP, for example, the hierarchy is error -> warning -> notice. How about using **important** for the orange one? Possibly we could also use **critical** instead of **error** for red, since a lot of time when there is an error in the Shields service, we use gray. And perhaps **notice** instead of **default** for lightgray.

This seems pretty independent from the rest of #1525 so ideally I'd say we should merge it separately. By keeping PRs small, they're easier to review and cause fewer conflicts.

> Not quite sure why they are there, will look into it a bit further and see if there is a reason.

I'd feel more comfortable if we checked that the colors were valid. I bet there's a library in npm that can do this. And, ideally we would display an error when the color is invalid instead of failing silently.

Btw #830 is open for CSS named colors.
