### ISSUE TITLE
Add Libraries.io SourceRank badge

### ISSUE THREAD

**Issue by Athari** [badges/shields#1532]
Libraries.io provides a ScoreRank based on existense of metainfo (readme, license), number of dependants and subscribers etc.

Documentation: https://libraries.io/api#project-sourcerank

Note that the docs are outdated, the request actualy outputs detailed JSON, not just one number, they have to be summed up:

```
{"basic_info_present":1,"repository_present":1,"readme_present":1,"license_present":1,"versions_present":1,"follows_semver":0,"recent_release":1,"not_brand_new":1,"one_point_oh":1,"dependent_projects":10,"dependent_repositories":6,"stars":4,"contributors":1,"subscribers":1,"all_prereleases":0,"any_outdated_dependencies":-1,"is_deprecated":0,"is_unmaintained":0,"is_removed":0}
```

A badge like `sourcerank : sum` would be nice.

**Comment by chris48s** [comment]
Hi @Athari . Good suggestion. I know Libraries.io are currently looking at reviewing the way that SourceRank is calculated (see https://github.com/librariesio/libraries.io/issues/1916 ). If anyone is interested in working on this, it might be sensible to put this on hold until SourceRank 2.0 is launched. It would be a shame to put time into this and then have to rewrite it in the near future because the API has changed.
