### ISSUE TITLE
Hitting JSON endpoint with valid "style" param causes timeout and 5xx error

### ISSUE THREAD

**Issue by movermeyer** [badges/shields#1577]
I was trying out using the `style` parameter:

`https://img.shields.io/pypi/format/pycparser.svg?style=plastic`

Which worked fine, as expected.

I then wanted to try the other output formats. I switched the URL to point at the JSON endpoint:

`https://imgshieldsio/pypi/format/pycparser.json?style=plastic` (replaced `img.shields.io` with `imgshieldsio`)

Which causes various 5xx errors. The first time I tried, [I got a 520](https://gist.github.com/movermeyer/a51427c0e47d18e12e1f1a56f2316624), and the second time, I got Cloudflare's 524:

![image](https://user-images.githubusercontent.com/1459385/37537245-d8be008e-2944-11e8-8d46-35966e55bccb.png)

This seems to be a result of the extra `?style=plastic` parameter, as the error disappears when I remove it.
Interestingly, this timeout doesn't happen for invalid params (`?abc=123`), nor invalid styles (`?style=abc`)

You may want to configure the server to ignore the `style` parameter for the `json` format.

I'm letting you know since I was worried that someone might be able to DDOS shields.io by sending requests that use more than their fair share of server resources.

**Comment by platan** [comment]
@movermeyer Thank you for reporting this. You're right and this request causes server process crash. This is a known bug https://github.com/badges/shields/issues/1348 and was fixed in https://github.com/badges/shields/pull/1429. We have to wait for deployment. 
I've changed domain name from `img.shields.io` to `imgshieldsio` in URL you provided, just in case.

**Comment by paulmelnikow** [comment]
We're tracking deploy status in #1538 😄
