### ISSUE TITLE
Add yaml dynamic badge

### ISSUE THREAD

**Issue by jacobtomlinson** [badges/shields#1617]
The json and xml dynamic badges are awesome. It would be great to add yaml to the list of supported markups.

One initial use case I can think of would be for [helm chart repos](https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#create-a-chart-repository) to show the latest version of a chart.

**Comment by paulmelnikow** [comment]
Great idea!

Would you be interested in making a pull request? We have a good tutorial, and since the JSON badge is already built, it's probably a matter of conditioning on json vs yaml in the URL, adding js-yaml to handle parsing, and adding some tests. If not, maybe someone else would like to pick this up!
