### ISSUE TITLE
Fork button on the website not working correctly

### ISSUE THREAD

**Issue by theel0ja** [badges/shields#1665]
[![gif](https://storage.theel0ja.info/theel0ja-img-up/ShareX/h/2018/04/ezgif.com-video-to-gif.gif)](https://storage.theel0ja.info/theel0ja-img-up/ShareX/h/2018/04/2018-04-28_14-30-38.mp4)

using firefox 60 beta

**Comment by chris48s** [comment]
Thanks for reporting this.

This affects the 3 badges on that page which we're rendering as an `<object>` tag. It seems to be trying to open the link href inline. Not sure if the right solution here is to change our footer template so we render these badges using a `<a href=".."><img src=".." /></a>` syntax, or to modify the badge code so that the links target `target="_top"` or `target="_blank"` or something to better support the `<object>` style embed.

**Comment by RedSparr0w** [comment]
Nice catch, I would assume this affects everyone's badges that use links (via object/iframe).
So would probably be best to add `target=_blank` or `target=_top` to the badge templates (if this still works cross origin?).

**Comment by RedSparr0w** [comment]
Note: on iOS9 (safari & chrome) when you click the links it just does nothing, doesn't try render inline or anything, can't even copy the link.

**Comment by theel0ja** [comment]
On Chrome (win 10) it doesn't show anything, such as that scrollbar after clicking that button.
