### ISSUE TITLE
Is it possible to connect to a private repo in bitbucket?

### ISSUE THREAD

**Issue by johnico** [badges/shields#1757]
HI, I have a private bitbucket repo . all my servers are local |
how can I use shields  ? 
Thanks for helping

**Comment by chris48s** [comment]
Which badges are you looking to use?

**Comment by johnico** [comment]
hi @chris48s thanks, 

I am looking for  build :pass,filed  ,tests, coverage  , pul requests .. etc  
and I cant do it with private repository 

all my work is no local machines  and without any connection outside

**Comment by chris48s** [comment]
OK. There's 2 things that are going to be a problem:

1. All the bitbucket badges are currently hard-coded to hit https://api.bitbucket.org - so they'll only work for repos hosted on bitbucket cloud in their current form. In principle if the bitbucket server and bitbucket cloud APIs are the same or compatible , these badges could be modified so they can also optionally talk to a self-hosted instance (as long as it is public or contact-able from the internet). We have several other integrations (JIRA, Discourse, Jenkins CI, etc) which can talk to any public instance. We'd could accept a PR for this, but it would have to be done so that the default is bitbucket.org and an instance can be passed as some optional parameter to avoid breaking compatibility for existing users.

2. The second issue is that your instance _isn't_ public or contact-able from the internet, so even if we did have that feature, we would not be able to contact your instance. In order to get around that, I think you would need to look at [self-hosting](https://github.com/badges/shields/blob/master/doc/self-hosting.md) your own shields instance.

**Comment by paulmelnikow** [comment]
Marking **service-badge** since this is a feature request too.

**Comment by nlowe** [comment]
We'd be interested in badges for on-prem bitbucket servers, even if we have to self-host. Would you accept a PR for this?

**Comment by chris48s** [comment]
Feel free to submit a PR for review if you work on it :+1:
