### ISSUE TITLE
Downloads badge doesn’t count github clones

### ISSUE THREAD

**Issue by vedantpuri** [badges/shields#1765]
The current downloads badge for github all releases doesn't account for number of brew installs. For eg. I created a brew tap for my repo and was hoping that the badge would account for those downloads as well but it doesn't.
**Further info:** Whenever someone brew taps my formula, a shallow clone of the repo is made. Hope that helps !

**Comment by chris48s** [comment]
Hi
You're right that GiutHub releases badge only counts downloads of published releases. We report the numbers from the GH API. See: https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

I don't think the GH API provides a way to count repository clones, but also a repo clone is a different thing from release downloads. For some repos, a release is a source distribution, but if you think about a project like atom which packages binary releases (e.g: https://github.com/atom/atom/releases/tag/v1.28.1 ) a clone of the source code is a different thing to count from a download of a release binary.

I don't really know anything about homebrew because I don't use macs, but it may be possible to (re-)write your brew formula so that it grabs a release tarball instead of cloning your repo. If so I guess that would allow the releases badge to count brew installs.

**Comment by paulmelnikow** [comment]
The clone count does show up in the UI. I wonder if they do expose that number in the API.

**Comment by diegohce** [comment]
Hi every body, the do have a clones count in the API
[Clones](https://developer.github.com/v3/repos/traffic/#clones)

On the UI, you can see that value clicking "Insights", then "Traffic"

Is it possible add this badge?

Thanks!

**Comment by chris48s** [comment]
Thanks for the update. In a similar way to how you can see the number of clones for your own repos, but not other peoples, that endpoint requires an API key with push access to the repo:

```
$ curl "https://api.github.com/repos/badges/shields/traffic/clones"
{
  "message": "Must have push access to repository",
  "documentation_url": "https://developer.github.com/v3/repos/traffic/#clones"
}
```

We wouldn't be able to make use of that endpoint in a secure way on shields.io because the user would have to expose a token allowing an attacker write access to their repo.

**Comment by davidnewhall** [comment]
Your homebrew formula can download from anywhere. Including a link shortener that tracks clicks. Just think about that for a minute. Then rejoice in what you've learned. Enjoy!

**Comment by Ana06** [comment]
Such a badge could be updated by using GitHub actions as you can provide a token with enough permissions. 🤔 That is some more work than if it could be integrated in shields. I don't understand why this number is not public. 😢
