### ISSUE TITLE
Named logo link not working

### ISSUE THREAD

**Issue by Richienb** [badges/shields#1787]
The [named logos](https://github.com/badges/shields/tree/gh-pages/logo) link recreated here from the [shields.io](https://shields.io/) website directs to a 404 error.

**Comment by paulmelnikow** [comment]
I wonder if there's an easy way to incorporate a directory listing into the front-end build.

**Comment by chris48s** [comment]
This is currently a 404 because `gh-pages` has these [additional commits](https://github.com/badges/shields/compare/master...gh-pages) at the tip which replace the source with the build output. We've just added the features in https://github.com/badges/shields/issues/1708 with the assumption that we can ff-merge commits from the master branch onto `gh-pages`. It might be nicer to present it as a dir listing as a separate issue, but it seems this break is a symptom of something we should change to support another feature anyway?

**Comment by paulmelnikow** [comment]
If the deploy commits were built on an empty branch, I think we'd have a problem with #1708, but since the deploy commits are added at the tip (as before) that feature should keep working. Does that make sense?

**Comment by Richienb** [comment]
I see. Just wondering when a fix will be rolled out.
- [x] Find out what's wrong
- [ ] Fix the problem

**Comment by chris48s** [comment]
In the meantime, if you're looking for a list of the currently available named logos:

https://github.com/badges/shields/tree/57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf/logo

**Comment by Richienb** [comment]
Ok. Maybe consider changing the link to go to that specific commit

**Comment by paulmelnikow** [comment]
Hey @Richienb, the fix is in progress. You can see what I've done in the review app:
https://shields-staging-pr-1794.herokuapp.com/

**Comment by Richienb** [comment]
ok!
