### ISSUE TITLE
npm download badge: project not found

### ISSUE THREAD

**Issue by andrey-helldar** [badges/shields#1882]
I published the package on npm and I want to display the badges. Of the three icons, only one returns with an error:

<p align="center">
    <img src="https://img.shields.io/npm/dt/dealers-fontface.svg?style=flat-square" alt="Total Downloads" />
    <img src="https://img.shields.io/npm/v/dealers-fontface.svg?style=flat-square" alt="Latest Stable Version" />
    <img src="https://img.shields.io/npm/l/dealers-fontface.svg?style=flat-square" alt="License" />
</p>

* ERROR: https://img.shields.io/npm/dt/dealers-fontface.svg?style=flat-square
* OK: https://img.shields.io/npm/v/dealers-fontface.svg?style=flat-square
* OK: https://img.shields.io/npm/l/dealers-fontface.svg?style=flat-square

**Comment by chris48s** [comment]
Hi. We request download stats from NPM using a call to https://api.npmjs.org/downloads/range/ Usually if we call something like https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/localeval that will return some stats. In the case of your package, if we call https://api.npmjs.org/downloads/range/1000-01-01:3000-01-01/dealers-fontface that is returning an error, so that is what the badge reports.

It looks like you've only published this today. I don't know the NPM API in much detail, but maybe there is some caching or it needs a full day's worth of data before it will give a response on that endpoint? If the problem doesn't resolve itself, maybe open an issue with NPM.

**Comment by andrey-helldar** [comment]
@chris48s I published the package yesterday, but the day has not passed. Got it. I'll wait for the cache update. Thank you!

**Comment by paulmelnikow** [comment]
Probably we should return **package not found**…

**Comment by paulmelnikow** [comment]
Has the package been removed? I can't quite make sense of what's happening right now.

- https://www.npmjs.com/package/dealers-fontface is showing 404 no package
- https://img.shields.io/npm/v/dealers-fontface.svg is showing **unparseable json response**
- https://img.shields.io/npm/dt/dealers-fontface.svg is showing **project not found**
- https://img.shields.io/npm/l/dealers-fontface.svg is showing **invalid**

**Comment by andrey-helldar** [comment]
@paulmelnikow 
Oh! Sorry, I today renamed it [official-fontface](https://www.npmjs.com/package/official-fontface), because the package was conceived as a repository of official fonts of various companies, but, by mistake, called it as dealer fonts.

* https://www.npmjs.com/package/official-fontface is showing 200 OK
* https://img.shields.io/npm/v/official-fontface.svg is showing v1.1.1 version badge
* https://img.shields.io/npm/dt/official-fontface.svg is showing project not found
* https://img.shields.io/npm/l/official-fontface.svg is showing MIT license

**Comment by andrey-helldar** [comment]
I update my first message.

**Comment by andrey-helldar** [comment]
Not when I described the problem, the package was available by the old name - it was published yesterday.
The name changed only tonight.

**Comment by paulmelnikow** [comment]
I'm 90% sure I understand. 😀 I think showing "too new" on the downloads badge is a pretty good way for us to handle this.

**Comment by andrey-helldar** [comment]
I agree. The option is excellent.
(I translate into English via Google Translate.)
