### ISSUE TITLE
Show popout style example with a logo on index page

### ISSUE THREAD

**Issue by TobiasRoeddiger** [badges/shields#2054]
First of all thank you very much for this awesome project. I figured there seems to be an issue with the logo when choosing the popout style:
This breaks the boundaries of the badge: https://img.shields.io/badge/style-popout-green.svg?logo=apple&style=popout
Whereas it is correct for e.g. the flat style: https://img.shields.io/badge/style-flat-green.svg?logo=apple&style=flat

**Comment by PyvesB** [comment]
Hello @TobiasRoeddiger,

That's actually intended behaviour, the popout style is supposed to make the logo pop out of the boundaries of the badge. See #1478 for more information. 😉 

Cheers,

Pyves

**Comment by TobiasRoeddiger** [comment]
Oh I missed something there - cheers!

**Comment by chris48s** [comment]
I suspect this is confusing for users because the example on the front page shows the popout style example without a logo. The main thing this style does is display the logo differently. I think we could make it more obvious what this style is for by showing an example of a flat badge with a logo and a popout badge with a logo.

**Comment by chris48s** [comment]
closed in #2084
