### ISSUE TITLE
Dependencies badge showing "invalid"

### ISSUE THREAD

**Issue by Dan503** [badges/shields#2110]
I wanted to add this dependencies badge to my fresh new [`gulp-file-loader` npm plugin](https://www.npmjs.com/package/gulp-file-loader).

It is showing up like this though (live version):

![Dependencies status](https://img.shields.io/depfu/depfu/gulp-file-loader.svg?style=for-the-badge)

Here is a static version of what I'm seeing incase the live version starts working:

![Dependencies status - static](https://user-images.githubusercontent.com/10610368/45927442-6bc63c80-bf76-11e8-9081-0f5b38de46c8.png)

The json in my package.json is valid. Is this because there is some sort of delay between an npm module going live and sheilds.io being able to read the dependencies badge?

It seems odd because it can display the node version badge just fine. 😕

![Node version badge](https://img.shields.io/node/v/gulp-file-loader.svg?style=for-the-badge)

**Comment by chris48s** [comment]
The link you've posted is calling https://img.shields.io/depfu/depfu/gulp-file-loader.svg [Depfu](https://depfu.com/) is a service for ruby projects, so that'll be why it isn't working for your NPM project. If you're interested in tracking dependencies for your javascript project, you could might a look at a service like [dependabot](https://dependabot.com/) or [david](https://david-dm.org/).
