### ISSUE TITLE
Confusing deploy status

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#2198]
I noticed the following whilst merging a few pull request this morning:

![deploy](https://user-images.githubusercontent.com/10694593/47253547-5268c100-d44c-11e8-910b-c100d4102df5.PNG)

This seems to happen when we have created a Heroku review app for a given pull request. We end up with a message from our Shields bot saying it hasn't yet been deployed (i.e. not live on our production servers) and a message from GitHub saying it has been deployed (i.e. only Heroku).

Any thoughts on this matter? Does anyone have ideas on how to solve or improve this?

**Comment by chris48s** [comment]
> Does anyone have ideas on how to solve or improve this?

GitHub has to be 'aware' of the heroku deploys and has no way to know if we've SSHed into a server somewhere, so there probably isn't a great solution to this with our current setup.

Just for lolz, next time we merge one we've deployed to staging, lets try removing the review app in heroku before we merge it and see what happens when we merge it..

**Comment by chris48s** [comment]
Having done a bit more investigation on this, I don't think this is very important to worry about because the deployment status is only visible to maintainers. If I view a PR like https://github.com/badges/shields/pull/2192 and I'm either logged out or logged in as a user who can't push to this repo, the GH deployment status card isn't visible. As such I don't reckon we need to care to much..

**Comment by PyvesB** [comment]
Indeed I didn't realise that it only showed to us maintainers. I agree that we don't need to care much, therefore I'll close this issue. 😉
