### ISSUE TITLE
dependency version badges for applications, from package.json

### ISSUE THREAD

**Issue by guylepage3** [badges/shields#2259]
**Description**
I would love to be able to add `dependency` version badges from my `package.json` and have those badges change to let developers know that a dependency is outdated. I am aware of david-dm.org for example...

[![peerDependencies Status](https://david-dm.org/guylepage3/lepage.cc.svg?colorA=212121&colorB=007BFF)](https://david-dm.org/guylepage3/lepage.cc)

But it would be amazing to have a badge for each of my dependencies..

**Comment by guylepage3** [comment]
Hey @paulmelnikow, I was thinking more along the lines of...

Up to date version is blue or green...
[![React Router DOM version](https://img.shields.io/badge/React_Router_DOM-v4.3.1-color.svg?colorA=212121&colorB=007BFF)](https://www.npmjs.com/package/react-router-dom)

[![React Router DOM version](https://img.shields.io/badge/React_Router_DOM-v4.2.1-color.svg?colorA=212121&colorB=FF0000)](https://www.npmjs.com/package/react-router-dom)

**Comment by nottrobin** [comment]
Any movement on this? Did anyone ever find a way to do this? I would also like to be able to display the exact version of a specific dependency that's used by the project.

**Comment by paulmelnikow** [comment]
Yea, we chatted on Discord about using the dynamic badge. @guylepage3 could you point us to what you ended up with?

**Comment by guylepage3** [comment]
Yeah. I was only able to execute what @chris48s is suggesting above. I would really love to remove the tilde `~` or `^` and replace it with `v`. But yeah. I didn't have anymore time to put into it. Sorry.

**Comment by nottrobin** [comment]
Works perfectly, thanks @chris48s, @guylepage3. I'm not sure replacing the `~` or `^` would be the right thing to do, as someone installing dependencies from `package.json` might not get that exact version. If the script could instead read from `package-lock.json` or `yarn.lock`, then you could confidently communicate the exact version.

Does anyone know if there's a way to get a similar badge for specific Python dependencies from `requirements.txt`?

**Comment by guylepage3** [comment]
For my purposes I was using the badge as a quick visual to let the viewer know which version of the dependency was currently in use. So for me it made sense. Much like how shields.io has set up my npm badge.
[![npm version](https://img.shields.io/npm/v/@universelabs/meta.svg?colorA=%23212121&colorB=%23007BFF)](https://www.npmjs.com/package/@universelabs/meta)

**Comment by paulmelnikow** [comment]
I can't think of a way to parse `requirements.txt` using the dynamic badge, though I'd really like to support custom use cases like this through a combination of #1525 and a [RunKit endpoint](https://runkit.com/docs/endpoint).

Also, as I think about this more, I'd be curious to see how you're using these requirements badges to communicate with developers. Could you guys link to repos?

**Comment by nottrobin** [comment]
@paulmelnikow for me, this is just something I'm thinking of doing, so don't have examples. But these are how I'd like to use it:

- To communicate the [Django](https://www.djangoproject.com/) version we're using in our Django website repos - e.g. https://github.com/canonical-websites/www.ubuntu.com
- The same with our [Flask](http://flask.pocoo.org/) website repos - e.g. https://github.com/canonical-websites/snapcraft.io
- We use a styling framework, [vanilla-framework](https://vanillaframework.io/), across all our sites. We'd similarly like to communicate the version of vanilla-framework on each site

In general, our repositories tend to have one or two particular dependencies (usually frameworks) that we would consider fairly central, where the exact version of those dependencies is particularly interesting.

**Comment by paulmelnikow** [comment]
Ah, thanks @nottrobin, that's really helpful! I think I understand some possible use cases:

- Warn other developers that an application still uses an old version of a dependency
- Signal that some upgrade attention may be needed.

We do have a bunch of [platform support](https://shields.io/#/examples/platform-support) badges. However the ones for Node and Python are designed for libraries. The ones for Python and Django version look at [PyPI trove classifiers](https://pypi.org/classifiers/), and the node ones look at `engines`. They both look at published packages.

Have you given consideration to [adopting pipenv](https://pipenv.readthedocs.io/en/latest/)? [`Pipfile` uses TOML](https://github.com/pypa/pipfile#examples-spec-v6), whereas requirements.txt is completely nonstandard to parse… not to mention [problematic by nature](https://www.kennethreitz.org/essays/a-better-pip-workflow).

We have a GitHub manifest version badge, which reads the version number from package.json or manifest.json. I could see adding support to show the version of a specific dependency. We could do the same for a Pipfile. It could explicitly support the big ones, like Flask and React, sort of like we do now for Django in libraries. It could let developers specify a specific library, too.

Finally, we could also add a dynamic TOML badge for people who want to do really specific things with their Pipfile.

Do you think that would work for you?

**Comment by nottrobin** [comment]
We have looked at pipenv. The problem with it for us is that it doesn't have a way to generate lockfiles from system level dependencies. We encapsulate all our dependencies using containers, so we have no need for the pipenv user environments.

It's a shame that pipenv bundles in the new dependency format with its environment management, so you can't have one without the other, and that its incompatible with other environment management options - like storing the dependencies at the system level.

**Comment by paulmelnikow** [comment]
System level dependencies… is that components like gunicorn and statsd? I take it they're getting installed here?

https://github.com/canonical-websites/www.ubuntu.com/blob/1116f4c8bb9d916477d40a376634e244f915ee19/Dockerfile#L12

**Comment by nottrobin** [comment]
No that's not what I mean. We do local development effectively like this (illustrative only):

``` bash
docker run --volume `pwd`:/srv python:3 --publish 8000:8000 bash -c "pip install -r requirements.txt && ./manage.py runserver"
```

It doesn't have to be the `python3` image, it doesn't have to be Docker (it could easily be [lxd](https://linuxcontainers.org/lxd/introduction/)). The point is, rather than using filesystem and `$PATH` tricks to pretend to have an encapsulated environment for our Python dependencies, we use linux containers. Using Python virtualenvs can both often have unexpected effects on the wider system and break because of quirks in your wider system. Using linux containers offers significantly more reliably encapsulation.

The simplest way to do that is to run everything as root inside the container - installing everything at the system level. We could, of course, configure our containers to have a whole encapsulated user environment and still use Python virtualenvs inside the container, but it's a whole load of extra weight and complexity to our containers that we don't need.

Pipenv looks like a really promising project, and I'd love to use it, but it unfortunately doesn't play at all well with actually working with dependencies that are installed at the system level. I've [tried](https://github.com/pypa/pipenv/issues/1792) to delve into this problem with the Pipenv devs, but unfortunately I don't think they have any plans or appetite to fundamentally rearchitect Pipenv to support our workflow.

**Comment by paulmelnikow** [comment]
Ahhh I gotcha. That pipenv thread sounds more philosophical than technical… and frustrating. Heh. Anyway, I get it, you need to use `requirements.txt`.

I'm not really up for implementing a requirements.txt parser in Node. (The [only one I found](https://www.npmjs.com/package/requirements-txt) was deprecated and labeled "trash" by its author.)

I'm thinking this case could be handled using a custom endpoint. I'll resume working on reviving #1525 – that'll allow creating a badge from an arbitrary JSON endpoint which returns something like `{ "label": ..., "message": ..., "color": ...}`.

That opens up options for the implementation. [Runkit endpoints](https://runkit.com/docs/endpoint) is a good one for Node. Basically you write a function like

```js
exports.endpoint = function(request, response) {
    const badge = { schemaVersion: 1, label: ..., message: ..., color: ... }
    response.end(JSON.stringify(badge))
}
```

and save it in your browser and then, voila, you have a JSON endpoint. I imagine your limited case could be handled well enough in Node with a regex.

Alternatively, it might be easy enough to parse `requirements.txt` using some Python code. I haven't looked too far into Python endpoint options. Are you familiar with Jupyter? [This approach](http://blog.ibmjstart.net/2016/01/28/jupyter-notebooks-as-restful-microservices/) using Jupyter Kernel Gateway seems promising. I don't know whether or not the free Jupyter notebook hosting providers like [Azure Notebooks](https://notebooks.azure.com/) would provide something that would work with Kernel Gateway.

**Comment by nottrobin** [comment]
Interesting option. I haven't looked into it, but I'm sure parsing requirements.txt in Python must be pretty trivial.

But I suspect the simplest would be, as you say, to write a small JSON endpoint that parsed our latest requirements.txt. Do you have an example of such an endpoint that parses a file from a GitHub repo that we could base it off?

And do you know if #1525 is likely to be merged soon?

**Comment by paulmelnikow** [comment]
I put this together: https://runkit.com/melnikow/version-from-requirements-txt

It seems to work well enough in this basic case:

- https://runkit.io/melnikow/version-from-requirements-txt/branches/master
- https://runkit.io/melnikow/version-from-requirements-txt/branches/master?dependency=metabolace

Cool stuff!

Yea, I'm working now on a replacement for #1525.

**Comment by chris48s** [comment]
> I'm not really up for implementing a requirements.txt parser in Node

Writing a javascript parser for `requirements.txt` is way down my list of things to do as well (like way way down). That said, if someone _did_ want to do that, as noted in https://github.com/badges/shields/issues/775 there is a NPM package for dealing with PEP440 versioning: https://www.npmjs.com/package/@renovate/pep440 which has some [relevant helpers](https://github.com/renovatebot/pep440/blob/master/lib/specifier.js) and this is an example of some Node JS code that consumes that to parse a `requirements.txt` file: https://github.com/renovatebot/renovate/blob/bed39f10ed768c802c551cd438fceb22c0810a95/lib/manager/pip_requirements/extract.js (Rennovate Bot is similar to greenkeeper, pyup, dependabot, etc)

> Pipenv looks like a really promising project, and I'd love to use it (especially its lockfile functionality), but it unfortunately doesn't play at all well with actually working with dependencies that are installed at the system level

I realise we've gone way way way off the original topic of this thread at this point, but if `pipenv` / `Pipfile` isn't a good solution for your project, `poetry` / `pyproject.toml` might be worth a look:

https://github.com/sdispater/poetry
https://poetry.eustace.io/docs/pyproject/

That said, for the love of god don't change your packaging tool if the only problem you're trying to solve is adding a badge to your `README.md` :D That's specialist-yak-barbershop levels of yak-shaving right there, especially given we don't even support TOML for the dynamic badge yet.

**Comment by nottrobin** [comment]
Thanks @chris48s, Poetry is very interesting. I'll try to look into it a bit further.

> for the love of god don't change your packaging tool if the only problem you're trying to solve is adding a badge to your README.md :D That's specialist-yak-barbershop levels of yak-shaving right there

Lol no. We've previously been looking into alternatives to `requirements.txt`. The main feature we wanted at the time (and still want) is a lockfile with package signatures to lend our builds a bit more security.

**Comment by paulmelnikow** [comment]
Yup! There are two badges, one for npm packages and the other for github. If you search for "dependencies" on https://shields.io/ they'll both come up:

<img width="1181" alt="screen shot 2019-01-13 at 11 31 06 am" src="https://user-images.githubusercontent.com/1487036/51087880-d4ecde00-1726-11e9-9b5c-fd61cdb54958.png">

Btw @nottrobin the Endpoint badge is still in progress. The best place to track that is #2473.

**Comment by guylepage3** [comment]
Awesome! Looking forward to this! 😄

**Comment by paulmelnikow** [comment]
Hey @nottrobin, the [Endpoint badge is live][endpoint badge]! Want to give it a shot? We can continue the discussion in #2838.

[endpoint badge]: https://shields.io/#/endpoint
[tools]: https://github.com/badges/shields/issues/2259#issuecomment-444186589
[beta]: https://github.com/badges/shields/issues/2259

**Comment by nottrobin** [comment]
@paulmelnikow works a charm!

https://github.com/canonical-websites/www.ubuntu.com/blob/251b4933c42f64ea8579eb5784a0d6c28b527897/README.md

Thanks so much!

**Comment by paulmelnikow** [comment]
Nice!! Can you share a link to your RunKit notebook?

**Comment by paulmelnikow** [comment]
Also… could you help spread the word about this?
https://twitter.com/paulmelnikow/status/1087707442824310785

**Comment by paulmelnikow** [comment]
Just thought I'd ping this thread to let anyone watching know that there is now a dependency badge for Pipenv applications. It reads Package.lock from a GitHub repo:

<img width="1241" alt="Screen Shot 2019-10-02 at 5 56 58 PM" src="https://user-images.githubusercontent.com/1487036/66085020-1126cf80-e53e-11e9-998d-860b073144bb.png">

**Comment by jonashackt** [comment]
Really great service for using the `package.json` dynamically @paulmelnikow 👍 

In my case this great service didn't work, since the `package.json` doesn't reside in the root of my GitHub repo, but in a subdirectory called `frontend` - the url to the package.json is: https://github.com/jonashackt/spring-boot-vuejs/blob/master/frontend/package.json Currently I found no option to use the great tools provided at https://shields.io/category/platform-support to use it.

If someone stumbles upon this issue like me, here's my solution how to get it working though: Just use the `Dynamic` endpoint `https://img.shields.io/badge/dynamic/json?` like that to query the `frontend/package.json`:

```
https://img.shields.io/badge/dynamic/json?color=brightgreen&url=https://raw.githubusercontent.com/jonashackt/spring-boot-vuejs/master/frontend/package.json&query=$.dependencies.vue&label=vue&logo=vue.js
```

You simply leverage the power of JSONPATH and use `query=$.dependencies.vue` to query the current version of your project's dependency (I used https://jsonpath.com/ for an easy validation of my JSONPATH query). Also make sure to use the `raw.githubusercontent.com` version of your `package.json`, otherwise the shields.io service can't parse the json.

And I also had packages not defined inside my `package.json`, but inside the `package-lock.json`. Using this approach, this is also not a problem:

```
https://img.shields.io/badge/dynamic/json?color=brightgreen&url=https://raw.githubusercontent.com/jonashackt/spring-boot-vuejs/master/frontend/package-lock.json&query=$.dependencies.webpack.version&label=webpack&logo=webpack
```

**Comment by JohnRDOrazio** [comment]
> Here's an example using dynamic json badge. The query is `$.dependencies.<mydependencyname>`
> 
> https://img.shields.io/badge/dynamic/json.svg?url=https%3A%2F%2Fraw.githubusercontent.com%2Fbadges%2Fshields%2Fmaster%2Fpackage.json&label=camp&query=$.dependencies.camp&colorB=blue
> 
> ![](https://camo.githubusercontent.com/2ed31eee6a07e74009e71c8092ef5deec641847fe33755cb52f30f27b7c0c537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f64796e616d69632f6a736f6e2e7376673f75726c3d68747470732533412532462532467261772e67697468756275736572636f6e74656e742e636f6d253246626164676573253246736869656c64732532466d61737465722532467061636b6167652e6a736f6e266c6162656c3d63616d702671756572793d242e646570656e64656e636965732e63616d7026636f6c6f72423d626c7565)
> 
> https://github.com/badges/shields/blob/0aee712738f0df50cfa6c62d7cf65b053c1e73fa/package.json#L25

For anyone stumbling upon this issue, the quoted badge is not currently working, I think because `camp` is no longer a dependency in the current package.json, it seems to have been renamed to `@shields_io/camp` in the meantime:

https://github.com/badges/shields/blob/master/package.json#L28

[This url](https://img.shields.io/badge/dynamic/json.svg?url=https://raw.githubusercontent.com/badges/shields/0aee712738f0df50cfa6c62d7cf65b053c1e73fa/package.json&label=camp&query=$.dependencies.camp&colorB=blue) is working: ![](https://img.shields.io/badge/dynamic/json.svg?url=https://raw.githubusercontent.com/badges/shields/0aee712738f0df50cfa6c62d7cf65b053c1e73fa/package.json&label=camp&query=$.dependencies.camp&colorB=blue)

Now that the package has been renamed to `@shields_io/camp`,  I'm not sure how you would go about doing the JSONPATH query with the `@` symbol.

You can however use the specific `package-json` route to produce a dynamic badge for a dependency from package.json in a repo, and this will work on packages that have the `@` symbol, so for the current master branch you can produce the badge for `@shields_io/camp` like this:

![GitHub package.json dependency version (prod)](https://img.shields.io/github/package-json/dependency-version/badges/shields/@shields_io/camp)

https://img.shields.io/github/package-json/dependency-version/badges/shields/@shields_io/camp
