### ISSUE TITLE
`npm start` with autoreload

### ISSUE THREAD

**Issue by techtonik** [badges/shields#2426]
:clipboard: **Description**

In TUTORIAL.md I need to start and stop `npm` server every time to load new changes? That's cumbersome. Is there any autoreload mechanism for /services/?

**Comment by paulmelnikow** [comment]
Yea… the frontend reloads when it changes, but it doesn't pick up changes to the badge examples until `npm run examples` is run again. If that happened automatically, that's something I would find quite handy.

The services do not reload either, though I haven't found that to be a significant problem since I do most of my work through the test runner.

Do you mean live editing of TUTORIAL.md? That's something else entirely.

**Comment by techtonik** [comment]
I followed the tutorial and found it too cumbersome to restart server on every change to example service. `nodemon` is good, but it keeps reloading all the time. Probably because `vim` updates some temporary file there.

**Comment by paulmelnikow** [comment]
How were you testing it?

**Comment by paulmelnikow** [comment]
I opened #3401 which adds nodemon. I tweaked the config a bit – it is only watching `.js` files – though it may be necessary to ignore some more files. The `verbose` option is on, so it should print what is triggering the reload.

If you take it for a spin and notice anything else that needs adjusting, let me know!
