### ISSUE TITLE
namedParams are not interpolated in examples

### ISSUE THREAD

**Issue by techtonik** [badges/shields#2427]
Are you experiencing an issue with...
 - [x] [shields.io](https://shields.io/#/)

:beetle: **Description**
Go https://shields.io/ enter `gem` watch this.

![image](https://user-images.githubusercontent.com/515889/49246186-5281b680-f425-11e8-9203-857205c52c50.png)

Click and watch this.

![image](https://user-images.githubusercontent.com/515889/49246211-60cfd280-f425-11e8-8979-22e349dcc9aa.png)

`formatador` string that is passed as `namedParams` here - https://github.com/badges/shields/blob/97139648129eaed8293307a0d175160f98786aba/services/gem/gem-version.service.js#L51 - is only interpolated in Example field, but not in Image field, making it broken.

**Comment by paulmelnikow** [comment]
Not lovely I agree, though that's the expected behavior. The idea is to show the developer what part they need to fill in. The CircleCI badge long appeared this way with `USER` and `REPO` in that field, and it's now the preferred standard for all badges.

A minor tweak, to make this a little nicer, could be to hide the live preview until all the colons have been filled in.

The real fix is #701, and there is a lot of progress. Examples will need to be switched over to patterns to work this way, but that's underway in #1961. And there's a PR to generate a new file format, with enough information for the frontend, in #2397. (That's the blocker right now.)

**Comment by paulmelnikow** [comment]
> A minor tweak, to make this a little nicer, could be to hide the live preview until all the colons have been filled in.

This has been implemented in #2441.

**Comment by paulmelnikow** [comment]
Let's track this in #2496.
