### ISSUE TITLE
Github revision count

### ISSUE THREAD

**Issue by CamiloMM** [badges/shields#244]
Pretty silly, but what about something like...

> ![](http://img.shields.io/badge/revision-123-brightgreen.svg)

...and a license badge that pulls the license from GitHub?

**Edit:** as per @waldyrious comment, let's make this just the revision count request then.

**Comment by paulmelnikow** [comment]
At this point, we have badges for latest release number and commits since latest release. It's not completely clear to me what's being asked for here, and whether it's the same as one of those things or not.

I'd ask that, if anyone who participated here would like to revive this request, please do so by opening a new issue. 😄
