### ISSUE TITLE
waffle.io support

### ISSUE THREAD

**Issue by marceloboeira** [badges/shields#257]

**Comment by hairyhenderson** [comment]
+1

While not really relevant to this issue, just want to mention that it looks like SVGs badges are supported by waffle.io too: i.e. 
https://badge.waffle.io/potherca/GraphvizWebEditor.svg?label=waffle:%20ready%20for%20development

This at least makes the badge a bit prettier when using retina displays etc.

...actually, after a bit of digging it looks like _all_ badges served by badge.waffle.io are actually SVGs, even when I request a `.png` URL. (this is weird, right?)

**Comment by marceloboeira** [comment]
@hairyhenderson  nice tip :+1:

**Comment by espadrine** [comment]
> ...actually, after a bit of digging it looks like all badges served by badge.waffle.io are actually SVGs, even when I request a .png URL. (this is weird, right?)

It is something we recommend. The file extension is ignored by browsers. The major thing they look at is the HTTP header which sets the content type. As a result, that trick allows all users to switch to the better image without requiring all of them to edit their URLs.

**Comment by zbeekman** [comment]
+1

**Comment by metaraine** [comment]
Would love the flat design for this badge :+1:

**Comment by marceloboeira** [comment]
@metaraine yeap!

**Comment by duckinator** [comment]
What's the status on this, and is there anything I can do to help out with it?

**Comment by ELLIOTTCABLE** [comment]
:+1: (also: ohai, @duckinator)

**Comment by Kubuxu** [comment]
:+1:

**Comment by koistya** [comment]
:+1: missing the flat style.

**Comment by chezstov** [comment]
:+1:

**Comment by nwalters512** [comment]
Any updates on this? Would love to see the flat style in use.

**Comment by espadrine** [comment]
Waffle's API was finalized last week: https://github.com/waffleio/waffle.io/issues/468.

```
curl 'https://api.waffle.io/potherca/GraphvizWebEditor/columns'
```

List of objects with those relevant fields:

- `displayName`: name to use by default on the left.
- `issues`: list of issues; count them and put that figure on the right of the badge.
- `label.name`: name to filter with.
- `label.color`: color to use if set.

Proposed shields URL:

- `/waffle/column/potherca/GraphvizWebEditor.svg` shows the number of `ready` issues.
- `/waffle/column/potherca/GraphvizWebEditor/in progress.svg` shows the number of `in progress` issues.

Any objection to that design?

**Comment by hairyhenderson** [comment]
@espadrine - maybe missing something, but why would `column` be part of the path?

Why not just `/waffle/potherca/GraphvizWebEditor.svg`?

**Comment by caalberts** [comment]
flat design :+1:

**Comment by lots0logs** [comment]
:+1:

**Comment by espadrine** [comment]
> Why not just /waffle/potherca/GraphvizWebEditor.svg?

We've had tons of issues in the past with vendors that offered more than one product, and suddenly we had a `/vendor/` path and a `/vendor/product/` path for every other thing. It's easier and more intuitive to start off with the second form.

**Comment by hairyhenderson** [comment]
@espadrine - :+1: that makes sense.

**Comment by Juanlu001** [comment]
:+1: and subscribing :)

**Comment by klarkc** [comment]
+1 and subscribing

**Comment by nelson6e65** [comment]
:+1:

**Comment by espadrine** [comment]
This is not yet featured on the front page. It would be great if you could check that the implementation works. Here are two examples:

https://img.shields.io/waffle/column/potherca/GraphvizWebEditor.svg
https://img.shields.io/waffle/column/potherca/GraphvizWebEditor/waffle:%20in%20progress.svg

**Comment by evancohen** [comment]
Hey @espadrine, thanks for this! 

I'm having an issue with this badge, it should show [1 item in progress](https://waffle.io/evancohen/smart-mirror) (at the time of this writing), but it shows none...

https://img.shields.io/waffle/column/evancohen/smart-mirror/in%20progress.svg
![https://img.shields.io/waffle/column/evancohen/smart-mirror/in%20progress.svg](https://img.shields.io/waffle/column/evancohen/smart-mirror/in%20progress.svg) 
VS
https://badge.waffle.io/evancohen/smart-mirror.svg?label=in%20progress&title=In%20Progress
![https://badge.waffle.io/evancohen/smart-mirror.svg?label=in%20progress&title=In%20Progress](https://badge.waffle.io/evancohen/smart-mirror.svg?label=in%20progress&title=In%20Progress) 

I was a bit confused so I took a look at the API you described above:
```
curl 'https://api.waffle.io/evcohen/smart-mirror/columns'
```

It appears that I am missing the `issues` field in the API response, which is why [this](https://github.com/badges/shields/commit/27ef17defb263307c1ff6f13c71655100a5102b7#diff-78c12f5adc1848d13b1c6f07055d996eR4937) will always result in 0 for any tag that I try to use.

Looks like @klarkc has a similar issue (although the `issues` array exists in his curl response it's always empty):
https://img.shields.io/waffle/column/klarkc/gulp-github-automator.svg
![https://img.shields.io/waffle/column/klarkc/gulp-github-automator.svg](https://img.shields.io/waffle/column/klarkc/gulp-github-automator.svg)
This should be 10, but it's 0.

**Comment by espadrine** [comment]
@evancohen Thanks for detailing that issue! There's definitely something strange happening. For starters, while https://api.waffle.io/evcohen/smart-mirror/columns does not provide the `issues` field, https://api.waffle.io/evancohen/smart-mirror/columns does, but it is empty where it should contain an issue.

Here is an issue I raised on this subject: https://github.com/waffleio/waffle.io/issues/2466. I'd expect this API to be more resilient (and faster, assuming caching) in the future.

In the meantime, I will try to extend the GitHub issues badge to support label querying, which will look something like this: https://img.shields.io/github/issues-raw/evancohen/smart-mirror/in%20progress.svg. Unfortunately, obtaining the color and display name would require two GitHub requests in the general case, so that won't happen.

**Comment by nelson6e65** [comment]
Hmm... I was trying to use label title (`In%20Progress`), but did not work: 
`https://img.shields.io/waffle/label/nelson6e65/php_nml/In%20Progress.svg`
* Shield: [![Waffle.io](https://img.shields.io/waffle/label/nelson6e65/php_nml/In%20progress.svg)](http://waffle.io/nelson6e65/php_nml) 
* Original: [![Stories in Progress](https://badge.waffle.io/nelson6e65/php_nml.svg?label=wip&title=In%20progress)](http://waffle.io/nelson6e65/php_nml)

Then, I used github tag instead (Because I changed to use `wip` instead of default):
``https://img.shields.io/waffle/label/nelson6e65/php_nml/wip.svg``
[![Waffle.io](https://img.shields.io/waffle/label/nelson6e65/php_nml/wip.svg)](http://waffle.io/nelson6e65/php_nml) 

It should be documented that format is 
``https://img.shields.io/waffle/label/{user}/{repo}/{github_tag}.svg`` 
instead of 
``https://img.shields.io/waffle/label/{user}/{repo}/{waffle_label}.svg``.
