### ISSUE TITLE
Can you get the latest version of an artifact from a selfhosted Sonatype Nexus?

### ISSUE THREAD

**Issue by Andre601** [badges/shields#2622]
:question: **Question**

I try to find out, if you can get the latest version from an artifact from a selfhosted Nexus Repository, but I'm stuck with finding out, what exactly is meant with `:scheme` in the link...
I'm fairly new to that, so I'm happy for fast help.

**Comment by calebcartwright** [comment]
Hi @Andre601, we just recently added support for connecting to self-hosted Sonatype Nexus instances. Please note that you will need to use run your own [self-hosted instance of Shields](https://github.com/badges/shields/blob/master/doc/self-hosting.md) in order to build badges for a self-hosted Nexus instance. 

If I recall correctly, `scheme` is where you specify whether your instance is `http` or `https`

**Comment by Andre601** [comment]
This really helped me. Thank you.

**Comment by calebcartwright** [comment]
Glad to hear it! Let us know if you have any other questions
