### ISSUE TITLE
Apply math to number in dynamic badges

### ISSUE THREAD

**Issue by iderdik** [badges/shields#2625]
:clipboard: **Description**
Some APIs (looking at you Bing Maps) provide data in less than ideal formats (i.e. seconds). It would be great if we could apply simple math operators (in this case divide by 60 to get minutes). jq allows this e.g. `echo '{ "aaa": 120 }' | jq .aaa/60` displays `2`.

**Comment by calebcartwright** [comment]
Interesting. How would you imagine providing the desired operation (via additional query params, etc.)?

**Comment by iderdik** [comment]
It could be as part of the path parameter `($..somethingThatResolvesTonNumericValue) /60` or a separate query string parameter that uses the value as a token. `&formula={{result}}/60`

**Comment by paulmelnikow** [comment]
This isn't possible with `jsonpath`. I looked into doing this with `jq` which indeed has a lot more power; however we'd have to invoke a subprocess for each request. (I even dug into the codebase to see about porting it to JavaScript, and as fun as that sounds, that looks like a _really_ complicated job.)

Rather than create our own programming language 😁or use `eval`, my preference would be to handle cases like this using a custom endpoint: #2473.

This could be combined with an endpoint on RunKit: https://runkit.com/melnikow/version-from-requirements-txt

That example is relative a relatively complicated, though the concept could be applied to something much simpler.

**Comment by iderdik** [comment]
I'm trying to avoid running an intermediary server at all and just use the remote API -> badge. Would a js library like https://github.com/FGRibreau/jq.node be helpful here?

**Comment by paulmelnikow** [comment]
You don't have to run the intermediary server; something like RunKit could do it for you.

Ooh, jq.node looks neat! However it looks like it lets you run arbitrary JavaScript code. So I imagine it would need adaptation to be used as an expression language on our server.

**Comment by iderdik** [comment]
I took a look at Runkit endpoints - I hadn't seen that before, thanks! It did what I needed it to and seems to be the cleanest way to offload custom porcessing/formatting. Thanks for your help!

**Comment by paulmelnikow** [comment]
The [Endpoint badge][] is live!

If you decide to use the new feature, your feedback is much appreciated! Please feel free to comment on [the Endpoint beta issue][beta] if you have feedback or questions about how to use it.

[endpoint badge]: https://shields.io/#/endpoint
[tools]: https://github.com/badges/shields/issues/2259#issuecomment-444186589
[beta]: https://github.com/badges/shields/issues/2838
