### ISSUE TITLE
SVG by default

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2674]
It'd be nice to simplify our badge URLs by dropping `.svg` from the end of the URLs. While it's common to include a `.svg` extension on a badge URL, there are a bunch of native status badges which don't, and it's hardly a requirement.

This would be easy to do in the modern badges because it's only handled in one place. For the legacy badges… well, maybe it'll motivate us to get the refactor done! 😁

We could support extensionless SVG in the modern badges as an undocumented feature, and hold off on advertising to the world and it in the UI until everything is fixed. If we're going to create a new static badge URL (#2673) it might make sense to advertise it for that.

I _think_ our Cloudflare rules apply regardless of file extension, though we'd need to verify that as well.

**Comment by conao3** [comment]
I am not in a position to give an opinion, but I will write information for reference.

codacy badge has no `.svg` suffix.
When writing Readme in .org document, it is necessary to execute workaround to suffix `?.svg` due to GitHub parser problem. (Perhaps should fix GitHub's renderer, but I do not have that skill...)

I think that it is a good thing to be able to omit the `.svg` suffix in general situations, but I think it would be nice if you do not lose the current specification for the .org user.

This codacy badge issue has already reported.

Rendered: https://github.com/conao3/playground/tree/codacy-support
Raw .org document: https://raw.githubusercontent.com/conao3/playground/codacy-support/Readme.org

**Comment by paulmelnikow** [comment]
It's useful to know there are some unusual cases where the extension is helpful. This is about [org mode](https://orgmode.org/), correct?

**Comment by conao3** [comment]
Yes! `.org` document is plain text along the format of org mode.

**Comment by paulmelnikow** [comment]
Since #2863 is done, we can do this now!
