### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by digi-brains** [badges/shields#2785]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

GitHub _Release_ returns the error: `repo not found`

:link: **Link to the badge**

https://img.shields.io/github/release/digi-brains/ya-router.svg

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
There are 2 things that are slightly confusing here.

GitHub shows your tags as "releases" through the front-end: https://github.com/digi-brains/ya-router/releases
but not the API: https://api.github.com/repos/digi-brains/ya-router/releases

Its hard for us to show a good error message in this case because `/releases/latest` gives a 404 error if the repo doesn't exist or if the repo does exist but has no releases (more info: https://github.com/badges/shields/issues/2017 )

The solution here is to either use the tag badge ![](https://img.shields.io/github/tag/digi-brains/ya-router.svg) -  https://img.shields.io/github/tag/digi-brains/ya-router.svg or publish your tags as [releases](https://help.github.com/articles/creating-releases/)

**Comment by digi-brains** [comment]
Very interesting. I have always been under the impression pushing the tag, in fact, created a proper release. Additionally I was unaware of the tag badge. Thanks, now I know!

**Comment by cagross** [comment]
Hello.  I'm also experiencing this issue.  I've confirmed that the front end of my repo shows releases, yet the API shows no releases:

- Here is the [repo in-question](https://github.com/cagross/outdated-plugin-notifier)). 

- Here are the releases displayed on the repo's front-end:  https://github.com/cagross/outdated-plugin-notifier/releases

- Here is what the API sees:  https://api.github.com/repos/cagross/outdated-plugin-notifier/releases

This solution was offered above:

> publish your tags as releases

But I am a little unclear on how to implement that.  My tags already appear to be published as releases ([screenshot](https://i.imgur.com/nmZh2Cw.jpg)).  So what should my next step be?

Like @sageworksstudio, I also did not explicitly create releases.  When I pushed my first tag to the remote repo, it seemed to auto-create a release for it.  At the time, that surprised me.  
.
FYI I'm already using the tag badge as a fallback solution.  I'd like to get the release working if possible.

Thanks.

**Comment by sageworksstudio** [comment]
@cagross 

What is confusing you is exactly what confused me. That when you push a tag, it shows up under your releases tab in GitHub, but not in the API.

To solve the issue you just need to actually click the "Draft a new release" button, and _manually_ create a new release. Only then will your release will show up in the API. Also sometimes the API is behind what you see in the repo, so give it a minute if the badge doesn't immediately work as expected.

As far as I'm concerned this is an issue with GitHub. Although maybe it's possible that there is a way to create a release when pushing a new tag? But I'm unaware of how to do that if it's possible.

Hope this helps.

**Comment by paulmelnikow** [comment]
By the way, this is a really common challenge that people run into. If anyone is up for adding documentation to the Shields badge popup for the GitHub releases badge which explains this, that'd be much appreciated! There's a `documentation` key in https://github.com/badges/shields/blob/master/services/github/github-release.service.js which can be filled with HTML. If you need help making that change, any of the maintainers could guide you.

**Comment by cagross** [comment]
@sageworksstudio OK thanks for that.  

> To solve the issue you just need to actually click the "Draft a new release" button, and manually create a new release. 

OK I understand that the API doesn't think I have any releases. But if I manually create new releases now, I'm a bit confused as to what will occur.  The GitHub front-end seems to already indicate that my repo has four releases--they are attached to the expected and desired tags/commits ([screenshot](https://i.imgur.com/axmPDbI.jpg)).  Let's say I follow your instructions and manually create a new release for the first release.  That has this info:

```
date:  Nov 4, 2019 
tag: v1.0.0
tag message:  Initial version.
Commit:  d3002bd
```

What will the GitHub 'releases' front-end indicate after I manually create this release?  Will there be two releases attached to tag v1.0.0?  Or will my new release overwrite the existing release? Or perhaps the front-end is a bit misleading, and there *are* no actual releases yet?

Also, currently the GitHub front-end indicates my four releases are from four different dates in the past.  These are the correct dates.  If I manually create four releases now, will these four new releases all be from the same date, i.e. today's date?  That would be undesirable.

@paulmelnikow I'd be happy to help out with that.  But first let me fully understand what is occurring, and the proper way to prevent/resolve it.  I'll follow up with you here (or anywhere else you'd like) when that's complete.

**Comment by calebcartwright** [comment]
@cagross - fundamentally the problem here is that git tags and GitHub releases are separate, distinct types of entities. The GitHub platform is very well aware of the distinction (so you won't confuse GitHub), but there's one place in the GitHub UI that often confuses users into thinking that git tags and GitHub Releases are synonymous.  

[tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are an entity provided by git (the VCS) and tags exist as refs within the actual repository. [GitHub Releases](https://help.github.com/en/github/administering-a-repository/about-releases) are a higher level construct provided by GitHub the platform. 

The GitHub Release construct is based on a git tag, but can (and usually does) contain a lot of extra content ranging from release notes/changelogs to assets/binaries. GitHub Releases don't exist within git itself, and GitHub does not create a corresponding Release for you when you push a git tag.

You've created and pushed git tags in your repo, but you've never actually created any GitHub Releases for any of those tags:
https://github.com/cagross/outdated-plugin-notifier/releases 

the same is true in this very repo:
https://github.com/badges/shields/releases

Here are some repos that _have_ created GitHub Releases for their tags
https://github.com/mochajs/mocha/releases
https://github.com/go-task/task/releases

and one where GitHub Releases were created for some, but not all, git tags (so you can see how the UI differentiates between them here)
https://github.com/swellaby/azp-bump/releases

The confusing portion of the GitHub UI is that the release page for a repository lists Releases **and** tags with subtle indicators in the UI to indicate which is a git tag and which is a GitHub Release. However, in repos that have no actual Releases, there's nothing to differentate so a lot of people incorrectly assume that their git tags are also actually GitHub Releases.

**Comment by cagross** [comment]
OK thanks for that.  It was very comprehensive and illuminating.

> The confusing portion of the GitHub UI is that the release page for a repository lists Releases and tags with subtle indicators in the UI to indicate which is a git tag and which is a GitHub Release. However, in repos that have no actual Releases, there's nothing to differentate so a lot of people incorrectly assume that their git tags are also actually GitHub Releases.

Indeed this is the confusing part.  If a Release page contains no releases, it would help if it explicitly indicated something like that.  It's especially confusing for the noobs :-)

ANYWAY, now that we've established my GitHub repo has no releases, I'd like to properly create them.  My repo has four tags:  v1.0.0, v1.0.1, v1.0.2, v1.0.3 and I'd like to simply create a release for each one.  In light of that, I would simply click 'Draft a new release,' then enter one of my four tags, a release title, and a release description.  Am I on the right track there?

**Comment by chris48s** [comment]
yep - for more info, github has a walkthough on creating a release from a tag you can follow: https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

we could probably link to that in the docs

**Comment by cagross** [comment]
@chris48s OK thanks for that.  I was able to add my releases as desired and as expected.  In-turn, they appeared in the GitHub web API for my repo, and the 'GitHub release (latest by date)' shield was able to display the correct info.  So my issue is resolved--great!

@paulmelnikow At this point, if you still want, I can add the documentation you mentioned.  But to be clear, what is the, "...Shields badge popup for the GitHub releases badge?"  Is it [this modal window](https://i.imgur.com/oRDXEzq.jpg)?
