### ISSUE TITLE
can not read cocoapods version

### ISSUE THREAD

**Issue by Danie1s** [badges/shields#2875]
https://img.shields.io/cocoapods/v/Tiercel.svg

this is my repo：
https://github.com/Danie1s/Tiercel

**Comment by chris48s** [comment]
When we query cocoapods for your package, we call https://trunk.cocoapods.org/api/v1/pods/Tiercel/specs/latest which is returning a 404. Normally this would return the podspec for a package (e.g: https://trunk.cocoapods.org/api/v1/pods/AFNetworking/specs/latest - a working example).

The API is giving us a 404 and we're reporting 'not found', so we are reporting the data the API gives us. This is somewhat unexpected though because I can see your package https://cocoapods.org/pods/Tiercel does link to a podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/2/3/c/Tiercel/2.0.0/Tiercel.podspec.json

Maybe try raising an issue with cocoapods support?

**Comment by paulmelnikow** [comment]
Is the API shutting down, I wonder? Both trunk.cocoapods.org links in that post are returning Forbidden.

**Comment by Danie1s** [comment]
I have updated the version

**Comment by paulmelnikow** [comment]
The badge looks okay now. Those endpoints still won't load in the browser, though they do open correctly with `curl -L`.
