### ISSUE TITLE
More specific node version badge?

### ISSUE THREAD

**Issue by Martii** [badges/shields#308]
Is it possible to get a full version of node.js in a badge? ~~Currently I'm looking at ![node badge](http://img.shields.io/node/v/gh-badges.svg) with 0.10.x... which is better than nothing... but~~ it would be nice to see the `.33` that it is currently on.

Thanks in advance and I love these little things... nice work. :)

**Comment by danday74** [comment]
Since no-one has covered this here the format for engines is ...

"engines": {
    "node": ">= 0.6"
 }

https://img.shields.io/node/v/<YOUR_PACKAGE>.svg

**Comment by Martii** [comment]
1. `package.json` may not always be on npmjs.com ... which is a related issue. The `private` bit may be set in which case it won't be on npmjs.com
2. More dynamic detection of a specific latest version, say 6.x, showing the latest version there is what is needed as alluded to with the `engines` property in the prior reply.

It's okay if it doesn't get done as the syntax was already mentioned as not changing... although another virtual field/parameter could be possible perhaps with the example of `http://img.shields.io/badge/node-v0.10.33-orange.svg` becoming `http://img.shields.io/badge/node-v0.10.latest-orange.svg` which could show the last *(latest)* version of that *node* version. e.g. a buzz word of `latest` invoking some process of finding it. In our case we would need in our README.md a value of something like `http://img.shields.io/badge/node-v6.0.latest-orange.svg`. As it sits right now we go visit https://nodejs.org/en/docs/ and see what it is with a click through.

**Comment by paulmelnikow** [comment]
Think this should be resolved by our existing node version support, updated in #1144, and our badge which pulls data from package.json on github, added in #739.

If there's something further we should do, would someone please open a new issue?

**Comment by Martii** [comment]
Examples taken from:
* https://github.com/badges/shields/pull/1144/files#diff-20b51e3176fb8c62d5ce21aee43e6cd1R512
* https://github.com/badges/shields/pull/1144/files#diff-20b51e3176fb8c62d5ce21aee43e6cd1R516
* https://github.com/badges/shields/pull/1144/files#diff-20b51e3176fb8c62d5ce21aee43e6cd1R520
* https://github.com/badges/shields/pull/1144/files#diff-20b51e3176fb8c62d5ce21aee43e6cd1R524

Rendered:

* ![`https://img.shields.io/node/v/passport.svg`](https://img.shields.io/node/v/passport.svg)
* ![`https://img.shields.io/node/v/@stdlib/stdlib.svg`](https://img.shields.io/node/v/@stdlib/stdlib.svg)
* ![`https://img.shields.io/node/v/passport/latest.svg`](https://img.shields.io/node/v/passport/latest.svg)
* ![`https://img.shields.io/node/v/@stdlib/stdlib/latest.svg`](https://img.shields.io/node/v/@stdlib/stdlib/latest.svg)


hmm... now I'm confused.

**Comment by paulmelnikow** [comment]
That PR is waiting for deploy. To see when that happens, you can keep an eye on https://github.com/badges/shields/tree/gh-pages.

I just pushed the latest to the staging server.

* ![`https://shields-staging.herokuapp.com/node/v/passport.svg`](https://shields-staging.herokuapp.com/node/v/passport.svg)
* ![`https://shields-staging.herokuapp.com/node/v/@stdlib/stdlib.svg`](https://shields-staging.herokuapp.com/node/v/@stdlib/stdlib.svg)
* ![`https://shields-staging.herokuapp.com/node/v/passport/latest.svg`](https://shields-staging.herokuapp.com/node/v/passport/latest.svg)
* ![`https://shields-staging.herokuapp.com/node/v/@stdlib/stdlib/latest.svg`](https://shields-staging.herokuapp.com/node/v/@stdlib/stdlib/latest.svg)

The server doesn't have the right font installed which is why the letter spacing is off.
