### ISSUE TITLE
Add ability to transform query params on redirector services

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#3118]
Dialog in #3074, in particular https://github.com/badges/shields/pull/3074#issuecomment-466714842

Use case/benefit is being able to simplify route patterns by moving certain optional params (for example tokens, urls, etc.)  from route to query params

**Comment by calebcartwright** [comment]
So I was originally only thinking about this in the context of a redirect being able to transform a route param to a query param, but as I've started working on this I realized that there may be a scenario when one would want to rename a query param (as part of a redirect, or even just in general)

My current thinking/assumption: https://github.com/badges/shields/pull/3042 added functionality that allows a service to specify query params via a Joi schema, and therefore renaming of a query param (`?foo=...` --> `?bar=...`)  would best be handled via Joi's [rename](https://github.com/hapijs/joi/blob/master/API.md#objectrenamefrom-to-options) functionality in the services query param schema.

Accordingly, I'm not currently planning on adding functionality to the redirector for renaming/transforming one query param to another query param. 

Please let me know if I've got anything wrong there and/or if anyone feels differently

**Comment by paulmelnikow** [comment]
Redirecting is a bit different from renaming. Redirecting is more cache-friendly. It's _nice_ for the user, and I think less confusing, to canonicalize the query params as we're rewriting the URL, particularly the badge-specific query params. Though that probably is relatively low priority.

As I think about it, the more important case of redirecting the query params would be in the context of an existing service (i.e. where the route is the same, but the query params are rewritten). So that feels like a different project entirely.

**Comment by calebcartwright** [comment]
> So that feels like a different project entirely.

So agreement that it's sufficient for the redirector `transformQueryParams` function to only allow for converting a route/pattern param to a query param as part of the redirect?

I.e. redirect: `/codecov/c/token/abc123def456/github/foo/bar.svg` -> `/codecov/c/github/foo/bar.svg?token=abc123def456`

**Comment by paulmelnikow** [comment]
Yep!
