### ISSUE TITLE
Maven URL badge: invalid response data

### ISSUE THREAD

**Issue by bsideup** [badges/shields#3180]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
Shields.io doesn't seem to support Spring's versioning scheme.

Spring projects use `1.2.3.M4` notation for the milestone releases.

:link: **Link to the badge**
[![](https://img.shields.io/maven-metadata/v/https/repo.spring.io/milestone/io/projectreactor/tools/blockhound/maven-metadata.xml.svg?label=Milestone)](https://repo.spring.io/milestone/io/projectreactor/tools/blockhound/)
https://img.shields.io/maven-metadata/v/https/repo.spring.io/milestone/io/projectreactor/tools/blockhound/maven-metadata.xml.svg?label=Milestone

Targets https://repo.spring.io/milestone/io/projectreactor/tools/blockhound/maven-metadata.xml

:bulb: **Possible Solution**
Support "1.2.3.M4"-like notation

**Comment by calebcartwright** [comment]
The issue is not with the version format, but that our schema currently balks when there's only a single version due to how the xml is parsed.

Adding a `.single()` to the schema [here](https://github.com/badges/shields/blob/master/services/maven-metadata/maven-metadata.service.js#L14) should resolve this (validated in my local env)

**Comment by bsideup** [comment]
@calebcartwright thanks for fixing it! 👍
