### ISSUE TITLE
Reddit subreddit subscribers badge

### ISSUE THREAD

**Issue by crazy-max** [badges/shields#3185]
:clipboard: **Description**

> Which service is this badge for e.g: GitHub, Travis CI

Reddit

> What sort of information should this badge show?
> Provide an example in plain text e.g: "version | v1.01" or as a static badge
> (static badge generator can be found at https://shields.io)

Subreddit subscribers count badge like :

[![](https://img.shields.io/badge/follow%20r%2FPortapps-8-red.svg)](https://www.reddit.com/r/Portapps)

:link: **Data**

> Is there a public API?

Here : https://www.reddit.com/r/Portapps/about.json (replace _Portapps_ with another subreddit)

> Does the API requires an API key?

Seems not required

> Link to the API documentation.

https://www.reddit.com/dev/api/#GET_r_{subreddit}_about

:microphone: **Motivation**

Like Twitter badge, display subscribers count for a subreddit :)
I have already worked on previous badges, I can work on it if you want ;)

**Comment by calebcartwright** [comment]
> I have already worked on previous badges, I can work on it if you want ;) 

Awesome!

**Comment by RedSparr0w** [comment]
Just adding a quick note that you can also create this badge with the `dynamic-json` badge:
`https://img.shields.io/badge/dynamic/json.svg?label=r/Portapps%20subscribers&query=$.data.subscribers&url=https://www.reddit.com/r/Portapps/about.json`
![](https://img.shields.io/badge/dynamic/json.svg?label=r/Portapps%20subscribers&query=$.data.subscribers&url=https://www.reddit.com/r/Portapps/about.json)

But i think this could be a good addition to add to shields.

**Comment by JosepBernad** [comment]
Guys, today I'm starting with this issue. I have an initial question: should we allow the user to change the color o use the reddit's color? Thanks!

**Comment by JosepBernad** [comment]
I don't know exactly how to do it, but I've created a new branch in my fork in order to show you my progress. 
Am I doing the workflow correctly?

[That](https://github.com/JosepBernad/shields/commit/13c6ed8e2bde06487f77f73d163dba3be9587143)'s the last commit where I've just pushed what I've done. I'm a little bit stuck because I don't know how to solve the issues. 

I've been using other services in order to learn how it works.

**Comment by calebcartwright** [comment]
#3443 is ready to merge to add this badge, but there is one item we'd like to get your thoughts on @crazy-max as the OP of this issue. 

The new badge #3443 will add the badge using our social badge style, so the badges will look like:
![](https://img.shields.io/badge/follow%20r%2FPortapps-13-blue.svg?style=social&logo=reddit)

instead of the badge style discussed above:
![](https://img.shields.io/badge/follow%20r%2FPortapps-13-blue.svg)

I think the social style is a better fit considering, but what are your thoughts?

**Comment by crazy-max** [comment]
@calebcartwright We can do both using [styles](https://shields.io/#styles) arg no ?

**Comment by calebcartwright** [comment]
Thanks @crazy-max  - I was thinking more about the fact that the _default_ style is different, but yes you should still be able to override the style. I also believe that the fact that default style is social means that the links are embedded into the badge image itself (which I believe still holds true even if you change the style).

**Comment by crazy-max** [comment]
@calebcartwright Yes indeed we could use the same implementation as twitter for example.

**Comment by calebcartwright** [comment]
Thanks @crazy-max! I'll go ahead and merge

**Comment by calebcartwright** [comment]
Closed in https://github.com/badges/shields/commit/d685cde52bd26070bccdf50cc555dfcb9118f130

It should be deployed in a few days, but anyone interested can track the deployment status [here](https://github.com/badges/shields/pull/3443#issuecomment-494985110)
