### ISSUE TITLE
Feature Request: Commits since a specific branch (vs just master) 

### ISSUE THREAD

**Issue by desimaniac** [badges/shields#3204]
:clipboard: **Description**

Would like to request ability to define a non-master branch when adding "commits since" badge. 

Line below shows that it is hardcoded to only compare with `master`.

https://github.com/badges/shields/blob/24bc7bcfc341c044c9ec815487fa07585b038ec2/services/github/github-commits-since.service.js#L73

**Comment by paulmelnikow** [comment]
Sounds like a good idea!

That badge is one of the last to be refactored, so that should happen first! Alternatively if one of the maintainers decides to pick that up, maybe this could be rolled in.

If you're interested in helping with the refactor, you're welcome to! See #2863 for more information on that.

**Comment by PyvesB** [comment]
Hey @desimaniac!

Thanks for your feature request, I've taken care of the implementation. Here is the new badge in action on our staging environment:
https://shields-staging.herokuapp.com/github/commits-since/badges/shields/d533bbd559fb6cfc7c2c8be13678529c0449e749/gh-pages.svg
![](https://shields-staging.herokuapp.com/github/commits-since/badges/shields/d533bbd559fb6cfc7c2c8be13678529c0449e749/gh-pages.svg)

It will be available on our live servers in the next few days. 😉 

Cheers,

Pyves
