### ISSUE TITLE
Packagist badges: invalid response data

### ISSUE THREAD

**Issue by cs-eliseev** [badges/shields#3238]
Are you experiencing an issue with...

- \[x] [shields.io](https://img.shields.io/packagist/l/cse/helpers-json.svg?style=flat-square)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

MIT Packagist license is not set. Display information: "invalid response data".

:link: **Link to the badge**
https://img.shields.io/packagist/l/cse/helpers-json.svg
[![Packagist](https://img.shields.io/packagist/l/cse/helpers-json.svg?style=flat-square)](https://github.com/cs-eliseev/helpers-json/blob/master/LICENSE.md)

**Comment by calebcartwright** [comment]
Problem looks to be related to the schema we're using. 

Relevant snippet from the API response shows that the `dev-master` object key does not contain an `extra` key
```json
"dev-master": {
  "name": "cse/helpers-json",
  "description": "The helpers allows you to JSON processing. Encode, decode, check error, throw exception - all this is available in this library.",
  "keywords": [],
  "homepage": "https://github.com/cs-eliseev/helpers-json",
  "version": "dev-master",
  "version_normalized": "9999999-dev",
  "license": [],
  "authors": [],
  "source": {...},
  "dist": {...},
  "type": "library",
  "time": "2019-03-25T08:37:18+00:00",
  "autoload": {...},
  "require": {...},
  "require-dev": {...}
},
```

But I believe the schema has `extra` as a required key: https://github.com/badges/shields/blob/master/services/packagist/packagist-base.js#L11

**Comment by stevebauman** [comment]
I'm getting this as well with downloads when I never used to have an issue:

<img src="https://img.shields.io/packagist/dt/adldap2/adldap2.svg?style=flat-square"/>
<img src="https://img.shields.io/packagist/dt/adldap2/adldap2-laravel.svg?style=flat-square">

**Comment by calebcartwright** [comment]
Same underlying issue, I'm working on fixing it now

**Comment by stevebauman** [comment]
Oh okay awesome thanks so much! :smile:

**Comment by calebcartwright** [comment]
Alright I believe I've got it fixed in the linked PR, viewable/testable in the associated staging app @ https://shields-staging-pr-3239.herokuapp.com/ 

Here's the corresponding badges mentioned in this thread using the staging app endpoint:

https://shields-staging-pr-3239.herokuapp.com/packagist/l/cse/helpers-json.svg
![](https://shields-staging-pr-3239.herokuapp.com/packagist/l/cse/helpers-json.svg)

https://shields-staging-pr-3239.herokuapp.com/packagist/dt/adldap2/adldap2.svg
![](https://shields-staging-pr-3239.herokuapp.com/packagist/dt/adldap2/adldap2.svg)

https://shields-staging-pr-3239.herokuapp.com/packagist/dt/adldap2/adldap2.svg
![](https://shields-staging-pr-3239.herokuapp.com/packagist/dt/adldap2/adldap2-laravel.svg)

I'm signing out for the night but if anyone else has any other badges that are currently broken, try checking them out in the staging app, and let me know if they're still broken even in the staging app

**Comment by kylekatarnls** [comment]
I have the badge broken too:
![Carbon downloads](https://img.shields.io/packagist/dt/nesbot/carbon.svg)

And shields-staging-pr-3239.herokuapp.com fix it:
![Carbon downloads](https://shields-staging-pr-3239.herokuapp.com/packagist/dt/nesbot/carbon.svg)

Thanks, hope to see it merged.

**Comment by cs-eliseev** [comment]
Okay awesome thanks so much! =)

**Comment by kylekatarnls** [comment]
Hello, I see you closed this but right now as you can see in my comment, the version on img.shields.io is still "invalid response data" and the herokuapp is not available neither. Would we see this on shields.io soon?

**Comment by kylekatarnls** [comment]
Sorry, I did not understood the procedure, it's a auto-close from the PR and deployment is in progress. Great!

**Comment by calebcartwright** [comment]
FYI the fix has been deployed, so your packagist badges should be working again @ https://img.shields.io/packagist/**

**Comment by stevebauman** [comment]
Thanks again for the quick fix @calebcartwright, much appreciated!
