### ISSUE TITLE
npm dev dependency version badge not working with scoped dependencies

### ISSUE THREAD

**Issue by kimseongrim** [badges/shields#3271]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

#### use:
/npm/dependency-version/react-boxplot/dev/@babel/core
https://img.shields.io/npm/dependency-version/react-boxplot/dev/@babel/core.svg

#### expected:
@babel/core  ^7.0.0

#### result:
404 badge not found

**Comment by chris48s** [comment]
The reason this isn't working is because you're missing the user/org of the repo.

I think you're trying to do this:

![](https://img.shields.io/github/package-json/dependency-version/paulmelnikow/react-boxplot/dev/@babel/core.svg) - https://img.shields.io/github/package-json/dependency-version/paulmelnikow/react-boxplot/dev/@babel/core.svg

**Comment by calebcartwright** [comment]
The modal window in the UI still looks buggy to me, as it's missing the field for the username:

![image](https://user-images.githubusercontent.com/13042488/55674282-4c3e9380-5878-11e9-9940-f27a86dce7f8.png)

**Comment by calebcartwright** [comment]
@chris48s - I still think this is a bug with npm badge. If I'm wrong or missing something please let me know though.

The npm dependency version and github package.json version badges are different. The package.json version badge can indeed be used as work around, but I think the [route pattern for the npm dependency version badges](https://github.com/badges/shields/blob/master/services/npm/npm-dependency-version.service.js#L17 ) can't handle scoped dependencies due to the extra `/` scope deps add.

**Comment by chris48s** [comment]
Oh yes. You're right - sorry. I hadn't noticed that we have 2 slightly different approaches to npm `dependency-version`
