### ISSUE TITLE
Coverity badge always gets "inaccessible" status

### ISSUE THREAD

**Issue by mity** [badges/shields#3334]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The Coverity Scan badge for [MD4C](https://github.com/mity/md4c) project always shows in a gray color with the status message as "inaccessible". Noticed this few days ago for the first time. But before that it used to work correctly for a long time.

I've just checked https://scan.coverity.com/projects/mity-md4c/badge.json and it seems to get the following JSON correctly:
```
{"project":"mity/md4c","status":"passed","message":"passed"}
```

:link: https://img.shields.io/coverity/scan/mity-md4c.svg?label=coverity%20scan

**Comment by calebcartwright** [comment]
Thanks @mity taking a look now, will update when we have more info

**Comment by calebcartwright** [comment]
Looks like there's an issue in the cert chain, below is the error we're getting internally:

`Inaccessible: unable to verify the first certificate`

Very similar underlying issue to #1956

**Comment by mity** [comment]
I see.

Well, the question is whether it makes any sense to be stricter then browsers are.

**Comment by calebcartwright** [comment]
> Well, the question is whether it makes any sense to be stricter then browsers are.

This isn't due to anything we're doing explicitly. It's just the default behavior of many http clients. Why the browsers operate the way they do vs. those http clients is an entirely separate conversation 😄 

The underlying issue is related to what sounds like a recently introduced issue in Coverity's certificate chain. We're mulling some options on if/how we could potentially work around such issues in the upstream services (like Coverity). However, ideally those services would resolve their certificate issues vs. us having to disable/relax ssl validation on our end.

**Comment by mity** [comment]
> This isn't due to anything we're doing explicitly. It's just the default behavior of many http clients. Why the browsers operate the way they do vs. those http clients is an entirely separate conversation 😄

Ok.

> The underlying issue is related to what sounds like a recently introduced issue in Coverity's certificate chain. We're mulling some options on if/how we could potentially work around such issues in the upstream services (like Coverity). However, ideally those services would resolve their certificate issues vs. us having to disable/relax ssl validation on our end.

I can fully understand that. But my attempts to contact them (for some other minor issue like [the service not working at all for some project](https://github.com/mity/centijson/issues/1)) all failed, and I never got any response from them, so I am skeptical. :-(

**Comment by calebcartwright** [comment]
Understood. I'll make sure that if we add a work around on our end that we include that support for our Coverity badge as well.

**Comment by jarun** [comment]
This affects one of my projects ([bcal](https://github.com/jarun/bcal)) too.

**Comment by calebcartwright** [comment]
All Coverity badges are going to show as `inaccessible` due to an issue in the Coverity service's cert chain. 

We may deploy a work around in the near future, but I'd still suggest that folks try to get in touch with Coverity to see if they can resolve those cert issues

**Comment by jarun** [comment]
Thanks for the quick response. I'll drop a mail right away. However, their response time is painfully slow in my experience.

**Comment by calebcartwright** [comment]
FYI we've updated things on our end so that requests for Coverity badges will explicitly disable the strict ssl check, thus restoring Coverity. 

Once #3336 is deployed to prod your badges will automatically start working again ([this](https://github.com/badges/shields/pull/3336#issuecomment-485150785) comment will track the status of that deployment). 

For a visual, here's the two Coverity badges referenced above from our staging app:

https://shields-staging.herokuapp.com/coverity/scan/mity-md4c.svg?label=coverity%20scan
![](https://shields-staging.herokuapp.com/coverity/scan/mity-md4c.svg?label=coverity%20scan)

https://shields-staging.herokuapp.com/coverity/scan/jarun-bcal.svg
![](https://shields-staging.herokuapp.com/coverity/scan/jarun-bcal.svg)

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Thank you!
