### ISSUE TITLE
Tag Dockerhub releases

### ISSUE THREAD

**Issue by nigredo-tori** [badges/shields#3558]
:clipboard: **Description**

We already have a `Dockerfile`, why make users [build it](https://github.com/badges/shields/blob/544d7d3648d8fa97643d7d387cb8e96eb5ddfec6/doc/self-hosting.md#docker) manually? There are, of course, some custom `shields` images floating around, but those seem to be poorly maintained/supported.

A relatively easy way to do this would be to set up an automatic build on Dockerhub, as described [here](https://docs.docker.com/docker-hub/builds/), which would build a tagged image for each Git tag. There are also some automatic tests there, though I can't find a simple way to pipe their results back to GitHub PRs.

An alternative would be to wire up image building/publishing in the CI script.

**Comment by calebcartwright** [comment]
Thanks @nigredo-tori - providing an "official" Shields docker image is something we want to do, and is on our roadmap. No timeline on delivering it though

**Comment by niccokunzmann** [comment]
> An alternative would be to wire up image building/publishing in the CI script.

Dockerhub can build images if one sends a request to a certain URL. I am in favor of having the CI-Script send the request to build because then, the docker image only gets build after the tests are successful.
I never built docker images for tags only, so I do not know how to configure this on dockerhub. Fromwhat I saw, I think, it is quite easy.

**Comment by nigredo-tori** [comment]
>  I am in favor of having the CI-Script send the request to build because then, the docker image only gets build after the tests are successful.

You seem to be talking about **build triggers**. It [should be possible](https://github.com/docker/hub-feedback/issues/330#issuecomment-138886896) to trigger the build for a specific reference. However the lack of any official documentation for these is a major red flag.

>  I never built docker images for tags only, so I do not know how to configure this on dockerhub. Fromwhat I saw, I think, it is quite easy.

Extremely. It's a Branch/Tag combobox, plus some simple string interpolation for building the Docker tag string.

**Comment by paulmelnikow** [comment]
Agreed this is a good idea.

We've had some discussion about providing a changelog for self-hosting, to correspond with tagged releases, probably using the date. So far no one has laid the groundwork for that. Perhaps we could run docker builds for those tagged releases.

Running another docker build for master also seems like a good idea; it might be an easy way to get a daily test of the docker build (#2816); alternatively maybe we can run the test within Circle.

**Comment by paulmelnikow** [comment]
I've started setting up Docker Hub to auto-build images at https://cloud.docker.com/u/shieldsio/repository/docker/shieldsio/shields on pull requests and pushes to master.

For the moment, commits to master will be published to the `next` tag for the moment. We've discussed a date-based version scheme for releases to the server. For the moment that will involve a manual process; `next` will auto-update, and we'll need to manually push the `2019-07-02` tag.

Docker Hub also has [an automatic test feature](https://docs.docker.com/docker-hub/builds/automated-testing/) which I think we could use to tackle #2816. The test runs inside the container which isn't ideal for making sure it works. It'd be better to hit the container from the outside. However it looks very easy to set up so maybe it's a decent tradeoff.

I've also added a couple maintainers to the Docker Hub org (please send me your Docker Hub account if you'd like to be added). I also deleted all the obsolete CI images so no one gets confused.

When this is working reliably we'll need to update the self-hosting doc to mention this option.

**Comment by paulmelnikow** [comment]
Heh. I've been waiting about 15 minutes so far for the first build to start. See docker/hub-feedback#464; we might need to tackle this in Circle CI instead.

**Comment by paulmelnikow** [comment]
It looks like one of the options for auto-building can look for new GitHub tags. So we could e.g. push a tag like `server-190702` and it'll trigger the creation of a Docker Hub tag `190702`.

That seems like it's most of the way there.

The other thing we might want to add is a `latest` tag that also gets updated with each release. Two options for that:

1. Create a branch `server-latest`, and after tagging a new release, and do a fast-forward merge to that branch.
2. After pushing a server tag, manually trigger a build on `latest` through the Docker Hub UI.
3. Automatically push every new `server-yymmdd` tag to `latest` as well, so it would go to both `yymmdd` and `latest`.

Option 3 sounds good; only concern being that we need to add the new tags chronologically; we can't go back in time and re-tag an old version.

**Comment by niccokunzmann** [comment]
I wonder: I would only use the latest build of shields anyway. So. For
me all this tagging is not useful.

Tagging it by day is also unusual. If there were releases, then it would
be expected that if there are tags, they
point to releases.

Maybe I missed it and there is a good point in tagging. Just having a
latest release would be good enough for most, I guess.
No need to reply except if you think you did not understand something.

**Comment by nigredo-tori** [comment]
@niccokunzmann, tagging is useful if some aspect of the image regresses in `latest` - then you can just switch to some older tag. Also, using a tagged version allows one to avoid unknowingly pulling a breaking configuration change. This is important for self-hosted instances, where stability trumps cutting-edge features.

At any rate, automatically building tagged images requires almost no setup (as described above), so in my opinion it is absolutely worth it.

I agree with you on tagging by day, though - tagging by version is more intuitive.

**Comment by paulmelnikow** [comment]
Right, we could have a tag for the latest version but that's basically bleeding edge, like running off master. Most people will want the latest stable release, and the also ability to perform reproducible installs of the same version as well as rollbacks.

> I agree with you on tagging by day, though - tagging by version is more intuitive.

We've had some previous discussions on versioning for the server. Maybe someone will have links to the discussion, though I'll try to summarize the decision.

Since Shields is an application, semver isn't appropriate. It's designed for libraries, not applications. What is the public interface of an application? You could try to use semver for breaking changes to the configuration, though even that seems fairly fiddly. There are a lot of behaviors that could change in the application, like removing a badge – should that be a breaking change, a minor, a patch? It seems like too much work for not enough effort.

The solution we came up with is a changelog, corresponding to periodic releases of the server. So maybe once a month or once a week we release a new version of the server, and update a changelog with everything that's changed in terms of configuration in that version (and maybe a link to the compare view to see the full feature changeset). We're not going to attempt to ship updates that can be dropped in blindly or try to classify releases as needing or not needing updates, as whether a change is "breaking" is dependent on the usage. It'll always be on the end user to read the changelog. 

As far as numbering those releases, the two options we discussed were sequential integer version numbers (0001, 0002, 0003, 0004 etc.) and the dates (e.g. 190702, 190715, 190804, though we haven't chosen a specific date format). We think numbering by the date of release makes for one less thing to keep track of. Plus the dates are semantic for the maintainers, and give end users a really quick idea of how old their code is.

I could see some benefits of using integers, too. I imagine a changelog being a little easier to follow with integer releases.

I don't feel super strongly; really just want to avoid creating a maintenance burden, and to make sure whatever workflow we choose supports our primary focus on the live service with a secondary focus on self-hosting.

**Comment by nigredo-tori** [comment]
@paulmelnikow, I see your point. It's just that for me personally, even remotely consistent versioning system is a more convenient reference framework than a time scale. That is, I'm more likely to remember that "feature A was added in 1.2" than "feature A was added by January 2nd 2020". You can guess that history wasn't my favorite school subject. :smile:
That said, if you tend to view this project's development as a continuum rather than a sequence - more power to you. I'm OK with any monotone version sequence, as long as I can easily get from a Docker tag to a Git commit.

**Comment by chris48s** [comment]
> We've had some previous discussions on versioning for the server. Maybe someone will have links to the discussion

Previous conversation is in https://github.com/badges/shields/issues/3404 but Paul's summary above is bang on the money.

> I'm more likely to remember that "feature A was added in 1.2" than "feature A was added by January 2nd 2020"

Date-based versioning doesn't necessarily prevent arriving at a nice version number. Relevant reading: https://calver.org/

**Comment by nigredo-tori** [comment]
Has this been silently [solved](https://hub.docker.com/r/shieldsio/shields) around two weeks ago? :smile:

**Comment by paulmelnikow** [comment]
Autobuilds from master have been running for about nine months. See this comment above: https://github.com/badges/shields/issues/3558#issuecomment-507822643

What we don't have yet are version numbers or a changelog.

**Comment by chris48s** [comment]
We're now publishing tags to dockerhub: https://registry.hub.docker.com/r/shieldsio/shields/tags?page=1&ordering=last_updated
More context on this in the docs: https://github.com/badges/shields/blob/master/doc/releases.md#shields-server
