### ISSUE TITLE
No enough space between numbers - for style=for-the-badge

### ISSUE THREAD

**Issue by thamaraiselvam** [badges/shields#3613]
<img alt="Packagist" src="https://img.shields.io/packagist/dt/thamaraiselvam/mysql-import.svg?style=for-the-badge"> <img alt="Visual Studio Marketplace Downloads" src="https://img.shields.io/visual-studio-marketplace/d/Thamaraiselvam.remove-blank-lines.svg?style=for-the-badge"> <img alt="Visual Studio Marketplace Installs" src="https://img.shields.io/visual-studio-marketplace/i/Thamaraiselvam.remove-blank-lines.svg?style=for-the-badge">

There is not enough space between these numbers so hard to read.

It happens when use `style=for-the-badge`

**Comment by paulmelnikow** [comment]
Hi, thanks for the report.

The problem is not just numbers, also letters, e.g.

![](https://img.shields.io/badge/foo-bar-green.svg?style=for-the-badge)
https://img.shields.io/badge/foo-bar-green.svg?style=for-the-badge

It seems like probably one of the issues is that we are displaying bold letters while computing the width using narrower letters. Though something else is causing the letters on the left to be squashed.

![](https://img.shields.io/badge/FOO-BAR-green.svg?style=for-the-badge)
https://img.shields.io/badge/FOO-BAR-green.svg?style=for-the-badge

Hmm, maybe we are measuring the lowercase letters…

![](https://img.shields.io/badge/downloads-5k-green.svg?style=for-the-badge)
https://img.shields.io/badge/downloads-5k-green.svg?style=for-the-badge

![](https://img.shields.io/badge/DOWNLOADS-5K-green.svg?style=for-the-badge)
https://img.shields.io/badge/DOWNLOADS-5K-green.svg?style=for-the-badge

Is the font size different, too?

**Comment by u3u** [comment]
Use uppercase spacing is not the same

<https://img.shields.io/badge/eslint-airbnb-ff5a5f.svg?style=for-the-badge&logo=airbnb>

![ESLint Airbnb](https://img.shields.io/badge/eslint-airbnb-ff5a5f.svg?style=for-the-badge&logo=airbnb)

<https://img.shields.io/badge/ESLint-AirBnb-ff5a5f.svg?style=for-the-badge&logo=airbnb>

![ESLint Airbnb](https://img.shields.io/badge/ESLint-AirBnb-ff5a5f.svg?style=for-the-badge&logo=airbnb)

Is it possible to provide a parameter to set the spacing?

**Comment by thamaraiselvam** [comment]
How can I specify those capital letters for VS Code marketplace APIs and packagist?

https://img.shields.io/visual-studio-marketplace/d/Thamaraiselvam.remove-blank-lines.svg?style=for-the-badge 

https://img.shields.io/packagist/dt/thamaraiselvam/mysql-import.svg?style=for-the-badge

**Comment by paulmelnikow** [comment]
> Use uppercase spacing is not the same

Yea, that's definitely a bug we should fix.

This code is in flight as part of #2428, maybe it can be tackled there.

In the meantime you can set `?label=SOMETHING` to tweak the spacing. There isn't a way to directlty override it.

**Comment by RedSparr0w** [comment]
It's strange that this makes a difference, Maybe the measurements are being done before this step:
https://github.com/badges/shields/blob/98f380b2549fdd3c765cdf96ad453584c606c4f8/gh-badges/lib/make-badge.js#L147-L149

**Comment by RedSparr0w** [comment]
Found the problem:
https://github.com/badges/shields/commit/84c60c87306067f32a75a6680aeaca1bfbc1db06#diff-8e42c268a94af1983cbdd09a6bdbe33eR114

This PR changed the text computation to measure `left`, `right` instead of `text[0]`, `text[1]`
But didnt change 
https://github.com/badges/shields/blob/98f380b2549fdd3c765cdf96ad453584c606c4f8/gh-badges/lib/make-badge.js#L147-L149
To use  `left`, `right`.
