### ISSUE TITLE
TypeError: template.endsWith is not a function

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#3758]
https://sentry.io/organizations/shields/issues/1122042844/?referrer=github_plugin

```
TypeError: template.endsWith is not a function
  File "/home/m/shields/gh-badges/lib/make-badge.js", line 134, in makeBadge
    if (template && template.endsWith('-square')) {
  File "/home/m/shields/core/base-service/legacy-request-handler.js", line 159, in null.<anonymous>
    const svg = makeBadge(cached.data.badgeData)
  File "/home/m/shields/core/server/monitor.js", line 57, in Array.server.handle
    next()
...
(26 additional frame(s) were not displayed)

TypeError: template.endsWith is not a function
```

**Comment by paulmelnikow** [comment]
Related to #3747

**Comment by PyvesB** [comment]
So, if I'm understanding this correctly, the input `template` is not always a string?

**Comment by paulmelnikow** [comment]
This is being pulled from the request cache. I haven't looked at that code in a while and can't remember what is actually placed in the cache for templates. I think what is cached is the before-rendering result.

It really doesn't make sense that something other than a string or `undefined` would be put into the cache, though.

55 times in the last hour, so it's happening regularly but definitely not every request.

**Comment by PyvesB** [comment]
A quick fix would be to strictly check for `popout-square` rather than calling an `endsWith`, or explicitly checking whether it's a string type. But those are only workarounds hidding a potentially bigger problem, you're right that it doesn't make sense that other types are cached. However, I didn't spot anything obviously wrong after a quick dig around, and it's getting late in my time zone. :confused:

**Comment by paulmelnikow** [comment]
I'm fine with a `=== 'popout-square'` check. That code should be going away soon anyway. (#3368)
