### ISSUE TITLE
Broken legacy badge redirects

### ISSUE THREAD

**Issue by squeek502** [badges/shields#3779]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

`https://img.shields.io/Freenode/%23luvit.png`
redirects to
`https://raster.shields.io/Freenode/%23luvit.png`
which gives
`404 | badge not found`. 

As far as I understand, it should be redirecting to 
`https://raster.shields.io/badge/Freenode-%23luvit-undefined.png`
instead.

---

Related to #3663 & #3644

**Comment by paulmelnikow** [comment]
Hi! Thanks for the report.

That route was removed in #3659 so that is the expected behavior. I've updated the top comment in #3663 to reflect that.

In your case I'd suggest updating to the static SVG badge:

https://img.shields.io/badge/Freenode-%23luvit-brightgreen
![](https://img.shields.io/badge/Freenode-%23luvit-brightgreen)

If you want a raster badge for some reason, you can use that too:

https://raster.shields.io/badge/Freenode-%23luvit-brightgreen
![](https://raster.shields.io/badge/Freenode-%23luvit-brightgreen)
