### ISSUE TITLE
AppVeyor tests badge say: no tests

### ISSUE THREAD

**Issue by bruno-garcia** [badges/shields#3878]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Even though there are tests (follow the link), the badge shows _not tests_.

:link: **Link to the badge**

https://img.shields.io/appveyor/tests/sentry/sentry-dotnet?compact_message
[![Tests](https://img.shields.io/appveyor/tests/sentry/sentry-dotnet.svg?compact_message)](https://ci.appveyor.com/project/sentry/sentry-dotnet/branch/master/tests)

:bulb: **Possible Solution**

This was working just a few hours ago so maybe it can't hit appveyor?
If that's the case would it be possible to show something else like an error message?

**Comment by calebcartwright** [comment]
For anyone looking at this, the badge is (at least this moment) displaying test results, but it was indeed showing `no tests` earlier

**Comment by calebcartwright** [comment]
My guess is that it was related to failing builds during the same period the issue was opened such as:

https://ci.appveyor.com/project/sentry/sentry-dotnet/builds/26768202
https://ci.appveyor.com/project/sentry/sentry-dotnet/builds/26768611

@bruno-garcia - two things I'd suggest if you see this again:

1. See if the test badge works for your master branch, as the original link you provided will be the latest across any branch and it seems like on certain build failures the test results aren't being published: 
https://img.shields.io/appveyor/tests/sentry/sentry-dotnet/master?compact_message
![](https://img.shields.io/appveyor/tests/sentry/sentry-dotnet?compact_message) 
2. Check the API response for your repo from AppVeyor and see if the tests are included in there. My guess based on the above is still that the root cause was the tests not being published to AppVeyor (and thus not being available for us to consume from the API), but if the API response includes tests and we're still showing a `no tests` badge then that would indeed be a problem on our end
https://ci.appveyor.com/api/projects/sentry/sentry-dotnet/{{branch}}

**Comment by bruno-garcia** [comment]
Oh I wasn't aware it was the latest commit in any branch.
Thanks!
