### ISSUE TITLE
GitHub repo under organization not working

### ISSUE THREAD

**Issue by emfomy** [badges/shields#3908]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

`https://img.shields.io/github/v/release/:user/:repo` not work with `:user` is an organization.

e.g. [https://img.shields.io/github/v/release/badges/shields](https://img.shields.io/github/v/release/badges/shields) shows (release|
no releases or repo not found).

Same problem also happened on `/github/release-date/...`, etc...

:link: **Link to the badge**

`https://img.shields.io/github/v/release/badges/shields.svg`
![version](https://img.shields.io/github/v/release/badges/shields)

`https://img.shields.io/github/release-date/badges/shields.svg`
![version](https://img.shields.io/github/release-date/badges/shields.svg)

:bulb: **Possible Solution**

It seems like the meta are not correct parsed.

**Comment by chris48s** [comment]
The reason you're seeing that for our repo is because our repo does not have any releases - its not because we're under an organisation. If you try it for an organisation repo that does publish releases, it works e.g:

![](https://img.shields.io/github/v/release/atom/atom.svg) - https://img.shields.io/github/v/release/atom/atom.svg

The things that appear on our [releases page](https://github.com/badges/shields/releases) are actually tags:
![](https://img.shields.io/github/v/tag/badges/shields.svg) - https://img.shields.io/github/v/tag/badges/shields.svg

Don't worry - the fact that GH shows tags on the releases page is a frequent source of confusion :)
