### ISSUE TITLE
Support for package quality

### ISSUE THREAD

**Issue by alexfernandez** [badges/shields#397]
Hi all,

I would like to add support for [package quality](https://github.com/alexfernandez/package-quality), adding custom badges: issue https://github.com/alexfernandez/package-quality/issues/25. The URL might be something like: https://img.shields.io/package-quality/npm/package-quality.png, and show something like: https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.png.

I have a few questions:

* What is the current practice, have a URL on our side (e.g. http://npm.package-quality.com/shield/package-quality.png) and redirect to a URL on your site (e.g. https://img.shields.io/package-quality/npm/package-quality.png), which in turn reads the data using our API and displays it? Looks a bit convoluted to me.
* Are there specific gains to using custom badges like https://img.shields.io/package-quality/...? It appears that the generic URL `/badge/` works mostly well (but see below), and users are not going to see the custom URL either. Is it OK to redirect to something like https://img.shields.io/badge/quality-%E2%98%85%E2%98%85%E2%98%85%C2%BD%E2%98%86-green.png?
* The URL for PNG images has problems with Unicode, while SVG images are fine. I reported it elsewhere: https://github.com/badges/shields/issues/396. I understand Unicode is supported?

Thanks!

**Comment by espadrine** [comment]
> What is the current practice, have a URL on our side (e.g. http://npm.package-quality.com/shield/package-quality.png) and redirect to a URL on your site (e.g. https://img.shields.io/package-quality/npm/package-quality.png), which in turn reads the data using our API and displays it?

That is indeed the most convoluted way to imagine such a system I have heard yet! ☺ Assuming you own package-quality.com and have a programmable HTTP server on it, you can determine what text you want on your badge, request it from shields.io's `/badge/` service, and send that data back to the client as is.

> Are there specific gains to using custom badges like https://img.shields.io/package-quality/...?

Not for you.

Users often contact us because a provider (ie, you) failed to carry forward information such as a badge style (as `?style=…`) or a custom label (as `?label=…`) to shields.io.

> The URL for PNG images has problems with Unicode, while SVG images are fine.

I recommend enforcing SVG. Welcome to 2015!

**Comment by alexfernandez** [comment]
Done [here](https://github.com/alexfernandez/package-quality/pull/34), thanks for your help! [Example](http://npm.packagequality.com/shield/express.svg).

**Comment by espadrine** [comment]
Excellent! Congrats!
