### ISSUE TITLE
Packagist versions not found

### ISSUE THREAD

**Issue by dant89** [badges/shields#4177]
I have the following packagist component with tags:

https://packagist.org/packages/dant89/smite-api-php-client
https://github.com/dant89/smite-api-php-client/releases

but neither of the badges pick up the version even though there are multiple tagged on Github, why is this?

https://img.shields.io/packagist/v/dant89/smite-api-php-client.svg
https://img.shields.io/packagist/vpre/dant89/smite-api-php-client.svg

**Comment by platan** [comment]
Hi @dant89!
I can see that you released all versions (0.0.1, 0.0.2 and 1.0.0) today. We are using packagist API as a source of information about versions. This API is described in "Using the API" section of https://packagist.org/apidoc#get-package-data:
> However it is generated dynamically so for performance reason we cache the responses for twelve hours. 

So you have to wait :-)

The problem is known and described in https://github.com/badges/shields/issues/2435
