### ISSUE TITLE
docker cloud build badge shows 'build failing' for passing build

### ISSUE THREAD

**Issue by aasaru** [badges/shields#4185]
I'm experiencing an issue with:

- [*] [shields.io](https://shields.io/#/)

:beetle: **Description**

I set up docker cloud build badges for several repositories. Some examples:
https://github.com/apache/fineract-cn-teller
https://github.com/apache/fineract-cn-office
https://github.com/apache/fineract-cn-portfolio

currently it shows 'docker build failing' but if you click on the links you see that the docker cloud builds actually pass.

For some of the repositories the same configuration works. For example:
https://github.com/apache/fineract-cn-accounting

**Comment by calebcartwright** [comment]
Hi @aasaru - thanks for the report. 

The Docker API is returning a `Failed` status which is why you're seeing the failed badges. I don't have any theories yet as to why the API is returning a `Failed` status 

https://cloud.docker.com/api/build/v1/source/?image=apache/fineract-cn-teller
```json
{ 
  "meta":{ .. },
  "objects":[ 
    { 
      "autotests":"OFF",
      "build_in_farm":true,
      "build_settings":[ 
        "/api/build/v1/setting/f867831d-e417-4754-a54c-cd926bcf6ce6/",
        "/api/build/v1/setting/b5ce9d60-d40a-4fbf-b767-309ecb580b6c/",
        "/api/build/v1/setting/d2c8c292-e154-4fee-bb3b-49c59cb6a865/",
        "/api/build/v1/setting/55d75055-a094-4ea0-99d6-0bc6a8f3a191/"
      ],
      "channel":"Stable",
      "deploykey":"",
      "image":"apache/fineract-cn-teller",
      "owner":"apache",
      "provider":"Github",
      "repo_links":false,
      "repository":"fineract-cn-teller",
      "resource_uri":"/api/build/v1/source/28bff642-6d8f-4fef-b25e-c7d06a2fbb82/",
      "state":"Failed",
      "uuid":"28bff642-6d8f-4fef-b25e-c7d06a2fbb82"
    }
  ]
}
```

**Comment by aasaru** [comment]
Thanks @calebcartwright for quick response. I will raise this issue with Docker cloud then.

**Comment by aasaru** [comment]
Dockerhub issue: https://github.com/docker/hub-feedback/issues/1902

**Comment by bittner** [comment]
**Note:** Shields.io users can fix this issue by switching to the Docker Cloud badge, e.g
```
https://img.shields.io/docker/cloud/build/<org>/<image>.svg
```

**Comment by aasaru** [comment]
@bittner are you sure?

https://img.shields.io/docker/cloud/build/apache/fineract-cn-rhythm.svg
shows build failing
but if you open up:
https://hub.docker.com/repository/docker/apache/fineract-cn-rhythm
you see that the latest build has passed

**Comment by jingpengw** [comment]
the docker cloud link works for me.

**Comment by amalic** [comment]
My build shows up as failed despite a success status on dockerhub.

**Comment by kevinrue** [comment]
Same here:

https://hub.docker.com/r/iseedevelopers/isee/builds

https://github.com/iSEE/iSEE

**Comment by calebcartwright** [comment]
@amalic & @kevinrue - this issue is related to an upstream issue in the Docker API, which is linked above in this thread. 

If you are having the same issue (the Docker API shows a `Failed` status for your project despite what it shows you in the Web) then I would suggest you follow/report that on the upstream issue to give the Docker folks a better idea of the breadth of the issue. There's nothing we can do about the upstream API response unfortunately so commenting on this closed issue isn't particularly helpful.

For example, if you look at the response for `iseedevelopers/isee`, you'll the state is also `Failed` 
https://hub.docker.com/api/build/v1/source/?image=iseedevelopers/isee

If your circumstances are different, then please open a new issue with the relevant details so that we can triage and address accordingly.
