### ISSUE TITLE
Maven-Metadata renders a version like "1.0" as "1"

### ISSUE THREAD

**Issue by loosebazooka** [badges/shields#4188]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

For the following metadata:

metadata: http://central.maven.org/maven2/com/google/guava/guava-beta-checker/maven-metadata.xml

The actual badge rendered
[![Maven Central](https://img.shields.io/maven-metadata/v/http/central.maven.org/maven2/com/google/guava/guava-beta-checker/maven-metadata.xml.svg?colorB=007ec6)](https://maven-badges.herokuapp.com/maven-central/com.google.guava/guava-beta-checker)

expected badge
![expected](https://img.shields.io/badge/maven-v1.0-blue.svg)

Presumably some kind of issue with how versions are handled (as strings vs numbers)?

**Comment by calebcartwright** [comment]
Thanks @loosebazooka 

You could use the MavenCentral version badge in the interim which provides your expected format
https://img.shields.io/maven-central/v/com.google.guava/guava-beta-checker?label=maven)
![](https://img.shields.io/maven-central/v/com.google.guava/guava-beta-checker?label=maven)

I recall something similar in the [MavenCentral](https://github.com/badges/shields/blob/master/services/maven-central/maven-central.service.js) service (fixed in #3935), so I imagine the same fix could be applied to the [MavenMetadata](https://github.com/badges/shields/blob/master/services/maven-metadata/maven-metadata.service.js) service to fix this

**Comment by netsgnut** [comment]
Thank you @calebcartwright for the pointer! Let's see if I could prepare a PR for that.

**Comment by calebcartwright** [comment]
Closed via #4224
