### ISSUE TITLE
Is the Coveralls logo not supported?

### ISSUE THREAD

**Issue by imbsky** [badges/shields#4349]
Is the Coveralls logo not supported?

**Comment by calebcartwright** [comment]
Shields uses the [simple-icons](https://www.npmjs.com/package/simple-icons) package to provide logos, and `simple-icons` added support for Coveralls in v1.19.1 (https://github.com/simple-icons/simple-icons/pull/1873). 

Production Shields.io is currently using `simple-icons` v1.19.0 which is why the Coveralls logo is unavailable ATM. We have updated Shields to v1.19.1 of `simple-icons` but that's not been deployed to prod yet. 

If you'd like, you can track [this comment](https://github.com/badges/shields/pull/4300#issuecomment-550447623) which reflects the current deployment state of the commit that bumps to v1.19.1. The deployment bot will update that comment once that version of `simple-icons` has been deployed

**Comment by imbsky** [comment]
I see, thank you! This is an off topic question, but when will GitHub Actions support be available? I really love your PR.

**Comment by calebcartwright** [comment]
> This is an off topic question, but when will GitHub Actions support be available? I really love your PR

😄 thanks! I hope soon, though there's no timetable I'm afraid

**Comment by imbsky** [comment]
Great!
