### ISSUE TITLE
Q: Github Tags Badges not rendering for pre-releases?

### ISSUE THREAD

**Issue by thatsIch** [badges/shields#436]
I tried to generate the latest tags for our github repo using shields, but its displaying none for us

image https://img.shields.io/github/tag/AppliedEnergistics/Applied-Energistics-2.svg
repo https://github.com/AppliedEnergistics/Applied-Energistics-2/tags

is that intended to only render the releases?

**Comment by espadrine** [comment]
Oh god. The history behind this is complex. I tried fixing [this](https://github.com/badges/shields/issues/175) with 1acc586bacd3df890e8d5e2dc015bd884e5aeddb while ensuring that versions that don't look like versions are discarded (because sometimes people put non-version things where versions should be, and using ascii ordering yields bad results for them, but using semver requires to discard non-version things).

I hooked github tags to this algorithm because people received the "wrong" tag, when they wanted the latest version stored in a tag.

However, none of your tags look like versions, so they are all discarded.

I feel like the `latestVersion()` algorithm is getting so smart it could become Skynet.

**Comment by espadrine** [comment]
That should fix it.

**Comment by metaraine** [comment]
I am also seeing an incorrect version for https://img.shields.io/github/tag/tjunnone/npm-check-updates.svg. It used to report the "unstable" tag of 2.0.0-alpha.9, but now it shows latest of 1.5.1. This a recent regression as far as I can tell.

I realize this is complicated. I would be happy with any default behavior, as long as there was some way to show the *greatest* version (e.g. last published... or whatever Skynet decides).

Use Case: I display the stable and unstable versions side-by-side in the README. I invite the community to test the unstable version before I push it to stable.

**Comment by espadrine** [comment]
@metaraine that seems to be a completely different issue, and a strange one at that. With the exact same code, a local shields server gives 2.0.0-alpha6, and shields.io itself gives 1.5.1. There might be a difference in what `https://api.github.com/repos/tjunnone/npm-check-updates/tags` returns on my machine and on our server.

That said, the fact that you're not using semver doesn't help. When all your versions were semver-compilant, we could use the known semver algorithm to find out which version is the latest. As soon as one tag has an invalid version, we can no longer use that algorithm, and we rely on ASCII ordering, which means that `"v2.0.0-alpha6" > "v2.0.0-alpha.10"`. That change in the algorithm used can absolutely give surprising results.

**Comment by metaraine** [comment]
I thought I was using semver. Can you clarify which of my published
versions is not semver-compliant?

That is strange that shields.io is giving 1.5.1. The API seems to show all
the alpha versions for me.

**Comment by espadrine** [comment]
You're right, it is semver compliant, sorry. However,
`semver.gt("v2.0.0-alpha6",
"v2.0.0-alpha.10")`.

**Comment by metaraine** [comment]
Yes, the change in prerelease version formatting was a bad idea. It's a moot point, however, when shields.io is returning 1.5.1!
