### ISSUE TITLE
Badge Request: AppVeyor Job Level Status Badges

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [badges/shields#4393]
:clipboard: **Description**
I'm using dynamic badges to display the status of separate AppVeyor jobs since AppVeyor does not support per-job status badges. It is working cool, here is an example ![Windows build status](https://img.shields.io/badge/dynamic/json?color=informational&label=Windows&query=%24.build.jobs%5B%3F%28%40.name%20%3D%3D%3D%20%22Windows%22%29%5D.status&url=https%3A%2F%2Fci.appveyor.com%2Fapi%2Fprojects%2Fwpmgprostotema%2Fvoicetranscoder%2Fbranch%2Fmaster).

The only problem the color is static, it does not indicate the build status (e.g. green for success, red for failure). I hope it can be made dynamic.

There are two options that I see:
- Add `colorQuery` parameter, but the problem here is that JSON does not contain a color name to be displayed, so this is not appropriate option.
- Add `message-to-color-map` parameter. I think its value should be JSON object, for example:
```JavaScript
{
  "success": "success",
  "failed": "critical",
  "<some placeholder to match other values>": "inactive"
}
```

The only problem here is placeholder value, I hope we can just use empty string for it. But I think it would be better to just use current `color` parameter as fallback.

So, the final idea:
- Add `message-to-color-map` parameter, if the message matches one of the key then use the matched value as badge color.
- If it does not match any key then fallback to the `color` parameter.

**Comment by calebcartwright** [comment]
Thanks for reaching out @WPMGPRoSToTeMa. 

Shields does al;ready directly support AppVeyor badges via the same API you are using with the Dynamic JSON badge, so IMO the better approach for your specific use case would simply be to extend our AppVeyor support to include job-level status badges

https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/master
![](https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/master)

This would be a very straightforward for Shields. 

The schema would simply need to include the `name` and `status` fields on the `jobs` objects (we're currently only including the test count fields):
https://github.com/badges/shields/blob/92b1380db0d3a2bb177c25c666237cc438caf600/services/appveyor/appveyor-base.js#L8-L19

And then the [existing service class](https://github.com/badges/shields/blob/master/services/appveyor/appveyor-ci.service.js) for the build status would either need to be tweaked to include the `job` name as an optional route param (and logic updated of course to grab the job status instead of the build-level status), or, more than likely, a new service class would need to be created (perhaps something `AppVeyorJobCI`) with a _required_ `job` route param. 

I suspect it'll likely be the latter given that the existing AppVeyor badge supports the optional `branch` name and branches can include `/`

**Comment by calebcartwright** [comment]
Would that meet your needs if you could do something like the below?

https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/windows/master
![](https://img.shields.io/badge/Windows-passing-brightgreen)
https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/linux/master
![](https://img.shields.io/badge/Linux-passing-brightgreen)
https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/pack/master
![](https://img.shields.io/badge/Pack-passing-brightgreen)

**Comment by WPMGPRoSToTeMa** [comment]
@calebcartwright wow, that's cool! Thanks for the quick answer. By the way, can I customize messages? I prefer `success` instead of `passing` for example.

**Comment by calebcartwright** [comment]
> By the way, can I customize messages? I prefer `success` instead of `passing` for example.

No, not that I'm aware of. You can explicitly override certain aspects of the badge via the query parameters (`color`, `style`, `label`, etc.) but not the message for these types of badges. 

> And I would like to customize the title with the branch name in the near future (e.g. `master - Windows`).

Yup, just use the label param `?label=master%20-%20Windows`

https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/master?label=master%20-%20Windows
![](https://img.shields.io/appveyor/ci/wpmgprostotema/voicetranscoder/master?label=master%20-%20Windows)

You can also use the badge builder window on the Shields.io website https://shields.io/, just navigate to your desired service, and click the badge listing to open the window:

![image](https://user-images.githubusercontent.com/13042488/70086402-f3c2c000-15d7-11ea-87d0-49ab0ac805b6.png)

**Comment by WPMGPRoSToTeMa** [comment]
Ok, thanks.

> > By the way, can I customize messages? I prefer `success` instead of `passing` for example.
> 
> No, not that I'm aware of. You can explicitly override certain aspects of the badge via the query parameters (`color`, `style`, `label`, etc.) but not the message for these types of badges.

Can I create a separate issue for that? As I can see this is applicable for all the build badges, not only for AppVeyor.

**Comment by calebcartwright** [comment]
> Can I create a separate issue for that?

@WPMGPRoSToTeMa - you certainly can. I feel like similar requests have been discussed before but I can't find any of the issues right now. One of the goals Shields has is consistency which is why there's a common set of pass/fail/etc. messages used for all the build tools (which was done back in https://github.com/badges/shields/pull/585) which IMO definitely makes sense as the default.

However, I wouldn't object to optional query params that would allow users to specify their desired pass/fail message for build status badges like we do with some of the monitoring badges (`?up_message=....&down_message=...`)

**Comment by calebcartwright** [comment]
Another, more readily available option for you would be to leverage our [Endpoint badge](https://shields.io/endpoint) with your own custom endpoint that would give you complete flexibility

**Comment by calebcartwright** [comment]
Also I've changed the title to focus in specifically on the AppVeyor enhancements to support Job-level status badges and as noted above feel free to open a new issue if you'd like to request the badge message customization. 

Regarding the original text in the title/description, IMO the Endpoint badge would likely be the way to go vs. additional logic/processing for the dynamic badge.
