### ISSUE TITLE
Unparsable jsonpath query on dynamic badge even when query is correct

### ISSUE THREAD

**Issue by adzo261** [badges/shields#4476]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
I was trying to create a dynamic badge to show dev dependency of a node package from JSON data from my Github repo. 
However, the badge says `unparsable jsonpath query` .
The query is as follows:
`$.devDependencies.@babel/core`

The JSON data is as follows:
```
{
  "devDependencies": {
    "@babel/core": "^7.7.5"
  }
}

```
Complete data can be viewed [here.](https://raw.githubusercontent.com/codeagni/mern-starter/master/client/package.json)

Attaching Screenshot of [jsonpath.com](http://jsonpath.com/)
![issue](https://user-images.githubusercontent.com/26338605/71547148-0905f100-29c2-11ea-9baa-65a8b1a7fdef.png)

:link: **Link to the badge**
https://img.shields.io/badge/dynamic/json?color=blue&label=%40babel%2Fcore&query=%24.devDependencies.%40babel%2Fcore&url=https%3A%2F%2Fraw.githubusercontent.com%2Fcodeagni%2Fmern-starter%2Fmaster%2Fclient%2Fpackage.json

Thank you for creating **shields.io**  :smile:

**Comment by calebcartwright** [comment]
hey @adzo261, I'm not sure about the jsonpath query, but we do have a badge that natively supports dependency versions from package.json files in GitHub repos. 

I believe this is what you'd want:
https://img.shields.io/github/package-json/dependency-version/codeagni/mern-starter/dev/@babel/core?filename=client%2Fpackage.json
![](https://img.shields.io/github/package-json/dependency-version/codeagni/mern-starter/dev/@babel/core?filename=client%2Fpackage.json)

**Comment by platan** [comment]
`@` is a special character in JSONPath. Instead of using the dot-notation, you can simply use the bracket–notation (https://goessner.net/articles/JsonPath/):
`$.devDependencies['@babel/core']`
https://img.shields.io/badge/dynamic/json?color=blue&label=%40babel%2Fcore&query=%24.devDependencies[%27%40babel%2Fcore%27]&url=https%3A%2F%2Fraw.githubusercontent.com%2Fcodeagni%2Fmern-starter%2Fmaster%2Fclient%2Fpackage.json
![](https://img.shields.io/badge/dynamic/json?color=blue&label=%40babel%2Fcore&query=%24.devDependencies[%27%40babel%2Fcore%27]&url=https%3A%2F%2Fraw.githubusercontent.com%2Fcodeagni%2Fmern-starter%2Fmaster%2Fclient%2Fpackage.json)

**Comment by adzo261** [comment]
@calebcartwright  great, I didn't know it supported dependencies versions' natively.
@platan  Thanks for clarifying my mistake.

Thanks to both of you and this wonderful community. :smile: :heart:
