### ISSUE TITLE
Shields.io badge doesn't show last package from Nuget.org

### ISSUE THREAD

**Issue by rmarinho** [badges/shields#4494]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Hi, we are using  shields.io in our project to point to a nuget.org package , but it seems it stopped showing our latest package 4.4.0.991265

:link: https://img.shields.io/nuget/v/Xamarin.Forms.svg?style=flat-square&label=nuget

https://www.nuget.org/packages/Xamarin.Forms/

 [![NuGet](https://img.shields.io/nuget/v/Xamarin.Forms.svg?style=flat-square&label=nuget)](https://www.nuget.org/packages/Xamarin.Forms/)

should show  4.4.0.991265

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
Thanks for the report @rmarinho! In looking at the versions in the API response
https://azuresearch-usnc.nuget.org/query?q=packageid%3Axamarin.forms&prerelease=true&semVerLevel=2

```json
{ 
    "version":"4.3.0.991211",
    "downloads":83770,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.3.0.991211.json"
},
{ 
    "version":"4.3.0.991221+389-sha.cb59ef699-azdo.3288473",
    "downloads":32713,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.3.0.991221.json"
},
{ 
    "version":"4.3.0.991250+393-sha.ad78adb23-azdo.3300037",
    "downloads":3560,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.3.0.991250.json"
},
{ 
    "version":"4.4.0.936621-pre1",
    "downloads":4877,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.4.0.936621-pre1.json"
},
{ 
    "version":"4.4.0.991210-pre2",
    "downloads":5721,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.4.0.991210-pre2.json"
},
{ 
    "version":"4.4.0.991220-pre3+sha.67178561f-azdo.3288472",
    "downloads":2738,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.4.0.991220-pre3.json"
},
{ 
    "version":"4.4.0.991265+398-sha.ee1eca51d-azdo.3306453",
    "downloads":58262,
    "@id":"https://api.nuget.org/v3/registration4-gz-semver2/xamarin.forms/4.4.0.991265.json"
}
``` 

it seems like the most recent versions have started including build metadata. `4.3.0.991211` (the version showing on the badge) is the latest non-prerelease version that doesn't include the build metadata. What's probably happening is that `4.4.0.991265+398-sha.ee1eca51d-azdo.3306453` is being detected as a pre-release version due to the complex build metadata. 

We can take a look at the pre-release version filtering within Shields, but please note that the versions on the badges are an exact mirror of the version from the API response. That means that with the current published versions you'd end up with a pretty gnarly looking badge:

![](https://img.shields.io/badge/nuget-4.4.0.991265%2B398--sha.ee1eca51d--azdo.3306453-blue)

**Comment by rmarinho** [comment]
Thanks for the feedback @calebcartwright  yeah, well imo i prefer to have  gnarly looking badge but with the correct last version :

it might be that since the 4.4.0.991265+ is not semver 2.0  also it gets confused, but seems in the VisualStudio IDE it looks ok (version 4.4.0.991265 appears as the latest stable). 

I also saw a issue opened by my fried @kzu  about the long badges #3926 maybe we can address that after.

**Comment by calebcartwright** [comment]
> I also saw a issue opened by my fried @kzu about the long badges #3926 maybe we can address that after

I was going to mention that as well, would be great to get that feature added too!

**Comment by calebcartwright** [comment]
Some recent-ish discussion on nuget package versions, where we did explicitly decide (for backwards compatability reasons) that for any non-semver complaint versions the existence of a hyphen would be treated as a pre-release version: https://github.com/badges/shields/pull/4222/files#r336798640

is `4.4.0.991265+398-sha.ee1eca51d-azdo.3306453` not semver compliant? Seems like it should be based on https://semver.org/#spec-item-10 but the `semver` lib check we're using is indeed flagging the versions with the build metadata as non-semver valid

https://github.com/badges/shields/blob/88e2cac0f8188a016682ca62c2675765d936186c/services/nuget/nuget-v3-service-family.js#L191-L195

**Comment by chris48s** [comment]
> is `4.4.0.991265+398-sha.ee1eca51d-azdo.3306453` not semver compliant? Seems like it should be 

A semver is `a.b.c+metadata`
That is `a.b.c.d+metadata`

**Comment by calebcartwright** [comment]
Lol 🤦‍♂ thanks Chris. I was staring so closely at the build metadata that I completely overlooked that

**Comment by rmarinho** [comment]
well in my comment I said  

> it might be that since the 4.4.0.991265+ is not semver 2.0 also it gets confused

Yes we aren't using semver yet, but we are using the metadata thing. So there's no fix because your lib for parsing gets confused?

**Comment by calebcartwright** [comment]
> So there's no fix because your lib for parsing gets confused?

No, not at all. I thought your versions w/build metadata were semver compatible, but I was obviously wrong, sorry about that. 

What's happened is that you started including extra content with your versions that include a `-` character. Shields has always treated these types of nuget package versions which contain a `-` as pre-release versions, and when you use the `/nuget/v` all pre-release versions are excluded. 

https://img.shields.io/nuget/v/Xamarin.Forms?style=flat-square&label=nuget
![](https://img.shields.io/nuget/v/Xamarin.Forms?style=flat-square&label=nuget)

If you use the `/nuget/vpre` route then pre-release versions are also considered, which is why that shows your latest 4.4.* version
https://img.shields.io/nuget/vpre/Xamarin.Forms?style=flat-square&label=nuget
![](https://img.shields.io/nuget/vpre/Xamarin.Forms?style=flat-square&label=nuget)

> Can't we just ignore the metadata part if it's a non semver ?!

IMO we should not start ignoring/dropping parts of a version in the absence of any known version specification. With a semver-compliant version, we know that the specification allows for the build metadata portion of the version to include a `-`, and that rule is accordingly used by Shields while filtering versions. 

I understand that your package doesn't intend version `4.4.0.991265+398-sha.ee1eca51d-azdo.3306453` to be a pre-release version, but since that's not a valid semver version, Shields doesn't apply rule 10 (or any other rules) of the semver 2 specification.

**Comment by calebcartwright** [comment]
As far as getting the nuget version badge for your package showing your expected version @rmarinho, there's a few options. 

Some things you could consider doing on your side:
* Start using semver-compliant versions for your package
* If can't/won't change to semver versioning, don't include a `-` in versions of your package that are not intended to be pre-release versions

Some things we could consider doing on the Shields side:
1. Change the default behavior for how nuget package versions are handled, basically treating all versions as semver-compliant (regardless of whether they actually are)
    * As mentioned above, this was recently considered by the Shields team but was rejected. We try really hard to not break existing users/badges, not change existing badge behavior, etc. and changing the default version filtering behavior of a long-established, widely used badge like this one would be highly likely to impact/break/change existing nuget version badges
2. Add an optional param for the nuget version badges that users could opt into to have their versions treated like semver versions. For example, maybe a query param something like `?semverMetadata=true`, and when a badge included that param then Shields would also apply semver rule 10, even if the versions aren't actually semver compliant. 

Without the flag, same default/current behavior:
https://img.shields.io/nuget/v/Xamarin.Forms?style=flat-square&label=nuget
![](https://img.shields.io/nuget/v/Xamarin.Forms?style=flat-square&label=nuget)

With the flag:
https://img.shields.io/nuget/v/Xamarin.Forms?style=flat-square&label=nuget&semverMetadata=true
![](https://img.shields.io/badge/nuget-4.4.0.991265%2B398--sha.ee1eca51d--azdo.3306453-blue)

I'd still be a firm "no" vote on that first option, but I think that second option may be a good compromise

**Comment by kzu** [comment]
I don't think shields should be tweaking its behavior to consider semver things that aren't (four version segments aren't semver). XF should use semver 2.0 instead of an unsupported format @rmarinho ;). And then #3926 would make the labels great again in that case. I think an optional query parameter to bring the metadata back would be nice (for semver valid values), though.

**Comment by chris48s** [comment]
I don't really have a handle on how good/bad "all nuget package versions should be a semver" is as an assumption. Does anyone know what the nuget packaging guidance is?

Another thing we could consider is a `?sort=semver` / `?sort=date` like we've done with GH tags/releases.

**Comment by rmarinho** [comment]
Well, I not going to disagree that we should be semver 2.0, but the true is we never were and this worked just fine before, the issue was when we started adding metadata to the packages. I think the assumption of having a '-' is a pre release should take account if it's after the '+' or not.

**Comment by kzu** [comment]
well, that would be just making up new rules for things that are not semver2 ;). How would you know that makes sense for other package managers? I'd say, remove the metadata and put it instead in the first line of the summary/description for the package, maybe. But, if and when the package is semver2, its sorting rules should be obeyed by shields, IMO.

**Comment by calebcartwright** [comment]
> I don't really have a handle on how good/bad "all nuget package versions should be a semver" is as an assumption. Does anyone know what the nuget packaging guidance is?

@chris48s - not sure I fully understand the question. nuget.org is now encouraging semver2 versioning schemes, but in my experience it has historically been more of a "wild west". I'm also not sure if that encouragement from the nuget.org folks is being echoed for myget and the other nuget-like registries we integrate with.

**Comment by calebcartwright** [comment]
From what I can tell looking at the code/history, we handle nuget package versions a bit differently than other version badges. For example, we've a renderer that uses 3 colors 🤷‍♂ 

https://github.com/badges/shields/blob/0e6d2c43f3f465ffae4fd33f3f02c9694a85c2d9/services/nuget/nuget-helpers.js#L6-L21

If we were just adding support for nuget version badges for the first time, I'd want to follow the same version badge conventions we use elsewhere and I'd also probably want to just leverage the `prerelease` query param (based on `/vpre` vs `/v` badge route) that we pass to the upstream endpoints and defer to the upstream provider to filter out whatever it considers prerelease versions.

https://github.com/badges/shields/blob/0e6d2c43f3f465ffae4fd33f3f02c9694a85c2d9/services/nuget/nuget-v3-service-family.js#L103-L119

FWIW that approach would result in OPs desired badge for XamarinForms package on nuget.org:
https://azuresearch-usnc.nuget.org/query?q=packageid%3Axamarin.forms&prerelease=false&semVerLevel=2

However, our nuget version badges have been around for quite some time and are used fairly heavily. In the last 24 hours we've had ~146k nuget.org version badge requests and ~20k myget version badge requests hit our badge servers (there's also chocolatey, resharper, and powershell gallery, self-hosted Shields instances, etc.), all of which are based on the current determination of whether a version is release or pre-release. Changing that **default** version filtering behavior would impact all of those badges, which is why we decided not to do so (this is option 1 [described above](https://github.com/badges/shields/issues/4494#issuecomment-572213226))

If there's any (non-subjective/preference-based) documented standard/specification/etc. that proves there is a bug in the way Shields is determining pre-release versions for nuget packages, then let's go ahead and make this change using the query param mentioned above (maybe the existence of that query param is sufficient in and of itself). Then Shields is out of the business of making the pre-release vs. release determination 😄 

However, if there's not, I think it would be a bad idea to change the current behavior based. Some folks may prefer the change, but I'm not sure what we'd tell any of our current/existing nuget version badge users that _don't_ like the change.
