### ISSUE TITLE
Sourceforge badge: Add support for download folder hierarchy

### ISSUE THREAD

**Issue by chrfranke** [badges/shields#4499]
:clipboard: **Description**
The sourceforge downloads badge allows to specify a 1st level folder but a 2nd level folder does apparently not work (sorry if I missed something).

Testcase:
https://sourceforge.net/projects/smartmontools/files/smartmontools/7.1/
JSON data for this level is available:
https://sourceforge.net/projects/smartmontools/files/smartmontools/7.1/stats/json?start_date=2019-12-30&end_date=2020-01-08

The badge returns "404 badge not found":
https://img.shields.io/sourceforge/dm/smartmontools/smartmontools/7.1
The badge works for root and 1st level download folder:
https://img.shields.io/sourceforge/dm/smartmontools/smartmontools
https://img.shields.io/sourceforge/dm/smartmontools

**Comment by calebcartwright** [comment]
Believe the problem is that the route for that badge isn't able to handle nested directory paths 

https://github.com/badges/shields/blob/fe02ac723f97e317a8a10a16674606c7944be3db/services/sourceforge/sourceforge.service.js#L42

so when you try to include one, the it's being interpreted as an additional route param that has no associated handler (hence the 404). 

This should be an easy fix if anyone is interested in working on this. Changing the `?` to a `*` should do the trick:

```js
      pattern: ':interval(dt|dm|dw|dd)/:project/:folder*',
```
