### ISSUE TITLE
Is it possible to JSON file's relative URL for endpoint?

### ISSUE THREAD

**Issue by gusbemacbe** [badges/shields#4528]
:question: **Question**

For example:

```html
<img alt="test" src="https://img.shields.io/endpoint?url=file://home/gusbemacbe/GitHub/repository/assets/json/badge.json&style=for-the-badge">

<img alt="teste" src="https://img.shields.io/endpoint?url=assets/json/badge.json&style=for-the-badge">
```

But both do not work. If I have to use full absolute HTTPS' URL, I have to upload/git pull every time, what it is boring. 

### Update

I had to use PHP to manipulate and used like:

```
<img alt="teste" src="https://img.shields.io/endpoint?url=https://localhost:1989/assets/json/insigna.json&style=for-the-badge">
```

But:

![image](https://user-images.githubusercontent.com/2257024/72337462-60ce7880-36a1-11ea-9c56-8e045e1227a2.png)

**Comment by calebcartwright** [comment]
Hi @gusbemacbe, could you please explain your use case/what you are trying to do?

**Comment by gusbemacbe** [comment]
Hi @calebcartwright 

Sorry for my absence, I have been working a lot. See the documentation: https://shields.io/endpoint

In this documentation, it suggests me to use full absolute URL address, but I would like to use the relative URL path, so I do not have to commit every time to check the test.

**Comment by calebcartwright** [comment]
> Sorry for my absence, I have been working a lot

No worries! I'm actually asking you to describe your use case, what type of badge you are trying to create, etc., because it's not clear from your issue description.

It sounds like you have some json file that resides local file system, and you are attempting to use the Shields.io service to create a badge based on that file on your local file system. If so, this is not a valid/possible use case; Shields.io does not have access to your local file system.

Shields.io creates badges by retrieving data from an internet-accessible API or file, and then uses that data to construct and return the badge. If you can make your json file internet-accessible, then you can use the Shields.io service to create a badge. However, you would probably just use the standard dynamic json badge and not the endpoint badge which is used for more complex use cases. 

https://img.shields.io/badge/dynamic/json.svg?url=https://github.com/badges/shields/raw/master/package.json&query=$.name
![](https://img.shields.io/badge/dynamic/json.svg?url=https://github.com/badges/shields/raw/master/package.json&query=$.name)

We have a badge builder on the main shields.io page that can help you construct such a badge
![image](https://user-images.githubusercontent.com/13042488/72639410-2a0b9300-392b-11ea-8c22-e046e099d52c.png)

If for some reason you need or want to work with a file on your local file system, then the only other thing we provide that you could potentially use would be our [gh-badges](https://www.npmjs.com/package/gh-badges) package. You could use this locally via the CLI or in a script with your local file to emit a badge

**Comment by gusbemacbe** [comment]
> No worries! I'm actually asking you to describe your use case, what type of badge you are trying to create, etc., because it's not clear from your issue description.

```html
<img alt="apps" src="https://img.shields.io/badge/apps_icons-2170%2B-33D17A.svg?style=for-the-badge&logo=gnome&logoColor=white&colorA=a89888" />
```

Preview: 

<img alt="apps" src="https://img.shields.io/badge/apps_icons-2170%2B-33D17A.svg?style=for-the-badge&logo=gnome&logoColor=white&colorA=a89888" />

```json
{
  "label": "apps icons 2170+",
  "labelColor": "#33D17A",
  "style": "for-the-badge",
  "logo": "gnome",
  "logoColor": "white",
  "colorA": "#a89888"
}
```

> If for some reason you need or want to work with a file on your local file system, then the only other thing we provide that you could potentially use would be our [gh-badges](https://www.npmjs.com/package/gh-badges) package. You could use this locally via the CLI or in a script with your local file to emit a badge

It was what I was looking for, but I have a doubt... Do I need to include `gh-badges` package or `node-modules` in my repository?

**Comment by gusbemacbe** [comment]
Observe that I need to increase logo height to be totally legible.

**Comment by gusbemacbe** [comment]
I am confused with `gh-badges`'s documentation.

**Comment by calebcartwright** [comment]
Where is the `2170+` number coming from/how is it being derived?

**Comment by gusbemacbe** [comment]
@calebcartwright 

```
<img alt="apps" src="https://img.shields.io/badge/apps_icons-2170%2B
```

**Comment by calebcartwright** [comment]
@gusbemacbe I understand how Shields and the static badges work 😄 

You have a json file with a label key that includes the number 2170. I'm asking how/where that 2170 number is being determined

**Comment by gusbemacbe** [comment]
@calebcartwright 

Ah, I made a mistake. I have just updated the JSON snippet above.

**Comment by gusbemacbe** [comment]
> Is that json file being generated automatically via some script or process? Are you manually specific the values in that file, etc.

Yes, it is what I tried. I tried to use `gh-badges` to catch JSON file, but I have no idea.

**Comment by calebcartwright** [comment]
> Yes, it is what I tried

Where are you getting the data from (the `2170` number)? I'm not familiar with "apps icons" at all. Could you please provide some additional context? It'll be a lot easier for us to answer your questions/offer suggestions/etc. if you can fully explain your scenario.

Please also feel free to join our [chat room in Discord](https://discordapp.com/invite/HjJCwm5) so that we could discuss things a bit more synchronously

**Comment by gusbemacbe** [comment]
> Where are you getting the data from (the `2170` number)? I'm not familiar with "apps icons" at all. Could you please provide some additional context? It'll be a lot easier for us to answer your questions/offer suggestions/etc. if you can fully explain your scenario.

2170+ is the fixed number of icons.

My badges are inspired by @SmartFinn's [Papirus icons](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)' README badges.

**Comment by calebcartwright** [comment]
Adding some additional context from discussion in Discord and closing accordingly. 

The OP has an icon set/theme (https://github.com/Bonandry/adwaita-plus) and wants to have a badge that displays the count of icons in that theme. 

Three options were suggested and discussed:
1. Use Shields Static badge with a hardcoded count and periodically update the count in the badge url to reflect changes in the icon count.
2. Use Shields GitHub Search Counter badge with a GH query that provides the correct count:
https://img.shields.io/github/search/Bonandry/adwaita-plus/extension:svg%20path:Adwaita++/apps/scalable?label=apps%20icons&colorB=33D17A&style=for-the-badge&logo=gnome&logoColor=white&colorA=a89888
![](https://img.shields.io/github/search/Bonandry/adwaita-plus/extension:svg%20path:Adwaita++/apps/scalable?label=apps%20icons&colorB=33D17A&style=for-the-badge&logo=gnome&logoColor=white&colorA=a89888)
3. Deploy a custom API/script that dynamically calculates the count, and returns an API response that conforms to the Shields Endpoint schema, which could be used with Shields Endpoint badge
