### ISSUE TITLE
Github (pre-)release downloads count latest by SemVer

### ISSUE THREAD

**Issue by ouuan** [badges/shields#4682]
**Edited by calebcartwright**: for anyone interested in implementing this, detailed steps/guidance can be found at the bottom of the thread, [here](https://github.com/badges/shields/issues/4682#issuecomment-590168537)

<hr />
:clipboard: **Description**

Make it able to get the number of downloads of the latest Github (pre-)release sort by SemVer.

:link: **Data**

Getting the latest (pre-)release sort by semver should be similar to `/github/v/release/:user/:repo?sort=semver` and `/github/v/release/:user/:repo?include_prereleases&sort=semver`.

Getting the download count should be similar to `/github/downloads/:user/:repo/:tag/total` and `/github/downloads-pre/:user/:repo/:tag/total`.

:microphone: **Motivation**

In this way, if a stable version (for example, 0.7.4) is released after a pre-prelease version (0.8.0-rc1), I can get both download counts.

**Comment by calebcartwright** [comment]
hi @ouuan 👋 

Just to clarify, I assume you are specifically talking about the case where the specified `tag` is `latest`, correct? (i.e. `/github/downloads/:user/:repo/latest/total`). Otherwise when `tag` is an explicit value, the download count for that exact tag is provided, and there is no derivation of what the "latest" tag is

**Comment by ouuan** [comment]
Yes, I'm talking about the `tag` is `latest`. I know the download count for that exact tag is provided, I'm asking for automatically set the `tag` to the latest (pre-)release sort by SemVer instead of time.

**Comment by calebcartwright** [comment]
> so I don't know what you mean by "specifically talking about the case where the specified tag is latest".

You likely already know much of the below, but recaping it anyway for clarity in response to your question.

Shields provides support for badges that display the download counts of GitHub Releases, with a few different varieties (which can also be configured to include or not include pre-releases):

1. the aggregated all-time download counts across all releases 
`https://img.shields.io/github/downloads/atom/atom/total`
![](https://img.shields.io/github/downloads/atom/atom/total)
2. the download count for a specific release (by specificing the associated tag)
`https://img.shields.io/github/downloads/atom/atom/v1.43.0/total`
![](https://img.shields.io/github/downloads/atom/atom/v1.43.0/total)
3. the download count for the "latest" release
`https://img.shields.io/github/downloads/atom/atom/latest/total`
![](https://img.shields.io/github/downloads/atom/atom/latest/total)

Your title and description in this issue appear to be in reference to use case 3, where you are asking for the ability to control if the download count is from the latest release by date (most recently published release) or by semver. 

I'm asking you to confirm if that is correct, as Shields uses different GitHub APIs and processing logic for those 3 scenarios.

**Comment by ouuan** [comment]
You can think it's similar to `latest` or not. I think how you classify them won't affect me, right?

> as Shields uses different GitHub APIs and processing logic for those 3 scenarios.

I've mentioned in the "Data" part of the description, I think the implementation should be like a combination of `/github/v/release/:user/:repo?sort=semver` and `/github/downloads/:user/:repo/:tag/total`. But, are you asking me how you should implement it? You can do whatever you like, I just want the feature I'm asking for.

**Comment by calebcartwright** [comment]
> You can do whatever you like, I just want the feature I'm asking for.
>
> You can think it's similar to latest or not. I think how you classify them won't affect me, right?

@ouuan - It is not entirely clear what feature you are asking for based on your original issue content, and some of your follow up responses and comments have only added to the confusion. That is why I've been asking you to clarify the request.

> But, are you asking me how you should implement it?

No. 

I've only asked you to clarify _what_ exactly it is you are requesting because again, it is not clear. In my last comment I asked you to confirm if I'd correctly summarized your request, but let's try some different questions.

Please answer the following questions, preferrably with a yes/no:

1. Are you currently using the GitHub Release Download badge and specifying `latest` for the `tag` parameter? (does your badge route look something like this: `https://img.shields.io/github/downloads-pre/[your-github-user]/[your-github-repo]/latest/total`)
2. Are you requesting the ability to control whether the selection of the "latest" release is based on date or semver with the GH Release Download badge for the latest release `https://img.shields.io/github/downloads-pre/[your-github-user]/[your-github-repo]/latest/total`
3. Are you requesting the GH Release Download badge for the latest release _always_ use semver to determine the "latest" release, and never use date?

**Comment by ouuan** [comment]
1. Yes.
2. Yes.
3. No.

**Comment by ouuan** [comment]
I said "**make it able to** get the number of downloads of the latest Github (pre-)release sort by SemVer.", both the questions 2 and 3 can "make it able to", but 3 is to remove an existing feature, which is not good.

In fact, I'm not exactly asking for 2, because you can use any URL you like, no matter `https://img.shields.io/github/downloads-pre-semver/[your-github-user]/[your-github-repo]/latest/total` or `https://img.shields.io/github/downloads-pre/[your-github-user]/[your-github-repo]/latest/total?sort=semver`. You can consider it as a "control" of `https://img.shields.io/github/downloads-pre/[your-github-user]/[your-github-repo]/latest/total`, or you can treat it as a new badge.

**Comment by calebcartwright** [comment]
> 2. Yes.

Great, thanks for confirming! 

This should be a relatively straightforward enhancement to the existing badge so marking as a `good-first-issue`.

For anyone interested in implementing this, there's a few helpers in `github-common-release` that can be reused, and just a couple steps to incorporate them:

1. Add the `queryParamSchema` from `github-common-release` to the downloads service class route
https://github.com/badges/shields/blob/ae4401ccb72a1b1f561a8f12dc8f255f81126162/services/github/github-downloads.service.js#L30-L35
The [github-release.service](https://github.com/badges/shields/blob/master/services/github/github-release.service.js) and [github-commits-since.service](https://github.com/badges/shields/blob/master/services/github/github-commits-since.service.js) may serve as helpful references
2. Update the `handle` function to accept the query params as the second parameter, and update the logic to utilize the `fetchLatestRelease` from `github-common-release` when the value for the `tag` parameter is `latest`
https://github.com/badges/shields/blob/ae4401ccb72a1b1f561a8f12dc8f255f81126162/services/github/github-downloads.service.js#L169-L191

**Comment by hjagodzinski** [comment]
@calebcartwright you suggest to use `queryParamSchema` from `github-common-release`. The schema contains two fields `sort` and `include_prereleases`. The latter information is already a part of the path as `kind` parameter. `kind` takes either `download` value which is equivalent to not passing `include_preleases` or `pre-download` which is equivalent to passing it. Is not a `size` parameter sufficient in this case?

**Comment by calebcartwright** [comment]
@hjagodzinski - good catch! that's correct, we wouldn't want to have a duplicative route and query param, so `sort` as the sole query param will suffice

**Comment by hjagodzinski** [comment]
@calebcartwright thanks for the confirmation!
