### ISSUE TITLE
CocoaPods: Can't render version or platform badge for package with no license

### ISSUE THREAD

**Issue by rayandrie** [badges/shields#4688]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

:link: **Link to the badge**
- https://img.shields.io/cocoapods/v/Cotter.svg?style=flat
- https://img.shields.io/cocoapods/l/Cotter.svg?style=flat
- https://img.shields.io/cocoapods/p/Cotter.svg?style=flat

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
The reason these are all failing is because we expect the JSON response from Cocoapods to include the keys `version`, `license` and `platforms` (we use the same validator for all badges).
When we call https://trunk.cocoapods.org/api/v1/pods/Cotter/specs/latest we get a response without a `license` key.

```json
{
  "name": "Cotter",
  "version": "1.0.1",
  "summary": "Cotter is the client SDK for Cotter authentication services",
  "swift_versions": "5.0",
  "description": "CotterIOS simplifies client's integration with Cotter. It is an SDK that provides necessary pages and API services that connects your application to Cotter authentication services.",
  "homepage": "https://github.com/cotterapp/ios-sdk.git",
  "authors": {
    "Cotter Team": "team@cotter.app"
  },
  "source": {
    "git": "https://github.com/cotterapp/ios-sdk.git",
    "tag": "1.0.1"
  },
  "platforms": {
    "ios": "10.0"
  },
  "source_files": "Source/**/*.swift",
  "resource_bundles": {
    "Cotter": [
      "Source/**/*.{png,storyboard,lproj}"
    ]
  },
  "frameworks": "UIKit",
  "swift_version": "5.0"
}
```

You can probably fix this by declaring a license for your project, but if this is a valid response object, maybe we need a different validator for the cocoapods license badge.

**Comment by rayandrie** [comment]
Hi Chris, thank you for your reply.

Thinking about it, a license should probably be a required parameter for an open-source CocoaPods project. Perhaps you're right about having a different validator since the JSON response is valid.

Thank you so much for your help!

**Comment by PyvesB** [comment]
By the way @rayandrie , we're open to pull requests if you want to help us out! Changing the schema _should_ be quite simple even for a first time contributor. 😉
