### ISSUE TITLE
Feature Request: Uppercase Parameter 

### ISSUE THREAD

**Issue by FredHappyface** [badges/shields#4694]
:clipboard: **Description**

Would there be any possibility of including a uppercase parameter for styles to have the text in uppercase as is the case for the 'for the badge' style but without the extra padding?

For example:

`https://img.shields.io/github/last-commit/FredHappyface/Nasm.LearningAsm`
![Last commit](https://img.shields.io/badge/last%20commit-today-brightgreen.svg)

`https://img.shields.io/github/last-commit/FredHappyface/Nasm.LearningAsm?uppercase=true`
![Last commit](https://img.shields.io/badge/LAST%20COMMIT-TODAY-brightgreen.svg)

With flat square and logo:

`https://img.shields.io/github/last-commit/FredHappyface/Nasm.LearningAsm?style=flat-square&logo=github`
![Last commit](https://img.shields.io/badge/last%20commit-today-brightgreen.svg?style=flat-square&logo=github)
`https://img.shields.io/github/last-commit/FredHappyface/Nasm.LearningAsm?style=flat-square&logo=github&uppercase=true`
![Last commit](https://img.shields.io/badge/LAST%20COMMIT-TODAY-brightgreen.svg?style=flat-square&logo=github)

Thanks for the awesome project! :smile: 
FH

**Comment by paulmelnikow** [comment]
Hi, thanks for the question. Since one of the goals of this project is consistency, I'd be 👎 on implementing this in the main Shields service. We try to limit the number of formats we support, and have removed one recently.

If you want to customize this, you could use the [Endpoint badge](https://shields.io/endpoint) to proxy the JSON result from Shields, reformat it, and emit it as you like.

**Comment by FredHappyface** [comment]
Ah that makes perfect sense. I may well take a look at that, thank you.

Thanks again 😁
