### ISSUE TITLE
Commits since badge is broken

### ISSUE THREAD

**Issue by S-B99** [badges/shields#4695]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The badge says repo or version not found. 

[This](https://github.com/S-B99/kamiblue/releases/tag/v1.0.1) is the version I'm trying to use. 

The badge worked previously, up until a few weeks ago. I thought it was my end until I realized I didn't modify anything. 

:link: **Link to the badge**

[![Commits badge](https://img.shields.io/github/commits-since/S-B99/kamiblue/v1.0.1?label=commits%20since&logo=git&logoColor=white)](https://github.com/S-B99/kamiblue/releases)

https://img.shields.io/github/commits-since/S-B99/kamiblue/v1.0.1?label=commits%20since&logo=git&logoColor=white

:bulb: **Possible Solution**

None I've been able to find.

**Comment by paulmelnikow** [comment]
Hi, thanks for your question.

I think the problem is that the badge assumes your main branch is called master, so you need to tell it which branch you want to compare to.

https://img.shields.io/github/commits-since/S-B99/kamiblue/v1.0.1/feature/master?label=commits%20since&logo=git&logoColor=white
![](https://img.shields.io/github/commits-since/S-B99/kamiblue/v1.0.1/feature/master?label=commits%20since&logo=git&logoColor=white)

**Comment by S-B99** [comment]
Ooooh, alright, that would explain it. Thanks!
