### ISSUE TITLE
Release shields aren't working

### ISSUE THREAD

**Issue by ruimaciel** [badges/shields#4805]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Release shields don't work, although link was created with template.

:link: https://img.shields.io/github/downloads/ruimaciel/mropes/total
:link: https://img.shields.io/github/downloads/ruimaciel/mropes/v0.0.2.0/total

**Comment by chris48s** [comment]
The reason its not working is because the things listed on https://github.com/ruimaciel/mropes/releases are tags, not releases.
Your project has 2 tags: https://api.github.com/repos/ruimaciel/mropes/tags
but zero releases: https://api.github.com/repos/ruimaciel/mropes/releases

Unfortunately, this is a frequent source of confusion for users.

There's a recent thread on this with more detail at: https://github.com/badges/shields/issues/2785

**Comment by ruimaciel** [comment]
Hi, thanks for the quick reply.

That's strange, because my project has two releases, which are also created with tags:
https://github.com/ruimaciel/mropes/releases
