### ISSUE TITLE
SSLLabs (SSL/TLS rating)

### ISSUE THREAD

**Issue by rugk** [badges/shields#4845]
:clipboard: **Description**

Similar to https://github.com/badges/shields/issues/2912, just a badge for the SSL/TLS rating shown by https://www.ssllabs.com/ would be nice.

:link: **Data**

https://www.ssllabs.com/

public API: https://www.ssllabs.com/projects/ssllabs-apis/ (has some legal restrictions)
even has a Go client: https://github.com/ssllabs/ssllabs-scan/

:microphone: **Motivation**

Same as https://github.com/badges/shields/issues/2912 (which actually refers the SSLLabs rating) it promotes a safer internet by rating the server configuration/TLS/HTTPS connection.

**Comment by PyvesB** [comment]
Hello @rugk, thanks for the suggestion!

I've read the terms and conditions of the API, and they seem really restrictive. Unfortunately, Shields would probably not qualify.

In particular, here are some sections of interest:
* use the API only to inspect only sites and servers whose owners have given you permission to do so.
* not allowed to use the API on a public web site.
* not allowed to publish any information received from us via the APIs without the owner’s express permission.
* not allowed to distribute, proxy, or otherwise make the API available for access or use by any person or entity other than your authorized employees, including but not limited to acting as a service bureau or developing a competing product or service offering.

We could contact Qualys SSL Labs to enquire about a relaxed set of terms for us, but I'm quite pessimistic this would succeed.

There's a section about "server tools" which could arguably cover self-hosted users who deploy their own Shields distribution privately. However, it contains a number of additional conditions, for example imposing constraints on the server startup. Even for self-hosted users I wouldn't feel comfortable in supporting such a service.

**Comment by paulmelnikow** [comment]
Feel free to comment on this issue or reopen if there's any new information from the service provider.
