### ISSUE TITLE
Design question for npm package

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#4849]
Continued from https://github.com/badges/shields/pull/4756#issuecomment-607420151, where @chris48s wrote:

> I think there is a big design question about what the badge-maker package should be which we don't all agree on:
> 
> One way of thinking about it is:
> Option 1 - Badge-maker should be a stand-alone package. It happens to live in the same repo as shields.io, but in principle it could live in its own repository if we wanted. Its a package with many users, but its biggest and main user is shields.io. Any functionality we depend on should be exposed and documented via the public interface of the package and we consume that functionality in the same way as any other user, eating our own dogfood.
> 
> Another way of thinking about it is:
> Option 2 - Badge-maker is a package which exposes only a subset of the badge rendering capibilites of shields.io to a wider audience. It lives in and is inseparable from the shields.io repo. The interface we give our users is different to the interface we consume internally.
> 
> Option 2 is where we are now. I've been thinking we should be heading towards option 1. I'm not necessarily _right_ about that, but that's definitely the direction I've been thinking in. Given that removing a feature that our own application depends on from the public interface of the package actively reverses that direction of travel, I think its worthwhile to be explicit about the reasons for that.

**Comment by paulmelnikow** [comment]
I agree with you that we should be heading toward option 1.

It has the lowest mental overhead, and also means we can harmonis/ze with the Endpoint badge spec. I think that could create a lot of flexibility for users.

It sounds like the gaps are:

1. Links
2. Logos
3. Possibly JSON, if we remove the JSON support as discussed at https://github.com/badges/shields/pull/4756#issuecomment-597782014

Is that right?

**Comment by chris48s** [comment]
Yep - I'd agree with that assessment. Just to flesh those three points out slightly more. In order to move from using relative imports to being a consumer of our own package, we need:

### Links

Exposing links is pretty trivial (although we do need to decide on the public interface for it) its passing through a couple of strings really.

### Logos

Logos is slightly more involved as we need to move the logo code from `/lib` into the package, allow simpleicons to be installed as a peer dependency (if the user wants/needs it) and work out the interface for logos (to deal with simpleicons/custom/base64) in the input object. Doing this would also remove the final remaining relative import to the package requiring anything other than `makeBadge`:

https://github.com/badges/shields/blob/8621fe42d76b809e9ba4ae844920f8ed0373817a/lib/logos.js#L4

I'd propose pushing this one back to 3.1 it is a feature add, not a BC-break (although its worth thinking about it now)

### JSON

If we need JSON for testing, it needs to be a supported output format for users too. We don't want to remove it. Maybe we do want to think about the shape/format of the JSON in the context of the input object as well :thinking:

**Comment by paulmelnikow** [comment]
> Exposing links is pretty trivial (although we do need to decide on the public interface for it) its passing through a couple of strings really.

Yea, agree.

Personally I think links are kind of a pointless feature of Shields since in most circumstances they don't work. (i.e. you have to use `<object>` when embedding the badge, not `<img>`)

Another option would be to remove them, though that seems like more work than keeping them.

> I'd propose pushing this one back to 3.1 it is a feature add, not a BC-break (although its worth thinking about it now)

:+1:

> If we need JSON for testing, it needs to be a supported output format for users too. We don't want to remove it. Maybe we do want to think about the shape/format of the JSON in the context of the input object as well 🤔

This one I disagree with. Here's how I'm thinking about it:

1. We do use JSON for testing – but more importantly, we provide JSON output as a service.
2. These four things are machine-friendly representations of the contents of a badge. They should be harmonized so they as are close to each other as possible:
    - The output of `coalesceBadge`
    - The input to the library's `makeBadge` function
    - The Endpoint badge schema
    - The JSON badge output schema
3. If these schemas are brought into close alignment, generating the JSON output badge on the Shields server is `JSON.stringify()`-ing a really minor transformation on the output of `coalesceBadge`, and there isn't a need to use a complicated rendering pipeline to do that.
4. Because the Shields JSON "badge" schema is such a minor/trivial transformation on a small piece of JSON, we don't need to expose that transform so that others can use it for testing. So it's not something the library needs to support.

**Comment by chris48s** [comment]
Yes. This is a good point. We could generate the JSON we need for our own JSON endpoint/testing outside of `makeBadge`. If we do that, we can still move in the direction of consuming our own package and it doesn't matter if we remove JSON output from the package (and also we don't need to care so much about backwards-compatibility if we change the format a bit, which is also useful). If we plan to do that, we could just drop it while we still don't depend on the public interface of the package. That breaking change is best made in v3.0 and we can work on moving things about for our internal use independently.

Do you have any thoughts on the other question in https://github.com/badges/shields/pull/4756#issuecomment-607420151 about changing the input object format? The change to the input format should also be done for v3.0.

I think given most of the params are optional, the non-nested version makes more sense when you're not using all of them e.g:


```js
{
  labelText: 'build',
  messageText: 'passing',
  messageColor: '#555',
}
```

**Comment by paulmelnikow** [comment]
Yea, I think flatter is easier. Easier to document, and easier to deal with across various platforms where developers might use this, and a little easier to validate.

`labelText`, `messageText`, and `messageColor` are more explicit which is good. However since we already use `label`, `message`, and `color` in (1) all the service implementations, (2) the Endpoint badge, and (3) the query params, I'd prefer we use those names here too. In particular I see the argument for `messageColor` over `color`, although I think it is okay to keep using `color` since the vast majority of badges, even the static badges, keep the default `labelColor`.

For `link` I'm more open to a new API, since (1) very few of the badges use it, (2) it's not in the Endpoint schema, and (3) the current API of specifying the query param twice is really strange. If the default is to link both sides of the badge to the same value, we could use `?link=http://whole-badge`, with `?link=http://right&labelLink=http://left` to link the label to something different, and `?link=&labelLink=http://left` to link the label and not the message (if we think we even need that). We should also decide if we want to keep backward compatibility with the double link query param. This question probably needs a comment period, and an issue of its own. Since we need to make a decision on the package now, three options come to mind:

1. Pick an API that we think will make sense everywhere (i.e. in services, coalesceBadge, Endpoint, query params) and adopt it first in the library, then bring it into the server codebase, and finally consider what to do about the legacy query param. If we change our mind during those discussions, ship a breaking change.
2. In the style of the query param (which yields an array) and `coalesceBadge`, allow `makeBadge`'s `link` to be either a string, or an array containing one or two values. Revisit and ship a breaking change if necessary.
3. Include it in the library but as an explicitly unstable feature. [React has methods in it which are preceded with `unstable_` to indicate they can change in any version.](https://gist.github.com/bvaughn/8de925562903afd2e7a12554adcdda16#warning-unstable_-apis-may-change-in-any-version-without-respecting-semver) We could name the parameter `unstable_link` to signal the same thing.

A final thought on link – and the reason I haven't spent any time working on it in the past 3+ years – is that IMO it is a _mostly_ useless feature. We could possibly consider seeking feedback from the community and then removing it.

**Comment by paulmelnikow** [comment]
Just noticed #3370. Should we close it and track here instead?

**Comment by chris48s** [comment]
> However since we already use label, message, and color in (1) all the service implementations, (2) the Endpoint badge, and (3) the query params, I'd prefer we use those names here too

Consistency with the endpoint badge/query params is a good point :+1: I'm convinced on `label`, `message` and `color`.

> We should also decide if we want to keep backward compatibility with the double link query param. This question probably needs a comment period, and an issue of its own

We could just defer links to 3.1 too. We need it to get rid of relative imports to package internals, but we can't actually do that until we do the logo work as well and adding links is non-breaking. I suggested adding it in 3.0 because it is "just passing 2 strings", but I agree the effort is really in working out how to expose it.

That would make the remaining jobs on #4756 :

* Change `text[]` to `label` and `message`, fix message only badge
* Remove JSON output format
* Update the docs

all of which are minor - I'll have a look at them this evening.

> We could possibly consider seeking feedback from the community and then removing it.

My gut instinct is that across the whole of shields.io, links is a very rarely used feature, but its on by default for the github and twitter social badges which do get a decent amount of traffic so removing the feature completely would probably have some friction (I wonder how many actually embed them with the `<object>` tag though?).

> Just noticed #3370. Should we close it and track here instead?

I have found this discussion useful, but its also covered several topics which won't all be worked on at once. Assuming you agree with the points above, I think we close this issue and move the future work to more focussed issues:

* What to do about links?
* Move JSON output out of the package and into core/server
* Keep #3370 open, but update it with relevant info from this thread

**Comment by paulmelnikow** [comment]
💯

**Comment by paulmelnikow** [comment]
Should we rename `template` to `style`, too?

I don't think that needs to block the merging of #4756, though it sounds like it should be changed before the release is made.

**Comment by chris48s** [comment]
I've added that to #4756 as well

**Comment by chris48s** [comment]
I've split the remaining future work from this issue into more specific issues
