### ISSUE TITLE
Strange space between 'o' and 'w' chars (windows 8)

### ISSUE THREAD

**Issue by Semigradsky** [badges/shields#486]
![](https://img.shields.io/badge/windows-download-green.svg)
https://img.shields.io/badge/windows-download-green.svg

In Chrome 43.0.2357.130 m:
![image](https://cloud.githubusercontent.com/assets/1198848/8391454/1f5c7a3e-1ccd-11e5-8fe8-9eb231a52212.png)

In IE 11.0.9600.17842:
![image](https://cloud.githubusercontent.com/assets/1198848/8391453/16be998e-1ccd-11e5-9631-2caa37bea1e3.png)

**Comment by espadrine** [comment]
This seems like an issue in the font rendering library in windows 8. It would be great to have similar images for different versions of windows.

We literally send strings of text to be rendered by the browser. I'd expect it would show up the same when part of a body of text; otherwise, the browser engines didn't set up kerning properly.

Unsurprisingly, it shows up fine on other systems: http://dev.modern.ie/tools/screenshots/#https://img.shields.io/badge/windows-download-green.svg

**Comment by Semigradsky** [comment]
It seems that it is even independent of a fixed set of updates.
On another machine with windows 8 it looks better:
![image](https://cloud.githubusercontent.com/assets/1198848/8613484/66afd938-26e8-11e5-843f-98f7ad252608.png)
