### ISSUE TITLE
Wrong GitHub tag is shown

### ISSUE THREAD

**Issue by Gama11** [badges/shields#490]
[This](https://github.com/HaxeFlixel/flixel) repo uses this badge:

[![Haxelib Version](https://img.shields.io/github/tag/HaxeFlixel/flixel.svg?style=flat&label=haxelib)](http://lib.haxe.org/p/flixel)

It shows the latest version as `3.3.9`, even though the latest tag / most recent version is [`3.3.11`](https://github.com/HaxeFlixel/flixel/releases/tag/3.3.11).

I suspect this might be caused by the double digit patch number.

**Comment by espadrine** [comment]
Thanks for raising this!

One of the [tags](https://api.github.com/repos/HaxeFlixel/flixel/tags) is `1.09`, which is not semver compliant. Since we can't use semver ordering, we fall back on to the next best thing, ASCII ordering. It is bad, but dealing with arbitrary complex versionning schemes (as are found in the wild) is hard. If you can think of a better algorithm, it would be welcome!

**Comment by Gama11** [comment]
Ah, I see... that's from before we followed semver.

In this case (and most cases I'd imagine?) simply using the most recent tag would work just fine. That's how I thought it works until now, actually.

Different urls to deal with different versioning schemes would be another option.. tag/latest, tag/semver etc.. that might overcomplicate it though?

**Comment by espadrine** [comment]
> simply using the most recent tag would work just fine

Hehe, it worked that way until someone told us that they had the wrong version on their badge… They had made a 3.2.14, then a 3.3.0, then a 3.3.1, then performed a bugfix patch tagged 3.2.15.

The use of a different URL is an interesting idea. It is an issue for all badges dealing with versions, though.

**Comment by drdanz** [comment]
We have the same issue here: [![Latest Release](https://img.shields.io/github/tag/robotology/yarp.svg?label=Latest Release)](https://github.com/robotology/yarp/tags)
We have a tag `start` that is probably causing the issue.
Would it be possible to add a list of tags to skip to the URL? i.e. something like
```
https://img.shields.io/github/tag/robotology/yarp.svg?label=Latest Release&skip=start;foo;bar
```

**Comment by espadrine** [comment]
@drdanz We filter out things that don't look like a version. In your case, you have a non-semver `v2.3.20.1`, which throws off the semver detection, which makes it fall back to ASCII comparisons.

**Comment by espadrine** [comment]
I intend to switch to a simplified three-tier version analysis: semver / a custom dotted-version comparator / ASCII. The ASCII tier will no longer have non-versions filtered out, while the new custom dotted-version will use integer list comparison (and trailing data ASCII comparison for the `-alpha` and the like). Initial testing shows that Flixel and Yarp will be fixed by that new design. Versions that follow a different convention than dots (eg, `v1-3-10`) won't be fixed, and will be handled by the third tier.

(It is irrelevant for https://github.com/badges/shields/issues/261, which now uses the PHP algorithm. The same goes for https://github.com/badges/shields/issues/377, which uses GitHub's /latest version.)
