### ISSUE TITLE
Badge request: GitHub submodule version number

### ISSUE THREAD

**Issue by MetRonnie** [badges/shields#4934]
:clipboard: **Description**

A badge to show the package.json version of a git submodule hosted on GitHub. E.g.

![Submodule version](https://img.shields.io/badge/submodule%20version-v1.2.1-blue)

:microphone: **Motivation**

When a GitHub repo contains a submodule, it can be useful to know the version of that submodule. One could also add a second badge to compare the latest release of that submodule repo (using `/github/v/release/:user/:repo?sort=semver`)

![Submodule version](https://img.shields.io/badge/submodule%20version-v1.2.1-blue) ![Latest submodule release](https://img.shields.io/badge/latest%20submodule%20release-v1.3.6-green)

:link: **Data**

This can already sort of be achieved using `/github/package-json/v/:user/:repo/:branch` where you put the commit SHA that the submodule is checked out at as the `:branch`. However, that requires manually updating README.md every time you checkout a new version/commit of the submodule. It would be useful if Shields could automatically get the submodule commit SHA from the parent repo (although I don't know how that would work).

Edit: In case it's not clear, here is a screenshot of a parent repo containing a submodule that is checked out at `f21a45c...`. Clicking on the submodule folder takes you to that repo checked out at that commit. The `.gitmodules` file provides the URL of the submodule repo (but not the commit SHA).

![image](https://user-images.githubusercontent.com/61982285/80208156-84517980-8627-11ea-98f9-740bd2545c73.png)

**Comment by LucBerge** [comment]
Hello, I am also looking for a badge like this!!

I have 4 repos which uses multiple submodules with neested submodules. A total of 10 repos to check if the submodule is up to date.
I simple badge could do the job.

> Proposed endpoint: `/github/package-json/v/:user/:repo/:branch`

A repo can have multiple submodules. In this case you must add the submodule name to the endpoint: `/github/package-json/v/:user/:repo/:branch/:submodule`

> One could also add a second badge to compare the latest release of that submodule repo [...]

Alternatively, you can have a green badge when you are using the latest version and a red badge when not up to date:

Submodule `my_submodule` is up to date: ![](https://img.shields.io/badge/my__submodule-v1.2.1-green)
Submodule `my_submodule` is **not** up to date: ![](https://img.shields.io/badge/my__submodule-v1.2.1-red)

**Comment by calebcartwright** [comment]
I do not think this is going to be viable for us to provide a native badge.

At the risk of stating the obvious, a git submodule will not necessarily reside on GitHub just because the consuming repo is hosted on GitHub (i.e. GitHub repos can and do have submodules which are hosted outside GitHub). That in turn means there's no fully deterministic way for us to check characteristics of that submodule via APIs; our badge servers would have to pull down the submodule and then inspect it, which is an absolute non-starter.

_If_ GitHub provides an API which returns the current sha of a submodule, then it would technically be possible for us to provide a badge that simply displays the sha of the specified submodule. However, I don't see that being a particularly useful badge, and would suggest deferring that to a [Custom Endpoint](https://shields.io/badges/endpoint-badge), unless and until someone can make a sufficiently compelling case for the value prop of such a sea-displaying badge and there's enough community interest to justify our time of review and maintenance/upkeep.

Even assuming the submodule repo is in GitHub, I don't think it would be possible for us to use that commit sha to discover any associated tags via GitHub's API (at least not directly, IIRC we'd have to do something like fetch the entire set of tags and then parse through them looking for the matching sha).

Continuing this chain of assumptions, I suppose if we were able to get the sha via the API and that the submodule repo was hosted in GitHub, then we could use GitHub's standard API surface to get a file from the repo for the she-associated blob to get something like the `version` value from a package.json file.

I'm going to go ahead and close this for now because this is not something the Shields team will ever work on ourselves, it's 3+ years old and has received little community interest, there are a large number of challenges/assumptions and missing info as I detailed above, and even in the happiest path case we'd still be dealing with a rather chatty networking scenario with lots of back and forth calls that may well run into GitHub's time limit for rendering static content (including badges).

If someone wants to do the hard work of gathering all the relevant data and proving out a potential solution then we'll consider, but otherwise, I just don't think that our static content badges are an effective solution for tracking whether git submodules are up to date.

**Comment by LucBerge** [comment]
@calebcartwright Yes it is not planed, this is the whole point of this issue... We request you or anybody to do it because it is usefull. Why don't you just make it low priority?

**Comment by chris48s** [comment]
So there are GitHub APIs that can be used to get data on submodules.

The GraphQL API has a `submodules` query. For example:

```gql
{
  repository(owner: "sharkdp", name: "bat") {
    submodules(first: 100) {
      nodes {
        branch
        gitUrl
        name
        nameRaw
        path
        pathRaw
        subprojectCommitOid
      }
    }
  }
}
```

For this purpose, the REST Contents API would probably be the most appropriate.

If we look at an example like
https://github.com/sharkdp/bat/tree/master/assets/syntaxes/02_Extra
we can request
https://api.github.com/repos/sharkdp/bat/contents/assets/syntaxes/02_Extra/AWK
which will also give us the SHA from the sub-repo.

Using that, we would be able to make a badge showing something like ![](https://img.shields.io/badge/awk-e23926e-blue.svg). That's a minimum viable submodule badge, but then (as you say) we would have to make additional API calls to resolve that to a tag or know how up-to-date that is, which we generally try to avoid.

If someone finds that useful and wants to add that basic implementation that just shows the SHA using the contents API, I think that would be reasonable tbh. As you say though, it might not be the most useful variant.
