### ISSUE TITLE
Switch default env in Grafana

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#4969]
Our [Grafana dashboard](https://metrics.shields.io) shows the `shields-io-production` env by default. This corresponds to the old OVH servers (prior to #4929).

This should be changed to display the `shields-production` env by default.

**Comment by platan** [comment]
https://metrics.shields.io/ is managed by https://github.com/platan/metrics-shields-io-config

If you want to change anything in dashboards, you have to:
- log into Grafana https://metrics.shields.io/
- change anything in dashboard (e.g. select a different env)
- copy dashboard definition: click "save dashboard" icon, then "Copy JSON to clipboard"
- paste dashboard definition in one of existing dashboard files https://github.com/platan/metrics-shields-io-config/tree/master/grafana/dashboards
- deploy new dashboards using Ansible (currently only I have an access to the https://metrics.shields.io/, but we can change it)

I've changed default env by https://github.com/platan/metrics-shields-io-config/commit/b1eed5ed34c7c364db2846c406ee43ab91dcbeac (diff is sometimes bigger than it should be, because JSON os produced by different Grafana versions).

**Comment by PyvesB** [comment]
Thanks for the quick response and documenting the steps! Works as expected, closing! 🎉
