### ISSUE TITLE
Dependencies badge David "inaccessible"

### ISSUE THREAD

**Issue by C0ZEN** [badges/shields#5133]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Since today the badge in Dependencies/David is broken with the "inaccessible" status.
Also I tried to create it once again but the same result happened on shields.io.
Screen: https://i.imgur.com/t98tTeC.png

:link: **Link to the badge**

Screen: https://i.imgur.com/wVjrhKP.png

https://camo.githubusercontent.com/1c155550be3dfea0398750ce1a486ac947348949/68747470733a2f2f696d672e736869656c64732e696f2f64617669642f736f6e69612d636f72706f726174696f6e2f696c2d6573742d6d6964692d646973636f72643f7374796c653d666c61742d737175617265
https://camo.githubusercontent.com/fc94e2dbec401fbf1bdb8a20c0de775eca647188/68747470733a2f2f696d672e736869656c64732e696f2f64617669642f6465762f736f6e69612d636f72706f726174696f6e2f696c2d6573742d6d6964692d646973636f72643f7374796c653d666c61742d737175617265

My repo issue
https://github.com/Sonia-corporation/il-est-midi-discord/issues/493

**Comment by chris48s** [comment]
Looks like https://david-dm.org/ is down.

There's a tracking issue at https://github.com/alanshaw/david/issues/163 but it seems to have been on and off for a while.

We'll have to keep an eye on this one. If its consistently down/flaky we may need to look at deprecating this one.

**Comment by C0ZEN** [comment]
This is back online.

**Comment by C0ZEN** [comment]
Down again...

**Comment by RocktimSaikia** [comment]
July 24, [They are still down](https://david-dm.org/). What can be done here for now?  Most of my projects used `dependencies` badge. Guess I have to update every `readme` file.

![david](https://user-images.githubusercontent.com/33410545/91049008-23b86480-e63a-11ea-8a98-2a8eaf724a98.png)

**Comment by calebcartwright** [comment]
This is down, again. The lack of stability with the David service is rather concerning. If it wasn't such a popular I'd badge I'd be inclined to just go ahead and deprecate it

Here's the latest issue in the David repo tracking the outage
https://github.com/alanshaw/david/issues/171

**Comment by calebcartwright** [comment]
And back up

**Comment by dmnsgn** [comment]
Down again. Is the `librariesio/release` badge a direct replacement?

**Comment by calebcartwright** [comment]
@dmnsgn - the David product has been offline for quite a while, see https://github.com/alanshaw/david/issues/179. We finally decided to deprecate our David badges because we just couldn't justify continuing to attempt to provide badges for a service that's offline as much as, if not more than, it's online.

https://github.com/badges/shields/issues/7135

If you decide to migrate from David to an alternative service, you'll need to find and select that replacement yourself (we try t o stay out of the vendor/product recommendations). We do support Libraries.io badges as well as one or two other dependency related badges if I recall correctly, though you can always browse and search for our badges on https://shields.io/

**Comment by dmnsgn** [comment]
Thanks for the pointers! `librariesio` will do for me.
