### ISSUE TITLE
Add CI check for missing dependencies in package

### ISSUE THREAD

**Issue by amirzahavi** [badges/shields#5158]
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [x] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

**badge-maker version: 3.0.0**

when consuming the "badge-maker" as a dependency the dependency "camelcase" is not installed and it causes a failure:

> module.js:550
>     throw err;
>     ^
> 
> Error: Cannot find module 'camelcase'
>     at Function.Module._resolveFilename (module.js:548:15)
>     at Function.Module._load (module.js:475:25)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)

:bulb: **Possible Solution**

**add to the [dependencies list in package.json](https://github.com/badges/shields/blob/master/badge-maker/package.json#L36)
camelcase: "5.x.x"**

**Comment by chris48s** [comment]
Thanks for reporting this. There's a PR open to fix this at #5159
Once another maintainer approves that I'll merge it and push a patch release.

Just thinking slightly more widely about this issue, this problem snuck in because we run the tests for the badge-maker package in the context of the shields.io application as a whole. This has the advantage that we don't need to specify all the testing dependencies in both `package.json`s and bump them all in 2 places every time there are new versions of `chai`, `mocha`, `sazerac`, `snap-shot-it`, etc

The downside is if we start using a dependency in badge-maker that also exists in the parent app's `package.json` and forget to add it to the badge-maker `package.json` (which is what happened here), all the tests will pass locally and in CI. I suspect this means we're doomed to repeat the same mistake again.

Anyone have any thoughts on how we can be smarter about this? I wonder if declaring the testing deps twice (so we can run the package tests completely independently in CI) is the lesser of 2 evils here..

**Comment by calebcartwright** [comment]
What if we added another CI check (maybe even with GHA) with a standalone mini-project that consumed badge-maker as a dep, but that never ran an npm install on the Shields server. 

We _kinda_ do something similar with the daily tests job

**Comment by chris48s** [comment]
Version https://www.npmjs.com/package/badge-maker/v/3.0.1 fixes this

As soon as we have another set of checks for just the package, that requires some kind of testing infrastructure to exercise the code, which then starts to look a lot like moving the test suite deps into the package..

**Comment by calebcartwright** [comment]
> which then starts to look a lot like moving the test suite deps into the package..

Does it have to though? Wouldn't simply running the cli as a CI check give us more than we have today? 

new simple-stand alone package.json, could be `echo`'d on the fly, reside in a separate test repo, etc.
```json
{
  "name": "foo",
  "private": true,
  "scripts": {
    "test": "badge build passed :green > mybadge.svg"
  }
}
```

pseudo ci check process:
```bash
# if necessary, but the PR version
git clone --depth 1 https://github.com/badges/shields.git
cd directory-that-contains-packagejson
npm i ../shields/badge-maker
npm test
```

**Comment by chris48s** [comment]
I hadn't thought of using the CLI tool as the test. That does have the nice property that (at least in current form) that `require()`s every file in the package which gives us a pretty decent smoke test for this issue.

**Comment by paulmelnikow** [comment]
:+1: that we're automating the check, in some way. These are easy mistakes to miss.

It doesn't help with undeclared dependencies which are listed in dev dependencies, though that's something we could add down the line if we find it comes up often. I guess it's usually caught in a staging deploy, which may be quickly enough.

**Comment by calebcartwright** [comment]
> It doesn't help with undeclared dependencies which are listed in dev dependencies

Would the `--production` flag on the install not help with that? (I forget if npm honors that for installs targeting a directory)

**Comment by chris48s** [comment]
> undeclared dependencies which are listed in dev dependencies

There are no `devDependencies` in badge-maker, which is.. sort of part of the problem - everything we need to test it is in the parent dir.

I've had a go at @calebcartwright 's idea in https://github.com/badges/shields/pull/5162 We can actually make it simpler..
