### ISSUE TITLE
Using shields.io twitter badge does not seem to work

### ISSUE THREAD

**Issue by stefansiegl** [badges/shields#518]
Hi,

Shields.io is really offering a great service, lots of thanks for that. I was trying out the badge for twitter and tried to understand how to set this up correctly and fail.

On your homepage you show an example of the twitter badge: https://img.shields.io/twitter/url/https/shields.io.svg?style=social - this shows 0 tweets, which I think is wrong.

I tried to use the shield with my twitter account (sieglst) and guessed that the badge should be: https://img.shields.io/twitter/url/https/sieglst.svg?style=social - this also shows 0 tweets.

What do I do wrong?

Thank you,
Stefan

**Comment by espadrine** [comment]
Thank you for raising this issue!

I actually believe that nobody has ever tweeted https://shields.io, because the secure version of the website is (shame on us!) using a self-signed certificate, because of various issues and an awkward setup (which will change reasonably soon).

On the other hand: ![](https://img.shields.io/twitter/url/http/shields.io.svg?style=social)… I'll switch to the non-TLS version on the front page.

I believe the purpose of the badge is unclear. You believe the badge shows the number of tweets produced (right?), while it shows the number of tweets related to a URL (for instance, `http://shields.io`). Since the URL `https://siegl` has never produced any tweet, that number is zero.

I will change the front-page title from "Twitter" to "Twitter URL", if that is clearer.

**Comment by stefansiegl** [comment]
Ah, now this explains it. Thanks a lot. 
I also briefly checked the twitter api and it seems that everything interesting requires some kind of auth.

**Comment by espadrine** [comment]
I'll close this in favor of https://github.com/badges/shields/issues/527
