### ISSUE TITLE
Cannot match a path ending with `.json`

### ISSUE THREAD

**Issue by alvis** [badges/shields#5187]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Matching pattern: `snyk/vulnerabilities/github/:user/:repo/:manifestFilePath*`
Example broken :link: https://img.shields.io/snyk/vulnerabilities/github/gatsbyjs/gatsby/package.json

Some services take `.json` as part of its URL match.
For instance, in the example link for synk above, it should take `package.json` as `manifestFilePath`.

However, #3644 & #3717 broke the URL matching mechanism accidentally.
Now, manifestFilePath is mapped to `package` only, not `package.json` since it has a `.json` extension.  

The problem is that it's now matching a `.json` in the path:
https://github.com/badges/shields/blob/5ba08b1deed2c8b890fac7cb9f11185c0ec05bfa/core/base-service/route.js#L31-L34

Is there any reason we should match `.json`?
It wasn't there before #3644.

**Comment by paulmelnikow** [comment]
Hi, the issue is that we support extensionless badges by default (per #3717 which you link to), but it doesn't work for badges which end with `.json`, `.png`, etc. because the server doesn't know whether the extension is part of the badge or the format.

If you tack a `.svg` on the end of that it should work fine:

https://img.shields.io/snyk/vulnerabilities/github/gatsbyjs/gatsby/package.json.svg
![](https://img.shields.io/snyk/vulnerabilities/github/gatsbyjs/gatsby/package.json.svg)

This didn't break with #3717; rather it's a limitation of that change.

**Comment by alvis** [comment]
It's a bit hacky, but I accept this as an intended trade-off of a better feature...

**Comment by paulmelnikow** [comment]
Sorry it feels hacky! 😀
