### ISSUE TITLE
Open VSX Registry Badge

### ISSUE THREAD

**Issue by HaaLeo** [badges/shields#5218]
:clipboard: **Description**

The [Open VSX Registry](https://open-vsx.org/) just launched as an alternative for microsoft's proprietary [Visual Studio Marketplace](https://marketplace.visualstudio.com/)

The badges should show information similar to the already existing VS Code Marketplace badges.

:link: **Data**

I could not find any official API documents. However, the registry is open source and can be found [here](https://github.com/eclipse/openvsx). [This file](https://github.com/eclipse/openvsx/blob/master/server/src/main/java/org/eclipse/openvsx/RegistryAPI.java) could be a good entry point for reverse engineering the API.

:microphone: **Motivation**

Since extension developers love to include status badges of their extensions in the extensions' README files to indicate where it is published, its rating and version, it would be great to enable badges for the new registry as well.

**Comment by calebcartwright** [comment]
Thanks for the suggestion @HaaLeo! I don't have any objections to supporting this service, though IMO we'd really need a more formalized API spec and documentation before adding that support.

The Shields badge servers can throw a lot of traffic at these upstream platforms/services to get the data needed for badges, and we'd want to make sure that this registry intends for the APIs to be leveraged externally along with any authentication/throttling/etc. implications. We'd also want readily consumable documentation for the API so that we don't have browse and grok source code in version control (which may not always reflect what's actually running) in order to support and troubleshoot our badges.

I'd suggest opening a request with the Open VSX Registry to get some clarify and formalization on their API (if one doesn't already exist) and then cross posting it here for awareness

**Comment by Surendrajat** [comment]
The API docs are available now: https://open-vsx.org/swagger-ui/

**Comment by calebcartwright** [comment]
Thanks @Surendrajat!

**Comment by helpsdev** [comment]
Hi there,  I'm a first-time contributor I got here from the hacktoberfest tag. Any chance I can work on this?

**Comment by calebcartwright** [comment]
Absolutely @helpsdev! We've got a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) that walks through the process of creating a new badge, and you can ping us here and/or on Discord with any questions

**Comment by IronGeek** [comment]
Hi @helpsdev, are you still working on this? If not, do you mind if I have a go at it?

**Comment by helpsdev** [comment]
Hey @IronGeek, yeah go ahead :)

**Comment by varunkumar** [comment]
How do we use these badges?
