### ISSUE TITLE
Update shields with GitHub's new look

### ISSUE THREAD

**Issue by urmilshroff** [badges/shields#5219]
:clipboard: **Description**

GitHub on the web got a new design (as a feature preview) this morning. It includes flatter, more minimal and rounded buttons, icons, etc. and gets rid of the old gradient buttons.

I would like to request updating all shields to reflect this new look, making things look more consistent and modern. Here is a screenshot of the new UI (notice the new clone button):

<img width="1280" alt="Screenshot on 2020-06-18 at 1 24 44 PM" src="https://user-images.githubusercontent.com/8844095/84999103-58a5c800-b16e-11ea-8200-4ee20847dcaf.png">

**Comment by chris48s** [comment]
Hello. We don't typically redesign our badge spec in response to GitHub (or other sites where our badges are frequently viewed e.g: NPM, PyPI, packagist, etc) changing their stylesheet. Shields badges in their current form have existed since before GitHub's current visual design and I expect they'll continue to do so after they get bored of this one too.

I'm going to leave this issue open for the moment in case anyone wants to comment on it, but in general the visual design of our badges is not tied to GitHub's UI.

**Comment by calebcartwright** [comment]
I agree with Chris :+1:  

It's not _entirely_ clear from me if your ask @urmilshroff was related to the Shields.io website, a request to update to one or more of the specific badge styles (flat, flat-square, plastic, etc.) that Shields offer, a request for a new style, a request to change the default style, some combination of the above, or something else entirely :smile:

**Comment by urmilshroff** [comment]
> I agree with Chris :+1:  
> 
> It's not _entirely_ clear to me if your ask @urmilshroff was related to the Shields.io website, a request to update to one or more of the specific badge styles (flat, flat-square, plastic, etc.) that Shields offer, a request for a new style, a request to change the default style, some combination of the above, or something else entirely :smile: 
> 

Sorry if I wasn't clear. I was requesting to update the little badges themselves (all of them) to match the new, flatter design language of GitHub's website, so that they look consistent with the rest of GitHub's UI when placed in a repository's README.

Infact, I didn't know that there _were_ multiple badge styles in the first place, so I guess that technically solves my problem! 😅

Thanks for letting me know, I'm closing this PR. Cheers!
