### ISSUE TITLE
Dependabot configuration management changes

### ISSUE THREAD

**Issue by calebcartwright** [badges/shields#5231]
Looks GitHub and Dependabot are tweaking how in-repo configuration files are managed. I don't suspect there's a need to make changes any time soon, and that whenever we do they would be fairly minimal. 

Nevertheless, opening this for awareness and for a tracking issue

https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
https://dependabot.com/docs/config-file/

> These docs are for "Dependabot Preview", the legacy non-native version of Dependabot. Use these docs if you have a .dependabot/config.yml checked into your repository. If you're new to Dependabot, learn more about how to set up the GitHub-native version.

**Comment by chris48s** [comment]
Hmm. "upgrading" to dependabot v2 means we have to give up automerged dependencies. See https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279 Maybe its not a huge thing to give up. Its may also not be a massive deal to roll our own solution with GH actions. For the moment we may as well just ride the v1 train as far as it goes :steam_locomotive: I don't think v2 adds anything we actually want/need

**Comment by calebcartwright** [comment]
> "upgrading" to dependabot v2 means we have to give up automerged dependencies. 

Is that something we're using currently? For some reason I can only recall the automerging happening for certain deps with GHA based job you configured.

> For the moment we may as well just ride the v1 train as far as it goes steam_locomotive I don't think v2 adds anything we actually want/need

Yeah I don't think there's a need to change any time soon, and would anticipate the current/v1 being around for quite some time

**Comment by chris48s** [comment]
> Is that something we're using currently? For some reason I can only recall the automerging happening for certain deps with GHA based job you configured.

I'd forgotten this is kind of opaque. We tell dependabot to automerge certain updates:

https://github.com/badges/shields/blob/c85512997ce505991f714fc400e9d96351030f58/.dependabot/config.yml#L7-L31

..but then dependabot can't actually auto-merge them because of the branch protection rules, so then the GH action picks up the PRs that dependabot wanted to auto merge and it approves them and adds the "squash when passing" label (so repo ranger will merge them). If we lose the ability to specify those automerged dependencies in the dependabot config, then we have to also implement the logic for  "is this a minor version bump to a chai plugin?" in the GH action rather than just "did dependabot want to automerge this PR?"

**Comment by calebcartwright** [comment]
> then we have to also implement the logic for "is this a minor version bump to a chai plugin?" in the GH action rather than just "did dependabot want to automerge this PR?"

Gotcha, thanks for the explanation!

**Comment by Andre601** [comment]
To bring this up here, rather than in the discussions (which I planned to do, but now decided to check the issues first).

I think having auto-merge active isn't really a good thing in the first place. It was mentioned in the [Linked Comment](https://github.com/dependabot/dependabot-core/issues/1823#issuecomment-641594279) that the rare case of having malicious code in dependencies could be undetected and having dependabot auto-merge it would just give a security-risk which should obviously be avoided.

From what I personally gathered will the old Dependabot(-preview) not stay active forever and ceise to exist in the near future (I recall a mention that in july auto-prs would be made for the switch to dependabot and that dependabot-preview will see end of its life soon. But not sure about that).

From my personal view is the loss of auto-merging a fairly minimal loss, whoch may be solved through GitHub Actions or a specific bot or whatever, but again: Overall a fairly minimal loss and a somewhat big risk for unwanted abuse through malicious dependencies.

**Comment by chris48s** [comment]
> I think having auto-merge active isn't really a good thing in the first place. It was mentioned in the Linked Comment that the rare case of having malicious code in dependencies could be undetected and having dependabot auto-merge it would just give a security-risk which should obviously be avoided.

If we lose the ability to auto-merge certain deps, our process isn't suddenly going to become "oh well I'll perform a forensic code audit on each tarball then". It just means a human is going to go "does the build pass? yes. merge" instead of a computer doing it for us. Fundamentally the reason we chose to enable auto-merge on that small subset of packages/update types is because that was what we were doing by hand for those types of updates, and a bot can do it for us. Also, dependabot-preview won't allow a PR to be auto-merged if it has a new maintainer (devils advocate: a check a human reviewer might miss).

> From what I personally gathered will the old Dependabot(-preview) not stay active forever

Sure, and we'll deal with that when we need to. Might as well keep this useful feature while we can though. If and when the update is forced, we can re-evaluate whether to just do more work by hand, try and make approve-bot smarter, switch to rennovate, etc.

**Comment by calebcartwright** [comment]
> If we lose the ability to auto-merge certain deps, our process isn't suddenly going to become "oh well I'll perform a forensic code audit on each tarball then"

Agreed. We do our due diligence up front when considering whether or not to add a dependency to our tree. Once we've determined a dep to be a helpful and trustworthy addition, we do not (and will not) do a forensic analysis on each patch update of those deps. Instead, we rely on services and bots for updates and security issues. TBH, the Dependabot Security and npm audit features, and their respective communities, are _far_ more effective at identifying security issues.

It simply wouldn't be viable for us (or any project frankly) to attempt to audit everything, and trying to review every line of code change in every dep you use would start to defeat the purpose of composable dependencies pretty quickly. For us, it's a termat of looking at the changelog and ensuring the new version doesn't break anything in our app, not a deep dive of the actual upstream code change (although when Dependabot tells us there's a new maintainer that publishes then I do poke around to ensure that person is indeed associated with the org/owner of the package).

Also want to note (and correct me if I'm wrong Chris), but our bots will only auto merge a handful of select development dependencies (deps which do not get introduced into any of our runtime environments)

**Comment by chris48s** [comment]
Yes all the packages on the auto-merge list are dev dependencies (testing, linting or mocking libraries).

You can definitely still say there is a non-zero level of risk here. For example, if someone hijacks eslint and publishes a release that contains malware a _contributor_ to shields may still potentially going to pull down that malware and run it on your local machine as a result of us merging that PR (even if we don't run that code in our production environment), but its a non-zero level of risk that will still exist if one of us presses the merge button rather than a bot doing it, given the level of scrutiny we can realistically give it. Its also a non-zero level of risk that we (as maintainers) are exposed to more than anyone, and hence we're incentivised to try and make good decisions for ourselves and our users.

**Comment by calebcartwright** [comment]
> You can definitely still say there is a non-zero level of risk here.

There's a non-zero level of risk with pulling in any dependency or any update to any dependency, unless we go to the extreme of using shrinkwrap and reviewing every line of change in the respective dep tree before pulling in any update of any dependency (and frankly even then as the human analyzing is also prone to errors/missing something)

I'd opened this to ensure we were tracking how GitHub was planning to change Dependabot configuration files. If there's a desire to have an in depth discussion about how we review/vet dependency updates, and/or bot-merging, then I really feel like that should happen in separate threads, especially because those are independently actionable from this issue.

**Comment by chris48s** [comment]
> There's a non-zero level of risk with pulling in any dependency

Indeed. I think we fully agree on this :)

**Comment by chris48s** [comment]
Not tried it yet, but this might be able to help us
https://github.com/apps/depend-a-lot-bot

**Comment by chris48s** [comment]
This has become suddenly urgent due to https://github.com/dependabot/dependabot-core/issues/3523
I think in the immediate term, we probably just switch to dependabot-native to get things working again and drop auto-merges
Slightly longer term, it might be worth considering a switch to rennovate as one of the options https://docs.renovatebot.com/automerge-configuration/

**Comment by chris48s** [comment]
Also have a look at https://github.com/chdsbd/kodiak

**Comment by chris48s** [comment]
Dependabot Preview will be shut down on August 3rd, 2021

**Comment by calebcartwright** [comment]
> Slightly longer term, it might be worth considering a switch to rennovate as one of the options https://docs.renovatebot.com/automerge-configuration/

Forgot to respond to this but wanted to note i'd be disinclined to go in this direction. I've used renovate in some other projects and generally find it to be inferior compared to dependabot, both in terms of configuration/versioning management and particularly with the PR experience (release notes, rebasing/recreating, etc.)

**Comment by Andre601** [comment]
> Forgot to respond to this but wanted to note i'd be disinclined to go in this direction. I've used renovate in some other projects and generally find it to be inferior compared to dependabot, both in terms of configuration/versioning management and particularly with the PR experience (release notes, rebasing/recreating, etc.)

I want to add to this by saying that the maintainer had a somewhat rude attitude when I asked beginner questions and gave my feedback about the bot.

Source: https://github.com/renovatebot/renovate/discussions/10610

**Comment by calebcartwright** [comment]
> I want to add to this by saying that the maintainer had a somewhat rude attitude when I asked beginner questions and gave my feedback about the bot.

Thanks for sharing @Andre601

For what it's worth, my impression has always been that the Renovate community is welcoming and helpful based on my own experiences and what I've heard from others.

It can often be incredibly difficult to interpret tone and intent with written text, and it's very easy to _misinterpret_. This challenge is also exacerbated by language and cultural differences as well. Sometimes someone will misinterpret a comment and have an emotional response in kind in the moment, and other times folks could just be having a bad day (we're all human after all! :smile:)

I understand why you wanted to share that thread, but I just wanted to note that I suspect that type of experience is more the exception than the norm.

**Comment by chris48s** [comment]
This got done in https://github.com/badges/shields/pull/6816
