### ISSUE TITLE
API badge (Scratch)

### ISSUE THREAD

**Issue by Ani-Xan** [badges/shields#5280]
:clipboard: **Description**
My idea is that there should be a badge that collects info from an API. Is there already a way to do this?

:link: **Data**
Here is the API I want to work with: https://scratchdb.lefty.one/v2/user/info/Ani-Xan and the info I want to extract is the "followers"

:microphone: **Motivation**
I want to use this on some forums and use this on multiple websites.

**Comment by calebcartwright** [comment]
> Is there already a way to do this?

Yup! Depending on your needs, you could leverage our [Endpoint badge](https://shields.io/endpoint) or our Dynamic Json badge (scroll down to the Dynamic section on the main https://shields.io/ page)

**Comment by Ani-Xan** [comment]
> > Is there already a way to do this?
>
> Dynamic Json badge (scroll down to the Dynamic section on the main https://shields.io/ page)

I have about 0 coding experience and only have used API's on no-code platforms. How exactly would I connect the API?

**Comment by calebcartwright** [comment]
> I have about 0 coding experience and only have used API's on no-code platforms. How exactly would I connect the API?

You don't have to do any coding. If you scroll down to the Dynamic badge builder section on the homepage as I suggested in my previous response, you can use the page to let it build the badge url for you.

Specifically, I think you'd end up with a badge url something like this
https://img.shields.io/badge/dynamic/json?color=blue&label=followers&query=%24.statistics.followers&url=https%3A%2F%2Fscratchdb.lefty.one%2Fv2%2Fuser%2Finfo%2FAni-Xan
![](https://img.shields.io/badge/dynamic/json?color=blue&label=followers&query=%24.statistics.followers&url=https%3A%2F%2Fscratchdb.lefty.one%2Fv2%2Fuser%2Finfo%2FAni-Xan)

The badge route you'd use is https://img.shields.io/badge/dynamic/json, and then you include query parameters to specify other inputs.

The badge builder section there helps you construct the badge url, instead of you having to do it manually. The **color** and **label** query parameters are pretty self explanatory, and you can plug in whatever you want there. The **url** param is where you specify the endpoint, which in your case is https://scratchdb.lefty.one/v2/user/info/Ani-Xan (just make sure to uri encode it, which becomes `https%3A%2F%2Fscratchdb.lefty.one%2Fv2%2Fuser%2Finfo%2FAni-Xan`) and then lastly you use the **query** param to specify the jsonpath query that grabs the desired data point. In your case I believe that's the values of `followers` key under the `statistics` key, so your jsonpath is accordingly `$.statistics.followers` (again uri encoded as `%24.statistics.followers`)

![image](https://user-images.githubusercontent.com/13042488/86493238-5a5ab880-bd36-11ea-92cd-81914df51904.png)

**Comment by Ani-Xan** [comment]
Wow, you're smart. Thank you **SO** much for helping me.

**Comment by calebcartwright** [comment]
Cheers! Closing this out now as the original inquiry appears to have been answered
