### ISSUE TITLE
Cirrus build badge shows "invalid response data"

### ISSUE THREAD

**Issue by billziss-gh** [badges/shields#5281]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

As per title the Cirrus build badge shows "invalid response data" for a FreeBSD build.

- Related project: https://github.com/billziss-gh/cgofuse
- Related Cirrus YAML: https://github.com/billziss-gh/cgofuse/blob/master/.cirrus.yml

:link: **Link to the badge**

![Cirrus CI](https://img.shields.io/cirrus/github/billziss-gh/cgofuse/master?script=build&task=freebsd)
https://img.shields.io/cirrus/github/billziss-gh/cgofuse/master?script=build&task=freebsd

----

**EDIT**: Please note that the "question" label was automatically added to this issue. I did not explicitly add it.

**Comment by calebcartwright** [comment]
> EDIT: Please note that the "question" label was automatically added to this issue. I did not explicitly add it.

Yup, that's by design as part of the issue template.

The corresponding API request that we issue for the referenced badge (https://img.shields.io/cirrus/github/billziss-gh/cgofuse/master?script=build&task=freebsd) is:

https://api.cirrus-ci.com/github/billziss-gh/cgofuse.json?branch=master&script=build&task=freebsd

which has a response body of:

```json
{"subject":"build","status":"aborted","color":"yellow"}
```

The problem is that the `status` value of `aborted` is not expected/allowed with our current schema validation

https://github.com/badges/shields/blob/master/services/build-status.js

https://github.com/badges/shields/blob/828d4cc40a22a1316badd9c31b2cff1795b36fe5/services/cirrus/cirrus.service.js#L7-L12

This should be relatively easy to fix so labeling accordingly. For anyone interested, one approach to resolve this would be to add another alternative to the schema in the cirrus service class, and a different approach would be to add `aborted` to the shared build status options defined in `build-status.js`

**Comment by billziss-gh** [comment]
Thank you @chris48s.
