### ISSUE TITLE
Docker security badges

### ISSUE THREAD

**Issue by dinuta** [badges/shields#5292]
:clipboard: **Description**

There isn't a badge for docker security scans (vulnerabilities). Maybe you can figure it out to integrate a service like: https://github.com/aquasecurity/trivy to have such.

- Which service is this badge for e.g: **GitHub**
- What sort of information should this badge show?
Docker image version and vulnerabilities. CLI output example: 
```
dinutac/jinja2docker:2.1.2 (alpine 3.9.4)
=========================================
Total: 16 (UNKNOWN: 0, LOW: 1, MEDIUM: 11, HIGH: 4, CRITICAL: 0)
```
https://img.shields.io/badge/v2.1.5-unknown%3A%200%20%7C%20low%3A%2011%20%7C%20critical%3A%202-red

:link: **Data**

:microphone: **Motivation**

**Comment by chris48s** [comment]
This would be a helpful badge, but pulling a docker container, running `trivy` and reporting the result on an ad-hoc basis would be impossible for us to implement for performance reasons. In order to be able to report this we would need to be able to request pre-computed data from somewhere in a performant way.

**Comment by dinuta** [comment]
Yes, we'll need a microservice somewhere with some key requirements:
- fetch trivy vulnerabilities map in background and store it in DB. Return imediately a response with NA if no Information is found.
- fetch trivy vulnerabilities map to a predefined scheduler. E.g. 1 Day for each image requested
- delete image, otherwise tremendous HDD space will be required through a background scheduler or after scan
- here Maybe pick golang as backend for concurrency... Multiple services May be needed for load Balancing. Dunno how manny requests hits daily shields. Io. 
- other requirements 


IT seems complicate, indeed. 

Maybe what can be done îs to integrate this thing directly with travis or circule ci build, store that json as artifact and read it with shields io

**Comment by calebcartwright** [comment]
Running cli tools/scans/services/etc. isn't part of Shields' remit, and as such _running_ trivy feels way outside our scope and something I'd oppose. 

While I agree that this would be useful information to convey in a badge, I feel that the data would need to be retrievable over HTTP in order for Shields.io to be able to provide this badge. 

> Maybe what can be done is to integrate this thing directly with travis or circle ci build, store that json as artifact and read it with shields io

Running trivy as part of your CI process seems like it would be the primary use case https://github.com/aquasecurity/trivy#continuous-integration-ci, and if the [json results](https://github.com/aquasecurity/trivy#save-the-results-as-json) were emitted and stored somewhere then you'd be able to use our Dynamic Json badge (or [Endpoint badge](https://shields.io/endpoint) depending on the complexity) to get the desired badge 

FWIW - We do provide badges for snyk (because the data is available over http) and I believe they have some support for [docker related scanning as well](https://snyk.io/product/container-vulnerability-management/)

**Comment by dinuta** [comment]
ok @calebcartwright, @chris48s. I'll try to figure it out. The solution with travis or circle might not be best because the vulnerability map evolves in time. This means i have to build my projects once a day or so to not serve lies to the users... 

For example a feature or correction I am doing once per 2 weeks or one month so in this time everything might change.

And snyk does not provide badges for dockerhub, only github even though they scan docker images in dockerhub, and I can see the results on their snyk.io. 

Anyways this was a good technical talk, and I will still try to figure it out somehow.

**Comment by dinuta** [comment]
Good news guys,

Snyk gave me email where they announced it will support soon docker hub badges.

Catalin
