### ISSUE TITLE
What is the right way to construct VersionEye shields URL for a Java project?

### ISSUE THREAD

**Issue by raindev** [badges/shields#531]
Example from the homepage for Ruby on Rails doesn't fit into user/repository pattern. I've tried the simplest URL (https://img.shields.io/versioneye/d/raindev/benjamin.svg) and of cause it doesn't work. Also, I've found some suggestions about VersionEye URLs for Java in #364, but none of them are working as of today.

**Comment by espadrine** [comment]
Can you get me a link to the VersionEye badge?

**Comment by raindev** [comment]
Sure, here it is: https://www.versioneye.com/user/projects/55f098901e87ad001d00054b/badge.svg

**Comment by adam-paterson** [comment]
It seems like the badges are only working for projects that appear in the search. I've been having some issues generating a badge for my php projects.

I have 4 projects and only two of them are appearing in the search.

**Working**
This project has a `/php/vendor/package` name because it appears in the search.

[![Dependency Status](https://img.shields.io/versioneye/d/php/adam-paterson:oauth2-rdio/1.0.1.svg?style=flat-square)](https://www.versioneye.com/php/adam-paterson:oauth2-rdio/1.0.1)
https://www.versioneye.com/php/adam-paterson:oauth2-rdio/1.0.1 
`[![Dependency Status](https://img.shields.io/versioneye/d/php/adam-paterson:oauth2-rdio/1.0.1.svg?style=flat-square)](https://www.versioneye.com/php/adam-paterson:oauth2-rdio/1.0.1)`

**Broken**
This project has a `/user/id` name and doesn't appear in the search yet. You can create the url assuming the same convention as the working one.

[![Dependency Status](https://img.shields.io/versioneye/d/php/adam-paterson:oauth2-slack/1.1.2.svg?style=flat-square)](https://www.versioneye.com/php/adam-paterson:oauth2-slack/1.1.2)
https://www.versioneye.com/php/adam-paterson:oauth2-slack/1.1.2 
`[![Dependency Status](https://img.shields.io/versioneye/d/php/adam-paterson:oauth2-slack/1.1.2.svg?style=flat-square)](https://www.versioneye.com/php/adam-paterson:oauth2-slack/1.1.2)`

Perhaps @reiz could shed some light on the situation? When are public projects index by the search?

**Comment by reiz** [comment]
Sure. Only packages that are crawled from packages managers such as Packagist, RubyGems, Maven Central and so on appear in the search. Projects which are created by users are in the name space `/user/projects/:PROJECT_ID` and don't appear in the search results.

**Comment by raindev** [comment]
Thank you everyone for all the insights! I'm going to upload my project to Maven Central and hopefully will close the issue shortly after that.

**Comment by reiz** [comment]
@raindev That's a good idea :+1:

**Comment by raindev** [comment]
I have released my project to Maven Central and it now appears in Versioneye search. Here is the package itself: https://www.versioneye.com/java/io.github.raindev:benjamin/1.0.0, URL to Versioneye badge is https://www.versioneye.com/java/io.github.raindev:benjamin/1.0.0/badge.svg?style=flat

I have tried to construct a shields.io URL as suggested by @adam-paterson (https://img.shields.io/versioneye/d/java/io.github.raindev:benjamin/1.0.0.svg?style=flat-square) or use use Versioneye suffix with shields.io prefix (https://img.shields.io/versioneye/d/java/io.github.raindev:benjamin/1.0.0/badge.svg?style=flat). But none of the them works. Am I doing something wrong?

**Comment by reiz** [comment]
@raindev @adam-paterson I just deployed an update for the badges. Now `?style=flat` is not ignored any more. Here is your flat badge: https://www.versioneye.com/java/io.github.raindev:benjamin/1.0.0/badge.svg?style=flat.

**Comment by raindev** [comment]
@reiz great, thank you! Any hints how to construct shields.io URL from it?

**Comment by reiz** [comment]
@raindev I have to double check the shields.io integration. It worked in the past, but it seems to be broken.

**Comment by reiz** [comment]
@raindev It works for this URS: 

https://img.shields.io/versioneye/d/ruby/rails.svg
https://img.shields.io/versioneye/d/java/junit:junit.svg

But it doesn't for this one:

https://img.shields.io/versioneye/d/java/io.github.raindev:benjamin.svg

I guess shields.io is confused by the points in the name of the java package. That is truly an exception. Java packages have very long names composed by GroupId and ArtifactId. Maybe @espadrine can give some advice?

**Comment by raindev** [comment]
In practice groupIds like "junit" are quiet rare. New groups with ID that do not represent a possibly-valid domain are no longer accepted to Maven Central, as far as I know.

**Comment by espadrine** [comment]
@reiz, you're right, there was a rather silly bug in the code. It should feel much better now.

**Comment by raindev** [comment]
Many thanks, finally my badge works :)
