### ISSUE TITLE
NPM tags containing slashes are unsupported

### ISSUE THREAD

**Issue by jsamr** [badges/shields#5364]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Given the following URL template

```
/npm/v/:packageName/:tag
```

The `:tag` variable cannot contain `/` characters, while this is a perfectly valid npm tag (see screenshot bellow).

![2020-07-25-100251_810x385_scrot](https://user-images.githubusercontent.com/3646758/88457578-0edf8a00-ce5e-11ea-8894-9c948876cca8.png)

:link: **https://img.shields.io/npm/v/react-native-render-html/release%2f4.2** 
:link: **https://img.shields.io/npm/v/react-native-render-html/release/4.2**

:bulb: **Possible Solution**

Parse the tag url-encoded, and url-encode when accessing npm API.

**Comment by paulmelnikow** [comment]
Hi! Thanks for raising this.

We've run into this with branch names containing slashes too. I think it can be fixed by changing the URL pattern:

https://github.com/badges/shields/blob/72c749c6b6dd1fea3bfafdfa464b734c2a274a4d/services/npm/npm-base.js#L50

to:

`':scope(@[^/]+)?/:packageName/:tag*'`

Any chance you'd like to give it a shot and make a PR? We've got a great testing framework and you can add a test with the example you've provided.

URL encoding won't solve the problem because the router acts on the decoded path. Moving it to a query parameter is possible, but fixing the route seems like a better way to go, and hopefully it will work.

**Comment by jsamr** [comment]
@paulmelnikow Sure I'll do that.

**Comment by paulmelnikow** [comment]
Sweet! Thank you! Feel free to post here (or in Discord #contributing) if you have any questions!
