### ISSUE TITLE
pypistats.org not up-to-date/inaccessible

### ISSUE THREAD

**Issue by udondan** [badges/shields#5371]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

For my PyPI package [cdk-iam-floyd](https://pypi.org/project/cdk-iam-floyd/), shields.io cannot find the package for the download badge. Though it can perfectly find the package for the version badge.

![Version](https://img.shields.io/pypi/v/cdk-iam-floyd) ![Downloads](https://img.shields.io/pypi/dm/cdk-iam-floyd)

The package exists since July 21, since 8 days, so it should not be a matter of "too new".

:link: https://img.shields.io/pypi/dm/cdk-iam-floyd

**Comment by chris48s** [comment]
Hi. While most of our pypi info comes from pypi itself, our download stats come from pypistats.org
We're not showing downloads for your package because pypistats doesn't have them: https://pypistats.org/api/packages/cdk-iam-floyd/recent Just looking over at their issue tracker, it looks like there is an issue already reporting saying they've not been pulling in new data for about 10 days https://github.com/crflynn/pypistats.org/issues/29 so thanks for flagging this.

**Comment by udondan** [comment]
Thanks @chris48s, for your time explaining the issue!

**Comment by chris48s** [comment]
As noted in https://github.com/badges/shields/issues/5397 https://pypistats.org/ is now down completely.
Will continue to monitor the upstream issue.

**Comment by JrooTJunior** [comment]
I think pepy.tech can be used instead of pypistats.org

**Comment by pbelskiy** [comment]
Can't you use another source of downloads?

**Comment by chris48s** [comment]
This should now be resolved https://github.com/crflynn/pypistats.org/issues/29

**Comment by mwojtyczka** [comment]
<img width="855" height="219" alt="Image" src="https://github.com/user-attachments/assets/48756759-80a5-46ec-96b2-4907b2b422c0" />

https://pypistats.org/ seems be down

**Comment by jNullj** [comment]
@mwojtyczka 
Please don't reply on old issues.
There is a new issue for the current issue at #11257 
Locking this now as this old issue was clearly resolved.
