### ISSUE TITLE
bundlephobia inaccessible

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [badges/shields#5412]
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
use size: npm bundle size (scoped version)

:link: **Link to the badge**

npm repo: <https://www.npmjs.com/package/@jsany/cli-kit>

![npm bundle size (scoped version)](https://img.shields.io/bundlephobia/minzip/@jsany/cli-kit/1.1.1?style=flat-square)
![npm bundle size (scoped version)](https://img.shields.io/bundlephobia/minzip/@jsany/cli-kit/latest?style=flat-square)

<https://img.shields.io/bundlephobia/minzip/@jsany/cli-kit/1.1.1?style=flat-square>
<https://img.shields.io/bundlephobia/minzip/@jsany/cli-kit/latest?style=flat-square>

:bulb: **Possible Solution**

**Comment by chris48s** [comment]
We're throwing inaccessible because bundlephobia is throwing a 500 error on this specific package:
https://bundlephobia.com/api/size?package=%40jsany%2Fcli-kit%401.1.1

Other packages seem to be returning a valid response e.g:
https://bundlephobia.com/api/size?package=%40cycle%2Fcore%407.0.0

so I think its an issue related to this particular package. If its not obvious what is wrong from the error, try raising an issue on the bundlephobia repo: https://github.com/pastelsky/bundlephobia

**Comment by Mr-jiangzhiguo** [comment]
Extremely grateful
