### ISSUE TITLE
Packagist badge not working

### ISSUE THREAD

**Issue by elazar** [badges/shields#543]
Image: https://img.shields.io/packagist/v/sparkphp/auth.svg

<img src="https://img.shields.io/packagist/v/sparkphp/auth.svg" />

Packagist profile: https://packagist.org/packages/sparkphp/auth

**Comment by espadrine** [comment]
Based on `curl 'https://packagist.org/packages/sparkphp/auth.json'`, you don't have a stable version (the dev-master one is considered prerelease). What ought to work is `https://img.shields.io/packagist/vpre/sparkphp/auth.svg`.

However, it turns out that we discard dev-* versions since 0645952a because of https://github.com/badges/shields/pull/366#issuecomment-75206920.

Do you have any idea to make aliases work?

**Comment by elazar** [comment]
I do not. @Seldaek might.

**Comment by Seldaek** [comment]
I have no idea what you are asking here.. if you'd like help please give some context :)

**Comment by paulmelnikow** [comment]
I believe this badge is working as intended. If not, please feel free to comment or reopen.
