### ISSUE TITLE
"invalid response data" on WordPress plugin badge

### ISSUE THREAD

**Issue by EdieLemoine** [badges/shields#5499]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

I'm trying to add a badge with the [WooCommerce plugin](https://wordpress.org/plugins/woocommerce-myparcel) version to our repository , but the shield doesn't work. I've tried several other plugins, `bbpress` (from the example), `woocommerce` and a random plugin I plucked from the WordPress website. All of them work, but our plugin's doesn't. Could there be something wrong in the plugin's settings? Or am I missing something?

:link: **Link to the badge**

https://img.shields.io/wordpress/plugin/v/woocommerce-myparcel

**Comment by calebcartwright** [comment]
Thanks for the report @EdieLemoine this is due to a mismatch between the schema we're currently using to validate the response from the Wordpress API (specifically the `requires` key can be a string _or_ a boolean, but [our schema only expects a string](https://github.com/badges/shields/blob/master/services/wordpress/wordpress-base.js#L14)).

This should be fixed in https://github.com/badges/shields/pull/5493, for example from the review app for that PR:
https://shields-staging-pr-5493.herokuapp.com/wordpress/plugin/v/woocommerce-myparcel
![](https://shields-staging-pr-5493.herokuapp.com/wordpress/plugin/v/woocommerce-myparcel)

**Comment by EdieLemoine** [comment]
Great, thank you!
