### ISSUE TITLE
font-awesome

### ISSUE THREAD

**Issue by diomed** [badges/shields#552]
what do you think of adding Font Awesome icons to shields?
at least for custom badges (Your Badge)
& we could select, for example, font awesome icon on the left side and write text on the right one.

https://fortawesome.github.io/Font-Awesome/icons/

**Comment by espadrine** [comment]
That is one fancy idea!

From their [CSS](https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css), it looks like I should be able to get an SVG font (which I could hope to transform to a set of SVG files), but unfortunately, this URL is empty: https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/fonts/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular.

**Comment by diomed** [comment]
so, I've asked about why that url is empty, to which I got an answer that everything is actually ok, but github actually sends a text/plain content-header, thats why it displays the source as clear text.

and if you look at the source code of that blank page, funny thing - it's all there.
so, what about that script, is that complicated to make, and do you plan to make it, maybe?

**Comment by espadrine** [comment]
Good to know!

That script would download and read the full SVG font, rip out its insides, and for each glyph (which is basically a `<path>` anyway), it would store it in a separate SVG file, each named after the glyph. We'd put that script on a separate git project, and put all the SVG files in `logo/`, with all those files starting with `fa-`.

I'm not sure how Font-Awesome contributors work. It seems daunting to edit the SVG font by hand and convert it to ttf & cie. The main author must have his own workflow, since the contribution file [states](https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md):

> At the moment we are not accepting pull requests containing icons

**Comment by Thraka** [comment]
Would be nice to have. I wanted a custom reddit badge and I think fontawesome has a reddit icon.

**Comment by espadrine** [comment]
@Thraka You can put logos in your badge as detailed in http://shields.io/#styles, through `?logo=data:image/png;base64,…`.

**Comment by tooomm** [comment]
By the way:
Font Awesome includes icons for github, twitter, telegram, bitbucket, facebook, gitlab, gratipay, slack etc. too!

**Comment by mabbas64** [comment]
Would be nice if support for Font Awesome 5 "Free" version is added :p So many nice icons to use from it in my forum signature badges. SimpleIcons just doesn't cut it.

**Comment by paulmelnikow** [comment]
Based on recent discussions, and quite a lot of time passing with some but not overwhelming support for this idea, I think we probably are not going to add this in core.

However, it's always possible to build a badge using an icon with your own SVG.

If someone wanted to build a web app that let you generate svg from a Font Awesome icon and base64-encode it, we'd be happy to link to it!
