### ISSUE TITLE
badge for Visual Studio Marketplace is not working

### ISSUE THREAD

**Issue by BigEgg** [badges/shields#5597]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

Both download and installation badge for visual studio marketplace are not working, here is the screen shot
![image](https://user-images.githubusercontent.com/1243699/94218736-ed207480-fe99-11ea-8b35-7e56c566f00f.png)

This is happened for Visual Studio Extension: [BigEgg.PowerMode](https://marketplace.visualstudio.com/items?itemName=BigEgg.PowerMode).

:link: 

Installs: https://img.shields.io/visual-studio-marketplace/i/BigEgg.PowerMode
Downloads: https://img.shields.io/visual-studio-marketplace/d/BigEgg.PowerMode

:bulb: **Possible Solution**

Don't know

**Comment by chris48s** [comment]
The detailed error here is

```
"results[0].extensions[0].versions[0].version" with value "0.7" fails to match the required pattern: /^(\d+\.\d+\.\d+)(\.\d+)?$/
```

looks like our [regex](https://github.com/badges/shields/blob/1b91b03b2b4265a6f7ae535e33c93269c46badbf/services/visual-studio-marketplace/visual-studio-marketplace-base.js#L25) is too strict, but interestingly the VSCode manifest spec says version should be a semver https://code.visualstudio.com/api/references/extension-manifest (which 0.7 isn't). Surprised this is the first time we've seen this if the marketplace doesn't enforce the spec though :thinking:

**Comment by BigEgg** [comment]
Thanks for the explanation. Let me update mine version.

**Comment by BigEgg** [comment]
Seem like the regex keep this on purpose. Here is the reference: [#1704 ](https://github.com/badges/shields/issues/1704)

**Comment by calebcartwright** [comment]
> Seem like the regex keep this on purpose. Here is the reference: [#1704 ](https://github.com/badges/shields/issues/1704)

I thought this sounded familiar :laughing: 

> BTW, this extension is for Visual Studio only not for Visual Studio Code. Maybe the schema is different?

It's the same for VS and VSC, while AzDO is different (which is reflected in our badge routes, schemas, and logic handlers)

**Comment by chris48s** [comment]
Thanks for the extra context.
Are we actually gaining anything from this input validation? AFAIK we're not actually relying on the version being in a certain format (for example, we're not splitting the version out into major/minor/patch and the doing something with the patch component). Assuming all we are doing is shoving the value of `versions[0]` on a badge, we we're not losing anything if we just make the input validation `Joi.string()`, right?
Sure its weird that MS say the version string should be in a certain format and then don't apply that constraint, but if the user can publish a plugin with the version number 0.7 then the expected behaviour is that we're going to serve a version badge that says 0.7 on it..

**Comment by calebcartwright** [comment]
> Are we actually gaining anything from this input validation? 

That question starts heading down a more philosophical path, and also circles back to some previous conversations around what exactly the purpose of the schema validation is and how loose/strict they should be.

It's come up enough times that I think it may warrant revisiting the topic in an offline conversation with the core team, and my preference would be that we codify the decision and enforce it consistently.

There's an easy fix for the user here, and precedent with semi-recent action on our part in a similar non-compliant version scenario, so I don't see any blocking issues with leaving the schema as is.

**Comment by chris48s** [comment]
> what exactly the purpose of the schema validation is and how loose/strict they should be

Good question. Lets start off by reviewing the history, just so we all understand how we got here.. Apologies if I'm just re-stating things we all already know, but lets start from a common baseline. Rewind a few years, and we used to frequently render badges like

![](https://img.shields.io/badge/version-null-blue)
![](https://img.shields.io/badge/coverage-NaN%25-red)
![](https://img.shields.io/badge/build-undefined-red)

due to poor error handling. It was a crap experience for users. Introducing service tests led us to identify a lot of this and we added a whole pile of manual error handling to guard against it i.e: doing the equivalent of

```js
if (obj.version === undefined) {
  throw new InvalidResponse()
}
render(obj.version)
```

instead of

```js
render(obj.version)
```

(except at that time we didn't have standard exceptions or a `render()` function, but.. you know what I mean). This was better for users, but we were duplicating the same checks over and over, throwing the same error responses in hundreds of places, and we still missed stuff sometimes (we couldn't log error cases to sentry, for example - we just rendered broken badges).

So.. approach number 3: Joi schemas. Every API response we accept, we validate it against a schema to make sure its the right shape. If we're going to use a value, we check it exists. If we need to multiply it by something, we check its a number. If we're going to call `.split()` on it, we make sure its a string. This allows us to make the validation declarative, centralise/DRY-up the rendering of error responses and log uncaught errors to sentry (which allows us to patch up the things we've missed over time). It works pretty well.

IMO validation on the input data only really needs to be strict enough that we don't have to manually implement guard conditions.

e.g: `version: Joi.string().required()` is there so we can write

```js
render(obj.version)
```

instead of

```js
if (obj.version === undefined) {
  throw new InvalidResponse()
}
render(obj.version)
```

to not render ![](https://img.shields.io/badge/version-undefined-blue) and defer throwing the error to `Joi`.

This is slightly different from the validation we do under test which is sometimes maybe necessarily a bit stricter to assert our own code is correct (on top of assertions about the input data).

What we _shouldn't_ be using input validation for is to say to users "your version number isn't good enough".


> my preference would be that we codify the decision and enforce it consistently

I think trying apply one rule across all services is a losing move for us. Registries are different. APIs are different. Sometimes people build weird APIs. Sometimes (get this, right) people build APIs that do one thing and write docs that say something slightly different 😮 Dealing with the messy reality of real-world APIs is part of the reason why we need input validation.

That said, there are probably some useful _principles_ we can agree on and apply in an appropriately context-sensitive way. Some I would suggest are:

1. Our definition of "valid" should be no stricter than the upstream service's definition of "valid". Perhaps to phrase this in RFC-like language: "our validation MAY be less strict than the upstream service but MUST NOT be more strict than the upstream service". Exactly where in that grey are we fall is going to be determined by other badge/service-specific criteria/requirements.
2. If theory (docs) and practice (real-world API responses) conflict, real-world outputs take precedence over documented behaviour. e.g: if the docs say `version` is a semver but we learn that there are real-world packages where the version number is `0.3b` or `1.2.1.27` then we should accept those values in preference to enforcing the documented API behaviour.
3. Shields is descriptive ("the registry says your package version is 0.7, therefore your package version is 0.7") rather than prescriptive ("you're doing versioning wrong - lol"). We reflect the established norms of the communities we serve. If it's good enough for the upstream, it's good enough for us.

Maybe there's some overlap between 1 and 3 there. Either way, happy to engage in wider discussion about working out what the full list should be (I suspect that is something that has to be seeded and then evolve over time though). I'll copy & paste some of this stuff over to a discussion thread where we can talk about it more.

In this particular situation, my strong preference is we loosen the validation. The user isn't doing versioning wrong - we're doing badges wrong. Sure we can say "Ha. I found a case where Microsoft's docs say one thing and their API response says something different - therefore I win", but if the prize is we have to respond to this same support request again in future, we're not exactly #WinningAtLife are we? :D

**Comment by chris48s** [comment]
Have opened https://github.com/badges/shields/discussions/5619 to discuss.

**Comment by calebcartwright** [comment]
Thanks for opening a separate issue (I was going to request the same) and the detailed write up. Haven't had a chance to digest it yet but am looking forward to the discussion. There's been different and yes some times conflicting prescriptions on this topic, and it was one of the more confusing, and occasionally frustrating, things for me when I first started contributing to Shields.

Ultimately I don't care all that much about what the decided outcome is, but really want to avoid contributors receiving different messages depending on which maintainer is reviewing (and what may be on that maintainer's mind that day), or which docs/existing badges are used as a reference.

**Comment by BigEgg** [comment]
Just an FYI, I had updated the version for my extension.
