### ISSUE TITLE
Not working on private repos on Organizations.

### ISSUE THREAD

**Issue by Ayfri** [badges/shields#5676]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
Hi!
I tried to add a badge with this website for a private repo on an organization that I have but on the website, it always says that it cannot found the repo (I didn't try on GitHub).

:link: https://img.shields.io/github/repo-size/Galileo-Bot/galileo
I think it is useless to add the badge as you can't see the repo but I don't know.

:bulb: I don't know :/

**Comment by calebcartwright** [comment]
hi @Ayfri :wave: The Shields.io service can only provide badges for publicly accessible targets (repos, projects, builds, etc.), as the Shields.io server doesn't have access to your private GitHub data either. 

In order to get badges for your private content, you'd need to deploy your own self-hosted Shields server that's configured with your own GitHub Authentication configuration. More details on how to do that can be found [here](https://github.com/badges/shields/blob/master/doc/self-hosting.md)
