### ISSUE TITLE
Badge request: Gitbook build state

### ISSUE THREAD

**Issue by xtaran** [badges/shields#569]
I'm not sure if their API (https://developer.gitbook.com/) supports that already. But at least if you're logged in you see a history of successful and failed builds for your books, e.g. mine at https://www.gitbook.com/book/dpmb/dpmb/activity

**Comment by espadrine** [comment]
Thanks for the suggestion!

The closest API I can see is this: http://developer.gitbook.com/books/index.html.

I can't access https://www.gitbook.com/book/dpmb/dpmb/activity unfortunately.

**Comment by jbytw** [comment]
Gitbook badge seems to be available http://bl.ocks.org/roachhd/bf4b22008e7b8b69c1c1#GitBooks.md
Now we only need a touch of shield!

**Comment by xtaran** [comment]
Thanks @jbytw for that hint!

**Comment by espadrine** [comment]
You may be able to use the `fetchFromSvg(request, url, cb)` function defined in server.js in that case.

**Comment by ochikov** [comment]
When the gitbook badge will be available? Any plans ?

**Comment by paulmelnikow** [comment]
Just wanted to put out there that Shields is a community project, and that means you can help make this happen! 👐 We have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) and welcome anyone who would like to dig into this! Our maintainer team is happy to provide guidance on the API design and provide assistance with the implementation. We've had many first-time contributors who don't use JavaScript and have tried to make the first-time contributing experience as straightforward as possible.

**Comment by PaulaBarszcz** [comment]
https://developer.gitbook.com/api/authentication

<img width="853" alt="Zrzut ekranu 2022-11-13 o 14 29 33" src="https://user-images.githubusercontent.com/31891675/201524258-dafe9d2f-3032-4bef-acc3-8e164ca8ef66.png">

Since the GitBook API is currently in beta, should we wait for its stable release before working on a GitBook badge?

**Comment by chris48s** [comment]
If the API is still beta 7 years after this issue was raised, I think we could be waiting some time :smile: 

I think more of a concern is the auth requirements and rate limiting. Based on https://developer.gitbook.com/api/authentication it looks like the GitBook API does not expose any public info - I think you need to supply a token to read anything.

There are basically 2 patterns for how we can interact with services that require auth:

1. We store one token at service level which allows us to read data for everyone's projects, or
2. If every user needs to provide their own token, that has to be a token which can be passed to us as a query param in the badge URL. This means it must be possible to generate a token that can be exposed in a public github README public with no negative consequences

It looks like with GitBook every user would need a token but the token would not be suitable to expose.

Also based on https://developer.gitbook.com/api/rate-limiting it looks like GitBook applies some fairly restrictive rate limits that would be hard for us to stay under.

I don't have any examples of a working project to experiment with any of this, but I think if the above is true, this one isn't viable and we close this issue.

**Comment by PaulaBarszcz** [comment]
You’re right @chris48s , every user would need to use their private token for API requests about their GitBook. 
No GitBook API is exposed publicly - I agree that we should close this issue.
