### ISSUE TITLE
[endpoint] Enable logoColor with logoSvg

### ISSUE THREAD

**Issue by mudlabs** [badges/shields#5728]
:clipboard: **Description**

When creating a badge using the `json` _endpoint_ method we should be able to specify the `logoColor` as a property in the `json` object, and override in the query string.

Just take the provided colour value and set it as the `fill` value on the provided `svg` string.

**Comment by calebcartwright** [comment]
`logoColor` should already be supported with the endpoint badge. is this a bug reporting that it's not working or are you asking us to add support for colorizing custom logos?

Full schema defined [here](https://shields.io/endpoint)

**Comment by mudlabs** [comment]
Yes, this is a request to add support for colorizing custom logos.

You already do colorizing for _Simple Icons_, just port custom logos into the same service. It's on the logo developer to ensure their svg will display the request color.

**Comment by calebcartwright** [comment]
I remain opposed to Shields dynamically colorizing custom logos as part of the badge rendering workflow.

cc @badges/shields-core - are we open to reconsidering this decision? (refs #4749)

Folks using the logo statically with any of our badges can colorize it in advance, and a user wanting to add logos to their badges with dynamic coloring using an Endpoint badge could still have pre-colorized versions, or do the colorization themselves within their Endpoint

**Comment by paulmelnikow** [comment]
What you're asking is that Shields recolorize the SVG that a developer has just sent us. The developer is converting the SVG to base64 and then adding it to their badge URLs. Colorizing it first is, at worst, a slight inconvenience. So it seems like something that need not be our responsibility. It's also inefficient as the recoloring really only need to be done once, not repeated for every render.

As an alternative I suggest adding a page to the shields.io site where you can paste in an SVG, optionally recolor it, and convert it to base64.

If there's something about your specific use case that makes it unworkable to pre-color the logos, I could be persuaded otherwise.

**Comment by mudlabs** [comment]
I understand developers can provide a custom icon as a base64, via a query param. But I am _only_ talking about the json endpoint requests. These requests can send through a `logoSVG`, which is a stringified `svg`. So the `svg` that's sent to you from the endpoint is the same as what you get from Simple Icons.

When you request a `namedLogo` from Simple Icons you get something like this;
```js
const simpleIcons = require('simple-icons');
console.log(simpleIcons.get('Simple Icons'));
/*
{
    title: 'Simple Icons',
    slug: 'simpleicons',
    hex: '111111',
    source: 'https://simpleicons.org/',
    svg: '<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">...</svg>',
    path: 'M12 12v-1.5c-2.484 ...'
}
*/
```

And the json endpint sent to Shields.io is something like this;
```js
{
  "schemaVersion": 1,
  "label": "Foo",
  "message": "Bar",
  "color": "af435a",
  "style": "for-the-badge",
 " logoSVG": "<svg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>...</svg>"
}
```

If it's a `namedLogo` the user can change the `logoColor` with a query param. Since the `logoSVG` is delivered to you it the same format as Simple Icons I don't see why the `logoColor` override param can't be implemented.

**My Use**
I am building a library of badges. Some use named logos, and others use custom svg logos. Obviously I can manually set the `fill` color on the custom svg logos. But then later if I, or someone else wants the logo to be a different color that endpoint would have to be recreated.
- It just seems to me the functionality for this is already well established on your end.

**Comment by paulmelnikow** [comment]
> I am building a library of badges. Some use named logos, and others use custom svg logos. Obviously I can manually set the fill color on the custom svg logos. But then later if I, or someone else wants the logo to be a different color that endpoint would have to be recreated.

What kind of library of badges? Who are the users? Why do you think they will want to override your badges’ `labelColor`?

**Comment by mudlabs** [comment]
It's just going to be a library of badges I use often, but also open-source, so anyone could add a badge.

I'm going to deploy an action that will fetch a badge from the library. If a user specifies their own `labelColor`, and the requested badge implements `logoSVG`, the action will edit the logos `fill` value and pass the badge logo to Shields.io as a base64; instead of using the endpoint method.

**Comment by calebcartwright** [comment]
Thank you for the extra context. However, I remain opposed to the ask.

A core distinction is that we know what we are dealing with for the logos from the Simple Icons package, whereas users can throw anything at us with custom logos.

Opening up the Shields.io service to having to perform on-request colorization of custom logos is simply not worth it just to support the scenario of some user wanting to use a badge from your personal collection/library but with a different logo color, which I'd argue is fringe at best. That's especially true since users would always have the ability to get their desired badge by colorizing the logo themselves and using Shields directly instead of your custom Endpoint.

I'm sure that's not what you want to hear and acknowledge you may disagree with our perspectives, but we've got to do what we view as best for Shields and this is just one of those cases where I feel we have to say no.

**Comment by mudlabs** [comment]
Sure

**Comment by PyvesB** [comment]
I'm in agreement with @calebcartwright on this one. Colouring the logo in the SVG string really shouldn't be much of an inconvenience for users, `logoSvg` can easily be tweaked to render any desired colors. From an API perspective, specifying both `logoSvg` and `logoColor` in the same request would be quite confusing , as you're effectively specifying two contradictory colors in two different places.
