### ISSUE TITLE
a version specific crates.io badge

### ISSUE THREAD

**Issue by robjtede** [badges/shields#5749]
:clipboard: **Description**

Like the existing "latest" crates.io badge but with a version parameter.

:link: **Data**

Same as existing crates.io badge.

:microphone: **Motivation**

Badges embedded in READMEs are not able to reflect the observed version when viewed on an older crate version's page on crates.io.

**Comment by calebcartwright** [comment]
I understand the situation you are describing, but I'm not really sure why that's problematic/what the value is in your ask, nor how you are requesting that be addressed.

The point of the referenced dynamic version badge is largely to convey the latest version published for that package that can in turn be linked to the registry page. That always holds true, as the latest version badge is simply a url-embedded svg with a value that's calculated by querying the crates.io API (not user/browser context specific). Regardless of the crate version you're looking at, the readme and the contents of that file (including embedded image urls) are static and based on the contents of that readme file at the time the crate was published.

Our svgs have no awareness of the context in which they are used/embedded/etc., so there's no way we can provide an svg that dynamically changes its values based on what version of a crate each user happens to be reviewing in their web browser at that point in time.

I guess if you _really_ wanted your readme badge version to match the crate version when viewed on the crates.io registry, you could instead use our static badge feature and ensure that you update the badge url value in your readme as part of every publish, e.g.

http://img.shields.io/badge/crates.io-v0.9.0-orange
![](http://img.shields.io/badge/crates.io-v0.9.0-orange)

http://img.shields.io/badge/crates.io-v0.10.0-orange
![](http://img.shields.io/badge/crates.io-v0.10.0-orange)

However, it's still unclear to me why you'd want to have that behavior especially in the context of the actual registry where the packages can be consumed by your users. If I'm browsing an older version of a crate on crates.io, I feel like crates.io already provides a lot of information that tells me which version of that crate I'm viewing. I'd also suggest that having a latest-published version badge at the top of the readme provides more useful information when looking at an old crate version, since that information isn't as prevalent (have to scroll down and look at the version listings on the right)

**Comment by robjtede** [comment]
Very good points, the static badge idea has come to mind since opening. In thinking about it, the value add is very little; only that having mismatched badges on a README page is weird and that the crates.io badge itself doesn't actually convey it represents the latest available version as context for older READMEs.

I think the jury is out for best practice of badges on these archived pages given the lack of injectable context (without some official support from crates.io). Thanks for your reply and feel free to close.

**Comment by calebcartwright** [comment]
Sure! Happy to help. I'll close the issue but also wanted to add that this situation isn't unique to crates.io and the same behavior is experienced with the npmjs registry, pypi, etc. 

Ultimately I think it's a matter of what folks assume the badge means. Perhaps changing the label up a bit could help if you really want an extra visual indicator that the badge reflects the latest version of the crate vs the version docs you happen to be browsing, for example

https://img.shields.io/crates/v/serde?label=latest
![](https://img.shields.io/crates/v/serde?label=latest)

**Comment by robjtede** [comment]
Ahh modifiers apply to pre-built badges, of course. I think this solution is most elegant.
