### ISSUE TITLE
Badge Request: Crates.io crate size

### ISSUE THREAD

**Issue by cgbur** [badges/shields#6011]
Crates.io crate size badge. 

Example for the [tokio](https://crates.io/crates/tokio) crate: ![Crates.io](https://img.shields.io/badge/dynamic/json?color=red&label=size&query=versions%5B0%5D.crate_size&url=https%3A%2F%2Fcrates.io%2Fapi%2Fv1%2Fcrates%2Ftokio%2Fversions)

That one was generated from a dynamic shield 
```
https://img.shields.io/badge/dynamic/json?color=red&label=size&query=versions%5B0%5D.crate_size&url=https%3A%2F%2Fcrates.io%2Fapi%2Fv1%2Fcrates%2Ftokio%2Fversions
```

The issue with this method is that the file sizes that are returned are in bytes which is pretty inconvenient. Ideally, you could just re-use the size conversion function that is used for NPM and github sizes. You can of course specify the version you desire just like how you handled the other crates.io shields. It looks like they are using 10^3 for kB instead of 2^10 so that would be whatever you guys use as a standard or whatever matches crates.io.

The returned information can be gotten by something like:
```javascript
// https://crates.io/api/v1/crates/:crate-name/versions
fetch("https://crates.io/api/v1/crates/tokio/versions").then(res => console.log(res.versions[0].crate_size))
```

This would be useful for easily gauging the size of the repositories you are adding straight from the git page and can also be used as a selling point if small sizes are something you are proud of.

**Comment by calebcartwright** [comment]
Thanks for the request @cgburgess, sounds reasonable to me. We have a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if you or anyone else is interested in implementing this badge.

It should be pretty easy to do so, especially since it's the same API endpoint and response our other crates badges work with

The schema would need to be updated here:
https://github.com/badges/shields/blob/61d2b0d07f9d67babbc82303069550914f395b44/services/crates/crates-base.js#L9-L32

and then a new service class and tester would need to be added under the crates directory.

Some things that may need to be considered however:
* Should this support the size for a specific crate version as well as the "latest" version (e.g. routes `/crates/size/:crate` and `/crates/size/:crate/:version`)
* What does the version at index 0 represent: `max_version` or `_newest_version`(presumably just like `semver` vs `date`) and do we need a query param here (this question would likely apply to the existing download count badge as well)

**Comment by cgburgess** [comment]
Awesome I will probably take a stab at implementing this over the weekend.
