### ISSUE TITLE
Microsoft Edge & Opera

### ISSUE THREAD

**Issue by avi12** [badges/shields#6041]
:clipboard: **Description**
Basically, similarly to the badges that exist for [Google Chrome](https://shields.io/category/downloads#:~:text=Chrome%20Web%20Store) and [Mozilla Firefox](https://shields.io/category/downloads#:~:text=Mozilla%20Add-on), just make ones that work for the Edge extensions store and Opera add-ons store

:link: **Data**
To get the rating of an Edge extension, you can just fetch it by its ID, and the same goes for Opera
As for the user count, Edge doesn't have that yet, and Opera displays the total downloads - not the weekly users

:microphone: **Motivation**
Some developers choose to publish their extensions to multiple stores (like me), so it's useful to have a badge for Chrome Web Store, Mozilla Add-ons, Edge Extensions, and Opera Add-ons

**Comment by calebcartwright** [comment]
Thanks for reaching out with your suggestion, but going to close this as a duplicate.

Edge duplicates (#5546 & #4690)
Opera duplicates (#827 & #990)

If any of the discussed upstream blockers have been resolved (namely an official, supported and documented API being made available) then we can revisit but otherwise there's nothing different here than those previous issues.

Thanks again!
