### ISSUE TITLE
Make GitHub Actions workflow check badges not count canceled runs as failing

### ISSUE THREAD

**Issue by itsmeow** [badges/shields#6043]
:clipboard: **Description**

The badge should ignore canceled runs and go to the first one with a result, or say "Canceled".

Ex:
![image](https://user-images.githubusercontent.com/10366817/104100362-19a2a580-526b-11eb-8be2-1d0cefa6ad6a.png)

![image](https://user-images.githubusercontent.com/10366817/104100283-13142e00-526b-11eb-9507-cf116a993027.png)

**Comment by calebcartwright** [comment]
It's unclear to me from the description what you're suggesting being changed due to a lack of context.

We get the corresponding workflow status directly from GitHub for the given repo (or branch in said repo), and other than some minor normalization/standardization of verbiage (e.g. converting `passed` to `passing` for consistency) we display that value the upstream provider gave us.

If GitHub says the status is `cancelled` then that's what our badge says. If you're claiming something to the contrary, please provide additional details (badge url, repository details, etc.) beyond the images in the issue description as those aren't particularly helpful for us.

**Comment by itsmeow** [comment]
Hm. If GitHub isn't saying canceled, then I suppose it's not an issue with the badges. Thanks for the help. Sorry to bother.

**Comment by calebcartwright** [comment]
No worries, thanks for reaching out!
