### ISSUE TITLE
Publish both snapshots and releases to DockerHub

### ISSUE THREAD

**Issue by carlspring** [badges/shields#6049]
:clipboard: **Description**

At the moment, only "snapshots" are being pushed to DockerHub. It is unclear whether these are nightly builds, whether they're done after a pull request, or manually when decided/needed. The community can clearly benefit from these.

The problem with the currently deployed version is that it's simply labelled as `next` which isn't an actual version and can easily be wiped next time a new version is pushed, making it a silent snapshot release. This is unstable and unreliable for use.

The documentation shows you how you can build your own Docker image from the `Dockerfile`, but it would be much better to have official releases for this. There should be a dedicated page on Docker and how to use the image.

Also, the currently available `shieldsio/shields:next` image, places the code under `/usr/src/app`. This is not really a conventional place to put an appliction and is actually mean for source code for various applications.

**Comment by calebcartwright** [comment]
Thanks for reaching out!

The current versioning approach is deliberate: it always reflects latest from trunk branch, which has all changes validated via our CI and PR/merge processes. The version of the Shields server in the image on DockerHub is basically identical to what's running on Shields.io service (with a couple days lag on average). However, we've been having discussions in the ops team meetings about potentially changing this to something like CalVer.

Are there any specific problems that you've encountered, or are you just offering some general feedback and suggestions?

I think it's important to note for context that we're a small team and are focused on the development and support of the Shields.io service itself. The vast, _vast_ majority of our users are consuming the Shields.io service and comparatively the self-hosted Shields server is not really a core use case nor one that's formally supported in any capacity at this time. That's largely because self-hosting is really only necessary in a handful of edgier cases where a user needs badges for a private service/tool (or private project), or from services/tools that are not internet facing (e.g. private corporate intranet).

We still try to enable that uncommon self-hosting case by having a couple straightforward ways to get up and running simply and quickly, because it tends to be a one-and-done action. For example, a typical self-hoster just wants to get setup so they can have badges for their private GitHub repos or from their Jira server; they neither care about nor need the random assortment of new badges for new services that get added every month.

As I mentioned before, we're open to potential improvements in this space and some discussions are under way, but the above context will still be in place unless and until something significant changes. We're not going to start formally "releasing" the server (we intentionally [don't even version it](https://github.com/badges/shields/blob/46b98c40be47b823a41746ca2caa39bc276702a2/package.json#L3)) as an on-prem/server-equivalent offering of Shields with LTS, etc., and DockerHub as one distribution channel. Like many open source projects we've only got a handful of unpaid volunteers with limited bandwidth that's essentially entirely occupied by Shields.io itself. The capacity to do more with self-hosting is extremely constrained.

> It is unclear whether these are nightly builds, whether they're done after a pull request, or manually when decided/needed

I think that's a fair point, and agree we can add some additional documentation to clarify.

> The problem with the currently deployed version is that it's simply labelled as next which isn't an actual version and can easily be wiped next time a new version is pushed, making it a silent snapshot release

I'm not really sure about some of the terminology being used here (e.g. "snapshot", "silent"), which seems intended to connote meaning that I can only associate to unrelated ecosystems (Java/maven). However, think I get the gist of the point, but I'd refer back to this being intentional. Though I have my personal qualms with the utilization of the publishing and consumption of `latest` with Docker images, it's not exactly a novel pattern and we're doing the exact same thing here, just with a different label.

> This is unstable and unreliable for use.

Have to say I strongly disagree with this, especially with the dearth of supporting evidence/real issues encountered. I can definitely appreciate the desire for additional documentation and tagging/release strategy, but that doesn't mean that the server we make available as an image is inherently unstable or unreliable.

Yes, we're aware that this means one can not go to DockerHub to grab an image that has the Shields server from a specific point in time from the past, but again this has been by design. Certainly aware of the benefits of being able to rollback in the abstract, but specifically within the Shields self-hosting context, to date there's hasn't been any need nor use case communicated as to why a self-hoster would need to rollback to an earlier version. 

> The documentation shows you how you can build your own Docker image from the Dockerfile, but it would be much better to have official releases for this.

Largely covered in previous commentary above, but will note "Official" can obviously have different meanings for different folks. Our core goal for the Docker image has simply been to provide an easy option for someone wants to use Docker as the means for self-hosting, and which was provided directly by the Shields team (not a random community image). Whereas you seem to be requesting the more formal/supported type of offering which is quite different.

> places the code under /usr/src/app. This is not really a conventional place to put an appliction and is actually mean for source code for various applications

I suppose that's also fair, though would suggest those that want to run a self-hosted Shields server via the simplest route of just grabbing a Docker image most likely aren't particularly concerned with the inner fs structure. Feel free to submit a PR with a suggested change though if you think changing this would be helpful!

<br />

See also #3558

**Comment by carlspring** [comment]
Hi @calebcartwright ,

Thanks for getting back to me and thank you for going into so much details in your explanation!

> 
> The current versioning approach is deliberate: it always reflects latest from trunk branch, which has all changes validated via our CI and PR/merge processes. The version of the Shields server in the image on DockerHub is basically identical to what's running on Shields.io service (with a couple days lag on average). However, we've been having discussions in the ops team meetings about potentially changing this to something like CalVer.
> 
> Are there any specific problems that you've encountered, or are you just offering some general feedback and suggestions?

There are currently no concrete problems, but we're planning on running this on-prem in our organization and while this will not be a mission-critical service, we are expected to have some form of guaranteed stability, which one would normally expect to get from a "released" (or otherwise "tagged") version that is a reproducible binary/image from a given point in time.

Both CalVer and Semver would be excellent choices and are widely used.

> I think it's important to note for context that we're a small team and are focused on the development and support of the Shields.io service itself. The vast, _vast_ majority of our users are consuming the Shields.io service and comparatively the self-hosted Shields server is not really a core use case nor one that's formally supported in any capacity at this time. That's largely because self-hosting is really only necessary in a handful of edgier cases where a user needs badges for a private service/tool (or private project), or from services/tools that are not internet facing (e.g. private corporate intranet).
> 
> We still try to enable that uncommon self-hosting case by having a couple straightforward ways to get up and running simply and quickly, because it tends to be a one-and-done action. For example, a typical self-hoster just wants to get setup so they can have badges for their private GitHub repos or from their Jira server; they neither care about nor need the random assortment of new badges for new services that get added every month.
>
> As I mentioned before, we're open to potential improvements in this space and some discussions are under way, but the above context will still be in place unless and until something significant changes. We're not going to start formally "releasing" the server (we intentionally [don't even version it](https://github.com/badges/shields/blob/46b98c40be47b823a41746ca2caa39bc276702a2/package.json#L3)) as an on-prem/server-equivalent offering of Shields with LTS, etc., and DockerHub as one distribution channel. Like many open source projects we've only got a handful of unpaid volunteers with limited bandwidth that's essentially entirely occupied by Shields.io itself. The capacity to do more with self-hosting is extremely constrained.
> 

I appreciate that you are a small OSS team! You're providing an excellent service for a very broad OSS community.

There are however, valid cases where an organization/company might want to host their own Shields service on-premise (mostly for security reasons), which is why I am pointing this out. :)
 
Would you mind providing some more details around why you've chosen to not use a version and are sticking with `0.0.0`? What benefits is this bringing you? As a Build & Release/DevOps Engineer, I'm really keen to find out. Is it about forcing everyone to be with the latest code?

> > It is unclear whether these are nightly builds, whether they're done after a pull request, or manually when decided/needed
> 
> I think that's a fair point, and agree we can add some additional documentation to clarify.

:+1: 

> 
> > The problem with the currently deployed version is that it's simply labelled as next which isn't an actual version and can easily be wiped next time a new version is pushed, making it a silent snapshot release
> 
> I'm not really sure about some of the terminology being used here (e.g. "snapshot", "silent"), which seems intended to connote meaning that I can only associate to unrelated ecosystems (Java/maven). However, think I get the gist of the point, but I'd refer back to this being intentional. Though I have my personal qualms with the utilization of the publishing and consumption of `latest` with Docker images, it's not exactly a novel pattern and we're doing the exact same thing here, just with a different label.
> 

In the Maven/Java world (but not only), a snapshot is the next unstable development version. In your case, since it's a version that will be overwritten next time you've merged changes and built and pushed a new image, it will still be under the same `next` version, (which is, effectively, the same thing).

> > This is unstable and unreliable for use.
> 
> Have to say I strongly disagree with this, especially with the dearth of supporting evidence/real issues encountered. I can definitely appreciate the desire for additional documentation and tagging/release strategy, but that doesn't mean that the server we make available as an image is inherently unstable or unreliable.
> 
> Yes, we're aware that this means one can not go to DockerHub to grab an image that has the Shields server from a specific point in time from the past, but again this has been by design. Certainly aware of the benefits of being able to rollback in the abstract, but specifically within the Shields self-hosting context, to date there's hasn't been any need nor use case communicated as to why a self-hoster would need to rollback to an earlier version.
> 

Perhaps I misspoke. Sure, you can use it. By "unreliable" I meant that you have no guarantee that the image might not change and you might be surprised by changes that unexpectely start breaking things for you. This is why code gets versioned and released.

> > The documentation shows you how you can build your own Docker image from the Dockerfile, but it would be much better to have official releases for this.
> 
> Largely covered in previous commentary above, but will note "Official" can obviously have different meanings for different folks. Our core goal for the Docker image has simply been to provide an easy option for someone wants to use Docker as the means for self-hosting, and which was provided directly by the Shields team (not a random community image). Whereas you seem to be requesting the more formal/supported type of offering which is quite different.

Yeah, in our case, we would be hosting it on-premise and we were hoping to use a "release" (fixed in time) version.

> > places the code under /usr/src/app. This is not really a conventional place to put an appliction and is actually mean for source code for various applications
> 
> I suppose that's also fair, though would suggest those that want to run a self-hosted Shields server via the simplest route of just grabbing a Docker image most likely aren't particularly concerned with the inner fs structure. Feel free to submit a PR with a suggested change though if you think changing this would be helpful!

This is a trivial fix, but it would be up to your team to decide where you're like to place this. I was just saying that, while it doesn't really matter where it's placed, (as long as it works), it's not exactly following any common conventions and they your might like to look into it.

> 
> See also #3558

Thanks! And thanks again for your very detailed answer!

I hope you view my notes and remarks as something constructive and useful (I have been building, releasing and deploying software, as well as contributing to OSS projects for quite a few years now and just wanted to share my thoughts on how things could be improved).

**Comment by chris48s** [comment]
> Would you mind providing some more details around why you've chosen to not use a version and are sticking with `0.0.0`? What benefits is this bringing you?

Basically the "advantages" of not versioning it, or reasons why we've not done it  are:
- Shields.io itself is essentially a "rolling" release: We don't really version it for our own purposes.
- We don't have to think about cutting releases. We merge PRs and dockerhub updates.
- We've struggled to work to how/when to version. We use semver for the [badge-maker library](https://www.npmjs.com/package/badge-maker) because it is relatively clearly defined how to determine what is a breaking change/feature/fix for a library or API. It is less clear what it means to make a breaking change when the deliverable is a website. I think the consensus we've arrived at is that calendar versioning makes more sense and solves that problem and we should just pick an interval rather than thinking of a release as a "milestone".

Personally I would like us to start versioning for self hosting users and providing some kind of changelog. We did talk about this at a recent core team meeting and I wrote up a plan for how we think we can start doing that in a relatively automated/low overhead way at https://github.com/badges/shields/issues/5866 . Nobody has started working on it (yet) but it is on my radar. I would like to pick it up soon. I think once we are creating tags on the repo it is relatively easy to have dockerhub create tagged builds too.

It is an infrequent occurrence, but the big advantage of versioning for me would be that it would make it easier to communicate about security issues. When we've published [advisories](https://github.com/badges/shields/security/advisories) affecting self-hosting users its is currently hard to say "if you're on version X or lower, you're vulnerable. Upgrade to version Y or higher to fix it". Putting out https://github.com/badges/shields/security/advisories/GHSA-pc52-cfhv-93g5 a few days ago has kind of re-focussed my mind on this.

**Comment by calebcartwright** [comment]
> we are expected to have some form of guaranteed stability, which one would normally expect to get from a "released" (or otherwise "tagged") version that is a reproducible binary/image from a given point in time.

@carlspring - I figured this was the case :+1: This tends to be the modus operandi in the corporate world, and I can definitely relate as it's the experience I have at my day job as well. I think the difference though with Shields as compared to say a product like Sonatype's Nexus is that we focus almost exclusively on the SaaS offering, with the on-prem/self-hosted being very minimal and secondary.

I run a self-hosted Shields server at my day job as well, and for some of these same reasons, I build the docker image from source which is then used for internal deployment. This is primarily driven by the need to not have stale components in there for security concerns, both from the app deps and the image itself (i also have to swap to an in-house base image for managing image updates)

> I hope you view my notes and remarks as something constructive and useful 

Absolutely! I felt like I had a sense of what you were looking for, and just wanted to provide detail on the self-hosted offering so you'd know what you're getting into: the only products that we offer and maintain today are Shields.io (SaaS) and the npm package, not a released/self-hosted version of the product that one typically thinks of in the enterprise world

> It is an infrequent occurrence, but the big advantage of versioning for me would be that it would make it easier to communicate about security issues. When we've published advisories affecting self-hosting users its is currently hard to say "if you're on version X or lower, you're vulnerable. Upgrade to version Y or higher to fix it"

@chris48s - yeah I had this in the back of my mind too and almost mentioned it, but decided against it because, at least at this time, I feel like our guidance is always going to be: upgrade to latest. The case where I think it would probably be most useful would be something like #4655 where we'd potentially need to make a "breaking" change (which to my recollection hasn't happened since we started pushing to DHub)

This thread actually emphasizes some of the concerns I have about expanding/enhancing our offerings of the server itself, via Docker or otherwise, namely what should users be expecting from versioned releases? What would we have done with the recent advisory (or previous) relative to affected versions? Remove them? Release some kind of Patch for each released version with a fix (so CalVer.Something?). What about Dependabot-raised security alerts for direct/indirect dependencies? What about issues stemming from the base layers? And on and on it goes :smile: 

There's a lot of reasonable assumptions users could make about what a released version means, and I think we need to have very explicit and obvious documentation about what we would/won't do for server versions to eliminate any ambiguity or interpretation.

What we've talked about so far would be (entirely my words) essentially: this is the server we had in source on this date. there's absolutely zero guarantees and zero support for this, use at your own discretion.

**Comment by chris48s** [comment]
> The case where I think it would probably be most useful would be something like #4655 where we'd potentially need to make a "breaking" change (which to my recollection hasn't happened since we started pushing to DHub)

That's also a good point. Putting aside the issue that it is hard to define "breaking" when the deliverable isn't a library or API, I'd say we probably made a breaking change for self-hosting users a couple of months back (albeit one more likely to affect users who run from source): https://github.com/badges/shields/pull/5864 Either way, "breaking" or "non-breaking" it was a change we wanted to tell self-hosting users about. I agree that's another case where it would have been nicer if when we posted https://twitter.com/Shields_io/status/1330984982710525953 we could have said "support for .env files will be dropped in server-2020.12" or whatever. It would also have been nicer if it was in a changelog somewhere.

> What would we have done with the recent advisory (or previous) relative to affected versions? Remove them? Release some kind of Patch for each released version with a fix (so CalVer.Something?)

I don't suggest doing either of those things and I don't think tagging the repo (or images) with a date implies we would, but if you're super worried it does we can add some notes in the self-hosting docs/security policy/wherever.

> this is the server we had in source on this date. there's absolutely zero guarantees and zero support for this, use at your own discretion

Sure, so exactly what we do now really.. only if you follow tags, then you actually know what version you're running and might be able to look at a changelog and find out what changed since the last one :)

**Comment by calebcartwright** [comment]
> I'd say we probably made a breaking change for self-hosting users a couple of months back (albeit one more likely to affect users who run from source): #5864

Yup, agreed! I was thinking about the Docker image with the next specifically where also agreed it almost certainly wouldn't have had real world impact because of how wonky it'd be to mount in the file instead of using more Docker friendly means, but it falls in the same category regardless.

>  Sure, so exactly what we do now really.. only if you follow tags, then you actually know what version you're running and might be able to look at a changelog and find out what changed since the last one :)

Agreed. It's more that current state is singular, constantly rolling/non-immutable tag on DockerHub, and we're moving to (as an augmentation of the current state) point-in-time tags that are immutable and have some associated change notes.

>  but if you're super worried it does we can add some notes in the self-hosting docs/security policy/wherever.

It's more so that I want to lean on the side of over communication rather than leaving anything to be interpreted subjectively by users, especially given some of the wording @carlspring used above:

> we are expected to have some form of guaranteed stability

Maybe the type of documentation I'm suggesting is duplicative and it'll be clear to all users what a calversioned tagged release of the server means, but I'm not convinced that's the case. We do not do any testing with the Docker image itself (if the image builds then it's pushed), we don't use any of the Docker images for the Shields.io deployments, we don't do any actual integration/functional tests with a self-hosted instance (e.g. with configured credentials and against integrated tools/services).

The calver tag is just whatever happened to be at the HEAD whenever the publish job was triggered that month, with no real difference in validation/quality in the preceding nor proceeding commits, and it is whatever it is: we don't support it, we don't provide any guarantees, we're not going to patch it, etc.

**Comment by chris48s** [comment]
We're now publishing tags to dockerhub: https://registry.hub.docker.com/r/shieldsio/shields/tags?page=1&ordering=last_updated
More context on this in the docs: https://github.com/badges/shields/blob/master/doc/releases.md#shields-server
