### ISSUE TITLE
Docker build status Shield returns invalid response data

### ISSUE THREAD

**Issue by fmigneault** [badges/shields#6235]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Something doesn't work about the first docker shield below. 
I'm not sure if it is related to the automated/manual build method, but status cannot be retrieved. 
Same link format but replacing the target repository works for another repo I work on. 

:link: **Link to the badge**

https://img.shields.io/docker/cloud/build/pavics/weaver.svg
![Docker Cloud Build Status](https://img.shields.io/docker/cloud/build/pavics/weaver?label=docker-build-status%20pavics/weaver)

https://img.shields.io/docker/automated/pavics/weaver.svg
![Docker Cloud Build Status](https://img.shields.io/docker/automated/pavics/weaver?label=docker-build-mode%20pavics/weaver)

https://img.shields.io/docker/cloud/build/pavics/magpie.svg
![Docker Cloud Build Status](https://img.shields.io/docker/cloud/build/pavics/magpie?label=docker-build-status%20pavics/magpie)

https://img.shields.io/docker/automated/pavics/magpie.svg
![Docker Cloud Build Status](https://img.shields.io/docker/automated/pavics/magpie?label=docker-build-mode%20pavics/magpie)

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment]
Thanks for the report! The `invalid response data` error is what happens when an upstream API response was something we were not expecting and unprepared for.

The API calls made for the two referenced repositories:
https://hub.docker.com/api/build/v1/source/?image=pavics/weaver
https://hub.docker.com/api/build/v1/source/?image=pavics/magpie

In the case of pavics/weaver, the `objects` array is empty while our code was expecting/reliant on there being at least one entry, as that's where the data for build status is found. We can update our schema validation that inspects the response from the DockerHub API to better handle this scenario since it's obviously a possible response, although TBH I'm not really sure what the message should be here, maybe throw some kind of error indicating automated builds haven't been setup for that repo?

I've marked this as a good-first-issue because the code change is relatively straightforward, though admittedly some TBD on what the error/text message of the badge should be

The schema can be found here, and the easiest fix would probably be to remove the `.required()` call chain on the object on line 11.
https://github.com/badges/shields/blob/cf7c9c11471bb227069c013657491d842f6c7940/services/docker/docker-cloud-common-fetch.js#L5-L14

There would then be a need to check added to account for the empty `objects` array and act accordingly. I'd think we'd want to do that in the cloud build service for this issue, https://github.com/badges/shields/blob/master/services/docker/docker-cloud-build.service.js and throw an error in the case of an empty array, whereas in the cloud automated build service we'd want to incorporate that possibility to properly indicate it as manual https://github.com/badges/shields/blob/master/services/docker/docker-cloud-automated.service.js

(note that the badges in the issue description are using the older/legacy route which ironically still work, but the same invalid response issue exists for the cloud automated badge https://img.shields.io/docker/cloud/automated/pavics/weaver ![](https://img.shields.io/docker/cloud/automated/pavics/weaver))

**Comment by fmigneault** [comment]
@calebcartwright 
I see. Makes sense since there are no build details. 
A specific message for this case would help indeed, but I agree that there is not much more that can be done with returned content.
Thanks!

**Comment by PaulaBarszcz** [comment]
I'd like to pick this one up :)

The badge error message for https://img.shields.io/docker/cloud/build/pavics/weaver.svg 
can say `automated builds not set up`, as per @calebcartwright's suggestion (unless there are some other ideas?).

@calebcartwright wrote:
> There would then be a need to check added to account for the empty objects array and act accordingly. I'd think we'd want to do that in the cloud build service for this issue, https://github.com/badges/shields/blob/master/services/docker/docker-cloud-build.service.js and throw an error in the case of an empty array, whereas in the cloud automated build service we'd want to incorporate that possibility to properly indicate it as manual https://github.com/badges/shields/blob/master/services/docker/docker-cloud-automated.service.js

Will do :) 👍
