### ISSUE TITLE
GitHub workflow badge breaks on newer workflows

### ISSUE THREAD

**Issue by cyyynthia** [badges/shields#6255]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Despite the repository and workflow existing, the badge is yielding a "repo, branch, or workflow not found" error.

:link: https://img.shields.io/github/workflow/status/squirrelchat/squirrel/test?style=flat-square

:bulb: **Possible Solution**

The service seem to be scraping the badge from `https://github.com/:user/:repo/workflows/:workflow/badge.svg` (according to [this piece of code](https://github.com/badges/shields/blob/master/services/github/github-workflow-status.service.js#L85-L87))

However in my case this badge [does not exist](https://github.com/squirrelchat/squirrel/workflows/test/badge.svg). Instead, the badge is hosted on `https://github.com/:user/:repo/actions/workflows/:workflow_file_name/badge.svg`.

It seems like a recent change GitHub did, and badges generated prior this change (like the ones used in the unit tests) are still hosted on the older url. Keep in mind that they never seem to be hosted at both locations, so the service needs to check for both URLs.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but that's not correct. Our badges use the _workflow_ name, not the name of the yaml file that contains the workflow definition. Also remember the workflow name is case sensitive.

You have named your workflow `Tests` so that's the value you need to use for the workflow name route parameter on our badge url

https://github.com/squirrelchat/squirrel/blob/5e8ed6ed2259baa73a5cc0f95b72cc3179b5dbc4/.github/workflows/test.yaml#L1

https://img.shields.io/github/workflow/status/squirrelchat/squirrel/Tests?style=flat-square
![](https://img.shields.io/github/workflow/status/squirrelchat/squirrel/Tests?style=flat-square)

**Comment by cyyynthia** [comment]
oh, sorry for that misunderstanding 😅 and thank you for your quick answer!

**Comment by calebcartwright** [comment]
No worries, we're always happy to help (especially when things are easy fixes like this one :smile:)
