### ISSUE TITLE
Website down & badges are slow or missing

### ISSUE THREAD

**Issue by BenjaminMichaelis** [badges/shields#6339]
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

When going to [https://shields.io/](https://shields.io/) running into this error:
```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

:link: **Link to the badge**

Entire [website](https://shields.io/) is down

**Comment by harryzcy** [comment]
Seems it's working now.

**Comment by BenjaminMichaelis** [comment]
Seems to be fixed

**Comment by paulmelnikow** [comment]
I'm going to reopen this because I suspect these problems are going to continue for a while. We're experiencing severe memory pressure on the server. It's begun to stabilize and we've mostly stopped dropping request. However the average badge response time is still around 10 seconds so we've a long way to go before we're back to normal.

**Comment by jonaschn** [comment]
The website is down again.

**Comment by calebcartwright** [comment]
Going to go ahead and close this now. We have observed some recurring trends of a sharp uptick in traffic on certain days of the week and are experimenting with some approaches to handle those increased loads.

No need to keep this issue open indefinitely though
