### ISSUE TITLE
Showing in-progress GitHub Actions as "in progress"

### ISSUE THREAD

**Issue by gennaroprota** [badges/shields#6367]
Hi,

I noticed that, while a build is in progress, the Shields.io badge that I have in my project readme, on GitHub, shows the status of the last completed build. That is, it never reports "in progress" or anything like that. Is there any way to fix this?

The readme I'm hinting at can be seen at:

<https://github.com/gennaroprota/breeze>.

Thanks.

**Comment by calebcartwright** [comment]
The workflow status badge in your readme is explicitly pointed to your master branch, so it's always, and only, going to reflect the  status for workflow runs against _that_ branch.

If you want it to reflect the current status of the workflow run independent of any single branch, then you should remove the `/master` route parameter from your badge url.

Please also note that even though we have the shortest cache duration for build status badges like this one (30 seconds) there are still a few layers of caching, and if your entire workflow run completes in significantly less than that 30 second then it might be fairly unlikely that you'd get a request and a cache miss at the same time a workflow was in progress.

**Comment by gennaroprota** [comment]
Yes, pointing to the master branch only was intentional, but thanks for the heads up! :-)

My tests normally take a few minutes (on average, a little more than 10 minutes when they succeed). But one thing that is occurring to me now is: should I load the readme page in the browser 30 seconds after the push, so that the badge cache expires? (I'm not sure how much I've been waiting after the push, so far: you know, it may be just a matter of hitting CTRL-TAB, F5 :-).)

**Comment by calebcartwright** [comment]
I'm going to close this as there doesn't really seem to be anything actionable. If you feel this is something you are still encountering, please feel free to reopen (or add a comment) with details and preferably screenshots showing both our workflow status badge and the native github workflow status badge side by side; if there's genuinely something different between the two then we'll take a look, but otherwise we just use the data the upstream services give us.
