### ISSUE TITLE
Add glowing/animated effect for badges with different colors

### ISSUE THREAD

**Issue by luke-who** [badges/shields#6385]
:clipboard: **Description**

This badge can be used for GitHub/Travis CI, can be used to show if the build is passing/running with animated effect
An example can be like this one [![here](https://camo.githubusercontent.com/bf7890ff422dc776d9a01b0b1084bfbb2b1c7678d229c1a871ba82433bb88d06/68747470733a2f2f63692e6c696e61726f2e6f72672f6a656e6b696e732f6275696c645374617475732f69636f6e3f6a6f623d6c6463672d707974686f6e2d74656e736f72666c6f772d6e696768746c79)]()

:link: **Data**

The example above's link can be seen [here](https://camo.githubusercontent.com/bf7890ff422dc776d9a01b0b1084bfbb2b1c7678d229c1a871ba82433bb88d06/68747470733a2f2f63692e6c696e61726f2e6f72672f6a656e6b696e732f6275696c645374617475732f69636f6e3f6a6f623d6c6463672d707974686f6e2d74656e736f72666c6f772d6e696768746c79)

:microphone: **Motivation**

This badge can be used to show an animated status for CI/CD pipelines, which is **more expressive** and **far more visually appealing** than than static ones

**Comment by calebcartwright** [comment]
Thanks for sharing your idea! 

> This badge can be used to show an animated status for CI/CD pipelines, which is more expressive and far more visually appealing than than static ones

It's important to remember that regardless of individual subjection opinions on what is/isn't appealing, our badge defaults are based on a well defined [specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md), and that spec and the associated defaults are not something that's going to change.

I suppose this could be added as an additional optional style. However, I'm personally mildly opposed to attempting to do so, primarily because I don't think the use case warrants the development and maintenance overhead. This feels like a style geared towards active observation of a build status, and I cannot relate to the notion of wanting to actively monitor a running build via a readme badge (I'd click on the badge to navigate to the build tool) especially since the badge itself isn't live/actively tailing a running build. It also would be quite nonsensical for something like a License or Code Coverage badge.

I won't stand in the way though if the rest of the team feels like this would be a worthwhile addition, cc @badges/shields-core

**Comment by PyvesB** [comment]
> I'm personally mildly opposed to attempting to do so

Same here. It's somewhat confusing to have something that looks dynamic but in reality needs reloading as the underlying information is static.

Not sure how it would work in terms of implementation and design, but this feels a bit like a plugin/extension to the main badge-maker NPM package.

**Comment by PyvesB** [comment]
There's not been much enthusiasm and engagement on this issue. In particular, at least two maintainers are not keen on seeing this feature implemented in the badge-maker codebase.

For the time being, I'll go ahead and close this. Thanks for the suggestion though! :)
