### ISSUE TITLE
Add IRC to the Chat badge list

### ISSUE THREAD

**Issue by Strykar** [badges/shields#6475]
:clipboard: **Description**
Show total user count which is provided by the server on connect, like `612 1022 :Current local users 612, max 1022`.
Could be displayed as https://img.shields.io/badge/IRC-612%20Total%20users%20connected-brightgreen.
Users in a channel could be displayed as https://img.shields.io/badge/IRC-612%20users%20in%20%23alice-brightgreen

:link: **Data**
The data is provided by the server via telnet or over IRC.

:microphone: **Motivation**
To show total users on IRC servers/channels.

**Comment by calebcartwright** [comment]
Thanks for reaching @Strykar but I'm going to close this because it doesn't fit within our guidelines for badges. For our native badges with values populated dynamically from some upstream source, our badge servers need to be able to retrieve the data over http.

The requested badge here would be best supported by leveraging our [custom Endpoint badge](https://shields.io/endpoint) where whatever custom endpoint you'd implement would be able to get the chat info via whatever means you'd prefer, and  then that endpoint could make that data available over http following our endpoint response schema.
