### ISSUE TITLE
move pre-commit hook from husky to simple-git-hooks

### ISSUE THREAD

**Issue by chris48s** [badges/shields#6507]
:clipboard: **Description**

https://github.com/toplenboren/simple-git-hooks

**Comment by PyvesB** [comment]
I don't think I've ever gotten this to work properly on my Windows machine. My understanding is that it just runs Prettier and the Linter before a commit, which doesn't sound like much added value, so I've not put much time into trying to fix the issue.

As far as I'm concerned, our pre-commit hook setup has only provided strictly negative value, by making me install an extra bunch of dependencies that aren't functional out of the box. This will probably not be to the taste of other folks, but my personal vote would be to remove all of this. :)

**Comment by calebcartwright** [comment]
> I don't think I've ever gotten this to work properly on my Windows machine

Just to clarify, are you referring to the existing setup with `husky` or with `simple-git-hooks`?

**Comment by PyvesB** [comment]
The existing setup with Husky.

**Comment by chris48s** [comment]
My view on these is that the pre-commit hook isn't primarily there to help maintainers - its more for casual contributors. I know I need to run `npm run prettier && npm run lint`. My instinct is that introducing the pre-commit hook reduced the number of casual contributors submitting PRs that failed the build due to trivial formatting errors because it makes it super-clear what they need to do but I don't have hard evidence on that. If you wanted we could try just disabling it for a bit, make sure its signalled in the contributing docs and see what happens..

**Comment by PyvesB** [comment]
>  If you wanted we could try just disabling it for a bit, make sure its signalled in the contributing docs and see what happens..

Frankly, I'm not too fussed either way. Simply wanted to flag up that things did not work for me!

**Comment by calebcartwright** [comment]
> The existing setup with Husky.

:eyes: that's odd. One of the major issues with the predecessors to husky is that they'd either work on unix-based/like systems but not windows, or vice versa. husky was the first one that "just worked" everywhere with minimal setup and config.

Our current setup worked for me out of the box on a windows machine as well when I last tested a while back (though using standard command prompt, didn't try in a powershell terminal, git bash, nor WSL). We do still see PRs from contributors every so often which CI on the prettier and/or lint check, so perhaps others are having the same issue. I hope that such experiences are more the exception rather than the norm, but probably worth some investigation to see if things actually are largely broken on windows.

> My view on these is that the pre-commit hook isn't primarily there to help maintainers - its more for casual contributors. I know I need to run npm run prettier && npm run lint

I share this perspective as well, although there's definitely been an occasion or two where I've forgotten to run manually and committed with the `-n` flag :grin: 

> As far as I'm concerned, our pre-commit hook setup has only provided strictly negative value, by making me install an extra bunch of dependencies that aren't functional out of the box
> If you wanted we could try just disabling it for a bit, make sure its signalled in the contributing docs and see what happens

I'm open to an experimentation as well. There was prior discussion scattered across a few PRs but worth noting here that one of the big changes with the updated husky versions as well as the husky alternatives under consideration is that it's no longer _really_ viable to have auto-setup, and each contributor essentially has to opt in if they want client side hook checks.

The dependency aspect isn't really a concern for me. At least on my system, the current Shields dependencies are using north of 850 megabytes of disk space, and the current v4 of husky only accounts for ~1 of those, with the alternatives being discussed being in the tens of kilobytes and which have zero dependencies themselves.

The bigger concern for me that could sway my perspective on dropping it outright would be whether it ends up having a negative impact on the developer experience for contributors (broken on some platforms, additional setup steps/docs, etc.)
