### ISSUE TITLE
My CocoaPods badge is not working

### ISSUE THREAD

**Issue by NSExceptional** [badges/shields#6596]
(If this is an issue on their side and not y'alls, I'll go open an issue with them instead)

Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

None of the badges for my CocoaPod, FLEX, are working:

![CocoaPods](https://img.shields.io/cocoapods/v/FLEX.svg)
![CocoaPods](https://img.shields.io/cocoapods/p/FLEX.svg)

But other pods are working:

![CocoaPods](https://img.shields.io/cocoapods/v/AutoCoding.svg)

:link: **Link to the badge**

https://img.shields.io/cocoapods/v/FLEX.svg

**Comment by chris48s** [comment]
Hi. I think this is an issue on the CocoaPods side rather than us.

We are calling https://trunk.cocoapods.org/api/v1/pods/FLEX/specs/latest which redirects us to a spec file that doesn't exist: https://raw.githubusercontent.com/CocoaPods/Specs/387275e64a7555c0c316840d4e3d5cd36043f401/Specs/f/7/1/FLEX/4.4.1/FLEX.podspec.json

Interestingly if I call https://trunk.cocoapods.org/api/v1/pods/FLEX/specs/4.4.1 that redirects us to a spec file that _does_ exist: https://raw.githubusercontent.com/CocoaPods/Specs/8ea09b48deb3a500717d2c4fac5634a5cb2f140a/Specs/f/7/1/FLEX/4.4.1/FLEX.podspec.json

Can you try raising an issue with them about it. Thanks

**Comment by NSExceptional** [comment]
Weird! Thanks for debugging that for me. I didn't know how you guys were calling into their API.

Thanks again :)
