### ISSUE TITLE
Get Discord user status

### ISSUE THREAD

**Issue by themysticsavages** [badges/shields#6622]
:clipboard: Check if a user in a Discord server is online.

This badge can show the status of a Discord user on a server (either offline or online). It is similar to the badge which can show the number of people online.

It may be possible to use the Discord API for this task.

This feature should definitely be implemented since it could be used to see if a Discord bot is up as well. It would be more convenient.

**Comment by PyvesB** [comment]
Hello @themysticsavages ! 👋🏻 

Could you give us a little more details on the use case? In what context would you imagine this badge being useful?

**Comment by themysticsavages** [comment]
A good use case for this badge would be to get the status of a user by their ID or discriminator, and the badge could return `ONLINE` or `OFFLINE`. The badge could be useful for bot uptime.

**Comment by calebcartwright** [comment]
> The badge could be useful for bot uptime.

:point_up: this strikes me as the core goal, and seems reasonable to me.

A badge that displays the online status of a specific user on a specific server seems like _one_ particular approach to achieving that goal. However, I don't see the user online status badge having any utility outside that one use case, and I'm not sure whether there are other bot-monitoring type solutions or even if the online status would be viable (we've had some challenges with the Discord API in the past).

> It may be possible to use the Discord API for this task.

@themysticsavages if this is something you're interested in seeing I'd suggest you dig into the Discord docs to see whether or not any such API exists, and importantly, if it's accessible without having to first join the server.

**Comment by themysticsavages** [comment]
Thanks, I will do that.

**Comment by themysticsavages** [comment]
So it seems like a Discord gateway can do exactly this. Although the documentation for this endpoint is a little vague.
https://discord.com/developers/docs/topics/gateway#presence-update

**Comment by advaith1** [comment]
User status can only be accessed by a bot that shares a server with the user, and can only be received through Discord's WebSocket gateway. This doesn't seem to be something that can be feasibly implemented into shields.io itself.

**Comment by themysticsavages** [comment]
Alright. It seems like this issue cannot be solved so I'm closing this.

**Comment by linntwc** [comment]
cuzin

**Comment by BeauBouchard** [comment]
I stumbled across this from a google search. 
This badge can be accomplished using the discord api to fetch the value needed for the badge's online / total members. 
My solution ended up using Dynamic Badge to query a json response and pull 2 values from the discord api. Unfortunately I can't seem to do both values in a single image, but i hope someone does figure out how to do it. 
![Online Discord Users](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=%24.approximate_presence_count&logo=discord&logoColor=white&color=green&label=Users%20Online)

![Total Discord Users](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=%24.approximate_member_count&logo=discord&logoColor=white&color=blue&label=Users%20Total)


### Explanation for the curious 
Looking at this url 
`https://discord.com/api/invites/kNFd4YvFPv?with_counts=true` 
Where the API response contains `approximate_member_count` and `approximate_presence_count` which are the `total` and `connected` user values respectively. 
Using [Dynamic JSON Badge from Shield](https://shields.io/badges/dynamic-json-badge) I am able to query these two values to produce a dynamic badge from just the invite ID. 

I use a [JSONPath](https://jsonpath.com/) to get the above mentioned `approximate_member_count` and `approximate_presence_count`  values both using a Union operator in [XPath](https://goessner.net/articles/JsonPath/index.html#e2) shown below.
```
$.[approximate_presence_count,approximate_member_count]
```

Adding the `logo` as discord, and making the `logoColor` white to contrast the discord color. 
```
?logo=discord&logoColor=white
```
make the value green, and add a label saying `users`
```
&color=green&label=users
```

Prepare the badge url: 
```
https://img.shields.io/badge/dynamic/json?url=
```


I URLencode my discord api call from above like so: 
```
https://img.shields.io/badge/dynamic/json?url=
https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue
```

add query param
```
https://img.shields.io/badge/dynamic/json?url=
https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=
```



URLencode the query above, 
```
%24.%5Bapproximate_presence_count%2Capproximate_member_count%5D
```

add it to the query

```
https://img.shields.io/badge/dynamic/json?url=
https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=
%24.%5Bapproximate_presence_count%2Capproximate_member_count%5D
```

add our style values at the end
```
https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=%24%2E%5Bapproximate_presence_count%2Capproximate_member_count%5D&logo=discord&logoColor=white&color=green&label=users
```
which, for some reason has an error due to the `[,]` union, but individually it works with both values... 

![Online Discord Users](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=%24.approximate_presence_count&logo=discord&logoColor=white&color=green&label=Users%20Online)

![Total Discord Users](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fdiscord.com%2Fapi%2Finvites%2FkNFd4YvFPv%3Fwith_counts%3Dtrue&query=%24.approximate_member_count&logo=discord&logoColor=white&color=blue&label=Users%20Total)
