### ISSUE TITLE
how to use shields.io setting commit numbers for a repository

### ISSUE THREAD

**Issue by S1U** [badges/shields#664]
Like this https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/3.4.7.svg, no idea how to set it for my own specific repo.

**Comment by LPGhatguy** [comment]
Put your GitHub username, repository name, and tag name into the URL like they did.

Here are some examples:

LPGhatguy/postcss-sassy-import: ![](https://img.shields.io/github/commits-since/LPGhatguy/postcss-sassy-import/v0.1.0.svg)

sk1418/zhuaxia: ![](https://img.shields.io/github/commits-since/sk1418/zhuaxia/v3.0.0.svg)

**Comment by espadrine** [comment]
@S1U Does it answer your question?

**Comment by S1U** [comment]
@LPGhatguy @espadrine Yes. Thanks!

**Comment by remkohdev** [comment]
for others: https://img.shields.io/github/issues-raw/USERNAME/REPO/LABEL-NAME.svg

e.g.: https://img.shields.io/github/issues-raw/remkohdev/node-red-contrib-cryptocompare/good-first-issue.svg
