### ISSUE TITLE
A rewrite to Rust

### ISSUE THREAD

**Issue by Milo123459** [badges/shields#6686]
Hey,

Would the Shields team be happy with a rewrite to Rust? It'd be easier on the servers and a bit faster.

**Comment by calebcartwright** [comment]
hi @Milo123459, I appreciate you sharing but I'm going to close this.

I'm a big fan of Rust myself, and we do have a very narrow slice of our capability set where we're evaluating Rust as part of the solution, but there's zero interest and zero chance in rewriting the entire product in a different programming language (Rust or otherwise).

Doing so would entail a massive effort for the rewrite itself, along with various new sets of problems, and wouldn't bring any significant benefits for the challenge set the project deals with today. The drawbacks clearly outweigh any potential benefits by a long shot.
