### ISSUE TITLE
Add new HTML badge

### ISSUE THREAD

**Issue by iron-coder12** [badges/shields#6713]

**Comment by calebcartwright** [comment]
For future reference, please provide the requisite information in an issue especially when using an issue template.

It's not really possible to have a discussion about a badge request in a description-less issue, but given the title I'm going to make the assumption that you're asking for a dynamic html type badge that entails html scraping. As such, I am going to close this because we intentionally do not support this and are not going to support this. It's far too open ended and expensive a process for what we want to provide.

If you want a badge that requires scraping html then the recommendation is to develop your own scraping implementation and utilize our [Endpoint badge service](https://shields.io/endpoint) to produce the badges.

If instead you are requesting something different than a dynamic html badge then please follow up with additional clarifying information and we'll reopen the issue if necessary.
