### ISSUE TITLE
support custom pypi index

### ISSUE THREAD

**Issue by LeoQuote** [badges/shields#6760]
:clipboard: **Description**
I set up an internal pypi repo , this repo support the identical api with pypi.org , can I create a badge for a custom pypi ?

I cannot see any parameter I can pass in the pypi badge.

**Comment by calebcartwright** [comment]
Could you please expand on which specific badges you're referring to (e.g. version vs. license vs. downloads vs. etc.)? Shields always has to reach out to some upstream API to get the required data needed for building a badge, and various badges, even those under the same "umbrella", use different APIs and sometimes even different API providers.

**Comment by LeoQuote** [comment]
Thanks for you reply. For now the version badge is most used, it would be good if sheild can support self-hosted pypi repo!

**Comment by chris48s** [comment]
I think it would be possible to do this for all the pypi badges except for downloads in a similar way to how we allow a `registry_uri` param for NPM.
One thing to note: If we added this feature to shields.io it would only be possible for the alternate pypi registry to be a public registry that does not require authentication. For a non-public registry you would have to host your own instance of shields in order to address it.

**Comment by LeoQuote** [comment]
certainly, non-public registry cannot be reached from shields.io
