### ISSUE TITLE
Badge reporting false positive for Snyk vulnerabilities

### ISSUE THREAD

**Issue by aarongoldenthal** [badges/shields#6831]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Using the `/snyk/vulnerabilities/npm/:packageName` format for Snyk vulnerabilities, the [pagean](https://www.npmjs.com/package/pagean) package badge consistently reports 1 vulnerability, but following the link and checking the Snyk results at https://snyk.io/vuln/search?q=pagean&type=npm no vulnerabilities are found.

### 🔗 Link to the badge

https://img.shields.io/snyk/vulnerabilities/npm/pagean

**Comment by calebcartwright** [comment]
We get our data from the upstream providers, and in the case of Snyk for npm packages we scrape Snyk's own badges. You can see Snyk are reporting 1 vulnerability, which is why our badge does too.

You'll need to reach out to Snyk if you think there's an issue with their reporting

https://snyk.io/test/npm/pagean/badge.svg
![](https://snyk.io/test/npm/pagean/badge.svg)
