### ISSUE TITLE
AUR badges use deprecated and undocumented API to retrieve information

### ISSUE THREAD

**Issue by eli-schwartz** [badges/shields#6835]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

IN #612 AUR support was added, which currently lives here:

https://github.com/badges/shields/blob/a08b523b4fc55a962aa2562dd4ac9126bbf032ed/services/aur/aur.service.js#L38-L46

Per the AUR documentation, there is supposed to be a version keyword `v=5`, which is missing. This is philosophically mandatory, but not a technical restriction: for backwards compatibility with the original v1 API a missing version is interpreted as the v1 API.

(Side note: the v=5 API was current at the time of that PR, not entirely sure why it ended up using the v=1 API instead.)

This is undocumented and may be dropped at any time. And in fact, we plan to drop it in the near future, and make specifying a version mandatory. (This will simplify the code a lot, and that's beneficial since we're currently porting it from PHP to python.)

According to server logs, 65% or more of unversioned requests are coming from shields.io, so this change would definitely impact you!

### 🔗 Link to the badge

https://img.shields.io/aur/maintainer/google-chrome
![AUR maintainer](https://img.shields.io/aur/maintainer/google-chrome)

### 💡 Possible Solution

Please specify the v=5 API and check that it performs as expected.

This will aid us in evaluating the ability to drop old API versions, and future proof shields.io against AUR service changes.

Thanks!

**Comment by calebcartwright** [comment]
Thanks for letting us know! I'll likely have time to look at this tonight.

Just my two cents as an outside opinion looking at the API spec for the first time (the one we have linked in the inline comment), but I feel like the docs are really light on info about the `v` query param. Even going in and searching for a version related query param it was really easy. It pops up in the response object but I felt like the query param was really easy to miss since it's not really referenced anywhere in text but simply appears in the urls.

Might help to call it out explicitly somewhere in the docs to draw attention to it.

**Comment by eli-schwartz** [comment]
Thanks for the fast response!

I see what you mean about the docs. The wiki page is actually based on the internal docs, which the live API will recite back to you if you visit https://AUR.archlinux.org/rpc without actually sending a query.

As you can see, it is missing there too. I think the docs kind of grew... organically. We should definitely fix that.

Thanks for the suggestion.
