### ISSUE TITLE
Idea: Due Date Badge

### ISSUE THREAD

**Issue by MacHu-GWU** [badges/shields#6851]
:clipboard: **Description**

Can you create a badge to track due date?

:link: **Data**

**Preset 1 - Two Week Dead Line**: 14-7 days = green, 7-4 days = yellow, 3-1 days = orange, overdue = red

Due Date = 2000-01-14, shields io url example https://img.shields.io/gitlab/duedate/2w/2000-01-14 Badge example on different date:

- on 2000-01-01: ![](https://img.shields.io/badge/due-2000--01--14%20%7C%2014%20days-brightgreen)
- on 2000-01-08: ![](https://img.shields.io/badge/due-2000--01--14%20%7C%207%20days-yellow)
- on 2000-01-11: ![](https://img.shields.io/badge/due-2000--01--14%20%7C%203%20days-orange)
- on 2000-01-15: ![](https://img.shields.io/badge/due-2000--01--14%20%7C%20overdue-red)

**Preset 2 - 3 Month Dead Line**: first month = green, second month = yellow, last month = orange, overdue = red

Due Date = 2000-04-01, shields io url example https://img.shields.io/gitlab/duedate/3m/2000-04-01 Badge example on different date:

- on 2000-01-01: ![](https://img.shields.io/badge/due-2000--04--01%20%7C%203%20months-brightgreen)
- on 2000-02-01: ![](https://img.shields.io/badge/due-2000--04--01%20%7C%202%20months-yellow)
- on 2000-03-01: ![](https://img.shields.io/badge/due-2000--04--01%20%7C%201%20month-orange)
- on 2000-04-01: ![](https://img.shields.io/badge/due-2000--04--01%20%7C%20overdue-red)

Or, you can implement some preset like: first 1/3 time period = green, 2/3 time period = yellow, last 1/3 time period = orange, overdue = red. Then shields io url example https://img.shields.io/gitlab/duedate/default/2000-04-01, automatically, first month = green, second month = yellow, last month = orange, overdue = red

- Is there a public API? **NO**
- Does the API requires an API key? **NO**
- Link to the API documentation. **NA**

:microphone: **Motivation**

Giving a due date is always useful in software engineering life cycle. If a Due Date badge available, **we can give any markdown / html / restructured text document the power of project management**.

For example, any system that support mark up language can use this feature to track due date. Let's if a software engineer wants to create a task or document in markdown, he can just put the the markdown ``[](https://img.shields.io/gitlab/duedate/2w/2021-08-14)`` ![](https://img.shields.io/badge/due-2021--08--14%20%7C%2013%20days-brightgreen) to mark the due date = 2021-08-14 using 2 weeks preset. And the badge automatically changes overtime. I believe this can be easily cached.

:heavy_dollar_sign: **Donation**

Donated in name of Sanhe Hu

**Comment by calebcartwright** [comment]
I think I get the gist of what you're asking for, but I'm a bit puzzled by your example badge urls that reference Gitlab.

We already provide a relative date badge which accepts unix timestamps for the target date:

https://img.shields.io/date/1629099776
live badge: ![](https://img.shields.io/date/1629099776)
screenshot: 
![image](https://user-images.githubusercontent.com/13042488/127797712-24e6deb5-5803-4a38-9f0d-b16d6375c388.png)

which could probably be used in some fashion (via query params like `?label=due`, etc.).

If that won't work for you, then I think you'd be better suited to leverage our custom Endpoint badge (https://shields.io/endpoint) that will allow you to define whatever color tiers you want. I think there'd be way too much subjectivity around the color tiers for something like an "on track" indicator for us to be able to incorporate this as a native badge.

**Comment by MacHu-GWU** [comment]
Hi @calebcartwright, thank you for your great snippet,

However, the one you offered doesn't change color based on ``time left``. Let's say a company use 2 weeks sprint. Then if 10 days left, color = green, 7 days left color = yellow, 3 days left color = orange, 0 days = over due.

**I create an AWS Lambda based custom endpoint server**, source code [here](https://github.com/MacHu-GWU/due_date_shields_io_badge-project/blob/main/app.py)

Here's some example with my custom endpoint:

Let's say today is 2021-08-01, then:

- in TWO WEEKS preset, due date = 2021-08-14 (13days left out of 2 weeks): https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-14 = ![](https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-14)
- in TWO WEEKS preset, due date = 2021-08-08 (7days left out of 2 weeks): https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-09 = ![](https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-09)
- in TWO WEEKS preset, due date = 2021-08-04 (3days left out of 2 weeks): https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-04 = ![](https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-08-04)
- in TWO WEEKS preset, due date = 2021-07-30 (overdue): https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-07-30 = ![](https://img.shields.io/endpoint?url=https://serp220j92.execute-api.us-east-1.amazonaws.com/api/2w/2021-07-30)

Of course, in my implementation, there are many preset are provided:

- ``1d`` = 1 day
- ``3d`` = 3 days
- ``1w`` = 7 days
- ``2w`` = 14 days
- ``1m`` = 30 days
- ``2m`` = 60 days
- ``3m`` = 90 days

**Comment by calebcartwright** [comment]
> However, the one you offered doesn't change color based on time left

Yes, I am aware :wink: That's why I suggested using the Endpoint badge for the flexibility around colors.

As stated in my prior response, the time periods and associated color scale are going to be highly personal to each individual user/team. Your endpoint and selected time periods/colors obviously work well for your personal use case, but those aren't ubiquitous and I don't see any way we could provide a native badge that would be sufficiently flexible to handle the variadic needs of everyone.

It's great that you've already got your use case solved with your own Endpoint badge and I could envision that type of Endpoint  being a good reference for others wanting something along the same lines, so you may want to consider a PR to add your endpoint to the [Awesome List](https://github.com/badges/awesome-badges).

Will wait a bit to see if any other maintainers feel differently, but I move that we close this issue, especially since you already have an operational Endpoint badge functioning.

**Comment by MacHu-GWU** [comment]
thank you. We can close it. Actually there are some existing badge similar to this use case, the pypi ( python package index) monthly weekly daily downloads badge. Shields io provides several preset like /dm, /dw, /dd (download daily).

In this use case, I think we can easily parameterize it like /duedate/${due_date}/${period_days} then you only need to implement one end point to adapt anybody's needs.

With this, developer can use markdown for project management without using JIRA, Trello, GitHub projects as flexible as they want.

Actually it is not my personal use case. it is a common use case because you can find enumerous people asking "how could I add due date in markdown / GitHub issues. " They just don't know shields io can solve this problem easily.

**Comment by calebcartwright** [comment]
I appreciate your interest and passion for your requested badge, but I feel like you're trying to pull me into a debate without actually reading my previous comments. That's not an effective use of either of our time and not something I'm keen on continuing.

As I've stated a few times, and will repeat for one final time, project management/status tracking is incredibly personal and subjective. There is no universally accepted set of time periods for projects, nor is there an accepted measure for what is/isn't on track relative to an approaching due date, and accordingly there is no universal color scheme we could project onto such nonexistent things.

> Actually it is not my personal use case. it is a common use case because you can find enumerous people asking "how could I add due date in markdown / GitHub issues. " They just don't know shields io can solve this problem easil

That's not what I said at all. You've defined a set of time periods and associated color scale in your endpoint badge that's meaningful to _you_. That's perfectly valid, but what's meaningful to you isn't necessarily meaningful, or at least doesn't carry the same meaning, to another team or another project. One developer could want the badge to still be green if there's seven days left into a 14 day period, a different one could want the badge to be orange if there's 4 days left (and another team could say red, etc.). Another team could want a 5 day based period, another a 3 week based period, etc. Those are each perfectly valid as well, because it's all about their respective context which varies widely across the software development discipline. We can't just use pick an arbitrary set of dates/colors, such as the ones you've proposed, and call those "right".

In order for Shields to provide a native badge that would be useful for everyone across all contexts, the badge would have to accept an open ended set of route/query parameters so that users could provide _their_ desired time periods and the associated color scale. That's just not feasible. 

> Actually there are some existing badge similar to this use case, the pypi ( python package index) monthly weekly daily downloads badge. Shields io provides several preset like /dm, /dw, /dd (download daily).

Again, as the maintainers of Shields we're pretty familiar with the product :wink: The download badges with intervals are completely different. They are simply a filter based on a set of common time periods that many, but not all, of the upstream services/vendors provide for their download status.

Those badges answer questions like "how many times has X been downloaded this week" which has an objective, factual answer. Conversely, the types of questions associated with the badge you've proposed are more like "is this on track for the specified due date", which can only ever have an explicitly subjective answer.

We completely understand the benefits of being able to have badges for those types of subjective cases/questions, and that's one of the many reasons why we provide the Endpoint badge so that users _are_ able to use our platform to make those badges. However, we can't natively incorporate something that subjective and that open ended which cannot feasibly be bound/configured via badge parameters.

**Comment by MacHu-GWU** [comment]
@calebcartwright  not at all to debate. I totally understand from a productive perspective, it is not a "high value" feature. **I apology that my bad english giving you this impression**.

**Comment by MacHu-GWU** [comment]
I closed this issue. Anyone see this discussion feel free to borrow the code to implement your own dynamic endpoint server.

Thanks again for the wonderful project @calebcartwright

**Comment by calebcartwright** [comment]
> @calebcartwright not at all that about debate. I totally understand from a productive perspective, it is not a "high value" feature. I apology that my bad english giving you this impression.

No worries @MacHu-GWU, probably just some miscommunication. I do want to stress that it's not a matter of whether a due date badge is valuable (it certainly is!), it's just that it's so custom and personal that the best implementation/solution is an Endpoint badge.

> Anyone see this discussion feel free to borrow the code to implement your own dynamic endpoint server.

Excellent, thank you for sharing! I wouldn't be surprised at all if other users find themselves wanting a similar (but slightly different) type of status tracking badge, and I think yours will serve as a useful example to others.
