### ISSUE TITLE
Docker version tag doesn't work with `arm64` images

### ISSUE THREAD

**Issue by joelhoisko** [badges/shields#6853]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm trying to use the "Docker Image Version (tag latest semver)" from shields.io on an `arm64`  architecture image. The resulting badge gives a "digest not found for given tag", even though [there is digest](https://hub.docker.com/layers/dolittle/runtime/6.1.0-arm64/images/sha256-4563cd5e1c6d20d2575656a67f9d5dab23e57a9dadb01075d0b6a9c5b1659045?context=explore) for it on Docker hub.

Just in case my image would be broken, the same thing happens for MongoDB's arm64 badge: https://img.shields.io/docker/v/arm64v8/mongo/latest

### 🔗 Link to the badge

https://img.shields.io/docker/v/dolittle/runtime/6.1.0-arm64

### 💡 Possible Solution

Looking into this, one old issue mentioned something regarding this https://github.com/badges/shields/issues/4904#issuecomment-613742586 and how it used to default to `amd64` architecture. Looking at the [current code](https://github.com/badges/shields/blob/37e83641abe980ee587696d06becf024d023b273/services/docker/docker-version.service.js#L91), it supports multiple architectures but it still defaults to `amd64` if nothing else is defined. So this could be about how shields.io handles setting that particular value.

**Comment by calebcartwright** [comment]
You need to use the `arch` parameter in cases where you either want to use a different architecture or where there aren't any amd64 images
https://img.shields.io/docker/v/dolittle/runtime/6.1.0-arm64?arch=arm64
![](https://img.shields.io/docker/v/dolittle/runtime/6.1.0-arm64?arch=arm64)

We have to default to _something_, and the x86 64 bit target was the most sane default. However, we subsequently added the `arch` parameter because as noted in the prior issues you referenced as well as the case at hand, it's definitely not always the desired behavior
