### ISSUE TITLE
Telegram - Join Us

### ISSUE THREAD

**Issue by iamWitchKing** [badges/shields#6905]
:clipboard: **Description**
plz add badges for telegram Join Us
plz add badges Witch King Hacker @iamWitchKing
thank you

:link: **Data**

:microphone: **Motivation**

**Comment by calebcartwright** [comment]
I'm going to close this, partly because the issue form data was not included and partly because the ask seems to be for a static badge specific to your handle/channel/etc.

You can use the static badge to build whatever you want:
https://shields.io/#your-badge
https://img.shields.io/badge/join%20us-Witch%20King%20Hacker-blue
![](https://img.shields.io/badge/join%20us-Witch%20King%20Hacker-blue)
and use standard markdown/markup syntax to make the badge navigable as needed

Feel free to follow up with the requisite information requested as part of the issue form for new badges if I've misunderstood, and we'll reopen if there's a real badge request.

**Comment by iamWitchKing** [comment]
Thank you

**Comment by iamWitchKing** [comment]
𝙷𝚎𝚕𝚕𝚘, 𝙸 𝚍𝚎𝚟𝚎𝚕𝚘𝚙𝚒𝚗𝚐 𝚂𝚝𝚛𝚘𝚗𝚐𝚑𝚘𝚕𝚍 𝙲𝚛𝚞𝚜𝚊𝚍𝚎𝚛 𝚅𝚒𝚍𝚎𝚘 𝙶𝚊𝚖𝚎 𝚆𝚒𝚗𝚍𝚘𝚠𝚜 𝙿𝚕𝚊𝚝𝚏𝚘𝚛𝚖. 𝚒𝚏 𝚊𝚗𝚢𝚘𝚗𝚎 𝚕𝚒𝚔𝚎 𝚝𝚑𝚒𝚜 𝚐𝚊𝚖𝚎 𝚘𝚛 𝚠𝚊𝚗𝚝 𝚝𝚘 𝚊𝚝𝚝𝚎𝚗𝚍 𝚝𝚘 𝚑𝚎𝚕𝚙 𝚒𝚖𝚙𝚛𝚘𝚟𝚎 𝚝𝚑𝚒𝚜 𝚐𝚊𝚖𝚎 𝚌𝚊𝚗 𝚌𝚘𝚗𝚝𝚊𝚌𝚝 𝚖𝚎 𝚋𝚢 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 𝙼𝚎𝚜𝚜𝚎𝚗𝚐𝚎𝚛 𝙸𝙳 𝚄𝚜𝚎𝚛𝚗𝚊𝚖𝚎: @𝚒𝚊𝚖𝚆𝚒𝚝𝚌𝚑𝙺𝚒𝚗𝚐
And also 𝚌𝚊𝚗 𝙹𝚘𝚒𝚗 𝚖𝚢 𝙼𝚊𝚒𝚗 𝙲𝚑𝚊𝚗𝚗𝚎𝚕 𝚗𝚎𝚠𝚜 𝚊𝚋𝚘𝚞𝚝 𝚖𝚢 𝙰𝚌𝚝𝚒𝚟𝚒𝚝𝚢 𝚘𝚗 𝚝𝚑𝚎 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 𝙲𝚑𝚊𝚗𝚗𝚎𝚕 𝚝𝚘 𝙰𝚍𝚍𝚛𝚎𝚜𝚜 𝚕𝚒𝚗𝚔: @𝙰𝚙𝚙𝚜𝙰𝚕𝚏𝙰
