### ISSUE TITLE
Support dynamic badge plain string responses

### ISSUE THREAD

**Issue by pke** [badges/shields#6987]
At least for json a string response (wrapped in quotation marks) should be selectable by the query argument.

The service returns `"text"` and that should be the label when using `$` as jsonpath selector.
Currently the badge errors out with: "needs to be object or array"

Maybe a general fallback could be to render as label what the service returns (200 OK) (excluding multi line responses).

**Comment by calebcartwright** [comment]
It's not entirely clear what you're saying, and I think some real examples would be illuminating.

However, if you're in need of a badge where upstream service  isn't well formed/isn't queryable, then you may want to consider taking a look at the [Custom Endpoint Badge](https://shields.io/endpoint) instead

**Comment by chris48s** [comment]
In JSON, a single literal value is technically valid JSON. e.g:

```js
> JSON.parse('"abc"')
'abc'

> JSON.parse('1')
1
```

so I think the feature request here is that this should be parseable by the dynamic JSON badge.

The thing is, although we throw the error here https://github.com/badges/shields/blob/1b871a97b450d54e82b71f444930ae8533c06142/services/dynamic/json-path.js#L46-L52 this is really a feature or limitation (depending on how you look at it) of the jsonpath library we use https://github.com/dchester/jsonpath which we've inherited, rather than a choice we have explicitly made

```
> const jp = require('jsonpath');

> jp.query("text", '$')
Uncaught AssertionError [ERR_ASSERTION]: obj needs to be an object
...
```

**Comment by pke** [comment]
Exactly, @chris48s thanks for doing my work of explaining the issue thoroughly myself ;)
You hit every point I would have made plus you added some insights into the library. 
The service in question returns a version string `"1.2.3"`, which is as you explained @chris48s, valid JSON.
The website https://jsonpath.com/ can also evaluate it just fine.

Would it be possible to switch out the JSON Path library?

**Comment by paulmelnikow** [comment]
Out of curiosity, what is the service?

**Comment by chris48s** [comment]
In principle I don't think we're married to https://github.com/dchester/jsonpath specifically.

In practice, my concern in adopting a new lib would be compatibility for existing users. There are a lot of existing dynamic json badges out there in the wild.  Of course, in principle JSONPath is JSONPath but if there are any minor differences in the implementation between the 2 libs there is the potential to cause a breaking change for existing users with no warning. I'd want to have a high level of confidence that isn't going to happen in order to commit to a switch (and that is a non-trivial thing to be sure of).

**Comment by pke** [comment]
> Out of curiosity, what is the service?

An internal private service of a company. They can't easily change the returned value, as it would break other contracts. Does shields request a particular content-type maybe? I couldn't see any specific `Accept` header on the requests. The `User-Agent` is shields but could the service rely on that?

**Comment by pke** [comment]
@chris48s I understand your back compatibility concerns. 

Kind of sad, that while JSONPath seems to be a standard, one has to worry to switch out a faulty library with a working one because who knows which other quirks this faulty library has hidden underneath.

One non-breaking change I would like to propose:
Instead of throwing an "invalid response" exception lets give another lib a try with the response instead. That way **all** the old badges still work because they never hit this code-path (in the past) and only responses that are potential valid JSON (but miunderstood by the current JSON Path lib) would be handed to the new, more compatible lib. It would mean another dependency on an external package though.

What do you guys think?

**Comment by calebcartwright** [comment]
I'm still not 100% convinced that the dynamic badge is the best fit for this scenario, and am not terribly keen on having to swap out the underlying lib and all the uncertainties that would entail, nor having to utilize two separate jsonpath libs for this one use case.

Functionally, this feels very much like a "get badge message from string" use case which I'd again suggest could be handled today pretty easily via a custom Endpoint badge, or perhaps even as its own standalone badge. Why have the complexity in route, code, and processing for querying something that doesn't need to be queried, as we would in the dynamic json/jsonpath approach?

**Comment by chris48s** [comment]
> one has to worry to switch out a faulty library with a working one because who knows which other quirks this faulty library has hidden underneath

I think this is probably a bit of a stretch to blanket label one implementation "faulty" and one "working". As this comparison table show https://cburgmer.github.io/json-path-comparison/ there is some room for manoeuvre in the spec and every JSONPath library (including JSONPath-Plus) comes with its own selection of quirks.

**Comment by pke** [comment]
> Why have the complexity in route, code, and processing for querying something that doesn't need to be queried, as we would in the dynamic json/jsonpath approach?

We don't know how many endpoints where changed just because shields JSON parser was unable to parse a valid JSON response properly.

So instead of slightly modifying an existing endpoint, which would work just fine with the `$` query and an alternative jsonpath lib instead of throwing an exception, you rather would introduce a new route, code and processing?

Sure its your project and I love it for what it does. That's why I didn't implement an `image/svg` response on the endpoint but rather used shields directly. 
But this little limitation (caused by a somewhat-working JSONpath implementation) already has me on the edge of deploying a jq lambda function to pipe the shields request through ;)
`https://img.shields.io/badge/dynamic/json?query=%24&url=https://json.stream/shields.io/https://faulty-response-server`

Maybe I should really add an `image/svg` response which would just redirect to the standard shield plain text badge composer.

**Comment by calebcartwright** [comment]
> We don't know how many endpoints where changed just because shields JSON parser was unable to parse a valid JSON response properly.
>
> So instead of slightly modifying an existing endpoint, which would work just fine with the $ query and an alternative jsonpath lib instead of throwing an exception, you rather would introduce a new route, code and processing?

I appreciate that you might be frustrated by the current state of affairs, but let's tone down the sarcasm as it isn't very constructive.

Yes, as I said previously, I do think it's worth considering a new Dynamic* badge if we want to support this natively.

Please keep in mind that we're not starting from a clean slate here. We're regularly serving up more than 100k dynamic json badges per day and we have to be careful and thoughtful about any change that impacts, or has the potential to impact, our existing users. Swapping out the jsonpath lib absolutely carries a non-zero risk of impacting our existing users, so that's not something we're going to stumble into haphazardly.

Additionally, I don't think trying to interoperate between two jsonpath libs is a good idea for us either, especially when it comes to ongoing maintenance and troubleshooting, all to support a jsonpath query for something that doesn't actually need to be queried.

When I speak about the route, I'm really talking about the user experience and the corresponding badge urls. I'm not sure why we'd want to force users to provide a `?query=$` which we then run through a jsonpath processor, all for what was a literal value to begin with. Trying to do that with the current jsonpath lib (for BC), which we know will throw an exception, only to then go and do again with a second jsonpath path lib, or having to inspect the response data and query contents to conditionally select the lib to use, all seem like unnecessary runtime churn to me.

It takes very little code (typically tens of lines) to make a service class, so yes, I absolutely think a separate class/handler has the potential to be a better option which would make for a cleaner badge route, avoids extra runtime work in our environment, and avoids the risk of having to switch out the existing lib, especially since we could easily augment our docs to help point folks to it should they find themselves in a similar situation.

**Comment by pke** [comment]
Perfectly understanding the reasoning here.
I think I will just add a little proxy route to make it work for now with the json endpoint.

And since I do not want to redirect attention away from more important bugfixes & features, I will close this issue. When the new endpoint is implemented eventually a little note into this issue would be appreciated.

Thanks again for this great service!

**Comment by chris48s** [comment]
Circling back to an old issue here, but it came up on discord. Although our JSONPath lib requires an object, an endpoint that just returns a literal value will work with the dynamic XML badge, so `https://img.shields.io/badge/dynamic/xml?query=/text()&url=...` can be used in this case. H/T to @RedSparr0w for this one :tophat:
