### ISSUE TITLE
Invalid Response Data for Reddit Karma Badge

### ISSUE THREAD

**Issue by sahrohit** [badges/shields#6991]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Even though **imadeyoureadthis26** is a valid Reddit username, the badge is giving out **Invalid Response Data**. I tried with my friend's username, it seems to work fine. 

Badge for my Username : 
![image](https://img.shields.io/reddit/user-karma/combined/imadeyoureadthis26?style=for-the-badge)
https://img.shields.io/reddit/user-karma/combined/imadeyoureadthis26?style=for-the-badge

Badge for my Friends Username : 
![image](https://img.shields.io/reddit/user-karma/combined/avin_timilsina?style=for-the-badge)
https://img.shields.io/reddit/user-karma/combined/avin_timilsina?style=for-the-badge

Here is a picture of my Reddit profile with a visible username.
![image](https://user-images.githubusercontent.com/63448670/132333096-19d09594-bcc3-4054-b464-f7f80872e282.png)

Here is a picture of shield io with "Invalid Response Data"
![image](https://user-images.githubusercontent.com/63448670/132333132-4247e46b-4a2a-4fb8-bebe-398d603c3848.png)

### 🔗 Link to the badge

https://img.shields.io/reddit/user-karma/combined/imadeyoureadthis26?style=for-the-badge

### 💡 Possible Solution

This might be the problem with my username.

**Comment by calebcartwright** [comment]
That's because our API schema validation made the apparently incorrect assumption that the karma values would be 0 or greater, whereas you've got a `comment_karma` value of -20

https://www.reddit.com/user/imadeyoureadthis26/about.json

This should be an easy fix by changing the type from `nonNegativeInteger` to `anyInteger` (which would need to be imported from `validators`)

https://github.com/badges/shields/blob/1b871a97b450d54e82b71f444930ae8533c06142/services/reddit/user-karma.service.js#L6-L11

**Comment by chris48s** [comment]
closed in #6992
