### ISSUE TITLE
PowerShell Gallery: Number of downloads for a module version

### ISSUE THREAD

**Issue by tenthirtyam** [badges/shields#7011]
:clipboard: **Description**

Today, `/powershellgallery/dt/:packageName` provides the **total** number of downloads for a module. There are instances where one might want to pull the number of downloads for the total, latest, or specif version.

Something like:

- `/powershellgallery/dt/:packageName` for total
- `/powershellgallery/dt/:packageName/tatest` for latest version
- `/powershellgallery/dt/:packageName/2.0.0` for a speciifc version

:link: **Data**

Not sure. 🤷🏻‍♂️ 

:microphone: **Motivation**

With each new release of a module, it would be nice to pull the statistics for the new version and across prior versions.

**Comment by calebcartwright** [comment]
I appreciate how that can be beneficial, and that's why many of our badges support that type of filtering/granularity. However, we're ultimately constrained to whatever data the upstream systems of records make available.

If this is something you (or anyone else from our community) would like to see implemented then we'd first need someone to do the work of figuring out what's possible from an API availability perspective.

**Comment by tenthirtyam** [comment]
Self closing.
