### ISSUE TITLE
MathWorks MATLAB answers user statistics

### ISSUE THREAD

**Issue by smamusa** [badges/shields#7038]
:clipboard: **Description**

Which service is this badge for : **MATLAB Answers user profile**

What sort of information should this badge show : 
* RANK
* REPUTATION
* CONTRIBUTIONS
  - Questions
  - Answers
* ANSWER ACCEPTANCE
* VOTES RECEIVED 

:link: **Data**

The data can be scraped from MATLAB user profiles such as [mine](https://www.mathworks.com/matlabcentral/profile/authors/21973659)
I've made a simple PoC [here ](https://github.com/smamusa/mystats-api/blob/main/index.js)
It uses Express.js simple endpoints and scrapes the profile page, then parses the HTML with RegEx

:microphone: **Motivation**

This would be used on developers GitHub profile (README.md) together with other stats such as StackOverflow reputation, GitHub statistics etc.

This would also include **File Exchange** and **Cody** statistics

**Comment by chris48s** [comment]
Hi. Thanks for the suggestion. but unfortunately looking at your proof-of-concept this would not be a suitable contribution for shields.io. As noted in https://github.com/badges/shields/blob/7d452472defa0e0bd71d6443393e522e8457f856/CONTRIBUTING.md#badge-guidelines

> Badges should not obtain data by scraping web pages - these are likely to break frequently. Whereas API publishers are incentivised to maintain a stable platform for their users, authors of web pages have no such incentive.

Feel free to re-open if there is a way of getting this data from an API or structured data source.

That said, it looks like you've already built an API endpoint that can be used with the [endpoint badge](https://shields.io/endpoint) so that's probably the best solution if you want to maintain the scraper.

**Comment by smamusa** [comment]
Ah, I misunderstood it then. No problem, I will do some work on my scraper and continue to use it with the endpoint badge. Thank you for the response.
