### ISSUE TITLE
Link directly to builder modals

### ISSUE THREAD

**Issue by chris48s** [badges/shields#7064]
:clipboard: **Description**

It would be really nice if the builder modal for each badge had its own URL. So for example if I wanted to link someone straight to

![Screenshot at 2021-09-25 16-09-25](https://user-images.githubusercontent.com/6025893/134776257-f89baccc-fbd9-4041-a888-63bc73f0c93e.png)

I could use https://shields.io/category/build#appveyor/build or https://shields.io/builder/appveyor/build or something (exact implementation details TBD) and that would load the site with that builder modal open.

**Comment by paulmelnikow** [comment]
Agree this would be a good idea. Lots of possibilities there. Something like https://shields.io/appveyor/build would be pretty cool, though maybe something like https://shields.io/builder/appveyor/build or https://shields.io/services/appveyor/build would be safer. Should definitely be thoughtful about these links since we want them to work permanently.

To accomplish this, we may want to also address the changes I was proposing in #3174, which involved combining multiple variants for the same badge into a single popup.

**Comment by chris48s** [comment]
Yeah we probably do need to this through properly if we are going to do something that adds a lot of routes to the frontend given the frontend and service badges share a single URL namespace.
We've already got ourselves into a pickle with `endpoint`.

**Comment by chris48s** [comment]
This is solved. Every badge documentation/builder page now has its own URL e.g: https://shields.io/badges/circle-ci
