### ISSUE TITLE
Matrix badge: room is not world readable or is invalid

### ISSUE THREAD

**Issue by Granitosaurus** [badges/shields#7107]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

For some reason matrix shield throws error "room is not world readable or is invalid" when referring to new/small rooms such as: https://matrix.to/#/%23web-scraping:matrix.org

What could be the cause of this?

### 🔗 Link to the badge

https://img.shields.io/matrix/web-scraping:matrix.org

**Comment by calebcartwright** [comment]
That's the result of the upstream endpoint returning a 403 response. There's apparently a good amount of setup/configuration required in order to get the badges working, detailed in our inline badge builder window for the Matrix badge (shown below). Have you followed all those steps?

![image](https://user-images.githubusercontent.com/13042488/136643533-45cced11-d53a-41dc-b12c-8703086527c8.png)
