### ISSUE TITLE
PyPi just removed download statistics

### ISSUE THREAD

**Issue by awnumar** [badges/shields#716]
The issue where it happened is here: https://bitbucket.org/pypa/pypi/issues/396/download-stats-have-stopped-working-again

You can visit any PyPi package to confirm.

**Comment by espadrine** [comment]
I'll leave the badges; they'll be converted to warehouse when it is done.

**Comment by libeclipse** [comment]
Converted to warehouse?

**Comment by espadrine** [comment]
Re: warehouse, I am not knowledgeable, I merely read [this comment](https://bitbucket.org/pypa/pypi/issues/396/download-stats-have-stopped-working-again#comment-27789841).

> all the developers are working on warehouse, the successor of PyPI

**Comment by libeclipse** [comment]
Ah. I'll leave this issue open then, unless you wish to close it.

**Comment by jab** [comment]
It looks like it might be possible to fix this without having to wait for PyPI to be migrated to the new site. Looking at [one of my libraries](https://pypi.io/project/bidict/#statistics) on the new site, it is pulling statistics in line with what I'd expect (5k/month):
![screen shot 2016-06-19 at 11 59 18](https://cloud.githubusercontent.com/assets/64992/16178536/19f90d80-3619-11e6-99b6-a46ac0673b3f.png)

My shields.io badge currently says 2/month: https://img.shields.io/pypi/dm/bidict.svg

Hopefully someone can look into how hard it would be to switch shields.io to using this other source for PyPI stats (including me if no one beats me to it).

**Comment by libeclipse** [comment]
Nope those statistics are false. Warehouse hasn't added stats yet.

**Comment by jab** [comment]
Derp, you're right, looks like it shows the same numbers no matter [what](https://pypi.io/project/requests/#statistics) [project](https://pypi.io/project/Flask/#statistics) [you](https://pypi.io/project/Werkzeug/#statistics) [try](https://pypi.io/project/Jinja2/#statistics). (Too bad they don't put "TODO" there instead of misleading fake numbers.)

I guess for now I'll just comment out my downloads badges, which are currently showing bogus, pitiful download counts, unless some better workaround is possible. (For example, there's no way to get at the most recent accurate number, is there?)

**Comment by joeyespo** [comment]
Sounds like the stats from Warehouse should be usable now: https://github.com/pypa/pypi-legacy/issues/396#issuecomment-237621141

**Comment by libeclipse** [comment]
As far as I can tell, there are no stats at warehouse anymore.

**Comment by libeclipse** [comment]
A workaround to access statistics: https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html

**Comment by idlesign** [comment]
Legacy JSON API of interest is and will probably be available at https://pypi.org/pypi/{package_name}/json
Yet download counters are zero for now.

**Comment by hugovk** [comment]
Any news/progress on fixing PyPI downloads badges?

**Comment by espadrine** [comment]
AFAIK, the only way to do it currently is through https://bigquery.cloud.google.com/dataset/the-psf:pypi, but it's non-trivial (nor free of charge), and the generic table is empty, we have a separate table for every day, so that we can't simply do:

```sql
SELECT count(*)
FROM [the-psf:pypi.downloads]
WHERE file.project = 'bidict'
AND timestamp > DATE_ADD(CURRENT_DATE(), -1, "MONTH");
```

**Comment by joernhees** [comment]
just a suggestion: instead of "downloads: 0" maybe write "downloads: -1" or "downloads: defunct"?

**Comment by paulmelnikow** [comment]
That's a great idea @joernhees. Would you, or anyone else, like to open a pull request?

**Comment by joernhees** [comment]
i think it will take you about as long as it took you to write that, but it would take me a lot longer to find the right place... please fix this yourself, it's very likely commenting out whatever is there now and hard returning a string that won't embarrass a whole lot of projects.

**Comment by joernhees** [comment]
no clue what just happened...

**Comment by joernhees** [comment]
everyone is doing this in their free-time, so let's be efficient about it... this also means that you as one of the maintainers should know about your efficiency advantage over outsiders who would first have to get to know your guidelines, code, CI setup, etc... you could easily have quick-fixed this in the time it took you to reply to me. Please do so instead of making me jump artificial hoops you invented.

**Comment by espadrine** [comment]
Don't worry, we're not expecting you to do it if you have no time! Given the amount of patches, maintainers tend to focus more on reviewing and helping others hop on board than on performing fixes themselves.

**Comment by joernhees** [comment]
from one maintainer to another: thanks and apologies for getting grumpy

**Comment by paulmelnikow** [comment]
This issue isn't a bug anymore so I removed that label.

Should we close it?
