### ISSUE TITLE
Undefined number of commits since

### ISSUE THREAD

**Issue by twhite96** [badges/shields#719]
Using the GitHub commits-since badge shows undefined number of commits. Not sure how to edit the badge. Here is my code: 

`[![GitHub commits](https://img.shields.io/github/commits-since/twhite96/address-book-demo/0.1.svg?maxAge=2592000)](https://github.com/twhite96/address-book-demo)`

**Comment by twhite96** [comment]
Found the answer. Will close this now.

**Comment by AkashGutha** [comment]
can you please share the solution? 
having similar problems

**Comment by qzb** [comment]
I'm not sure, but I guess that @twhite96 just changed version number to valid one: [img.shields.io/github/commits-since/twhite96/address-book-demo/**0.**0.1.svg](https://img.shields.io/github/commits-since/twhite96/address-book-demo/0.0.1.svg)

To make this badge work make a tag in you repository and specify it in badge's path:
`https://img.shields.io/github/commits-since/<user>/<repo>/<tag>.svg`

**Comment by AkashGutha** [comment]
Do you know any place to proper documentation.. because I didn't find it in github
