### ISSUE TITLE
wordpress downloads service tests failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#7356]
:clock11: **When did the problem start?**

5 days ago

:camera: **Live badge**

![](https://img.shields.io/wordpress/plugin/dm/100)

this looks sensible until you realise the crucial detail: is not a real wordpress plugin

:wrench: **Is the live badge working?**

Kinda. It definitely returns _some numbers_ for a valid plugin, but also returns some numbers for plugins that definitely don't exist so who knows if they are right. Seemingly whatever slug I give this API it gives us some numbers back

https://api.wordpress.org/stats/plugin/1.0/downloads.php?slug=100
https://api.wordpress.org/stats/plugin/1.0/downloads.php?slug=definitely-not-a-real-plugin
https://api.wordpress.org/stats/plugin/1.0/downloads.php?slug=sadikovtdjoiybvjtdoivgrdjashc

These are definitely not real wordpress plugin names.

:link: **CircleCI link**

example:
https://app.circleci.com/pipelines/github/badges/daily-tests/1381/workflows/efbc35ec-6526-4fe6-9e68-9740a51293a3/jobs/2283/tests#failed-test-17

:lady_beetle: **Stack trace**

```
AssertionError: message mismatch: expected '35/week' to equal 'plugin not found or too new'
    at Function._expectField (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:70:51)
    at IcedFrisbyNock.<anonymous> (file:///home/circleci/project/shields/core/service-test-runner/icedfrisby-shields.js:55:26)
    at IcedFrisbyNock.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:954:10)
    at invokeNextHook (node_modules/icedfrisby/lib/icedfrisby.js:1003:24)
    at /home/circleci/project/shields/node_modules/icedfrisby/lib/icedfrisby.js:1017:7
    at new Promise (<anonymous>)
    at IcedFrisbyNock._runHooks (node_modules/icedfrisby/lib/icedfrisby.js:976:12)
    at IcedFrisbyNock.run (node_modules/icedfrisby/lib/icedfrisby.js:1276:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (node_modules/icedfrisby/lib/icedfrisby.js:1348:9)
```

:bulb: **Possible solution**

I can't begin to fathom what manner of terrible thing has happened here, but I'm pretty sure the problem is is upstream and there's not much we can do about it.

**Comment by PyvesB** [comment]
I've opened a bug report with Wordpress: https://core.trac.wordpress.org/ticket/54989#ticket

**Comment by PyvesB** [comment]
I got some responses from the Wordpress team. Here's a summary of what I've understood:
* the endpoint does seemingly respond with valid numbers for valid slugs.
* returning sane-looking data for invalid slugs is by design. Apparently this is meant to prevent DDOS attacks. I'm not exactly sure how as no further information was given, and I would've expected their other API endpoints to also use this so-called DDOS protection, which is not the case.
* the [public-facing documentation](https://codex.wordpress.org/WordPress.org_API) is not meant for public use. This is not mentioned anywhere, and consequently all our Wordpress badges have unfortunately ended up using unsupported APIs intended for internal Wordpress services only. I came across forum posts from years ago where others got caught out by this; they had asked Wordpress to add a warning to the documentation, but this suggestion was rejected. I'm not exactly sure why Wordpress is so keen on misleading people to use an API they don't want them to use.
* the `/1.0` bit in the path is not actual API versioning, the response format may change independently of the version number.
* the downloads API may change without notice or get removed completely.
* Wordpress claim that metrics, amongst which download counts, offer no user value. They have no intention of providing any supported API alternatives.

I can't say I'm impressed by some of the obnoxious, contradictory, and absurd answers I received. This is quite disappointing given that we basically  provide and maintain a bunch of Wordpress badges for them at no cost.

Moving forward, unless someone wants to go down a different route, I'll delete failing tests, remove the bit of logic that was checking for a download number equal to 0, and add a warning to the badge builder documentation; something along the lines of "double-check you're using the correct slug and bear in mind that these badges may break at any time in the future".

**Comment by calebcartwright** [comment]
> I can't say I'm impressed by some of the obnoxious, contradictory, and absurd answers I received. This is quite disappointing given that we basically provide and maintain a bunch of Wordpress badges for them at no cost.
>
> Moving forward, unless someone wants to go down a different route, I'll delete failing tests, remove the bit of logic that was checking for a download number equal to 0, and add a warning to the badge builder documentation; something along the lines of "double-check you're using the correct slug and bear in mind that these badges may break at any time in the future".

That's disappointing indeed. Thanks for driving this, I concur with your suggested path forward :+1:

**Comment by chris48s** [comment]
Well done for persevering with that
