### ISSUE TITLE
Badge request: GitLab License

### ISSUE THREAD

**Issue by DaRubyMiner360** [badges/shields#7371]
It would be useful to have the ability to see the license from the README of a GitLab repository. You can already do it with GitHub, after all.

Example:
![License](https://img.shields.io/badge/license-MIT-green)

There is a public API with an API token and it's already used for other GitLab badges.

**Comment by calebcartwright** [comment]
Thanks for the suggestion!

> You can already do it with GitHub, after all.

Want to note that just because a badge exists for service Foo doesn't make a similar badge automatically come into existence for some other service Bar :wink:

In order for a badge to be added someone has to actually add the code for it, and that doesn't typically happen unless and until someone asks for it. There's also a rather lengthy history with added GitLab badges that was concluded in https://github.com/badges/shields/issues/541#issuecomment-919580720.

> There is a public API with an API token and it's already used for other GitLab badges.

Please do the work to gather the details/link on the API as requested in the issue template, and then either update your issue description with that info or include it in a follow up comment. The more information and actionable you make the issue the greater the chance that someone will work on it.

**Comment by sunny0826** [comment]
Maybe I can contribute this part of the code. @calebcartwright Can you assign this Issue to me?

**Comment by chris48s** [comment]
bit late closing the issue, but this was added in #8024
