### ISSUE TITLE
Website: 301 code status say page down

### ISSUE THREAD

**Issue by Shirobachi** [badges/shields#7375]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

If some page make redirect them IMO page's up, your badges say down in that situation.

### 🔗 Link to the badge

#301: ![](https://img.shields.io/website?url=https%3A%2F%2Fapi.hryszko.dev%2F)
#200: ![](https://img.shields.io/website?url=https%3A%2F%2Fapi.hryszko.dev%2Fdocs)

**Comment by calebcartwright** [comment]
Thank you for reaching out but I'm going to close as the claim is incorrect. We use the HEAD method and treat all response codes less than 310 as success, but your first endpoint (https://api.hryszko.dev/) is returning a 405 because it doesn't support head requests. If you'd like to use our badge then I'd encourage updating your config to support the method

https://github.com/badges/shields/blob/86895cf25679ff775b85dd1e19188174acdc3bb5/services/website/website.service.js#L92


```
$ curl -I https://api.hryszko.dev/
HTTP/2 405 
server: nginx/1.18.0 (Ubuntu)
date: Wed, 15 Dec 2021 16:52:54 GMT
content-type: application/json
content-length: 31
```

**Comment by Shirobachi** [comment]
Thanks for that information, I am new user, so I checked it via `curl api.hryszko.dev` 

Thank you very much for explanation!

**Comment by calebcartwright** [comment]
No worries!
