### ISSUE TITLE
If necessary, add a plus sign `+` to the right of the number of users in the chrome web store

### ISSUE THREAD

**Issue by lmk123** [badges/shields#7400]
:clipboard: **Description**

When the number of users of the chrome extension exceeds 100,000, the icon does not show the plus sign `+` on the right side.

For example, [this extension](https://chrome.google.com/webstore/detail/ikhdkkncnoglghljlkmcimlnlhkeamad) has more than 200,000 users, but the icon only shows `200k`:

![](https://img.shields.io/chrome-web-store/d/ikhdkkncnoglghljlkmcimlnlhkeamad.svg)

It would be more accurate to show `200k+`

**Comment by calebcartwright** [comment]
Thanks for sharing your suggestion, but I'm going to close this.

The way we display our metrics is intentional, and is not something we're going to change. While at the lower quantities the precise value is more relevant (e.g. 27 users vs 34 users), at higher quantities the relative differences are much less significant. More specifically, the badge will display `201k` once the extension has at least 200,500 users.

Conversely a `+` is more vague and subject to interpretation, which actually ends up making it less precise (i.e. does it mean 200,001 users or could it mean 299,999 users). That vagueness of content and noise in the message text doesn't work well with our overarching goals and badge specification, which is why we have the behavior you see today.

If you feel strongly enough about wanting the `+` suffix on your badges, then your best option would probably to leverage our [Custom Endpoint Badge](https://shields.io/endpoint) which allows for such customization.
