### ISSUE TITLE
HN (YCombinator's Hacker News)

### ISSUE THREAD

**Issue by Symbian9** [badges/shields#7401]
:clipboard: **Description**

A clear and concise description of the new badge.

- *Which service is this badge for e.g:* HN (YCombinator's Hacker News)
- *What sort of information should this badge show?*
  - User name & user karma
    - https://news.ycombinator.com/user?id=app4soft
  - Post upvotes & comments count
    - https://news.ycombinator.com/item?id=28819927

:link: **Data** 

- Is there a public API?
  - Yes: https://blog.ycombinator.com/hacker-news-api/
- Does the API requires an API key?
  - Probably, no.
- Link to the API documentation.
  - https://github.com/HackerNews/API

:microphone: **Motivation**

- What is the specific use case?
  - Add info about user in readme on GitHub & other sites.

### REFERENCE

There are few other related projects:

- Post upvotes badge: https://github.com/AnandChowdhary/hackerbadge
  - Light badge: https://hackerbadge.now.sh/api?id=28819927
  - Orange badge: https://hackerbadge.now.sh/api?id=28819927&type=orange
  - Dark badge: https://hackerbadge.now.sh/api?id=28819927&type=dark
- User profile details (no badges for embed): https://hnbadges.netlify.app/ (see https://news.ycombinator.com/item?id=28389773)
  - Generated page: https://hnbadges.netlify.app/?user=app4soft

**Comment by calebcartwright** [comment]
Thanks for sharing and including those details! Based on a cursory review it does seem like there should be some badges we could provide, though I've some skepticism of others based on textual warnings in the documentation. We have a really tight window in which to respond to our user requests for badges, and that typically limits our ability to make sequential API calls for data retrieval.

So any data points that can be retrieved with a single call should be fine, but any that require a progressive call flow will most likely not be viable.

**Comment by tapanchudasama** [comment]
If anybody hasn't picked this, I'd like to.

**Comment by calebcartwright** [comment]
Go for it @tapanchudasama!

**Comment by tapanchudasama** [comment]
Created a PR for this => https://github.com/badges/shields/pull/7411

**Comment by Symbian9** [comment]
> Created a PR for this [User name & user karma]

Nice!

What about post upvotes & post comments count for the single?

- Example: https://news.ycombinator.com/item?id=21462689

**Comment by calebcartwright** [comment]
> > Created a PR for this [User name & user karma]
> 
> Nice!
> 
> What about badge for the single post upvotes & post comments count?
> 
>     * Example: https://news.ycombinator.com/item?id=21462689 (`Shields.io` discussion thread on HN)
>       
>       * `109 points | 10 comments`

Perhaps you'd be interested in submitting a PR yourself @Symbian9? Also, please note that those would most likely need to be separate badges (e.g. ![](https://img.shields.io/badge/points-109-blue) and ![](https://img.shields.io/badge/comments-10-blue)) as per our [badge specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md)

**Comment by Symbian9** [comment]
> Perhaps you'd be interested in submitting a PR yourself `@Symbian9`?

To be clear, I know nothing about such type of coding, so I just suggested/requested, because can't do it myself.

**Comment by tapanchudasama** [comment]
I'll submit a PR for this, probably by Saturday. @Symbian9

**Comment by Symbian9** [comment]
Thanks!

**Comment by tapanchudasama** [comment]
> I'll submit a PR for this, probably by Saturday. @Symbian9

Raised A PR => https://github.com/badges/shields/pull/7462

**Comment by Symbian9** [comment]
> Raised A PR for

Thanks! What about ***HN-user profile details*** (karma)

- https://news.ycombinator.com/user?id=app4soft
![Screenshot_2022-01-07_19-04-33](https://user-images.githubusercontent.com/13188580/148579891-1398aa31-ce86-47ea-9c8e-2f5be0b7dfc7.png)

**Comment by calebcartwright** [comment]
> Thanks! What about _**HN-user profile details**_ (karma)

This was already mentioned above on this thread, but that already exists and is available for use

https://img.shields.io/hackernews/user-karma/pg?style=social
![](https://img.shields.io/hackernews/user-karma/pg?style=social)

**Comment by Symbian9** [comment]
> This was already mentioned above on this thread, but that already exists and is available for use

I see it is a little bit incorrect as it shows account name first letter capitalized:

- Actual: ![App4soft](https://img.shields.io/hackernews/user-karma/app4soft?style=social)
- Expected: `app4soft`

**Comment by tapanchudasama** [comment]
I was doubtful about this while implementing also. `pg` which is in smallcase also comes capitalised. Should we do something about this? @calebcartwright

**Comment by Symbian9** [comment]
JFTR, On HN some users has accounts with mixed letter cases:

- https://news.ycombinator.com/user?id=ChanningAllen
- https://news.ycombinator.com/user?id=ColinWright

**Comment by calebcartwright** [comment]
As a general note, I'd like to avoid using this one issue as a rolling feature request/bug tracker, so let's cap the scope of this issue to what's already been covered and address new items to separate, focused issues.

> I see it is a little bit incorrect as it shows account name first letter capitalized

You're right that it's not right, but not for the right reason :laughing: The default label should be `Karma`, as was discussed in the PR (not sure how that slipped through!). If users want to change the label value then they can do so via the `?label=foo` query parameter.

Shields is responsible for the rendering concerns and the way our badges look, while upstream platforms are simply the sources of data. We do not base our presentation/rendering concerns based on what other platforms do. The history and rationale for this is captured in places throughout the repo (e.g. https://github.com/badges/shields#history)

So casing differences between how we display labels vs. HNs displays is irrelevant

**Comment by tapanchudasama** [comment]
> The default label should be Karma, as was discussed in the PR (not sure how that slipped through!).

I did not quite understand @calebcartwright 🤔 . Something that I missed?

**Comment by Symbian9** [comment]
> We do not base our presentation/rendering concerns based on what other platforms do
>
> So casing differences between how we display labels vs. HNs displays is irrelevant

This is not about how "HN displays" — here I pointing out to the state that HN user accounts names are casesensitive as users set them.

**Comment by calebcartwright** [comment]
> > The default label should be Karma, as was discussed in the PR (not sure how that slipped through!).
> 
> I did not quite understand @calebcartwright thinking . Something that I missed?

No worries, we missed it on follow up review too - https://github.com/badges/shields/pull/7411#discussion_r775085044

**Comment by calebcartwright** [comment]
> This is not about how "HN displays" — here I pointing out to the state that HN user accounts names are casesensitive as users set them (the same way as on Twitter):

It's not clear to me what exactly you are arguing for/against given the above, particularly this from https://github.com/badges/shields/issues/7401#issuecomment-1007639424

> The default label should be Karma, as was discussed in the PR (not sure how that slipped through!)

I.e., it's a bit moot given what the label value is supposed to be. However, as far as I know, the user profile names aren't actually case sensitive, `colinwright` and `ColinWright` are not distinct human profiles, but are instead the same account.

The fact that a platform (Twitter or HackerNews) supports displaying the same profile in different casing **is**, unequivocally, orthogonal to (a) what our default badge label should be for any/all of our HN-based badges, and (b) the fact that we always upper case the first character in the label on social badges.

I'm not personally very receptive to the possibility of supporting additional customization on label casing in our social style, because even for those that feel strongly about the casing, badges of the `username | metric` variety really don't make much sense as there's zero context.

E.g. ![](https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=app4soft)  would mean what? there's some 6.6 thousand app4softs? :laughing: 

However, if you think you need the ability to have a social-styled label with casing you control, that's a completely separate request that needs to be discussed in a separate issue (and again which I don't see being likely to come to fruition)

**Comment by Symbian9** [comment]
> `colinwright` and `ColinWright` are not distinct human profiles, but are instead the same account.

No, you just misinterpreted HN account URL with HN account username/registered name:

![Screenshot_2022-01-07_22-46-46](https://user-images.githubusercontent.com/13188580/148605467-bea6653f-f961-4928-9f72-6021e4e0f1fa.png)

For example on Twitter, both `@karibyron` & `@KariByron` are valid cast URL, BUT account registered with casesensitive `@KariByron`:
- [![`@KariByron`](https://img.shields.io/twitter/follow/KariByron?style=social&logo=twitter)](https://twitter.com/KariByron/)
-  [![`@karibyron`](https://img.shields.io/twitter/follow/karibyron?style=social&logo=twitter)](https://twitter.com/karibyron/)

But on Twitter, as on HN, account cast URL shown exactly as user set it during registration:

- https://twitter.com/KariByron/
![Screenshot_2022-01-07_22-53-48](https://user-images.githubusercontent.com/13188580/148606228-c8c8df13-910e-4d0f-85a7-3aa8c8450f32.png)

ANYWAY, Capitalizing first letters in linked account on shields badge, ignoring user input name with lowercase first letter, is NOT permitted.

**Comment by calebcartwright** [comment]
@Symbian9 -

> ANYWAY, Capitalizing first letters in linked account on shields badge, ignoring user input name with lowercase first letter, is NOT permitted.

Let's check the tone here.

We, as the maintainers of this service, amongst other responsibilities, ensure adherence to the project's goals, and that includes the styles we provide and consistent defaults across our badges. Those are not dictated based on the "Website representation" of an upstream service, nor any individual user. You do not get to determine what is "permitted" here, period.

Your comments also give me the impression that you haven't actually taken the time to read and process the previous comments nor linked material, but instead are continuing to issue instruction instead. That is increasingly leading to this thread getting off topic, and this needs to be the end of it. You're free to continue participating constructively in the discussion/ask questions/etc., but any additional comments with the same type of tone are going to be hidden/removed, and I'll lock the thread if if becomes necessary.

> For example on Twitter, both @karibyron & @KariByron are valid cast URL:

Again, it seems you're too busy telling us what to do instead of reading and processing what's been said. As already stated previously (emphasis added):

> we always upper case the **first character** in the label on social badges.

You will notice in your own example that the first character in those twitter badges is the `F` in the word "Follow", and that is, indeed, capitalized. It does not start with the user's handle by default. However, if you were to customize the label to only include the handle, you'd see the same behavior.

https://img.shields.io/twitter/follow/espadrine?label=espadrine&style=social
![](https://img.shields.io/twitter/follow/espadrine?label=espadrine&style=social)

> @calebcartwright, if so, would mean there are 409 app4softs on Twitter

No, not at all. The Twitter Followers badge is poor counter argument, especially because it has the context about the "what" in the label: the word "Follow" clearly denotes that the badge is talking about followers/following. It has that extra context because unlike the badges you've requested for HN, it's an "actionable" badge where the message is clickable with an embedded link to start following the user.

Conversely, ![](https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=app4soft) doesn't actually have any context. Does it mean 6.6k submissions/posts? karma? something else? There's no way to know definitively from the badge itself/it's entirely subjective. That's why we have our aforementioned badge specification to define our defaults, and that's why there is indeed a need to change the current default label as has already been discussed.

Any additional debate about using the id as the default label, or the first character casing in our social style, is futile at this point, so I anticipate this being my last comment on the subject. However, I will recap the options that will already be available/pursuable if you'd still like to include the id in a case-sensitive manner in the badge label:

- Don't use the social style, e.g.: 
  https://img.shields.io/hackernews/user-karma/app4soft?style=flat&label=app4soft
  ![](https://img.shields.io/hackernews/user-karma/app4soft?style=flat&label=app4soft)
- Add your own prefix (any prefix) to the custom label, e.g.
  https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=@apP4sOFt
  ![](https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=@apP4sOFt)
  https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=hackernews%20app4soft
  ![](https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=hackernews%20app4soft)
- If you want to request that Shields adds a new feature to allow the user to control whether the first character is capitalized in the social style (a feature which is independent of any particular badge), then you'd need to open a request, as stated in https://github.com/badges/shields/issues/7401#issuecomment-1007700412

**Comment by Symbian9** [comment]
> Does it mean 6.6k ~~submissions/posts?~~ karma?

Yes, *that is karma*. I tell that in the header comment and clarified it few more times in next comments.

### Offtopic

> Let's check the tone here.

To be clear, I'm not trying to be rude here, but  "[ 6.6 thousand app4softs?](https://github.com/badges/shields/issues/7401#issuecomment-1007700412)" was not a funny joke.

**Comment by tapanchudasama** [comment]
What I think @Symbian9 means is this:
- The `Pg` in the badge https://img.shields.io/hackernews/user-karma/pg is actually the username of the person in HN. And that is casesensitive. So for username `pg` and username `Pg`, out badges are same, which should not be the case. Right, @Symbian9 ? 

What I think can be done:
- Not make the style social
- Keep style social and not show username, but just `HN Karma` instead.

WDYT @calebcartwright ?

**Comment by Symbian9** [comment]
> And that is casesensitive. So for username pg and username Pg, out badges are same, which should not be the case. Right, @Symbian9?

Not exactly.

> Keep style social and not show username, but just HN Karma instead.

Yes, that is what I mean for `https://img.shields.io/hackernews/user-karma/<id>` — there shold be NO name of user shown in a badge at all.

Instead "user-karma" badge should be shown as next: `<site-ico> HN Karma <karma-points>`

**Comment by calebcartwright** [comment]
@tapanchudasama

> WDYT @calebcartwright ?

We need to change [the label](https://github.com/badges/shields/blob/10e2f55bfee7d0da957985fe437d2133d52bd0a7/services/hackernews/hackernews-user-karma.service.js#L36), and do so ASAP, but no the style needs to remain social as-is. If you're up for working on that'd be great (feel free to use a reaction to indicate if so)!

The exact value can be discussed on a PR, but please note that it needs to be based on the direction of the maintainers and our [badge specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md), which does not allow for promotional/branding (i.e. no `HN`, no `HackerNews`), and must have self-evident semantics.

The current labeling, and the labeling @Symbian9 has been insisting on debating thus far, fails to pass those gates which is why we need to do something different than both those demands and what is out there currently.

Specifically, the problem with the current label is that if one were to go to https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=app4soft

or see :point_down: rendered on a readme or some other page, it's not self-evident to the reader what it means (even though the author who put it there knows)
![](https://img.shields.io/hackernews/user-karma/app4soft?style=social&label=app4soft)

**Comment by calebcartwright** [comment]
@Symbian9 - thanks again for your original suggest/request for some HN badges. I think they'll prove a worthwhile edition in a similar vein as the reddit badges.

Unfortunately, however, you seem intent on trying to keep this a 1-directional discussion where you're simply talking _at_ everyone else. I appreciate that users get frustrated when they don't get the answers they want, but that doesn't mean the thread should have been detoured into the non-productive territory we currently find ourselves in.

Information has already been provided above about what we need and why, as well as why the answer was a "no" to your repeated requests/direction, including the ones that are off topic. There's no point in continuing to run in circles on that any more.

As such, I'm going to close the issue at this time because (a) the specific badge requests have already been received and are already completed or in-flight, and (b) the dialog has devolved far too much past the point of utility.
