### ISSUE TITLE
Maybe you can provide Alipay 2D code, so China users can donate you conveniently.

### ISSUE THREAD

**Issue by zh0903** [badges/shields#7415]
:clipboard: **Description**

**Comment by calebcartwright** [comment]
Thanks for reaching out. Could you provide a little information? I'm not familiar with Alipay, but are there issues with donating via Open Collective from certain locations/countries?

**Comment by zh0903** [comment]
[Reply on "provide Alipay 2D code"]
Thanks for reply to my suggestion.
More info:&nbsp; &nbsp;https://global.alipay.com/docs/&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;Maybe you can take a look at “Documentation--online payment--” entry&nbsp;&nbsp;When you have a free time.
What I want to say is : In china, it is very convenient to use Alipay QR code in China, and Donating via Open Collective is realizable but slightly inconvenient.
"Provide Alipay 2D code" is just an proposal . If you want to make donation channels more unobstructed in you free time,you can give it a try.
&nbsp;The collection QR code may not be as transparent as other methods，but I think more important thing is to donate your marvelous work more quickly.
------------------&nbsp;原始邮件&nbsp;------------------&nbsp;
发件人:                                                                                                                        "badges/shields"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月24日(星期五) 凌晨2:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [badges/shields] Maybe you can provide Alipay 2D code, so China users can donate you conveniently. (Issue #7415)





 
Thanks for reaching out. Could you provide a little information? I'm not familiar with Alipay, but are there issues with donating via Open Collective from certain locations/countries?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by calebcartwright** [comment]
Thanks again for the suggestion and follow up, but I'm going to close this because this isn't a path we want to take at this time. 

Open Collective greatly simplifies the process of accepting and spending donations without the legal/tax/etc. overhead that comes with other types of processors. We have an incredibly small maintainer team with limited bandwidth, and a donation platform in Open Collective that works best for us. Trying to incorporate other sources would actually create more problems for us than it would solve.
