### ISSUE TITLE
Request: 'Time passed since'  shield

### ISSUE THREAD

**Issue by majkinetor** [badges/shields#749]
It would be awesome to have a way to get how much time is passed since argument, for instance

```
[age | 1 hour]  
[age | 3 years]

or

[published before | 1 minute]
[last build before | 1 day]
```

URL Example:

```
https://img.shields.io/badge/age-2016_07_18_T_15_05_30-red.svg
```

**Comment by GammaNu** [comment]
i'm looking for similar behaviors.
Github badge for : 
- time since last commit (how alive/dynamic is the project)
- time since first commit (how old/mature is the project)

**Comment by Ang-YC** [comment]
@RedSparr0w @chris48s I would like to ask if this issue need any PR and my suggestion for the endpoint for this issue is
`https://img.shields.io/badge/date/<SUBJECT>-<TIMESTAMP>-<COLOR>.svg`

Example
`https://img.shields.io/badge/date/christmas-1545696000-red.svg`
![](https://img.shields.io/badge/christmas-in%2055%20days-red.svg)

I will be using `moment` which is already a dependency.
If the timestamp is 2 minutes before now, return `2 minutes ago`.
If the timestamp is 2 minutes after now, return `in 2 minutes`.

**Comment by Ang-YC** [comment]
Tagging @paulmelnikow as well

**Comment by paulmelnikow** [comment]
Hi, yes, and thanks for taking this on! What you’re suggesting sounds good.

We’ve been moving away from APIs with dashes like the static badge, so let’s model on the dynamic badge instead:

https://img.shields.io/date/1545696000.svg?label=christmas&colorB=red
