### ISSUE TITLE
Badge request: GitHub status API

### ISSUE THREAD

**Issue by X-sam** [badges/shields#755]
https://developer.github.com/v3/repos/statuses
would be useful to support it, as it allows for CI-agnostic build shields.

**Comment by paulmelnikow** [comment]
We do a badge for check state of the head commit on a pull request. So I think what probably would be useful to add is the same for branches, and if it's easy to do, for any commit hash.

**Comment by oliviertassinari** [comment]
THIS. In the project I'm working on, we have a couple of different CI tools. It would be much simpler if we could display the state of the default GitHub branch in a badge. It already aggregates all the CI tools.

**Comment by PyvesB** [comment]
We've now got a bunch of badges that can report the status of commits, branches, tags, and pull requests. For example: https://shields.io/badges/git-hub-branch-status

Will go ahead and close this issue. :)

**Comment by oliviertassinari** [comment]
I have migrated to it, but compared to CircleCI badge, it shows the latest build status: <img width="108" alt="SCR-20240602-qbse" src="https://github.com/badges/shields/assets/3165635/55e2af73-b73e-46e1-9d17-0b38b1c2adf6">

while CircleCI badge shows the latest non-pending build status. CircleCI seems the expected behavior.
