### ISSUE TITLE
Docker Image serves incorrect `User-Agent`

### ISSUE THREAD

**Issue by Changaco** [badges/shields#7573]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The requests coming from shields.io currently have `Shields.io/${GITHUB_SHA::7}` as user agent. That's obviously unintended, and it might lead to those requests being blocked by web application firewalls.

**Comment by chris48s** [comment]
Good spot. This will have been affecting self-hosting users for some time. The reason this is currently affecting production is because it is currently running from a docker container which is not usually the case. See https://github.com/badges/shields/issues/7574#issuecomment-1030637680 for more details on that.

Bug is at:
https://github.com/badges/shields/blob/9e8f50315046a0f73e76825cddd37f65d8e4c297/.github/workflows/build-docker-image.yml#L21-L22
https://github.com/badges/shields/blob/9e8f50315046a0f73e76825cddd37f65d8e4c297/.github/workflows/publish-docker-next.yml#L29-L30
This should be giving us the short commit hash, but clearly isn't. Might need to be `version=${{GITHUB_SHA::7}}` but I've not tested that.
