### ISSUE TITLE
Shields.io reports false contributor count for GitHub

### ISSUE THREAD

**Issue by Paebbels** [badges/shields#764]
Hello,

Shields.io reports 241 contributors, but our project has only 7 contributors.

Shield: ![GitHub contributors](https://img.shields.io/github/contributors/VLSI-EDA/PoC.svg)
Project statistics: https://github.com/VLSI-EDA/PoC/graphs/contributors

Kind regards
    Patrick Lehmann

**Comment by ahyattdev** [comment]
I came here to report this too. 

For my project, it displays the commit count instead.

**Comment by qzb** [comment]
Yep, this badge shows number of commits made by top contributor instead of number of contributors. AFAIK Github API doesn't provide any way to get number of contributors without obtaining contributors list. Unfortunately fetching whole contributors list could cause performance issues, but instead of that we could fetch only first page and obtain last page number from link specified in `Link` header. It isn't pretty but it will work.
