### ISSUE TITLE
Accept date/timestamp as a type for dynamic and endpoint badges

### ISSUE THREAD

**Issue by tanho63** [badges/shields#7688]
:clipboard: **Description**

Hi! I've been experimenting with using badges to show "last update" dates on my repo and was curious about trying to generate relative date badges from either a dynamic or API request (rather than having to commit a change in URL for the badge)

I don't believe this is currently possible (because the value seems to be only looking for a string) but I'd be happy to be proven wrong!

e.g.
`https://img.shields.io/badge/dynamic/json?color=brightgreen&label=last%20updated&query=message&url=https%3A%2F%2Fgithub.com%2Fnflverse%2Fnflverse-data%2Freleases%2Fdownload%2Fsnap_counts%2Fts.json` generates a badge for a given date/timestamp like ![](https://img.shields.io/badge/dynamic/json?color=brightgreen&label=last%20updated&query=message&url=https%3A%2F%2Fgithub.com%2Fnflverse%2Fnflverse-data%2Freleases%2Fdownload%2Fsnap_counts%2Fts.json), but I'd really like to be able to generate the same styling as 
![](https://img.shields.io/date/1646545047?label=last_updated)  from a more dynamic source

**Comment by calebcartwright** [comment]
Thank you for the question. You are correct that you cannot do this type of formatting transformation as part of the dynamic badge (not unless there's some fairly exotic json path function that happens to be supported by the jsonpath lib we use).

However, this is precisely one of the types of scenario that the Endpoint is designed to support. In the Endpoint badge model, you write the main processing code that retrieves data from the upstream source and then applies whatever sort of extraction/transformation logic you want in order to derive the badge rendering attributes like the message and color.

The Shields.io servers then simply calls your Endpoint to get those values specified in the response in order to provide a corresponding badge

https://shields.io/endpoint/

Going to close this as there's no action to be taken on our end, but please feel free to post any follow up questions

**Comment by tanho63** [comment]
Followup question: is it possible for me to tap into the logic used by the relative-date + timestamp badge by supplying `1646147085` or are you suggesting that I would have to convert `1646147085` to "11 hours ago" for myself?

**Comment by calebcartwright** [comment]
Would encourage reading the aforementioned docs for the Endpoint badge which explain this. It's you/your Endpoint's responsibility to set the `message` value to be `11 hours ago` or whatever you want yourself.

The response schema of an API for an Endpoint badge looks like this:

```json
{
  "schemaVersion": 1,
  "label": "hello",
  "message": "sweet world",
  "color": "orange"
}
```

Shields' Endpoint badge uses those values that _you_ define in your Endpoint to render a badge, Shields is not going to subsequently do any additional processing/transformation of Endpoint values.

**Comment by tanho63** [comment]
Thanks for the clarification! I realize that it's not in-scope (currently), I've been using dynamic badges to read from a GitHub json file and was hoping to replicate functionality without making a new commit to change the timestamp and/or without setting up an api to respond to said requests. 

Appreciate you taking the time to respond and I'm massively grateful for the badges project!

**Comment by calebcartwright** [comment]
Sure thing, happy to help!

To be clear though, what you're asking is never going to be in scope for our Dynamic badge, again that's why the Endpoint badge exists. Setting up an Endpoint can be incredibly easy and free, with just a few lines of JavaScript using a free service like [RunKit](https://runkit.com/docs/endpoint).

As I'm sure you can imagine, there's myriad possibilities for the types of manipulation the internet may want to do with values from an arbitrary json/xml/yaml file and that's why it's simply not possible for us to try to support anything/everything our users might want to do.

The Endpoint badge serves this use case, and yes that does mean that if you want to apply some custom logic then you'll need a dash of code for yourself, either as part of Endpoint badge if you don't control the upstream data source, or if you do control the source, to modify how the json file is being written to ensure it contains the formatting you want with a Dynamic badge
