### ISSUE TITLE
Twitter follow badge showing "not found" instead of follower count

### ISSUE THREAD

**Issue by daneah** [badges/shields#7698]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The follower count for the Twitter Follow badge is currently displaying the text "not found" instead of the follower count.

### 🔗 Link to the badge

Example:

https://img.shields.io/twitter/follow/easyaspython?label=Follow&style=social
![Twitter Follow](https://img.shields.io/twitter/follow/easyaspython?label=Follow&style=social)

Noticed this in the wild on [my GitHub profile](https://github.com/daneah).

**Comment by nicholascarey** [comment]
Came here to report this too!

**Comment by carlosperate** [comment]
Looks like the badge provided as an example in the bug report is now working, but there are badges still showing this issue. For example in the shields.io website:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4189262/157887102-6175611f-0624-4143-851c-98a4f358f3db.png">

**Comment by calebcartwright** [comment]
Please keep in mind that Shields itself is not a system of record, and that we have to fetch relevant data from an upstream data source in order to get the values to build the badges, and as such it's helpful when folks provide specific badge details since we need those parameters to query said upstream sources.

In this instance, the upstream provider is intermittently returning 404 responses, hence our badge message of `not found`

```
$ curl -I http://cdn.syndication.twimg.com/widgets/followbutton/info.json?screen_name=easyaspython
HTTP/1.1 404 Not Found
Access-Contol-Allow-Origin: platform.twitter.com
Access-Control-Allow-Methods: GET
cache-control: no-cache, no-store, max-age=0
Content-Type: application/json;charset=utf-8
date: Fri, 11 Mar 2022 15:02:34 UTC
server: tsa_b
Server-Timing: "x-cache;desc= ,x-tw-cdn;desc=VZ",edge;dur=30
strict-transport-security: max-age=631138519
x-connection-hash: 07ac9abb99eb1cc2c04c2c751ea2819537b07b6f3f047afb2b7da49c0857d007
X-Content-Type-Options: nosniff
x-response-time: 3
x-tw-cdn: VZ
x-tw-cdn: VZ
Content-Length: 68
```

There's not much we can do about such an upstream issue, especially in the short term so going to label the issue as such.

**Comment by daneah** [comment]
Thanks for the clarification @calebcartwright—I definitely reported this merely as a Shields user without really thinking about the system architecture. Appreciate you taking a look one layer down.

**Comment by chris48s** [comment]
Hmm. Twitter API service status does not show any incidents
https://api.twitterstat.us/
I wonder if this is intermittent or if the endpoint has just been quietly dropped.
We'll have to keep an eye on it..

**Comment by calebcartwright** [comment]
> Thanks for the clarification @calebcartwright—I definitely reported this merely as a Shields user without really thinking about the system architecture. Appreciate you taking a look one layer down.

Sure thing @daneah, thanks for the report and including your badge!


> I wonder if this is intermittent or if the endpoint has just been quietly dropped.

It has been intermittent at least since the issue was reported. I've seen two separate occasions where the badge in the issue description was able to get and render the follower count, before then later going back to not found. Gather others have seen the same based on comments like https://github.com/badges/shields/issues/7698#issuecomment-1065166440

**Comment by calebcartwright** [comment]
Is anyone still seeing this behavior? Obviously not observing it 24/7 but anecdotally it seems to have been resolved

**Comment by nicholascarey** [comment]
Working ok for me.

**Comment by calebcartwright** [comment]
Thank you, going to close then

**Comment by lexcraw4d** [comment]
I am having the same issue, just leads to a dead end page with the twitter img badge. Any input on how to resolve this greatly appreciated. Same experience as @daneah. I see yours is still doing it as well @daneah. Please let me know if there is a resolution. Kind vibes!

**Comment by daneah** [comment]
@lexcraw4d I'm seeing my badge working at present — perhaps another intermittent issue with the Twitter API?

**Comment by lexcraw4d** [comment]
@daneah all is good now 😃 thanks for checking back! Happy coding!
