### ISSUE TITLE
add a 'publisher' badge for Dart packages

### ISSUE THREAD

**Issue by devoncarew** [badges/shields#7714]
:clipboard: **Description**

This request is for a badge to display the publisher information for Dart packages. There already exists a 'last published version' badge for Dart packages - implementation here: https://github.com/badges/shields/blob/master/services/pub/pub.service.js.

The badge might look something like `[publisher | my.publisher.io]`; or, thuswise: ![publisher my.publisher.io](https://img.shields.io/badge/publisher-my.publisher.io-blue).

:link: **Data**

There is an API for this data - it's available as a simple http get and returns JSON. It's `https://pub.dev/api/packages/<package-name>/publisher`. So, for package path, it's https://pub.dev/api/packages/path/publisher, and for `usage`, it's https://pub.dev/api/packages/usage/publisher.

The returned json looks like `{"publisherId":"tools.dart.dev"}` - you just want to extract the `publisherId` out of the map.

:microphone: **Motivation**

This is one of the more important pieces of data related to Dart packages (the last published version being the other one). The publisher info is useful for anyone looking at a readme for a package - it can given the potential consumer of that package a rough indication of the quality of the package and potentially an expected SLO. 

The use case for this badge is to add it to the top of a github readme file - along with the github actions status and publisher version badges. For high quality packages, the publisher badge can act as an indication of the expected SLO.

ℹ️ **also**

I see the contributing info here: https://github.com/badges/shields/blob/master/doc/TUTORIAL.md. I'm willing to take a stab at an implementation here, but don't have a lot of background in JS development.

**Comment by calebcartwright** [comment]
Thank you for sharing your suggestion.

Is the publisher id of a published package a mutable value?

**Comment by devoncarew** [comment]
> Is the publisher id of a published package a mutable value?

Yes - it is possible for it to change. Typically that doesn't happen though - generally a package won't change publishers, and for those that do, they'd likely only do that once or twice over the package's lifetime.

Is your question related to a caching lifetime?

**Comment by calebcartwright** [comment]
It's more about trying to determine whether we're dealing with a static or dynamic data point.

We do provide the static badge builder (which you leveraged for the example in the description) that's best suited for static content

https://img.shields.io/badge/publisher-my.publisher.io-blue

We wouldn't want to deal with the extra work/time and send extra traffic to some upstream data point all to get to a static data point, so I'm trying to understand more about the context, and whether this is a badge that could be sufficiently conveyed already with a static badge or if there's a need/use case to treat it as significantly dynamic enough to need to deal with that overhead.

Obviously some attributes of a package published to a registry can change but do so rarely, e.g. the license. However, the owner/publisher strikes me as something significantly more immutable, though I'm not terribly familiar with dev.pub (know _of_ it but not experienced with it)

**Comment by calebcartwright** [comment]
I.e. are we talking about something that would be more analogous to the publisher of an extension on the vs code marketplace or the author of an npm package, or something more like our AUR maintainer badge (my sense is that it's the former).

A consideration/potential concern with trying to do this as a dynamic badge is that I think it could actually end up displaying incorrect information on the registry itself given the ability to browse prior versions.

E.g. if the owner/publisher of package X is Foo for all v1 versions, but then X is "transferred" to Bar and released under v2, the views/docs for all the v1 versions of X would show Bar being the publisher, even though those were published by Foo

**Comment by chris48s** [comment]
Happy to wait for more info from the OP, but my instinct is we can view this as being similar to a licence badge.

- Like with (pretty much) everything on shields (accepting some badges do have a version-specific variant), the badge would reflect the current state of affairs, or the latest version. e.g:
    - The current version of the package is compatible with NodeJS >= 14, but previous versions of the package might be compatible with other versions
    - The package is currently MIT licensed, but previous versions might have been released under some other licence
    - etc
- Pub has a global namespace, so this data point is a property of a package. I guess this concept of 'publisher' from Pub doesn't map exactly onto most other registries, but it is unlike say packagist where packages are namespaced: If I transferred https://packagist.org/packages/chris48s/cakephp-searchable to someone else, it is a different package - it becomes `someone-else/cakephp-searchable`.
- In principle, this property can change but in practice this will be infrequent so we can set a reasonably long cache on it

**Comment by devoncarew** [comment]
Hi - sorry for the delay :)

Thanks for for questions - here are some responses in-line:

> Obviously some attributes of a package published to a registry can change but do so rarely, e.g. the license. However, the owner/publisher strikes me as something significantly more immutable, though I'm not terribly familiar with dev.pub (know of it but not experienced with it)

For me, it's less that this info wouldn't change that often, and more about that fact that the pub site - pub.dev - is the system of record for who the publisher is. I don't think we want that info duplicated in pub.dev and across the various markdown files. There are 10's of thousands of packages; having a live badge - querying pub.dev - seems like a solution w/ less tech debt than having static badges in markdown files, that would likely slowly drift out of date (for some percentage of those packages) over time.

> E.g. if the owner/publisher of package X is Foo for all v1 versions, but then X is "transferred" to Bar and released under v2, the views/docs for all the v1 versions of X would show Bar being the publisher, even though those were published by Foo.

Pub and Dart packages don't have a separate notion of ownership of a package vs. ownership of various versions of that package. So, having a package transfer to a different publisher would be ~= all the versions transferring. I think we want want to badge to just reflect the latest info - the current publisher.

**Comment by calebcartwright** [comment]
I'm still on the fence about this one so I'm going to pose a few questions to help me get a better idea of what the field _is_ as opposed to what it _isn't_.

From my perspective we don't have a frame of reference within our existing badge ecosystem, and I suspect that's likely due to one (or more) of a small set of reasons:

- pub.dev's publisher field has no analog on any of the other registries/marketplaces we already integrate with
- there are analogs, but no one has ever requested/proposed a corollary badge for another registry/marketplace (either due to lack of utility or lack of imagination).

I've yet to hear anything that convinces me that first reason would be true (though please correct me if I'm wrong). The pub.dev publisher field continues to strike me as being very similar (at least in spirit) to the publisher construct on the [VS Code Marketplace](https://marketplace.visualstudio.com/), especially with the distinction between verified and unverified publishers. I suspect it also bears some similarities to things like the  "collaborators" attribute of a package on an npm registry or "maintainers" of a package on pypi, with a crucial distinction being that pub.dev packages strictly have a single publisher (again analogous to the VS Code marketplace). As such I'm operating under the assumption that it's more the latter the latter reason why we've not crossed this bridge before.

Accordingly, some questions I have:

- Is the above description of a Dart package publisher an accurate/fair representation? That of the sole, official "owner"? If not, what's the correct definition/meaning?
- The only benefit/description of the info conveyed by the badge that's been provided on this thread is that the name of the publisher is indicative of things like quality and, potentially, the SLO of the package. Could you elaborate on how that's the case? Are the publisher id's sufficiently well known/popular knowledge amongst the Dart developer community that many/some ids not only resonate, but inherently connote quality? i.e. An average/random dev browsing a GitHub repo will recognize some foo.bar.baz publisher by name?
- What specific scenarios/meanings do you think this badge would be used for, specifically outside the context of someone reviewing a package's docs on pub.dev? Some/None/All of the below?
  - User/group conveying "this is _my_/_our_ publisher id "
  - User/group conveying that a publisher id is official/verified
  - Package owner/publisher conveying their publisher id outside the registry context, where the id in term conveys well understood meaning to end users
- In what circumstances would the publisher id change, and are there any well known examples (e.g. a community package being transferred into/adopted by a larger or more "official" group)

<hr />

More for the maintainers here, but taking a step back under the assumption we move ahead with this badge, what are the potential implications for future badges/requests? Would we want to/accept badges for other owner-like data points for other registries/marketplaces? If _not_, why?

There's loads of additional metadata available on most, if not all, of the registries/marketplaces/etc. that we already integrate with which is not technically immutable and which could technically have a badge. What, if any, criteria would we have for determining whether to incorporate a badge that displays such a data point?

**Comment by chris48s** [comment]
> More for the maintainers here, but taking a step back under the assumption we move ahead with this badge, what are the potential implications for future badges/requests? Would we want to/accept badges for other owner-like data points for other registries/marketplaces? If not, why?

I think it would not make sense for situations where it is part of the URL. So I gave the example of packagist earlier. In the same bucket would be something like a badge that shows the github user/organization associated with a repo: If you have to change the badge URL when the data point changes, its a static badge.

For Pub/Dart specifically, `publisher` and `authors` are two different data points and this publisher concept is a bit of a special snowflake amongst package registries.

More widely I wouldn't necessarily see a problem with accepting badges for other registries that show an author/maintainer. We already carry a maintainer badge for Arch User Repositories, for example

![](https://img.shields.io/aur/maintainer/google-chrome) - https://img.shields.io/aur/maintainer/google-chrome

AFAIK I don't think it is something we've ever had requested for NPM/PyPI/Ruby Gems/Rust Crates/etc (probably because its not massively useful) but I wouldn't rule it out.

**Comment by devoncarew** [comment]
Some responses in-line:

> pub.dev's publisher field has no analog on any of the other registries/marketplaces we already integrate with

I think this is roughly correct? It sounds like from above, for some other package managers the package's publisher is part of its identity. For Dart, a package can retain the same identity (`package:args`) even when it changes publishers.

> Is the above description of a Dart package publisher an accurate/fair representation? That of the sole, official "owner"?

Yes, I think that's fair. A publisher is the only entity that can publish new versions of the package to pub.dev. The group of people in the publisher likely correspond closely to the people who are the primary maintainers (but may be a subset, or a disjoint set).

> The only benefit/description of the info conveyed by the badge that's been provided on this thread is that the name of the publisher is indicative of things like quality and, potentially, the SLO of the package. Could you elaborate on how that's the case?

Sure - I'll outline the use case we're thinking about this for now.

The Dart team would like to better indicate the SLO for the packages that it itself publishes. We'd like to do that by augmenting the UI for both the pub pages as well as for the main github page for the package - have a clear indication of SLO and publisher from both pub.dev and from the readme when looking at the github repo.

The three SLOs we have map exactly to our three publishers - `dart.dev`, `tools.dart.dev`, and `labs.dart.dev`. We'd like badges at the top of the repo's readme which indicate the publisher; those badges would then be hyperlinked to the pub page for the publisher - https://pub.dev/publishers/dart.dev/packages - which we'd update to clearly call out the SLO. The existing SLO levels can also be seen here: https://dart.dev/dart-team-packages.

> Are the publisher id's sufficiently well known/popular knowledge amongst the Dart developer community that many/some ids not only resonate, but inherently connote quality?

Yes - the publishing entities for the Dart team would - `dart.dev`, `tools.dart.dev`, `labs.dart.dev`, as well as some of the other larger publishers, like `fluttercommunity.dev`, `material.io`, `firebase.google.com`, ...

Also, having the publisher be unverified (`publisher: unverified`) is also a signal of quality.

> In what circumstances would the publisher id change, and are there any well known examples (e.g. a community package being transferred into/adopted by a larger or more "official" group)

I think there could be many reasons here? General ownership changes as someone moves off a project and someone else takes it over. For the Dart team, our different publishers imply a certain SLO, so promoting something to a higher SLO would mean moving it into `dart.dev`; moving to a lower SLO would mean moving to `tools.dart.dev` or `labs.dart.dev`.

Some general background on pub verified publishers:
- docs: https://dart.dev/tools/pub/publishing#verified-publisher
- note that a publisher can be an individual or a group

**Comment by calebcartwright** [comment]
Thanks Chris. Agreed with you relative to not having a "dynamic" badge for obviously static data/data provided to our servers as badge route query params.

I suppose a different phrasing of the more general question I was asking was essentially "should we add native/dynamic badge just because we can/someone asks, or do we want to apply any other criteria", though in fairness this is probably a topic best suited to a different thread.

> We already carry a maintainer badge for Arch User Repositories, for example

Yup, and fwiw I mentioned that explicitly as well back in https://github.com/badges/shields/issues/7714#issuecomment-1065494808 while attempting to draw parallels.

I believe subsequent conversation has sufficiently convinced me that the publisher data point here is far closer to the publisher on the vsc marketplace as opposed to any of the other mentioned maintainer data points, though on pub.dev it has some slightly different attributes as well.

**Comment by calebcartwright** [comment]
I'll confess that I'm still skeptical of the use case, as it seems like a badge that's primarily geared towards a very specific subset of the platform (i.e. the small set of well-known publishers whose badges would potentially/likely have meaning that could be inferred). I also have some minor concerns about this becoming precedential.

However, I don't feel too strongly and don't want to block, especially since it seems like there's a building consensus to move forward.

Thank you @devoncarew for not only making the suggestion and entertaining these questions, but also for submitting an implementation PR as well!

As an aside, Dart's pretty high on my list of languages to dig into so perhaps this will resonate with me more down the road once I've gotten more familiar with the ecosystem and paradigms.
