### ISSUE TITLE
pyversions shows pre-release version numbers

### ISSUE THREAD

**Issue by zachriggle** [badges/shields#775]
When using PyPi shields, the version number fetched is the most recently uploaded version, which may include pre-release versions.

For example, the latest released version of pwntools is 3.0.1, however v3.1.0b0 shows up.

![](https://img.shields.io/pypi/v/pwntools.svg)

**Comment by JoabMendes** [comment]
The Same is happening with my pypi package. The latest version is [1.2.0](https://pypi.python.org/pypi?name=fbbotw&version=1.2.0&:action=display), but the badge only shows the pre-release:
[![PyPI](https://img.shields.io/pypi/v/fbbotw.svg)](https://pypi.python.org/pypi?name=fbbotw&:action=display)

**Comment by chris48s** [comment]
Pre-release naming convention for PyPI is defined in [PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases)

**Comment by chris48s** [comment]
I did a little bit of investigating on this issue, but looking at our current code for this, we're relying on reporting the 'latest' version as determined by PyPI (we're not actually doing anything to work it out ourselves) and during the ~2 years since this issue was reported the entire PyPI codebase has been completely revamped as [warehouse](https://github.com/pypa/warehouse) so I suspect the upstream API behaviour might not be exactly the same now anyway.. I'm not going to do anything else on this for now but if we get a more up-to-date example, I'm happy to revisit it.

For future reference, if we do want to do any explicit parsing of PEP440 version strings in this project, there is a JS package for that can help with this: https://www.npmjs.com/package/@renovate/pep440

**Comment by chris48s** [comment]
I think this isn't a problem any more. Given there has been no traffic on the issue for over a year I'm going to close it
