### ISSUE TITLE
Create Prefix to retrieve Shield.io as a SVG or PNG

### ISSUE THREAD

**Issue by WestonCao** [badges/shields#7839]
Would it be possible to retrieve a Shield.io label by prefixing?

Context:
I'm creating a project that has 6 status checkboxes for each github repo I have. I post into each github repo README files a Shield.io labels for each status checkboxes when checked. I want to prefix the Shield.io labels where if I update a repo and select another checkbox, another Shield.io should display on the README automatically without having to run a cron job/update on a time or get & posting an updated REAME file.

**Comment by chris48s** [comment]
I don't think I understand the question.

The title seems to suggest you want a prefix that determines whether the rendered badge is a SVG or PNG, which we do have:

- https://img.shields.io/badge/foo-bar-blue is a SVG
- https://raster.shields.io/badge/foo-bar-blue is a PNG

but the body of this issue seems to be talking about something totally different and I don't really get it.

**Comment by calebcartwright** [comment]
Going to close. Feel free to follow up with clarifying information and we'll reopen if necessary.
