### ISSUE TITLE
AUR badges sometimes provide invalid value

### ISSUE THREAD

**Issue by ReenigneArcher** [badges/shields#7863]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Sometimes the badges provide invalid as the value. I originally thought this is depending on the badge type. However now I believe it may be some sort of rate limit.

![image](https://user-images.githubusercontent.com/42013603/163853090-c15d6d02-027b-4563-8f1a-61c90d1f7f71.png)

![image](https://user-images.githubusercontent.com/42013603/163853142-a144bd2e-3a62-4de6-8f8a-d4a69921bbfc.png)

### 🔗 Link to the badge

https://img.shields.io/aur/maintainer/sunshine?style=for-the-badge

![AUR maintainer](https://img.shields.io/aur/maintainer/sunshine?style=for-the-badge)

![AUR maintainer](https://img.shields.io/aur/maintainer/sunshine?style=flat-square)

**Comment by chris48s** [comment]
After a bit of investigation I think there is either an intermittent issue with the upstream API or we've been rate limited (possibly some of the servers behind our load balancer have been banned and some of them haven't). I'm not sure there is much we can do about this.

**Comment by ReenigneArcher** [comment]
Can you cache responses from AUR for 24 hours or so, to reduce the number of hits to their API?

**Comment by calebcartwright** [comment]
The [upstream API is rate limited at 4k requests per _day_](https://wiki.archlinux.org/title/Aurweb_RPC_interface#Limitations) which is a rather strict amount to begin with. For reference, we've received >18k requests for AUR badges in the last 24 hours.

There's just a fundamental conflict between the volume we're dealing with and what the upstream service is willing to support.

We do cache the badges, and I suppose we could try increasing the ttl on those to see if it helps. However, I'm not convinced that'll really solve the problem. Additionally, there have been a number of discussions over the years around caching in the responses from the upstream API response and on paper that would be beneficial in this case given that there's a family of badges all using the same endpoint. However, there's good reasons why we haven't expanded our solution architecture to incorporate that; there's a lot more complexity than just "adding cache".

I'm just not sure caching is going to be a silver bullet here, regardless of which layer(s) caching is applied/extended. I worry that given our volume we'd have to cache so heavily that the badges would be displaying information that's far too outdated in my opinion.

From my perspective the best approach would be to try to get in contact with those folks (assuming we haven't already done so) to see if they're willing to work with us on providing a higher rate limit. If not, and increasing the ttl indeed doesn't solve the problem, then I'd actually suggest we consider deprecating the badges. I realize there woulds still be some potential workarounds we could point people to, but I don't think we should point people in those directions unless and until we talk to the upstream team first (since such workarounds would essentially be violating their rate limiting attempts).

**Comment by ReenigneArcher** [comment]
I don't know the inner working of your service. Is there any indication how many requests there are to the AUR if you remove duplicate aur package names? For example, I have 4 badges to a single package, on one page. I assume every time someone loads that page, it makes 4 requests to AUR?

**Comment by chris48s** [comment]
Yeah I did finally manage to reproduce this and confirm it is rate limit. We get a 429 response with a `{"version":5,"results":[],"resultcount":0,"type":"error","error":"Rate limit reached"}` body. Well done for tracking down the documented rate limit as there is nothing in the headers that tell us what the limit is or what our usage is. I'm not entirely sure how the rate limit works though in that it says

> The API rate is limited to a maximum of 4000 requests per day per IP

but we run like ~20 servers so I'd assume we'd actually be well _under_ their rate limits, assuming load balancing.. balances :smile: Also our staging server is rate limited but that must do hardly any traffic to them. Also I got different results making the request from a node script vs using wget (even if I use the same user-agent) so.. not sure if 4k per day per IP is actually the rate limit we are trying to stay under.

I was thinking some of the AUR badges (like maintainer and licence) are basically static so we could set like 1 day cache on those, but the reality is all the meaningful traffic (lets round it to 100%) of our hits for AUR are for the version badges so that is where we need to focus. We could try putting the s-maxage on the AUR version badges up to like an hour or something (of course, then if we do hit the rate limit the badges stay broken for a really long time!) and see what happens. Otherwise I think you're right we do need to either negotiate a higher rate limit or deprecate the badges.

**Comment by calebcartwright** [comment]
I don't feel like there's enough specificity in your question for me to be able to answer, and I don't want to make assumptions about what you're saying either.

As I mentioned on the linked PR, ~16k of the 18k requests are version request badges, so caching the API response to avoid duplicate hits on the same endpoint for different badges is not something I'd expect to help that much

**Comment by calebcartwright** [comment]
> but we run like ~20 servers so I'd assume we'd actually be well under their rate limits, assuming load balancing.. balances smile Also our staging server is rate limited but that must do hardly any traffic to them

I don't know enough about fly's internal networking but until we know otherwise I'm going to assume they are all operating on the same subnet (at least those in the same region) and utilize a single outbound IP that external services see, just like we had with Heroku

**Comment by chris48s** [comment]
I guess so. The thing I haven't figured out is why if I SSH into the staging instance on fly I get a 429 making the request by running this node script:

```js
import { AurMaintainer } from './services/aur/aur.service.js'
import { fetch } from './core/base-service/got.js'

const aur = new AurMaintainer(
  { requestFetcher: fetch, authHelper: {}, metricHelper: {} },
  { handleInternalErrors: function () {} }
)

const result = await aur.handle({ packageName: 'sunshine' })
```

but if I run

```
wget -U "Shields.io/2374962" -q -S -O - "https://aur.archlinux.org/rpc?v=5&type=info&arg=sunshine"
```

that's a 200.

That detail is baffling.

**Comment by calebcartwright** [comment]
Quite baffling indeed. Definitely something we should ask them about if/when we hopefully chat. We've seen other cases where a rate limiting implementation diverged from documentation so perhaps there's something additional going on

**Comment by ReenigneArcher** [comment]
As a temporary workaround, I've created a github action that caches the responses from the aur once a day, and uploads/replaces the json files in the release. https://github.com/SunshineStream/service-repo/blob/master/.github/workflows/cache_aur_package_metadata.yml

Then use a json query badge like so

https://img.shields.io/badge/dynamic/json?color=blue&label=AUR&style=for-the-badge&query=$.results.0.NumVotes&url=https%3A%2F%2Fgithub.com%2FSunshineStream%2Fservice-repo%2Freleases%2Fdownload%2Fdaily%2Faur_sunshine-git.json&logo=archlinux
