### ISSUE TITLE
go Badge: Go repo not found, branch not found, or go.mod missing

### ISSUE THREAD

**Issue by michael-observerly** [badges/shields#7886]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm currently seeing an issue with a badge in relation to my Go repo, and the three issues that the badge is reporting are not as far as I can see affecting my repo. Could someone please advise?

### 🔗 Link to the badge

https://camo.githubusercontent.com/3265ce97cf4191cc9be521081ca6c3b2b1493bd5cb6569a305a8a9470149b69e/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f676f2d6d6f642f676f2d76657273696f6e2f6f627365727665726c792f6475736b

**Comment by chris48s** [comment]
The link you've provided is to a cached image. Also its a cached image of working badge. There's not really much to go on here.
If there is still an issue to follow up, can you re-open with the link to the badge. It would be something like `https://img.shields.io/github/go-mod/go-version/<user>/<repo>` rather than `https://camo.githubusercontent.com...`
Thanks
