### ISSUE TITLE
Chocolatey badge shows wrong value

### ISSUE THREAD

**Issue by slonopotamus** [badges/shields#7931]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

https://img.shields.io/chocolatey/v/stevedore badge says that latest version is `v101.0.4951.54` while in fact latest version is [0.6.1](https://community.chocolatey.org/packages/stevedore/0.6.1). I'm not sure where that `v101.0.4951.54` string comes at all.

### 🔗 Link to the badge

https://img.shields.io/chocolatey/v/stevedore
![](https://img.shields.io/chocolatey/v/stevedore)

**Comment by slonopotamus** [comment]
UPD: now it shows `v1.2.9.0`...

**Comment by calebcartwright** [comment]
Seems likely to be an upstream issue. Assuming there's been no recent massive changes to the Chocolatey API surface, the following is the API target for your `stevedore` package:

https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true

For whatever reason, this is (at least at the moment) issuing a redirect to the results for `7zip` instead:

```bash
$ curl -I "https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true"
HTTP/2 301 
date: Sun, 08 May 2022 01:27:47 GMT
content-type: text/html
location: https://chocolatey.org/api/v2/Packages()?$filter=(tolower(Id)%20eq%20'7zip')%20and%20IsLatestVersion&includePrerelease=false&$top=80&includeAllVersions=false
x-github-request-id: 15C2:26B5:952BBA:E51B0D:62771A06
accept-ranges: bytes
via: 1.1 varnish
age: 653
x-served-by: cache-dfw18668-DFW
x-cache: HIT
x-cache-hits: 1
x-timer: S1651973268.539109,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: 86f1eb503f9863dcc91dab58a41f86b4d1f96215
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=12960000
x-content-type-options: nosniff
server: cloudflare
cf-ray: 707e6a39f8ab8173-DFW
```

This also occurs for some other packages I checked, like `git`.

We're not a system of record, so we work with whatever data the systems of record give back to us which is why the badge is displaying these versions. Going to label this issue as blocked on the upstream service for now, though also wouldn't be surprised if we need to switch to a different endpoint.

**Comment by slonopotamus** [comment]
Weird. I'll report this to Chocolatey and leave a link to upstream issue here.

**Comment by chris48s** [comment]
I've checked this badge a couple of times over the last few days but hadn't had time to really dig into it locally. I've seen the badge showing all kinds of different values - there is clearly something strange going on here.

The super odd thing is if I try the badge on my local install I'm getting 0.6.1 and if I call `curl -I "https://www.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true"` I'm getting a redirect to `location: https://chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true` but the badge requested from `img.shields.io` is showing a totally different value.

I'm glad you've managed to reproduce the same issue we're seeing server-side @calebcartwright as I am not seeing the same thing locally. I agree the problem is upstream. Very strange.

**Comment by calebcartwright** [comment]
> I'm getting a redirect to location: https://chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true but the badge requested from img.shields.io is showing a totally different value.

I wonder if it may be GTM related given both I and prod are in the US vs the UK

**Comment by gep13** [comment]
Can I suggest that you try the following:

https://community.chocolatey.org/api/v2/Packages()?%24filter=Id+eq+%27stevedore%27+and+IsLatestVersion+eq+true

As pointed out in the referenced issue, using the API directly is not recommended, as things can, and do, change.

**Comment by slonopotamus** [comment]
> Can I suggest that you try the following

_Currently_ it returns correct value for me (testing from multiple subnets around the globe).

I've created #7952 to switch to new URL
