### ISSUE TITLE
Add [Sonatype Lift] badge

### ISSUE THREAD

**Issue by doddi** [badges/shields#8047]
:clipboard: **Description**

This request is to add a badge for Sonatype Lift (lift.sonatype.com
The information provided will represent if a given repository is currently enabled by sonatype Lift analysis

:link: **Data**

Sonatype Lift will be publishing a badge endpoint at https://lift.sonatype.com/api/badge

The API will be as follows:

`/api/badge/<owner>/<repo>`

```
{
  label: <label to be displayed>
  message: <message to be displayed>
  url: <url to the repository reports>
}
```

:microphone: **Motivation**
Project maintainers can use the badge to show to the public that their repository is being protect by [Sonatype Lift](https://lift.sonatype.com) tools

**Comment by calebcartwright** [comment]
Thanks for reaching out!

While I do agree that Sonatype Lift is the type of service we'd be willing and interested in providing badges for, I'm not convinced the particular data point proposed here is a relevant/worthwhile one for us to provide natively. Additionally, and apologies as we've still not documented this yet, but we do not want to provide native badges that are actually based on our Endpoint badge, as is proposed here (see also https://github.com/badges/shields/pull/5701#discussion_r513048352), so the approach wouldn't be viable either.

My opposition to the badge is due to it seeming to likely be in violation of the branding/marketing clause in [our badge specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md). Whereas it'd make sense and I'd be a :+1: for a badge that displayed analysis result/etc. type of info, I just don't see us adding a badge that conveys anything to the effect of "I use some named service/tool". If you'd be interested in seeing something like the former then please feel free to open a new issue with relevant details.

I'd like to close this as a won't fix/implement, but will wait for a bit lest any other maintainer(s) strongly disagree with me.

**Comment by doddi** [comment]
@calebcartwright thank you for your detailed response. I totally understand your concerns. I'm not asking for a change to your concerns but thought I would convey why we took this approach on this first PR.

It is our first badge and I made label, message etc all dynamic to allow us to iterate quicker (changes on our end rather than an external PR once we establish what to provide in the badge) so we can probably make this more static and fit your requirements.

Sonatype Lift doesn't just provide a single data point on analysed projects, so this initial badge was just to get 'something' available with the intent to add multiple badges, vulnerabilities, code quality findings etc. We just hadn't decided on how to present our data and what just yet.

**Comment by calebcartwright** [comment]
> It is our first badge and I made label, message etc all dynamic to allow us to iterate quicker (changes on our end rather than an external PR once we establish what to provide in the badge) so we can probably make this more static and fit your requirements.

Understand the desire to get something out quickly, but the part I want to stress is that Shields must and will set the badge values for the badges we provide natively. The Endpoint badge is essentially a power form of the Dynamic badge, or for cases where users want a badge for more bespoke cases or services, or which require private authentication. We don't want to directly consume our own Endpoint model for native badges, and certainly not in a way that cedes control of those defaults.

We'd love to still collaborate on any future badges, but I given the context of this thread it might be advisable to first discuss the target badge(s).

In the interim, I do think there's aspects of our service (or even just the spec itself) you could utilize to get badges to your users, but we'll just want to go a different route for adding any native badges to our catalog.
