### ISSUE TITLE
[Feature] Ability to format numbers in short form when using dynamic JSON badges

### ISSUE THREAD

**Issue by DenverCoder1** [badges/shields#8075]
:clipboard: **Description**

If for example a JSON API endpoint you want to use has a number, eg:

```json
{
    "count": 1234
}
```

When using this endpoint on a dynamic badge, it would be nice to be able to make use of a number formatter to make its appearance more similar to other badges from shields.io.

Eg, using the JSON above, you could make a badge:

```md
https://img.shields.io/badge/dynamic/json?formatter=metric&color=088&label=count&query=%24.count&url=https%3A%2F%2Fexample.com
```

Which would display like:

![image](https://user-images.githubusercontent.com/20955511/173279223-6b419276-0d91-4f76-8cbe-a67bbaa8de4e.png)

Instead of:

![image](https://user-images.githubusercontent.com/20955511/173279258-debb6167-fa91-4149-bd7e-b652fcc52e37.png)

In this example, I have used `formatter=metric` to show a possible way this could be requested in the URL, this is open to alternative suggestions.

### Text formatters

To add to this, possibly more formatters from https://github.com/badges/shields/blob/master/services/text-formatters.js can be supported.

- none
- starRating
- ordinalNumber
- metric
- omitv
- addv
- formatDate
- formatRelativeDate

**Comment by calebcartwright** [comment]
I understand the motivation for this and am somewhat sympathetic, but feel we're still opposed to the ask with the same rationale we've articulated elsewhere (e.g. https://github.com/badges/shields/discussions/6135#discussioncomment-329581).

The [Endpoint badge](https://shields.io/endpoint) exists to allow users to apply whatever sort of processing and customization the want to any aspect of the badge, including type-based formatting of the message. In many ways, the Endpoint badge is going after this precise use case.

As such I'm going to close this and the associated PR, though sincerely thank you for providing an accompanying implementation with your idea.

On the off chance any maintainers have changed their positions or would at least like to revisit then we can always reopen.

**Comment by DenverCoder1** [comment]
@calebcartwright

I'm not sure I see how that's a viable alternative.

It seems to me that using the endpoint badge requires writing code and hosting an endpoint.

It is significantly simpler to just add an extra parameter to format badges (similar to `prefix` and `suffix`) to make them look consistent.

For people who don't have a lot of time and just want to use an API not yet supported by shields.io, it takes almost no time to add a parameter to their shields.io badge URL, compared to making an API, throwing an extra middleman into the whole process.

The reasoning for this is not any different from why someone would want `prefix` or `suffix` options. If those are accepted, I don't see why this should not.

If the goal is consistency, this helps that goal as it takes all the work out of allowing users to format their existing badges and dynamic badges with consistent formatting.

**Comment by calebcartwright** [comment]
I realize you're coming into this topic without necessarily having all the background, but this is something that has been discussed at length so I want to be unequivocally clear that this isn't up for debate. 

The above represents our explicit strategy on the topic which has been reaffirmed a few times in the recent past, and which has been our implicit strategy for an even longer period of time. This has been articulated in many places, with the discussion item I shared in my prior response just being one of many.

Here's a snippet from another thread with a good summary and articulation from both Paul and Chris that includes some historical context and some of the additional reasons (taken from #6786)

> I really agree with how Chris put it:
>
>>    The dynamic badges (JSON, XML and Yaml) were our first attempt to provide a way for users to self-serve their own feature requests. They are indeed limited.
>>
>>    As we received feature requests for more customisable functionality, our response to this was to implement the endpoint badge, which is a much more flexible solution, although it does require you to host your own endpoint. Of course, many users still rely on the dynamic badges..
>
> I'll add a few thoughts of my own about the design history of the dynamic and endpoint badges.
>
> The dynamic badge was intended for picking values out of existing JSON files which have values in them which you want to render. Typically these schemas were pre-existing, and not designed for badges. JSONPath provides a fair amount of power, but is really inadequate for all the kinds of things people want. We included support for prefixes and suffixes, but users want more: flexible transforms, number formatting, and colors derived dynamically from values in the JSON file (e.g. "100" means brightgreen). Stuffing all of this into a badge URL makes, well, really difficult-to-read badge URLs. And these are hard to troubleshoot and maintain.
>
> The endpoint badge was our solution for all of this. Do whatever computation you want to do, and put it behind a JSON endpoint you host. Or, run all your transforms, and put the result into a static JSON file. JSON is super readable.
>
> I would prefer that we keep the dynamic badge frozen, as it's been for a long while, rather than go down the slope of extending it for additional cases. The reasoning again is that, while it's easy to implement these customization features on the server, the result is badges which are difficult to read, debug, and maintain.

Yes, we're aware that the Endpoint badge requires users to do a bit more (although it's not as much as you'd think, #2838, especially since we provide json versions of the data for all our own badges, e.g. https://img.shields.io/github/v/release/angular/angular.json), but that's the tradeoff with the solution we're willing to support.

Again, if any maintainers have had a change of heart and want to revisit the topic then we'll circle back here or in a new issue. However, the matter is currently settled and we'll be treating it as such.

**Comment by DenverCoder1** [comment]
Thanks for the response, but I'm going to have to disagree and I hope it is reconsidered.

I definitely would find it very useful as well as I'm sure many others as well.

In the meantime, I'm hosting my fork of the repo at https://formatted-dynamic-badges.herokuapp.com/

I find this approach will save a lot of time since it's just one endpoint and it doesn't require creating a new one for each dynamic badge.

I'm using it already on my profile readme, so now I can format the number with:

<https://formatted-dynamic-badges.herokuapp.com/badge/dynamic/json?formatter=metric&label=Stars&style=for-the-badge&query=%24.stars&url=https://api.github-star-counter.workers.dev/user/DenverCoder1>

![formatted](https://formatted-dynamic-badges.herokuapp.com/badge/dynamic/json?formatter=metric&label=Stars&style=for-the-badge&query=%24.stars&url=https://api.github-star-counter.workers.dev/user/DenverCoder1)

Instead of using shields.io:

https://img.shields.io/badge/dynamic/json?label=Stars&style=for-the-badge&query=%24.stars&url=https://api.github-star-counter.workers.dev/user/DenverCoder1

![shields](https://img.shields.io/badge/dynamic/json?label=Stars&style=for-the-badge&query=%24.stars&url=https://api.github-star-counter.workers.dev/user/DenverCoder1)

If anyone else comes across this issue, they can feel free to use my self-hosted version as well.

**Comment by calebcartwright** [comment]
I've deleted the last comment and am locking this thread.

I've deleted the comment because while I'm sure you had good motivations and wanted to help others by encouraging the use of your fork of the project, I'm not going to let our issue tracker be used to promote/market an entire fork of this project.

To be honest, I feel like a fork of the project is a rather extreme and unnecessary step in response to not getting a capability you want in the way you wanted it. There's a lot of alternative ways in which one could support use cases while directly participating in the ecosystem instead of bifurcating it.

Again, the Endpoint badge model is extremely powerful and supports a plugin type of architecture. One of the things we've had people do is create and share their Endpoints for others to consume, sometimes directly on issues/requests (e.g. #4964) and we'd also like to use our [Awesome Badges](https://github.com/badges/awesome-badges) collection to highlight things like highly desirable Endpoints.

I would suggest that a custom Endpoint that provides the types of transformations you'd like to support would be much more concise (dozens of lines of code) and free to host using the Endpoint model as opposed to forking and hosting the entire server.

I am locking the thread because this has been resolved for a while now and is not a matter of subjective material that needs to be debated.

Nothing new has been shared here, but is simply a somewhat myopic rehashing of a fairly small subset of the broader discussion, requests and arguments that have been made before in many previous issues and PR (only a couple of which have been shared here in prior comments). We have to look at the project holistically and in that much broader context; it's not about whether someone "would find it very useful" but about what makes sense for the project as a whole.
