### ISSUE TITLE
pub.dev badges for Dart and Flutter with logo - take over badges.bar

### ISSUE THREAD

**Issue by bruno-garcia** [badges/shields#8086]
I'm a longtime [fan of this project](https://opencollective.com/bruno) and service.

I've been [maintaining project](https://github.com/bruno-garcia/badges.bar) and service called [badges.bar](https://badges.bar/). It includes the Dart icon on the left, and the pub points/popularity/likes, just like shields provides today. I'm planning to eventually sunset this service so I wonder if shields would be able to render a similar looking badge to what badges.bar currently does. And would like to take over the domain and redirect to it.

**Comment by calebcartwright** [comment]
Thanks for reaching out and for your support of this project!

As you noted, we already provide badges with the same data points, so my understanding of your ask is that we change our existing badges to look more like badges.bar. In short, no I don't think that's something we'd be willing to do. 

Our badges are based on our own [specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) and approach to defaults. As such any changes to our pub.dev badges would start diverging from the way we do things. We [support the ability](https://github.com/badges/shields/blob/master/doc/logos.md) for our users to inject logos into our badges, but it's not something we do by default with these types of badges.

Accordingly, I really don't think it would make sense for us to take on any of the domain/networking aspects of badges.bar either. You could consider incorporating the redirect yourself (including with the `?logo=...` param if you'd like to maintain those) but I don't think there's anything we can/will do from our end.

Will leave this open for a bit though to allow others from the ops and/or core team to weigh in

**Comment by chris48s** [comment]
I think broadly we wouldn't be looking to take on the domain or service itself.

That said (and expanding on Caleb's comment), if you are looking to sunset badges.bar and direct users to use our dart/pub badges instead, my suggestion would be to replace it with some redirects. So you retain control of the badges.bar domain but replace what is running there now with a very lightweight service that implements the following logic:

- if it gets a request to https://badges.bar/sentry/likes you issue a 301 redirect to https://img.shields.io/pub/likes/sentry?logo=dart
- if it gets a request to https://badges.bar/sentry/popularity you issue a 301 redirect to https://img.shields.io/pub/popularity/sentry?logo=dart
- if it gets a request to https://badges.bar/sentry/pub%20points you issue a 301 redirect to https://img.shields.io/pub/points/sentry?logo=dart

You can probably find hosting that allows you to operate that at low or zero cost and "set it and forget it". This would allow you to stop maintaing the service but preserve continuity of service for your existing users.

You could also use the existing customisations (such as they are) to make our badges look a bit more like yours if you wanted. For example

- Instead of redirecting https://badges.bar/sentry/pub%20points to https://img.shields.io/pub/points/sentry?logo=dart you could redirect to https://img.shields.io/pub/points/sentry?logo=dart&label=pub%20points to retain the same label
- Instead of using the SimpleIcons logo, you could redirect to a URL that uses a custom one. e.g: https://img.shields.io/pub/likes/sentry?logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCI+PHBhdGggZD0iTTE3LjU4MiAxNy40MjRsLTQuMTM4LTQuMTQuMDE2IDI5LjkwMy4wNSAxLjM5NmMuMDIuNjYuMTQ1IDEuNC4zNDUgMi4xN2wzMi43NzUgMTEuNTYgOC4yLTMuNjMuMDA3LS4wMTJMMTcuNTggMTcuNDI0eiIgZmlsbD0iIzAwYzRiMyIvPjxwYXRoIGQ9Ik0xMy44NTYgNDYuNzUzaC4wMDNjLS4wMDMtLjAxMi0uMDA4LS4wMjYtLjAxNC0uMDQuMDA3LjAxNS4wMDcuMDMuMDEuMDR6bTQwLjk2NiA3LjkzbC04LjIgMy42My0zMi43Ny0xMS41NmMuNjI1IDIuNDA0IDIuMDEyIDUuMTA2IDMuNTAyIDYuNThsMTAuNjkgMTAuNjM3IDIzLjc4OC4wMyAyLjk4LTkuMzE3eiIgZmlsbD0iIzIyZDNjNSIvPjxnIGZpbGw9IiMwMDc1YzkiPjxwYXRoIGQ9Ik0xMy41NTYgMTMuMjg1TC44MTMgMzIuNTNjLTEuMDU4IDEuMTMtLjUzIDMuNDYyIDEuMTczIDUuMThsNy4zNTYgNy40MTYgNC42MjQgMS42M2MtLjItLjc2OC0uMzI2LTEuNS0uMzQ1LTIuMTdsLS4wNS0xLjM5Ni0uMDE1LTI5LjkwM3oiLz48cGF0aCBkPSJNNDYuOSAxMy42N2MtLjc3LS4xOTUtMS41MDgtLjMxOC0yLjE3My0uMzM3bC0xLjQ3OC0uMDU0LTI5LjgwNS4wMDcgNDEuMzkyIDQxLjM4NiAzLjYzNi04LjItMTEuNTctMzIuOHoiLz48L2c+PHBhdGggZD0iTTQ2Ljg2MiAxMy42NjNjLjAxMy4wMDUuMDI3LjAwOC4wMzguMDF2LS4wMDRjLS4wMTMtLjAwMy0uMDI1LS4wMDMtLjAzOC0uMDA4em02LjYxNSAzLjUxOGMtMS41MDUtMS41MTUtNC4xNy0yLjktNi41NzctMy41MDhMNTguNDcgNDYuNDdsLTMuNjQgOC4yIDguODgyLTIuODM4LjAyLTI0LjM1Mi0xMC4yNTYtMTAuM3oiIGZpbGw9IiMwMGE4ZTEiLz48cGF0aCBkPSJNNDUuMjc4IDkuMDc1bC03LjQtNy4zNkMzNi4xNTIuMDE4IDMzLjgyLS41MTIgMzIuNy41NDRsLTE5LjI0NCAxMi43NCAyOS44MDUtLjAwNyAxLjQ3OC4wNTRjLjY2NS4wMiAxLjQwNC4xNDIgMi4xNzMuMzM3TDQ1LjI4IDkuMDczem0tMzEuODMzIDQuMiIgZmlsbD0iIzAwYzRiMyIvPjwvc3ZnPg==
- etc

Additionally, although we probably wouldn't directly take changes to the pub badges just to make them look more like the ones at badges.bar, if you have suggestions for improvements to the pub badges which meet [our usual guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines), feel free to contribute.

**Comment by bruno-garcia** [comment]
> * if it gets a request to [badges.bar/sentry/likes](https://badges.bar/sentry/likes) you issue a 301 redirect to [img.shields.io/pub/likes/sentry?logo=dart](https://img.shields.io/pub/likes/sentry?logo=dart)
> * if it gets a request to [badges.bar/sentry/popularity](https://badges.bar/sentry/popularity) you issue a 301 redirect to [img.shields.io/pub/popularity/sentry?logo=dart](https://img.shields.io/pub/popularity/sentry?logo=dart)
> * if it gets a request to [badges.bar/sentry/pub%20points](https://badges.bar/sentry/pub%20points) you issue a 301 redirect to [img.shields.io/pub/points/sentry?logo=dart](https://img.shields.io/pub/points/sentry?logo=dart)

These look good, and would serve as a replacement.

The main reason I'm reaching out is because I don't have the time to maintain the project and also because I don't want to continue to pay for the domain. If you folks don't want to take over the domain, I think I'll just set a date to sunset the service and suggest that folks adopt shields instead.

Thanks for your reply.

**Comment by SantiiRepair** [comment]
Any final solution?

**Comment by bruno-garcia** [comment]
You can use shields.io:

Example:
* https://github.com/getsentry/sentry-dart/pull/889
