### ISSUE TITLE
Badges for Coveralls.io code coverage do not support GitLab repositories

### ISSUE THREAD

**Issue by othalan** [badges/shields#8132]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The Coveralls.io badges for code coverage support github and bitbucket only. 
However, Coveralls.io also integrates with GitLab. 
There is no option to select a GitLab repository and adding 'gitlab' to the url manually fails.

**Comment by chris48s** [comment]
This should not be hard to add, but we'll need to convert branch to a query param and set up a redirect for the legacy routes because on gitlab the repo can be nested in sub-organisations. This means both the `user/repo` bit of the url and the `branch` can contain an arbitrary number of slashes.

https://github.com/badges/shields/blob/16fdf3251b8936508062fd98c3266c7143957078/services/coveralls/coveralls.service.js#L13

Do know an example of any public repos on gitlab that use coveralls we can use for testing?

**Comment by othalan** [comment]
> Do know an example of any public repos on gitlab that use coveralls we can use for testing?

You can use my new project, wsrouter, which I recently released as open source:

GitLab: https://gitlab.com/selcouth/wsrouter

Coveralls: https://img.shields.io/coveralls/github/selcouth/wsrouter

**Comment by PaulaBarszcz** [comment]
I would like to work on this issue.
