### ISSUE TITLE
Gitlab Badges not working for Private Repositories

### ISSUE THREAD

**Issue by CanisHelix** [badges/shields#8143]
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

On a self-hosted solution (Docker), with the GITLAB_ORIGINS and GITLAB_TOKEN defined as environment variables. Badges for private repositories on Gitlab.com are returning 'project not found'.

At request on Discord, enabling TRACE_SERVICES reveals that the gitlab password is not being picked up.

```
        url: URL {
          href: 'https://gitlab.com/api/v4/projects/<project id>/repository/contributors?page=1&per_page=1',
          origin: 'https://gitlab.com',
          protocol: 'https:',
          username: '',
          password: '',
          host: 'gitlab.com',
          hostname: 'gitlab.com',
          port: '',
          pathname: '/api/v4/projects/<project id>/repository/contributors',
          search: '?page=1&per_page=1',
          searchParams: URLSearchParams { 'page' => '1', 'per_page' => '1' },
          hash: ''
        },
```

Mounting a local.yml into the container also produces the same. So neither solution picks up a password for Gitlab.com at the moment.

**Comment by chris48s** [comment]
Thanks for moving the conversation over here from Discord.

Working out that the credentials aren't getting set is a step forward.

You said you are running this using docker. Are you running one of the tagged releases https://registry.hub.docker.com/r/shieldsio/shields/tags?page=1&ordering=last_updated if so which one? If you're just pulling from the next tag or building your image locally are you able to give us the SHA? I'd like to try and reduce this to a minimal repro.

**Comment by calebcartwright** [comment]
Echo the sentiment about shifting to an issue, thanks!

Think we may want to change the title to reduce the scope.

I've confirmed that the auth is being sent for all other GitLab badges (license, tags, releases) but isn't for the Contributors badge and that's due to the approach taken with that particular badge being different from the others in terms of how the request is made and how the request is processed.

Note that it's not utilizing the `fetch` function defined in the GitLab base class which is what wires up the respective GitLab auth

https://github.com/badges/shields/blob/0ceb558bb4262b22f9e089d5935c3f926a4f28c8/services/gitlab/gitlab-contributors.service.js#L61-L70

So that's at least one problem. Next it would be good if you can test the same project with another badge, like tag, release, or license. As discussed in chat, the debug output from `TRACE_SERVICES` will show that the response headers include the rate limit changes for the associated token so it is being accepted at least in the sense that GitLab isn't treating the request as a 403/4xx error and is treating each request as a hit on the rate limit. However, there could still be a subsequent auth related issue that's being obfuscated

**Comment by CanisHelix** [comment]
Releases:

```
        url: URL {
          href: 'https://gitlab.com/api/v4/projects/<project id>/releases?page=1',
          origin: 'https://gitlab.com',
          protocol: 'https:',
          username: '',
          password: '',
          host: 'gitlab.com',
          hostname: 'gitlab.com',
          port: '',
          pathname: '/api/v4/projects/<project id>/releases',
          search: '?page=1',
          searchParams: URLSearchParams { 'page' => '1' },
          hash: ''
        },
````

Tags:
```
    requestUrl: URL {
      href: 'https://:<GITLAB_TOKEN>@gitlab.com/api/v4/projects/<project id>/repository/tags?order_by=updated',
      origin: 'https://gitlab.com',
      protocol: 'https:',
      username: '',
      password: '<GITLAB_TOKEN>',
      host: 'gitlab.com',
      hostname: 'gitlab.com',
      port: '',
      pathname: '/api/v4/projects/<project id>/repository/tags',
      search: '?order_by=updated',
      searchParams: URLSearchParams { 'order_by' => 'updated' },
      hash: ''
    },
```

Both return 404

**Comment by calebcartwright** [comment]
Linked PR #8145 should address everything but the Contributors badge

**Comment by chris48s** [comment]
Aah yes - the contributors badge is my bad. It doesn't use the `fetch` function from `GitLabBase` because we wanted to validate and use values from the headers rather than the body. We'll have to replicate the use of `withBearerAuthHeader()` when we call `_request()`.
