### ISSUE TITLE
Margin Top parameter

### ISSUE THREAD

**Issue by snoweuph** [badges/shields#8253]
:clipboard: **Description**

A parameter like ?top_margin=10px that will add a margin to the top of the Badges image.

Why  Im suggestion that: 

looking at this example:

- Text: ![JDK_NAME](https://img.shields.io/static/v1?label=JDK_NAME&message=vX.X.X&color=orange&style=plastic)
- Text: ![OS_NAME](https://img.shields.io/static/v1?label=OS_NAME&message=VERSION_AND_ARCHITECTURE&color=yellow&style=for-the-badge)

Im a little bit triggered that that isn't centered, I know that this is a Github problem, but it can also be easaly befixed by allowing to set the Top margin of the Image

**Comment by calebcartwright** [comment]
Thanks for reaching out.

I'd be pretty strongly opposed to incorporating such a parameter, as I think that quickly runs afoul of both our goals, specification, and position we've held elsewhere on requests for other such parameters.

If there is an issue with vertical alignment in one more styles, then I think that's something we should look at directly, and correct if necessary.

Additionally, I think the plastic style is actually centered, it's just the dimensional nature of the style that may make the text appear slightly off center

https://img.shields.io/badge/JDK_NAME-vX.X.X-orange?style=plastic
![](https://img.shields.io/badge/JDK_NAME-vX.X.X-orange?style=plastic)

https://img.shields.io/badge/JDK_NAME-vX.X.X-orange?style=flat-square
![](https://img.shields.io/badge/JDK_NAME-vX.X.X-orange?style=flat-square)

The FTB _may_ be slightly off, but it's a bit hard to tell. Here's some different flavors for comparison

https://img.shields.io/badge/OS%20NAME-VERSION%20AND%20ARCHITECTURE-yellow?style=for-the-badge
![](https://img.shields.io/badge/OS%20NAME-VERSION%20AND%20ARCHITECTURE-yellow?style=for-the-badge)

https://img.shields.io/badge/OS_NAME-VERSION_AND_ARCHITECTURE-yellow?style=for-the-badge
![](https://img.shields.io/badge/OS_NAME-VERSION_AND_ARCHITECTURE-yellow?style=for-the-badge)

https://img.shields.io/badge/OS__NAME-VERSION__AND__ARCHITECTURE-yellow?style=for-the-badge
![](https://img.shields.io/badge/OS__NAME-VERSION__AND__ARCHITECTURE-yellow?style=for-the-badge)

Perhaps one of my fellow maintainers that have more experience with old templates/badge-maker package could weigh in whether this is expected behavior

**Comment by snoweuph** [comment]
![grafik](https://user-images.githubusercontent.com/76737863/181645445-797ebf8c-2731-4241-a25c-f1bbc8465504.png)

this is how it looks for me, and I think its clearly to see.

I thought about it and there is actually another thing that would work, that wouldn't add a new parameter: a new style, a style that has about 65% of the hight of the plastic style

or if a new parameter where an option an overall scaling parameter would also work, allowing to make it smaller.

the only 2 ways to center it in github would be a margin of transparency on top or a smaller scaling

**Comment by snoweuph** [comment]
> Perhaps one of my fellow maintainers that have more experience with old templates/badge-maker package could weigh in whether this is expected behavior

To that thing is expected behavour 
![grafik](https://user-images.githubusercontent.com/76737863/181646060-615ed66d-9c48-4adf-a0cc-4463fa3cca71.png)

**Comment by calebcartwright** [comment]
> this is how it looks for me, and I think its clearly to see.

Thanks for including a screenshot and reiterating your position. I don't really have anything else to say that's not going to be duplicative of my prior comments so I'll just leave it at: the plastic style looks right to me; the FTB is tougher to tell for me because it is impacted by the explicit underscore characters.

> I thought about it and there is actually another thing that would work, that wouldn't add a new parameter: a new style, a style that has about 65% of the hight of the plastic style
>
> or if a new parameter where an option an overall scaling parameter would also work, allowing to make it smaller.

This is also a hard no for me. I realize you don't have all the backstory around our past discussions and decisions, but tl;dr, we determined quite some time ago that we're not going to take on the maintenance burden of any additional styles. Additionally, the same comment I made previously applies for the alternative parameter you suggested.

> To that thing is expected behavour

I am aware :wink: It seems like you misunderstood my comment which was directed at the team. To elaborate for clarity however, my question to them is whether or not the FTB spacing is _intentional_. It's based on https://forthebadge.com/ and at first glance what we have seems consistent to me.

If it's not intentional, then we'd want to address that by correcting the FTB style (and any other styles suffering from a similar issue). We would not want to address that by expanding the parameter surface nor by adding an entirely new style.

However, if it is intentional then I think you're probably out of luck. Though since you seem to be working with static badges you could always grab the initial svgs from us and tweak them to your liking yourself.

**Comment by snoweuph** [comment]
Thx for the more detailed explanation. I actually wanted to use these badges inside of Issue Templates and let the user easaliy tweak the parameters while having it looking nicer then just GitHub markdown, but it is how it is, I will play around a little more and maybe I will find something that is to my liking :)

**Comment by calebcartwright** [comment]
You keep implying that GitHub is a factor, could you elaborate on why you think that's the case?

We're quite familiar with GitHub's processes for rendering certain types of content via camo for anonymization and proxying, but I wouldn't expect GitHub to manipulate that actual content and your badges look the same for me in GitHub as they do outside of GitHub

**Comment by snoweuph** [comment]
What I'm trying to imply is that because of how GitHub positions Images is isn't centered

**Comment by chris48s** [comment]
I haven't actually worked it out pixel by pixel, but if the text positioning is slightly off in the FTB style, we should fix it so it is centred, not add a param to allow users to manually reposition the text. However.....

One variable we've not talked about here is fonts: When we render the badge the SVG output contains

```
font-family="Verdana,Geneva,DejaVu Sans,sans-serif"
```

This means if you don't have Verdana installed, it will render with Geneva. If you don't have Geneva, it will fall back to DejaVu Sans and if you don't have that it will pick your system's default sans-serif font, which might be all sorts of things. All of the measurements are based on the text being rendered using Verdana. We've tried to pick fallback fonts which are as close as possible in measurements, but the further you go down the fallback list the more skewey its going to get, especially if you get all the way to sans-serif. I'm not a font expert but looking at the screenshot you've posted in https://github.com/badges/shields/issues/8253#issuecomment-1198680450 I think you're probably looking at the badges rendered in DejaVu Sans (?) so if the centring isn't 100% pixel perfect that is kind of par for the course.

If the measurements are bang on in Verdana but slightly off in DejaVu Sans, then its working as expected.

**Comment by calebcartwright** [comment]
@snoweuph - perhaps I've misunderstood you as well.

I assumed you were referring to the position of the text _within_ the badge (e.g. the `VERSION_AND_ARCHITECTURE` string within the badge), but are you referring the placement of the badge on the _page_, relative to the text you have to the left of the badge (the literal `Text:`)?

Everything said from our side so far is about the former, but if you're talking about the latter then we can go ahead and close this. If you want finer grained control over how the markdown is rendered, you'll probably want to consider using html directly. We have absolutely no control/influence over how renders choose to place the images we provide, and there's absolutely nothing we can do (parameters or otherwise) that would impact that

**Comment by snoweuph** [comment]
> @snoweuph - perhaps I've misunderstood you as well.
> 
> I assumed you were referring to the position of the text _within_ the badge (e.g. the `VERSION_AND_ARCHITECTURE` string within the badge), but are you referring the placement of the badge on the _page_, relative to the text you have to the left of the badge (the literal `Text:`)?
> 
> Everything said from our side so far is about the former, but if you're talking about the latter then we can go ahead and close this. If you want finer grained control over how the markdown is rendered, you'll probably want to consider using html directly. We have absolutely no control/influence over how renders choose to place the images we provide, and there's absolutely nothing we can do (parameters or otherwise) that would impact that

I was speaking about the placement all along. Ive tryed html with css, but sadly github ignores css for the html. I dunno how the missunderstanding came together, because I was speaking about margin and not padding.

well, becuase you wont implement a parameter for the outside margin of the badge I will just have to live with it or make my own fork with it.

**Comment by snoweuph** [comment]
With Margin I understand Outside spacing and under Padding I understand Inside spacing. Speaking about Margin on the Badge I mean spacing on the Outside of the Badge. What you thought I meant I would refere to Margin on the Text or Padding on the Badge.
