### ISSUE TITLE
Badge request: stars for github gist

### ISSUE THREAD

**Issue by maratori** [badges/shields#8269]
:clipboard: **Description**

Please add dynamic badge to show number of stars for github gist (not repo).

Example: [![GitHub Gist stars](https://img.shields.io/badge/stars-11-white?style=social&logo=github)](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322)

:link: **Data**

Looks like need to use GraphQL: https://docs.github.com/en/graphql/reference/objects#gist
```graphql
{
  user(login: "maratori") {
    gist(name: "47a4d00457a92aa426dbd48a18776322") {
      stargazerCount
    }
  }
}
```
As far as I understand, it requires authentication.

:microphone: **Motivation**

It'd be great to add this badge into my [github profile](https://github.com/maratori#-useful-gists).

**Comment by Abhiyadav02** [comment]
spyder

**Comment by notanmay** [comment]
hi @chris48s , i would like to work on this issue, can you please elaborate a little bit on how to go on to solve this issue?

**Comment by chris48s** [comment]
Our tutorial is at https://github.com/badges/shields/blob/master/doc/TUTORIAL.md That covers most of the basics for adding a new badge and writing tests.

For this specific badge you will need to set your local copy up with a github api token by setting

```yml
private:
  gh_token: 'your-token-here'
```

in `config/local.yml`.

Because this badge will use a GraphQL query, you will need to write a new service class that extends `GithubAuthV4Service`. If you have a look at other services which extend `GithubAuthV4Service` https://github.com/badges/shields/search?q=GithubAuthV4Service you can find some similar examples to crib from.

**Comment by notanmay** [comment]
okay, i get it, thanks for your help

**Comment by notanmay** [comment]
hi @chris48s , I have written a new service class for this issue and tests as well. although I am confused about what should be passed as a GitHub username? 
We can pass any username until the username actually exists.  
So, this is valid:
`{
  user(login: "**maratori**") {
    gist(name: "47a4d00457a92aa426dbd48a18776322") {
      stargazerCount
    }
  }
}`
`API: "github/stars/gists/maratori/47a4d00457a92aa426dbd48a18776322"`

and even this is valid(even if the user does not own the gist): 
`{
  user(login: "**notanmay**") {
    gist(name: "47a4d00457a92aa426dbd48a18776322") {
      stargazerCount
    }
  }
}`
`API: "github/stars/gists/notanmay/47a4d00457a92aa426dbd48a18776322"`

I thought about taking input from the user for username, but that would be a bad user experience, because stargazerCount would be returned for any username(that resolves to actual account!). 

I looked in other classes that extend `GithubAuthV4Service ` class but couldn't find any help.
Is it a good idea to retrieve username from the provided `gh_token` ? 
It would be great if you can help me in this, thanks.
