### ISSUE TITLE
Downloads shield shows total 0, what am I missing?

### ISSUE THREAD

**Issue by Cigaras** [badges/shields#833]
I could not find information on how to configure this, whatever I do it always shows 0, please help, what am I missing? I did authorize shield.io with github at https://img.shields.io/github-auth

[![Github All Releases](https://img.shields.io/github/downloads/cigaras/iptv.bundle/total.svg)](https://github.com/Cigaras/IPTV.bundle)

Link to my project: https://github.com/Cigaras/IPTV.bundle
Link to shield: https://img.shields.io/github/downloads/Cigaras/IPTV.bundle/total.svg

**Comment by RedSparr0w** [comment]
if you have a look at the [API response](https://api.github.com/repos/Cigaras/IPTV.bundle/releases) there does not seem to be a `download_count` field, which could either mean no one has downloaded it via the [github releases page](https://github.com/Cigaras/IPTV.bundle/releases) or it hasn't been updated with recent stats yet.

**Comment by Cigaras** [comment]
I got that, source code doesn't count, I need to upload a binary.

**Comment by gradinkov** [comment]
So it's basically useless for scripting projects that don't have binaries. That's not too helpful.

**Comment by calebcartwright** [comment]
FWIW The badge linked in the original post is showing 24k downloads now. 

@ElfQrin I don't have much context around what you're working with/trying to show, but if you'd like to open a new issue we'd be happy to see if we can help.

**Comment by ElfQrin** [comment]
Thank you @calebcartwright , I've just opened a ticket here:

https://github.com/ElfQrin/webservertest/issues/1

**Comment by freescout-helpdesk** [comment]
> I got that, source code doesn't count, I need to upload a binary.

It looks like your counter is working now. How did you solve this issue? It looks like there is no any binary in your repo https://github.com/Cigaras/IPTV.bundle

**Comment by RedSparr0w** [comment]
There are releases now in their repo, which is the download stats that are being counted:
https://github.com/Cigaras/IPTV.bundle/releases

**Comment by freescout-helpdesk** [comment]
> There are releases now in their repo, which is the download stats that are being counted:
> https://github.com/Cigaras/IPTV.bundle/releases

Thanks. We also have releases in our [repo](https://github.com/freescout-helpdesk/freescout/releases), but github API shows no `download_count`: https://api.github.com/repos/freescout-helpdesk/freescout/releases

By some reason `assets` parameter which contains `download_count` is empty in all our repos:
```
"assets": [

    ],
```

**Comment by RedSparr0w** [comment]
Ah I see what you are saying now,
It's because you haven't got any other files attached to your release, as when the source code is downloaded, GitHub doesn't seem to track it. _(or at least they don't give us those stats)_

![image](https://user-images.githubusercontent.com/7288322/59659167-b28d4e00-91f9-11e9-9b6b-d0dbe696eb3b.png)
![image](https://user-images.githubusercontent.com/7288322/59659171-b5883e80-91f9-11e9-9878-c16f63c68be5.png)

The only way around it that I can think of is adding your own archive to the releases along side the source code.

**Comment by eyalroz** [comment]
It is super annoying that the source code doesn't count towards downloads. That means source-only projects can simply not ever track their downloads. I wish GitHub fixed this.

**Comment by River-Mochi** [comment]
hello,
 we also have python script just like the poster here and have we have "releases" in zips but the download button doesn't work and the API does not show  download_count.
I downloaded the zip from the OP that  has a working badge and it's just python and some png/jpg/json files.

https://api.github.com/repos/builder555/PineSAM/releases

What is the difference in how this one is working:  https://github.com/Cigaras/IPTV.bundle/releases

thanks

**Comment by calebcartwright** [comment]
> hello, we also have python script just like the poster here and have we have "releases" in zips but the download button doesn't work and the API does not show download_count. I downloaded the zip from the OP that has a working badge and it's just python and some png/jpg/json files.
> 
> https://api.github.com/repos/builder555/PineSAM/releases
> 
> What is the difference in how this one is working: https://github.com/Cigaras/IPTV.bundle/releases
> 
> thanks

This is answered above, be sure to read the comments and screenshots closely:

https://github.com/badges/shields/issues/833#issuecomment-502971734
https://github.com/badges/shields/issues/833#issuecomment-1159629610

**Comment by River-Mochi** [comment]
is the work around that you simply figure out how to make a named package that is not the default name of
 **Source code.zip**  and **Source code.tar.gz**
and you dont even need to add anything different inside the download zip and just name it differently?

**Comment by calebcartwright** [comment]
@River-Mochi - I understand that you're just trying to get your badge working, but before responding to your question I want to stress a couple points:

* Shields is not a system of record. We fetch data from upstream tools/platforms/services, and we use the data they provide in the badges
* We're not responsible for those upstream systems, we do not (necessarily) have expertise in the systems we pull data from, and we should not be a first stop for support/inquiries about the behaviors of those upstream systems.

In this case the system of record is GitHub, and questions about/for GitHub should really be directed to GitHub via their supported channels, e.g. https://support.github.com/

That being said, I'll try to recap/rephrase what's been established above in the hopes that provides some clarity for you.

When you create a Release in GitHub (at least those associated with a Tag), GitHub automatically, and transparently/independently of user action, attaches two archive files of the repo's source code at that ref in both zip and tarball formats. Repository owners/maintainers have the option to attach _additional_ "binary assets" to the Release.

Those Release assets often include things like platform native binaries, so that users can grab an executable tool instead of having to build from source. 

GitHub internally tracks download counts for release assets, but crucially, GitHub does **not** track download counts for the two GitHub-generated source archive files. That is in turn reflected in their API response: if your Releases do not have any user-attached Release assets (assets _above and beyond_ the two source archives GitHub adds), then the GitHub API is always going to represent that as there being no downloads.

Shields in turn can only display the data that the system of record gives us, hence the 0 download count badge

**Comment by River-Mochi** [comment]
thanks, I don't know enough about how github works.  I'll go look at github documentation to see if there is anything related and also the support github channel you linked to try and figure it out.
 I really appreciate the link to github support and sorry if I asked in the wrong channel. might even be tickets in github already about download badge or download_count  and info of how github tracks things that might be useful to figuring it out and learning more.
