### ISSUE TITLE
Badge Request: Gitcoin Grants

### ISSUE THREAD

**Issue by TheFrozenFire** [badges/shields#8422]
:clipboard: **Description**

[Gitcoin grants](https://gitcoin.co/grants/) are a common funding source for crypto-related projects.

* **Which service is this badge for:**  
Gitcoin
* **What sort of information should this badge show?**  
    * `gitcoin | $15,000 lifetime`
    * `gitcoin | $3,950 current round`
    * `gitcoin | $3,950 + $21,814 matched`
    * `gitcoin | 1171 contributors`

:link: **Data**

Where can we get the data from?

- Is there a public API?  
`https://gitcoin.co/grants/v1/api/grant/<grant id>`

- Does the API require an API key?  
Seemingly no

- Link to the API documentation.
No public documentation

:microphone: **Motivation**

Many crypto projects use Gitcoin grants for funding, and would like to promote their grants in the README of their repositories, or on their dApps.

**Comment by chris48s** [comment]
> Link to the API documentation.
> No public documentation

How did you find out this API exists?

**Comment by TheFrozenFire** [comment]
I just looked up the network request that the Gitcoin front-end makes when requesting grant pages.

**Comment by chris48s** [comment]
OK thanks. The reason we say

> Badges should not obtain data from undocumented or reverse-engineered API endpoints.

in [our guidelines](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines)

is because we had some situations where a contributor worked out that a project had an API by inspecting the frontend code for their website or whatever, added a badge that calls it, and then we ended up relying on an API that wasn't really intended for public use. This then either annoyed the maintainers of the company/project behind it or we had no reasonable expectation of stability/compatibility over time (because devs maintaining the the API were making the assumption the only thing consuming it was their own frontend code) and stuff kept breaking.

That's pretty much the situation we've got here so I am going to close this issue, but we could revisit in future if there is a reliable public source for the data. It looks like this service meets all our other criteria.
