### ISSUE TITLE
AGPL3 is not detected on GitHub or GitLab

### ISSUE THREAD

**Issue by dboehmer** [badges/shields#8443]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

My project has license AGPL3 but that’s not correctly detected. Applies to GitHub as well as GitLab (project moved recently).

* GitHub: *not identifiable by github*
* GitLab: *Other*

### 🔗 Link to the badge

https://img.shields.io/github/license/dboehmer/coocook.svg

https://img.shields.io/gitlab/v/license/coocook/coocook

**Comment by chris48s** [comment]
Hi.

If I call https://api.github.com/repos/dboehmer/coocook it says the license is

```
"license": {
  "key": "other",
  "name": "Other",
  "spdx_id": "NOASSERTION",
  "url": null,
  "node_id": "MDc6TGljZW5zZTA="
},
```

If I call https://gitlab.com/api/v4/projects/coocook%2Fcoocook?license=1 it says the license is

```
"license": {
  "key": "other",
  "name": "Other",
  "nickname": null,
  "html_url": "http://choosealicense.com/licenses/other/",
  "source_url": null
},
```

In the case of GitHub, it tries to auto-detect your license from the LICENSE file (more details https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license ). If you're using a well-known license and it is not auto-detected this is often due to some minor difference between the license file in your repo and the reference copies in https://github.com/licensee/licensee . Even really minor differences like whitespace can cause this. I'd imagine GitLab does something similar, but I've not looked into it.

In any case, the badges are reporting the values from the API responses correctly so this is an issue that will need to be resolved elsewhere. Thanks
