### ISSUE TITLE
Dynamic Endpoint jsonpath query parsing error

### ISSUE THREAD

**Issue by theofficialgman** [badges/shields#8585]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I am attempting to create a badge to parse a github hosted json file https://raw.githubusercontent.com/Botspot/pi-apps-analytics/main/package_data.json as suggested here https://github.com/badges/shields/discussions/7435#discussioncomment-1879283

The badge that I have created using the shields.io dynamic web GUI is https://img.shields.io/badge/dynamic/json?color=blue&label=Prism%20Launcher&query=%24.%5B%3F%28%40.Name%3D%3D%22Minecraft%20Java%20Prism%20Launcher%22%29%5D.Version&url=https%3A%2F%2Fraw.githubusercontent.com%2FBotspot%2Fpi-apps-analytics%2Fmain%2Fpackage_data.json

this produces an `unparseable jsonpath query` error and I am not certain why as the JSONPath online evaluator returns the output correctly:
```
[
  "5.0-5"
]
```

https://jsonpath.com/

`$.[?(@.Name=="Minecraft Java Prism Launcher")].Version`

simple test json:
```
[
  {
    "Name": "Minecraft Java Prism Launcher",
    "Version": "5.0-5",
    "Description": "Prism Launcher is an Open Source Minecraft launcher with the ability to manage multiple instances, accounts and mods. Focused on user freedom and free redistributability.",
    "URL": "https://prismlauncher.org/",
    "Architecture": "ARM32/ARM64"
  },
  {
    "Name": "Minecraft Java Server",
    "Version": "unknown",
    "Description": "This is a simple tool to create a Minecraft server: Vanilla, Fabric, Forge, Paper, Bukkit, Spigot, Sponge, Purpur and Tuinity are supported",
    "URL": "https://serverjars.com",
    "Architecture": "ARM32/ARM64"
  }
]
```

### 🔗 Link to the badge

https://img.shields.io/badge/dynamic/json?color=blue&label=Prism%20Launcher&query=%24.%5B%3F%28%40.Name%3D%3D%22Minecraft%20Java%20Prism%20Launcher%22%29%5D.Version&url=https%3A%2F%2Fraw.githubusercontent.com%2FBotspot%2Fpi-apps-analytics%2Fmain%2Fpackage_data.json

**Comment by theofficialgman** [comment]
this appears to be a bug on your end or an oversight
on jsonpath, the evaluator works with:
`$.[?(@.Name=="Minecraft Java Prism Launcher")].Version`
or
`$..[?(@.Name=="Minecraft Java Prism Launcher")].Version`

but shields.io only works with the latter
`$..[?(@.Name=="Minecraft Java Prism Launcher")].Version`

**Comment by chris48s** [comment]
The jsonpath library we use is https://github.com/dchester/jsonpath

The reason why we say its an `unparseable jsonpath query` is because https://github.com/dchester/jsonpath can't parse it.

```js
> const jp = require('jsonpath');

> jp.query({}, '$.[?(@.Name=="Minecraft Java Prism Launcher")].Version');
Uncaught Error: Parse error on line 1:
$.[?(@.Name=="Minecraf
--^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', got '['
```

JSONPath has a variety of murky areas and different libraries/parsers make some different calls where there are ambiguities. The comparison table at https://cburgmer.github.io/json-path-comparison/ indicates that dot bracket notation is a construct where there is not a clear consensus between different tools. This is why you got different results from the online evaluator your posted and the lib we are using.

Seems like you've managed to find a workable solution but if you want to follow it up further, https://github.com/dchester/jsonpath/issues is the place.

Cheers

**Comment by chris48s** [comment]
Going to close this one as I don't think there is any additional follow up needed
