### ISSUE TITLE
504 error on some badges

### ISSUE THREAD

**Issue by lechuckcaptain** [badges/shields#8627]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I'm getting often (not always) 504 errors on some badges of my project:

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/341895/201694005-fa3801bb-067c-4eb6-9cde-469d0f4af864.png">

The following is the markdown generated from your [website](https://shields.io/category/license):

![Version](https://img.shields.io/cocoapods/v/SBTUITestTunnelServer)
![License](https://img.shields.io/cocoapods/l/SBTUITestTunnel)
![Platform](https://img.shields.io/cocoapods/p/SBTUITestTunnel)

Some examples ([1](https://camo.githubusercontent.com/8d90c845da7ec2900478d2864f791c818aa852127a762053c190b89f592cad4c/68747470733a2f2f696d672e736869656c64732e696f2f636f636f61706f64732f6c2f53425455495465737454756e6e656c), [2](https://camo.githubusercontent.com/19b7909ee9f71371a6029416d1d4a1f09109ac184b66fdefcbf059f7956efddb/68747470733a2f2f696d672e736869656c64732e696f2f636f636f61706f64732f762f53425455495465737454756e6e656c536572766572), [3](https://camo.githubusercontent.com/308590d1b2cc9ac7f29ec57f23ed6648d992d031ce9dcbad6f3459198b39f459/68747470733a2f2f696d672e736869656c64732e696f2f636f636f61706f64732f702f53425455495465737454756e6e656c)) of generated URLs that (at the moment) are not working.

### 🔗 Link to the badge

https://github.com/Subito-it/SBTUITestTunnel/blob/master/README.md

<img width="610" alt="image" src="https://user-images.githubusercontent.com/341895/201698947-e591b9cf-d1e6-413f-bceb-71d5d47a1ec6.png">

**Comment by chris48s** [comment]
Hi. The 504 errors are actually being returned by GitHub's image proxy (Camo). If we can't respond with a badge within 4 seconds of GitHub's request, Camo will give up and return this error.

At the moment, it looks like there is an outage with the CocoaPods API which means CocoaPods badges are taking a long time to render because we are waiting a long time for the API response.

You'll note if you call https://trunk.cocoapods.org/api/v1/pods/SBTUITestTunnel/specs/latest (which is where the data displayed on these badges comes from), it will probably take 5-10 seconds to return a response.

Other badges appear to be rendering within the expected timeframe so I'm going to close this issue as it is a problem with an upstream API. There may be some mileage in following it up with the CocoaPods project. Cheers
