### ISSUE TITLE
Badge Request: combined download count

### ISSUE THREAD

**Issue by ajeetdsouza** [badges/shields#8629]
:clipboard: **Description**

This badge uses multiple services (GitHub, Chocolatey, Homebrew, etc.) and combines the download count across all these repositories.

:link: **Data**

We already have this data! We just need to add the download count from different sources and display the total result.

:microphone: **Motivation**

Most packages are published across a number of repositories, so showing numbers from a single repository can be inaccurate. If we could combine the numbers from each source, I think that could provide a lot of value.

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close this (for now). Perhaps this is something we could reconsider down the line, but it's not something I'm willing to have us take on because it's wildly open ended (e.g. combinations within defined sets of services, sets of services, etc.) and is not something our existing user-facing route conventions nor internal code codebase is really structured to support.

If this is something you are passionate about having then your best bet is to either follow the standard pattern of having the relevant badges side by side, or utilizing our [Endpoint badge](https://shields.io/endpoint) feature to develop your own endpoint that would perform all the fetches and aggregate the results, e.g.

```mermaid
sequenceDiagram
    actor User
    participant B as Badge Server
    participant E as Your Endpoint
    participant DA as Registry/Store A
    participant DB as Registry/Store B
    participant DN as Registry/Store N
    User->>+B: Get aggregate download badge from my endpoint
    B->>+E: Get badge data
    E->>+DA: Get download count
    DA-->>-E: Download count
    E->>+DB: Get download count
    DB-->>-E: Download count
    E->>+DN: Get download count
    DN-->>-E: Download count
    E->>E: Combine download counts
    E-->>-B: Badge data
    B->>B: Make badge with data
    B-->>-User: Here's your badge!
```

Finally note that your Endpoint implementation doesn't necessarily need to reach out directly to the underlying registries/stores, and could get the download count in json form directly from Shields, i.e. the endpoint could go to https://formulae.brew.sh/api/... directly to get the download count or it could go to https://img.shields.io/homebrew/installs/dm/cake.json and let Shields do it.
