### ISSUE TITLE
Branch or event not found

### ISSUE THREAD

**Issue by alanshaw** [badges/shields#8732]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Trying to update to the new URL:

![](https://img.shields.io/github/actions/workflow/status/web3-storage/w3up-client/test.yml?branch=main)

### 🔗 Link to the badge

https://img.shields.io/github/actions/workflow/status/web3-storage/w3up-client/test.yml?branch=main

**Comment by chris48s** [comment]
The reason why this one isn't finding anything is because your `test.yml` workflow only runs on pull requests

https://github.com/web3-storage/w3up-client/blob/d26664c15f6ca17e91dbf3860c7c8fea72047f61/.github/workflows/test.yml#L2-L5

so there are no runs on `main` itself

https://github.com/web3-storage/w3up-client/actions/workflows/test.yml?query=branch%3Amain

This is actually one of the situations where the old badge had confusing behaviour - what you were probably seeing before was the status of the last run of `test.yml` on whatever pull request last triggered it.

My guess would be this either flags that you really want to be running `test.yml` on pushes to main, or maybe you wanted to be reporting the status of one of your workflows that _does_ run on your main branch, like `release.yml`

https://github.com/web3-storage/w3up-client/blob/d26664c15f6ca17e91dbf3860c7c8fea72047f61/.github/workflows/release.yml#L1-L4
https://github.com/web3-storage/w3up-client/actions/workflows/release.yml?query=branch%3Amain

I'd be interested to understand this one more.

**Comment by chris48s** [comment]
We've just merged https://github.com/badges/shields/pull/8738 and deployed to production. This would allow you to omit the branch param, which may or may not be what you want. Either way I'm going to close this as I think the original query is answered.
