### ISSUE TITLE
badge for visual studio does not work

### ISSUE THREAD

**Issue by 1YiB** [badges/shields#8751]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

shields.io does not display the downloads for a vscode extension even if the extension very well does exist 

output:
![badge](https://img.shields.io/visual-studio-marketplace/i/jock.svg)

expected output:

<kbd>vsmarketplace<kbd>658K </kbd></kbd>

fyi: the extension jock.svg does exist
https://marketplace.visualstudio.com/items?itemName=jock.svg
![image](https://user-images.githubusercontent.com/121028104/209457967-5c5707a0-6b73-4930-a193-9f802935b8cd.png)

other services like [`vsmarketplacebadges.dev`](https://vsmarketplacebadges.dev/) seem to work (based on shields)

![a](https://vsmarketplacebadges.dev/installs/jock.svg.svg?&logo=visualstudiocode&color=A3BE8C&label=vs%20marketplace)

### 🔗 Link to the badge

https://img.shields.io/visual-studio-marketplace/i/jock.svg

**Comment by calebcartwright** [comment]
The problem is that the marketplace uses publisher.extensionName, and the name of this extension overlaps with our (optional) file extension for our badges. To avoid this you'll need to explicitly provide the badge extension too:

https://img.shields.io/visual-studio-marketplace/i/jock.svg.svg
![](https://img.shields.io/visual-studio-marketplace/i/jock.svg.svg)
