### ISSUE TITLE
Valid badge types that aren't found should respond with 404

### ISSUE THREAD

**Issue by nickmccurdy** [badges/shields#8764]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I wanted to automate finding invalid badges due to #8671. Unfortunately many of these respond with 200, so it's difficult to determine if they're valid programatically. In order to troubleshoot this I would need to host my own server, which isn't practical when I'm contributing to repositories in many organizations, some of which I don't admin.

The standard HTTP error code for resources that cannot be found is 404. GitHub already responds with this when you don't have permission to access a repository on the web or API. I think it would be best to stay consistent, and we can add custom headers if we want to further distinguish types of errors from badges.

### 🔗 Link to the badge

- https://img.shields.io/bitbucket/issues/nickmccurdy/rose
- https://img.shields.io/github/workflow/status/nickmccurdy/rose/build
- https://img.shields.io/github/actions/workflow/status/nickmccurdy/rose/doesntexist.js.yml
- https://img.shields.io/github/actions/workflow/status/nickmccurdy/doesntexist/doesntexist.js.yml

### 💡 Possible Solution

Any image request where a resource can't be found should respond with 404.

**Comment by nickmccurdy** [comment]
This should be a bug, not a question.

**Comment by chris48s** [comment]
Hello. The reason why we don't do this is we want the output to be visible to users if there is some kind of error (be that not found, or a validation error or whatever). If you link an image in a `<img>` tag and we return a response with a 404 status code (or other error code) rather than a 200 then browsers will render a ![Screenshot at 2022-12-30 21-29-05](https://user-images.githubusercontent.com/6025893/210112940-1e51cf72-752e-47cf-95ee-af083e1651fb.png) rather than <img src="https://img.shields.io/bitbucket/issues/nickmccurdy/rose" /> (or whatever), even if there is usable image data in the body of the error response.

Obviously there is a tradeoff to be made here. We've picked rendering user visible output as the thing to optimise for ahead of RESTful-ness.

**Comment by nickmccurdy** [comment]
Thanks, I wasn't aware, that is unfortunate. Perhaps a codemod or linter could be helpful instead.
