### ISSUE TITLE
Badge request: Homebrew total downloads instead of monthly or yearly downloads

### ISSUE THREAD

**Issue by GyulyVGC** [badges/shields#8844]
### 📋 Description

The badge should show the total number of downloads of a Homebrew formula (not just the downloads of the past month/quarter/year). 

### 🔗 Data

You could get this data from the Homebrew API I guess, [this](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fsniffnet) is an example of package; the page automatically shows also the total number of downloads.

### 🎤 Motivation

It would be useful to have such a badge to be consistent with the other overall downloads badges already present.

**Comment by calebcartwright** [comment]
Thanks but I'm going to close for now. We already get our data from the Homebrew API, and we make our badge downloads available at the same intervals as their API provides https://formulae.brew.sh/api/formula/sniffnet.json

[The page you linked to](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fsniffnet) is actually [GitHub Packages](https://github.com/features/packages), GitHub's native package/artifact registry.

GitHub has its own separate API and download tracking stats for Packages, which we don't yet support because we're currently blocked/needing some major changes to proceed (#4169).

At some point down the road if we've incorporated support for being able to provide download badges for GitHub Packages (#4071) then we'd similarly support the same set of intervals that GitHub's API provide which would presumably include the total downloads number you see on their page.
