### ISSUE TITLE
https://shields.io/ resource unavailable

### ISSUE THREAD

**Issue by andreynav** [badges/shields#8884]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

[525 error](https://take.ms/0vcog)

**Comment by jozefizso** [comment]
Cloudflare Ray ID: 793e54c50b8d9235

**Comment by Jonathan357611** [comment]
Same for me :/
Ray ID: 79447b780f8f929b

**Comment by calebcartwright** [comment]
Duplicate of #8424

**Comment by andreynav** [comment]
@calebcartwright I son't see the fix of the bug

**Comment by calebcartwright** [comment]
I'm not really sure what the objective is in the downvote and subsequent comment, but the status/resolution of an issue is quite orthogonal to whether an issue is a duplicate of an existing one.

#8424 is the older, existing issue with more details around cause and discussion about potential resolution. That's where we intend to track the item that you've reported here in a separate, duplicative issue. There's no benefits in bifurcating that discussion and maintaining multiple duplicate issues, which is why this one has been closed and directed towards the main issue.
