### ISSUE TITLE
GitHub badges showing "Unable to select next Github token from pool"

### ISSUE THREAD

**Issue by DenverCoder1** [badges/shields#8907]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All GitHub badges appear to display "Unable to select next Github token from pool".

![image](https://user-images.githubusercontent.com/20955511/218998788-41ac8f74-5bab-45bd-b276-669877addb4f.png)

### 🔗 Link to the badge

All GitHub-related badges, eg.
https://img.shields.io/github/forks/badges/shields?style=social
https://img.shields.io/github/stars/DenverCoder1?style=social

**Comment by l0rd** [comment]
It looks like the [GitHub license service is currently down](https://stats.uptimerobot.com/PjXogHB5p): 

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/606959/219003427-9654e74d-c33e-41e0-96c4-0318e3d6d226.png">

**Comment by GyulyVGC** [comment]
It's working again now!

**Comment by adamlui** [comment]
It's still happening 4 hours later :(
![image](https://user-images.githubusercontent.com/10906554/219058329-b784977f-c658-498f-9ca6-27ba79be0684.png)

**Comment by scarqin** [comment]
<img width="346" alt="image" src="https://user-images.githubusercontent.com/15225835/219061598-2199737e-9afb-4ccc-9f33-a1d348b7d0ec.png">
Yes,i havs same issue.

**Comment by eryajf** [comment]
I rely on this in a lot of places, and now I can't work at all.

see: https://github.com/eryajf

As far as I know, github officials should have made a lot of adjustments recently, looking forward to the repair of this problem.

**Comment by calebcartwright** [comment]
Folks we're aware of this and investigating, but no ETA on a root cause determination nor a resolution. I'm going to lock the issue for now to avoid pile on comments that aren't going to be particularly helpful because whatever the underlying root cause, it's going to impact all* GitHub badges

* All those that need to use authentication when fetch data from GitHub's APIs

**Comment by chris48s** [comment]
@calebcartwright - I'm at work at the moment so can't spend loads of time on it, but I _think_ this happened because of
- https://status.compose.com/incidents/v2k11kzvwx1l
- https://help.compose.com/docs/compose-deprecation
and we've got ~2 weeks to move the token pool somewhere else :grimacing: I'll look into it more after work.

**Comment by calebcartwright** [comment]
> @calebcartwright - I'm at work at the moment so can't spend loads of time on it, but I _think_ this happened because of
> 
>     * https://status.compose.com/incidents/v2k11kzvwx1l
> 
>     * https://help.compose.com/docs/compose-deprecation
> 
> 
> and we've got ~2 weeks to move the token pool somewhere else 😬 I'll look into it more after work.

I'm in the same boat, but that indeed seems like the cause. Happy to have an ad-hoc ops meeting in the near future too given the urgency driven by that deadline

**Comment by chris48s** [comment]
Calling this one closed. We have now taken our tokens elsewhere
