### ISSUE TITLE
Web Bloat Score Badge

### ISSUE THREAD

**Issue by Kittenlover229** [badges/shields#8988]
### 📋 Description

This badge is for the [Web Bloat Score](https://www.webbloatscore.com/), a website in use by the web-minimalistic community. It calculates the ratio of the website's screenshot size to it's payloads' size sum. Lower means the payloads take less bandwidth, greater means they require more bandwidth than an image of the website would. It also provides some additional information, such as page size, screenshot size. Therefore it's possible to create the following badges! I think they would fit into the "size" section well enough.

Plain score might look something like this:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-0.297-informational)

Whilst a version with a value judgement might look something like this:
* For all values below one and a bit (say 1.1):
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-0.750-brightgreen)
* For all values above 1.1, when the size difference is not critical, but noticable:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-1.364-green)
* For all values 1.5 and above:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-1.784-yellowgreen)
* For all values 2 and above:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-2.638-yellow)
* For all values 4 and above:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-4.998-orange)
* For all values 8 and above:
![Web Bloat Score Info](https://img.shields.io/badge/Web%20Bloat%20Score-18.461-red)

Just in case it is also possible to display Page Size and Image Size, however, I don't find them particularly useful or easy to fit on a badge.
![Web Page Size](https://img.shields.io/badge/Web%20Page%20Size-54906-informational)
![Web Page Screenshot Size](https://img.shields.io/badge/Web%20Page%20Screenshot%20Size-184968-informational)

I am glad to implement the feature myself, but the ranges for each colour and the necessity of Page Size and Screenshot Size are questionable. 

### 🔗 Data

The API is available through as `https://www.webbloatscore.com/Capture`. The request body simple enough: `{ url: "https://www.w3.org/People/Berners-Lee/", timeout : "60" }`. The Bloat Score is returned to more than enough significant digits. It also doesn't require any authentication.

### 🎤 Motivation

As a part of the community that prides themselves on tiny websites and minuscule request payloads, I find demonstrating the website's Bloat Score on it's README as important, as other statistics such as code coverage, commit activity, etc. Making it into a badge would display the value in a format that is already familiar to most developers and will add to README's appeal.

**Comment by chris48s** [comment]
Two things:

1. Is there any documentation for this API?
2. I tried requesting this for example.com and it took 9 seconds to return a response. For shields we really need the upstream API call to usually return in under 4 seconds for a badge to be viable. GitHub (which is the place where badges are most commonly viewed) has a hard limit of 4 seconds on an image request so if it takes us >4 seconds to render a badge, they just don't show up.

**Comment by Kittenlover229** [comment]
1. The API is not documented, no, is that an issue? I assumed it was clear enough.
2. That is a problem, sadly. It could possibly be solved by caching the value on the server side perhaps? The API generates an image, so no wonder it might take so long. Where is GitHub's timeout limitation mentioned? I can't find it in the docs.

**Comment by calebcartwright** [comment]
> 1. The API is not documented, no, is that an issue? I assumed it was clear enough.

Yes, unfortunately it's a deal breaker issue. We have this guideline called out in our [docs](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines) because we've had a number of issues in the past with badges that were reliant upon undocumented/unsupported APIs.

> 2. That is a problem, sadly. It could possibly be solved by caching the value on the server side perhaps? The API generates an image, so no wonder it might take so long. Where is GitHub's timeout limitation mentioned? I can't find it in the docs.

This is also a deal breaking issue.

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls
https://github.com/cactus/go-camo
https://github.com/atmos/camo

I'm not sure if GH explicitly document the timeout period, but this project has rather extensive experience and history with github's rendering behavior so we know the general parameters our service needs to work within wrt response times. It's behavior you can replicate/observe fairly easily provided you can find and use a reference to content which takes a few seconds to fetch.

This isn't something we can cache around on our end, but would encourage you to work with WebBloat to see if they'd be willing to expand their offering and API surface to provide a cached version of their score derivation.

Happy to revisit if that comes to fruition and/or circumstances otherwise change, but going to close for now as this isn't going to be viable. If you'd still like to push for these badges then you could consider using our [Custom Endpoint](https://shields.io/endpoint), provided you don't mind the badges not rendering in GitHub more often than not (which may or may not be a concern for you depending on where you plan on placing those badges)
