### ISSUE TITLE
Please support Github token as param. Github has fine grained personal access tokens already.

### ISSUE THREAD

**Issue by stalek71** [badges/shields#9056]
Please kindly consider supporting the utilization of Github tokens as parameters, given that Github offers [highly refined personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#fine-grained-personal-access-tokens).

**Comment by chris48s** [comment]
A few thoughts on this

I assume the projected use-case for this would be badges for private repos via shields.io? (i.e: without having to self host an instance)

There are some limitations to fine-grained tokens as opposed to classic PATs. There are some more notes on this in https://github.com/badges/shields/issues/8792

Although
a) we do accept a user-supplied token in a query param for some services and
b) it may be possible to generate tokens allowing read-only access to repo metadata you are willing to expose in some cases
Obviously it would be up to users to assign the right token permissions and embed the badges in safe places, with this particular service it seems like accepting GH tokens in a query param comes with a disproportionately high risk of exposing sensitive data.

**Comment by calebcartwright** [comment]
> Obviously it would be up to users to assign the right token permissions and embed the badges in safe places, with this particular service it seems like accepting GH tokens in a query param comes with a disproportionately high risk of exposing sensitive data.

This is the key point for me, and why my initial reaction is to still be opposed to accepting GitHub tokens via query params. If GitHub had _started_ with the fine grained PATs instead of them being the evolution to the now-branded "classic" tokens then it would be a different story for me. However, given the historical context and present day ease in which badges can be obtained for private repos via other means (including self-hosting), I don't think it's worth the risk nor the likely added complexity it would require on the codebase to support it

**Comment by calebcartwright** [comment]
I'm going to close this for now. Perhaps we can reconsider if/when GitHub fully drop classic tokens
