### ISSUE TITLE
The badge is no status

### ISSUE THREAD

**Issue by SimFG** [badges/shields#9066]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

![badge](https://img.shields.io/github/actions/workflow/status/zilliztech/GPTCache/pylint.yaml?branch=dev&label=Pylint)

![image](https://user-images.githubusercontent.com/21985684/230726948-c1ac29b1-4be4-4e4b-81cc-2b1192dc7aa4.png)

Why is it no status?

### 🔗 Link to the badge

https://img.shields.io/github/actions/workflow/status/zilliztech/GPTCache/pylint.yaml?branch=dev&label=Pylint

### 💡 Possible Solution

want it to show normally

**Comment by chris48s** [comment]
The badge is set to report the status of builds on the branch called `dev` on the repo `zilliztech/GPTCache`

The build in your screenshot ran on a branch called dev on a forked copy. That's why it says `SimFG:dev` under branch not `dev`

If you look at the badge for a workflow which has a run on the `dev` branch on the source repo zilliztech/GPTCache (e.g: [CI_integration_test_main.yaml](https://github.com/zilliztech/GPTCache/actions/workflows/CI_integration_test_main.yaml) ) you will see a build status: https://img.shields.io/github/actions/workflow/status/zilliztech/GPTCache/CI_integration_test_main.yaml?branch=dev

**Comment by SimFG** [comment]
@chris48s thank you so much!!!
