### ISSUE TITLE
Github Workflow badge showing CI build as failing when it is successful.

### ISSUE THREAD

**Issue by xthursdayx** [badges/shields#9073]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

My Github workflow status badge that I use for my Docker image CI build process is showing that the workflow is failing, despite the fact that the last two runs were successful.

I wonder if this may be related to https://github.com/badges/shields/issues/8733 however, I only have one branch (`main`) currently, so I assume that cause is unlikely to be the same.

### 🔗 Link to the badge

https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/workflows/docker-build-and-publish.yml/badge.svg?branch=main

[![Build and push images](https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/workflows/docker-build-and-publish.yml/badge.svg?branch=main)](https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/workflows/docker-build-and-publish.yml)

**Comment by chris48s** [comment]
I'm looking at your README and it has a shields badge in it, but then the links you've posted in the issue are links to GitHub's native badge (which we essentially scrape/wrap).

The exact logic that GH's native badge implements is somewhat opaque to us. I'd expect that https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/workflows/docker-build-and-publish.yml/badge.svg (without the branch param) would pick up https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/runs/4658475707 as your "latest" build for that workflow file, but my guess it it is falling back to one of the older runs for that workflow because it "prefers" a different event type (probably "push"). My guess would be that https://github.com/xthursdayx/yacreaderlibrary-server-docker/actions/workflows/docker-build-and-publish.yml/badge.svg?event=release give the result we expect but its difficult to tell precisely because the badge only shows the status, not which build the status value comes from or why it was selected.

If you think the value on GitHub's native badge is wrong, then it might be worth contacting GH support.

**Comment by david-c14** [comment]
This was causing me issues today.  Not only does github's native badge prefer
event=push, it also prefers the default branch.   While setting up my workflow I accidentally 
ended up with the workflow running for push on the main branch.

Neither a successful run on the release event from main, nor a successful run on
push to develop would override the failed status.

I ended up deleting the offending workflow runs
