### ISSUE TITLE
GitHub Latest release including pre by date: not the latest pre-release

### ISSUE THREAD

**Issue by Commifreak** [badges/shields#9119]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Its about this releases: https://github.com/Commifreak/unraid-appdata.backup/releases

Inside the readme, I list the latest pre release via `https://img.shields.io/github/v/release/Commifreak/unraid-appdata.backup?include_prereleases`. In my case, I would expect to see `2023.04.24b5` but I actually see the `2023.04.24b1`. The way I use it should sort by date. So, why isnt it showing the right one?

### 🔗 Link to the badge

https://img.shields.io/github/v/release/Commifreak/unraid-appdata.backup?include_prereleases

**Comment by calebcartwright** [comment]
You've pushed a git tag for 2023.04.24b5, but you haven't created a GitHub Release with that tag. Tags and Releases are related, but different entities

https://img.shields.io/github/v/release/Commifreak/unraid-appdata.backup?include_prereleases
![](https://img.shields.io/github/v/release/Commifreak/unraid-appdata.backup?include_prereleases)

https://img.shields.io/github/v/tag/Commifreak/unraid-appdata.backup?include_prereleases
![](https://img.shields.io/github/v/tag/Commifreak/unraid-appdata.backup?include_prereleases)

**Comment by Commifreak** [comment]
Are you sure?

there is clearly a release available:

![IMG_3605](https://user-images.githubusercontent.com/87267/234095618-e69c2e2e-c55e-4dca-8491-6e9a7c0ea2a0.png)

**Comment by calebcartwright** [comment]
> Are you sure?

Yes, I am sure. Unequivocally.

I would encourage you to check on a web browser from a laptop (where the visual distinction may be more clear), review the response from GitHub's API for yourself, as well as reading some previous commentary we've shared in this repo about this topic.

Aggregated for your reference and ease of consumption:

https://api.github.com/repos/Commifreak/unraid-appdata.backup/releases  

https://github.com/badges/shields/issues/2785#issuecomment-587430236  

And screen grab from a browser on a computer:

![image](https://user-images.githubusercontent.com/13042488/234104751-6c2bf44f-cbf9-4e36-9a57-d60ede8af31e.png)

**Comment by Commifreak** [comment]
Interesting. Because I created it as always. There are assets behind the not shown release. And its clearly listed under „Releases“ but yes: the API does not show it.

thanks for the insight, I will delete and recreate the release and check if it helps.

**Comment by Commifreak** [comment]
A simple edit and resave of the release did it.

**Comment by colinbrislawn** [comment]
> | | Tags and Releases are related, but different entities
> | Are you sure?
> Yes, I am sure. Unequivocally.

I found this issue because I thought I understood this 🙃 


correct (https://img.shields.io/github/v/release/colinbrislawn/unite-train?include_prereleases)
![alt](https://img.shields.io/github/v/release/colinbrislawn/unite-train?include_prereleases)

correct (https://img.shields.io/github/v/tag/colinbrislawn/unite-train?include_prereleases)
![alt](https://img.shields.io/github/v/tag/colinbrislawn/unite-train?include_prereleases)

too old?? (https://img.shields.io/github/release-date-pre/colinbrislawn/unite-train)
![alt](https://img.shields.io/github/release-date-pre/colinbrislawn/unite-train)

### It turns out that GitHub releases have two dates! Shields.io supports both!

- `?display_date=published_at`
- `?display_date=created_at`

I was using the wrong one:

just right (https://img.shields.io/github/release-date-pre/colinbrislawn/unite-train?display_date=published_at)
![alt](https://img.shields.io/github/release-date-pre/colinbrislawn/unite-train?display_date=published_at)

More docs: https://shields.io/badges/git-hub-release-date
