### ISSUE TITLE
GitHub sponsor badge count doesn't include private sponsors 

### ISSUE THREAD

**Issue by Auburn** [badges/shields#9120]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

GitHub sponsor badge count doesn't include private sponsors 

### 🔗 Link to the badge

/github/sponsors/:user

### 💡 Possible Solution

Looking at the GraphQL API the `sponsorshipsAsMaintainer` interface has an argument `includePrivate` which defaults to false. So it's hope fully simple to add this argument to the request.

**Comment by chris48s** [comment]
Interesting. I expected `includePrivate` would only work when authenticated with your own API key, but I had a bit of a play and it seems that passing `includePrivate: true` does allow any API user to see the `totalCount` including private sponsors, but you can't view the identities of the sponsors.

You up for submitting a PR? I think it is reasonable to just change the default to include private sponsors, rather than making it a flag.

**Comment by Auburn** [comment]
I did have a look at the code to lookup the API it uses and if I could do this as a PR, but I don't know anything about JS so I made this issue instead :D

**Comment by calebcartwright** [comment]
> I did have a look at the code to lookup the API it uses and if I could do this as a PR, but I don't know anything about JS so I made this issue instead :D
> 
> I also agree that including private count should be the default behaviour

@Auburn  Just in case you (or anyone else for that matter) have an interest in working on this, it really should be quite simple and not require JS knowledge/experience (though one would indeed likely want to at least have Node.js installed so that you can run the test script).

The query for this can be found here:

https://github.com/badges/shields/blob/c773563e60e8df3edf23984a176f8db2fdb6932e/services/github/github-sponsors.service.js#L44-L59

and I suspect that's all that would need to be changed
