### ISSUE TITLE
Can not use branch name with slashes in `GitHub commits since tagged version (branch)`

### ISSUE THREAD

**Issue by andry81** [badges/shields#9140]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The URL does not accept slashes in a branch name part.

### 🔗 Link to the badge

<img src="https://img.shields.io/github/commits-since/andry81/tacklebar/r204-update4/dev/r204_update?label=Github%20commits%20since%20r204-update4" valign="middle" alt="GitHub commits since tagged version" />

https://img.shields.io/github/commits-since/andry81/tacklebar/r204-update4/dev/r204_update?label=Github%20commits%20since%20r204-update4

### 💡 Possible Solution

May be add an explicit branch name parameter?

`...?branch=dev/blabla`

**Comment by andry81** [comment]
Another url example with the issue:

<img src="https://img.shields.io/badge/dynamic/json?color=blue&label=Github%20commits%20since%20previous&query=total_commits&url=https://api.github.com/repos/andry81/tacklebar/compare/r204-update4...dev/r204_update" valign="middle" alt="GitHub commits since tagged version" />

https://img.shields.io/badge/dynamic/json?color=blue&label=Github%20commits%20since%20previous&query=total_commits&url=https://api.github.com/repos/andry81/tacklebar/compare/r204-update4...dev/r204_update

**Comment by calebcartwright** [comment]
@andry81 - the badge route does indeed support branches that have slashes within. The issue seems to be with your repo and the comparison points, which you can observe in the response from GitHub's API directly:

https://api.github.com/repos/andry81/tacklebar/compare/r204-update4...dev/r204_update

```terminal
$ curl -i https://api.github.com/repos/andry81/tacklebar/compare/r204-update4...dev/r204_update
HTTP/2 404 
server: GitHub.com
date: Mon, 08 May 2023 21:05:45 GMT
content-type: application/json; charset=utf-8
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-ratelimit-limit: 60
x-ratelimit-remaining: 56
x-ratelimit-reset: 1683583505
x-ratelimit-resource: core
x-ratelimit-used: 4
content-length: 171
x-github-request-id: B7E0:1BBE:1171144:23D9E26:64596429

{
  "message": "No common ancestor between r204-update4 and dev/r204_update.",
  "documentation_url": "https://docs.github.com/rest/commits/commits#compare-two-commits"
}
```

We _try_ to give helpful error messages to our users when we receive a 404 response from the upstream system of record, but in some cases there's too many potential sources of the Not Found response and we can't always cover all of them in the error message.

I'd encourage you to figure out what's caused the bifurcation between these and afterwards you should see the badge working

https://github.com/andry81/tacklebar/tree/r204-update4

![image](https://user-images.githubusercontent.com/13042488/236935722-40987b67-0878-45b3-b1ef-9a17f32a3941.png)
