### ISSUE TITLE
Badge request: timestamp of last github workflow run

### ISSUE THREAD

**Issue by AutumnSun1996** [badges/shields#9141]
I have a github repo with auto scheduled actions.
It will be great to have a badge for `time since last github workflow run` to show if the repo is up-to-date.

Should be something like this:

`/github/actions-timestamp/status/:user/:repo/:workflow+?branch=main`

![](https://img.shields.io/badge/last%20run-2023--05--04%2012%3A45%3A32-brightgreen)

![](https://img.shields.io/badge/last%20run-2023--05--01%2012%3A45%3A32-yellow)

`/github/actions-timestamp/status/:user/:repo/:workflow+?branch=main&timezone=Asia/Shanghai`

![](https://img.shields.io/badge/last%20run-2023--05--04%2012%3A45%3A32%2B08%3A00-brightgreen)

![](https://img.shields.io/badge/last%20run-2023--05--01%2012%3A45%3A32%2B08%3A00-yellow)

`/github/actions-timestamp/status/:user/:repo/:workflow+?branch=main&timezone=Asia/Shanghai&relative=true`

![](https://img.shields.io/badge/last%20run-1%20min%20ago-brightgreen)

![](https://img.shields.io/badge/last%20run-3%20days%20ago-yellow)

**Comment by calebcartwright** [comment]
I'm not necessarily vehemently opposed to this, however, I'm a little skeptical that something like a CI run is a great fit for this given the typical structure of the badge.

Phrased differently, I feel like the badge would need to have a _lot_ of text in order to provide sufficient context for general purpose scenarios and meet some of our core criteria for badge defaults about being self-explanatory without being service-promotional. Namely, it's common for most projects to have multiple CI pipelines/workflows/jobs/etc. that support different triggers, different refs, etc. I'm also sure folks would want to be able to differentiate based on results.

E.g. Being able to at a glance tell that the badge reflects the last non-failed run started by a non-manual trigger for branch foo.

I understand you aren't asking for all those filters and based on your planned usage may not care about that visual explicitness and delineation. However, those are factors we have to take into consideration when adding a dedicated badge route for broad use.

Personally, I'd recommend you consider utilizing our [Endpoint badge](https://shields.io/endpoint) functionality to put something together and see how it works. We can also leave this open for a while to see if there's any broader community interest or if, as I suspect, it's a bit more bespoke and better suited to the Endpoint badge model long term.

**Comment by AutumnSun1996** [comment]
Thanks for your response.  I'm closing it for now since I already found another workaround for my specific problem.

For anyone who may need it, I'm currently using a `badges` branch with svgs updated by github actions to achieve similar result.
It's not possible to show relative time, but abs time is also acceptable for me.
