### ISSUE TITLE
A bug that may have occurred on the GitHub Workflow Status badge

### ISSUE THREAD

**Issue by MGMCN** [badges/shields#9156]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

This is my rep -> [rep_url](https://github.com/MGMCN/bilibiliWordCloud)
I used ![image](https://img.shields.io/github/actions/workflow/status/MGMCN/bilibiliWordCloud/release.yml?label=build&logo=github) 
I expect this badge is successful because my latest release.yml execution was successful. -> [latest_release](https://github.com/MGMCN/bilibiliWordCloud/actions/runs/4928347673)
But this badge reads the state of my previous release. -> [previous_release](https://github.com/MGMCN/bilibiliWordCloud/actions/runs/4927515423)
![WeChat15fc46317a6d0d39f54e5c61d1f5b51f](https://github.com/badges/shields/assets/49364055/a85625ae-6577-464d-a591-bad6bdd73b6d)
I'm wondering if it's because the track_id of the repository I'm releasing twice is the same, causing badge to only read the first matched item by default each time.

### 💡 Possible Solution

Maybe there are multiple operations with the same commit_id and we should take the status of the last operation?

**Comment by MGMCN** [comment]
Maybe the problem happens in this file. -> Im not sure...  
https://github.com/badges/shields/blob/c773563e60e8df3edf23984a176f8db2fdb6932e/core/base-service/base-svg-scraping.js#L36
Maybe when there is more than one match, we should return the latest?
~~~ts
 static valueFromSvgBadge(svg, valueMatcher = defaultValueMatcher) {
    if (typeof svg !== 'string') {
      throw new TypeError('Parameter should be a string')
    }
    const stripped = svg.replace(leadingWhitespace, '')
    const match = valueMatcher.exec(stripped)
    if (match) {
      return match[1]
    } else {
      throw new InvalidResponse({
        prettyMessage: 'unparseable svg response',
        underlyingError: Error(`Can't get value from SVG:\n${svg}`),
      })
    }
  }
~~~

**Comment by chris48s** [comment]
Our GH actions badge is basically a "scraper" for GitHub's native one. It presents the same information but allows you to customise it with the standard shields formatting options.

If I call https://github.com/MGMCN/bilibiliWordCloud/actions/workflows/release.yml/badge.svg it also shows failing, so that is what we report. The logic behind it is a bit opaque tbh·

Looking at https://github.com/MGMCN/bilibiliWordCloud/actions/workflows/release.yml this is surprising to me too.
I suspect it is probably preferring this build https://github.com/MGMCN/bilibiliWordCloud/actions/workflows/release.yml?query=branch%3Amain to any of the other builds because it is associated with the `main` branch, but I am not sure how you would work around that now. It might be worth contacting github support if you think the result of https://github.com/MGMCN/bilibiliWordCloud/actions/workflows/release.yml/badge.svg is incorrect for your repo.

**Comment by MGMCN** [comment]
Ok, I see, that means you just crawl the GH native badge and display it. 
The main problem is probably with GH's native badge.svg.
Thank you for your reply, I will contact the github staff.
