### ISSUE TITLE
CTAN license badge is broken

### ISSUE THREAD

**Issue by paternal** [badges/shields#921]
URL `https://img.shields.io/ctan/l/tex.png` produces this: ![tex](https://cloud.githubusercontent.com/assets/6587757/24522355/98e6b4fc-158f-11e7-8c04-407136e66a3c.png)

I think the problem is from [ctan](ctan.org). Their API might have changed since you wrote the code for this badge, and it no longer contains copyright information. For instance (stripped to the interesting bit):

~~~sh
$ curl http://www.ctan.org/json/pkg/tex | python -m json.tool
{
    ...
    "copyright": [],
    ...
}
~~~

**Comment by paulmelnikow** [comment]
Hi, thanks for reporting this issue.

The problem seems to be specific to the tex package:

http://ctan.org/json/pkg/novel <-- has `license`
http://ctan.org/json/pkg/libertine <-- has `license`
http://ctan.org/json/pkg/tex <-- empty `license`

I see http://ctan.org/pkg/tex lists the Knuth License. A custom license, I suppose.

Would you like to reach out to CTAN about it?

I don't like 'undefined' showing up on a badge, so I opened #922 to improve the CTAN error handling.

**Comment by paternal** [comment]
> Would you like to reach out to CTAN about it?

Sorry, I cannot do this (I have a baby at home, and I barely have enough time to do the chores; unfortunately, reporting a few issue here and there is the only way I can contribute to free software these days).

-- Louis
