### ISSUE TITLE
ToDo list completion

### ISSUE THREAD

**Issue by studentenherz** [badges/shields#9217]
### 📋 Description

I'd like a dynamic badge that gets the percentage of TODO items completed from a public repo. Initially from a TODO.md file should be ok:

![TODO | 20%](https://img.shields.io/badge/TODO-20%25-blue)

### 🔗 Data

The data can be obtained from the repo if it's public.

### 🎤 Motivation

This badge could serve the same purpose as the milestones and tasklist in Github issues within the repository. It could be used in the repository in case or in other places to show the completion status of various repos.

**Comment by calebcartwright** [comment]
Thank you for reaching out and sharing your idea. I can certainly understand the motivation, but I'm a little skeptical about the practicality of it due to the nature of the data source.

I've not seen any TODO.md files in my experiences, is that a common paradigm in yours, and do you know if there's any associated specification?

Specifically, I'm concerned about the arbitrary nature of markdown the aspects of attempting to parse and extract data from something that's so open ended

**Comment by studentenherz** [comment]
@calebcartwright, yeah, I don't think there is a standard specification not even TODO.md files are a common thing.

**Comment by calebcartwright** [comment]
Thanks for confirming. I'm going to go ahead and close then because this won't be actionable for us in the absence of any form of standardization (we can't support fetching arbitrary markdown files and trying to apply a non-deterministic extraction/parsing process)

You could probably still use some other things we offer though in your particular context, where you'd handle the portion of grabbing and extracting from your markdown file, and then use us to create a badge with the data.

For example, using our [Custom Endpoint badge](https://shields.io/endpoint/) or even the [badge-maker](https://github.com/badges/shields/tree/master/badge-maker#badge-maker) package.

If you do get something working and think it could be beneficial for others, feel free to post a follow up comment with results

**Comment by chris48s** [comment]
> this won't be actionable for us in the absence of any form of standardization

This was kind of my original reaction when I first read this issue, but if someone wanted to contribute a slightly more general "markdown tasks" badge route which can accept the URL to some markdown document as a param (not necessarily hard-coded to TODO.md or with any expected format beyond "parseable as a markdown document") that counts the number of

- [x] completed tasks

and

- [ ] incomplete tasks

in the document and shows completed as a percentage of all tasks, I think that would be reasonable and probably fulfil this use-case and maybe some others.

At the moment we only have base classes for JSON, Yaml, XML, etc so it would require a bit more of a lift to add a markdown parser, but I don't think its completely invalid tbh. Do you see any issues with that I am not thinking of?

**Comment by calebcartwright** [comment]
> At the moment we only have base classes for JSON, Yaml, XML, etc so it would require a bit more of a lift to add a markdown parser, but I don't think its completely invalid tbh. Do you see any issues with that I am not thinking of?

I wouldn't say issues per se, more just that it sounds like I'm a little more philosophically opposed to it based on what we know currently, and would still steer towards the Endpoint badge. Again I can understand the motivation, but I don't feel like this is a sufficiently compelling use case in its own right that justifies the drawbacks, and I'm not aware of any other markdown-related use cases off hand either (though certainly correct me if my memory is failing me).

For a scenario like this that, imo, is tantamount to "support counting the # of nodes of a given type within the parsed syntax tree of a markdown" I do feel like there'd be a significant amount of overhead in having to introduce another dependency, whether that dependency would allow us to operate at a more intermediate stage (i.e. perhaps more at the lexing stage? certainly something prior to the final html output), doing so would of course entail i/o but then introduce another cpu bound processing stage on our runtime environment and given the tendency for markdown files to be "big" would we be able to identify a reasonable limit on the size of the doc we'd fetch that would both minimize the potential attack surface and still be feasibly large for non-malicious docs, would we need to support something analogous to jsonpath/xmlpath/etc. to support specifying which list within a doc that contains multiple lists of checkboxes, etc.

Fully understand these are all questions/considerations for which we could feasibly derive a reasonable answer/approach. I just don't think the overhead of such work and the potential (dare I say some likely) drawbacks are justified right now
