### ISSUE TITLE
Docker badges rate limited by upstream service

### ISSUE THREAD

**Issue by kroese** [badges/shields#9342]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

All docker shields show:

"Rate limited by upstream service"

at the moment.

**Comment by chris48s** [comment]
This is new.

DockerHub are not super explicit about their rate limits. From https://docs.docker.com/docker-hub/download-rate-limit/#other-limits :

> Docker Hub also has an overall rate limit to protect the application and infrastructure. This limit applies to all requests to Hub properties including web pages, APIs, image pulls. The limit is applied per-IP, and while the limit changes over time depending on load and other factors, it’s in the order of thousands of requests per minute. The overall rate limit applies to all users equally regardless of account level.
> 
> You can differentiate between these limits by looking at the error code. The “overall limit” returns a simple `429 Too Many Requests` response. The pull limit returns a longer error message that includes a link to this page.

Clearly we are hitting their limit. Also there is not much we can do to increase out rate limit. For example, we can't get a higher rate limit by authenticating with a token.

I've opened PR https://github.com/badges/shields/pull/9343 to see if we can solve this by cacheing badges for longer to reduce our usage

**Comment by chris48s** [comment]
Since deploying https://github.com/badges/shields/pull/9343 earlier today, docker badges seem to be rendering again. I'm going to close this but if we start seeing problem again (we usually see higher traffic on weekdays than we do at the weekends), re-open the issue.

**Comment by chris48s** [comment]
I'm seeing working badges at the moment, but lets continue to monitor this

**Comment by chris48s** [comment]
"a couple of hours ago" from that post was before we merged/deployed https://github.com/badges/shields/pull/9350 Since we deployed that, every time I have checked a docker badge it has been working. Are you still seeing failures over the last few days?

**Comment by goose-ws** [comment]
Sorry to comment on a closed topic, but I'm still seeing rate limited messages, I'm not so sure it's solved

**Comment by chris48s** [comment]
One thing this has inspired me to do is look and see if there are `x-ratelimit-` headers on the responses from the DockerHub API. There are. Previously I had only looked at https://docs.docker.com/docker-hub/download-rate-limit/#other-limits

Right now we seem to be getting a limit of 180 reqs/minute.

I'm going to keep an eye on whether that number seems to be static or not. If the `x-ratelimit-limit` is moving over time (as https://docs.docker.com/docker-hub/download-rate-limit/#other-limits implies) then it is going to be really hard for us to stay under it. If it seems to be stable, then I've at least got a better idea of what number we're aiming for now.


> Yes instead of having a static variable in the code it would be better if it detected this rate limit message, and dynamicly increased/decreased the polling based on that. Because currently it does not slow down as soon as it hits the limit.

So first off: We aren't "polling" anything, and the thing we are cacheing is the badge response we serve, rather than the API response from DockerHub. We make requests to the DockerHub API on demand  (i.e: if you request https://img.shields.io/docker/pulls/_/ubuntu we'll try to serve the badge from cache. If it is not cached or expired, we'll call https://hub.docker.com/v2/repositories/library/ubuntu to generate a new one). We set the max-age on the badge at the point we serve that response, so once that max-age is set, that's it. The response has been served and we've told downstream how long to keep it. We can't retrospectively change it.

What you're saying does seem kind of reasonable on the face of it: Crank the value up as the rate limit goes down, but looking at docker's rate limits, the window for rate limiting is 1 minute. We're already cacheing badges for 2 hours as a baseline so if we start increasing that, its not going to stop us hitting the limit inside this minute. If we get another request for the same badge inside this minute, we're already definitely not going to make a second API call anyway. It might reduce the number of requests we're doing in a few hours time, but not now. As such, there is no mileage in increasing the max-age on the badge in response to the `x-ratelimit-remaining` header from the DockerHub API request. Our starting point would have to be setting a max-age of well under a minute for that approach to have any chance of making any difference.

Another thing to note is: Cache can only ever take us so far. We can cache popular badges, but fundamentally lets say we've got a rate limit of 100 requests per minute. If we get 101 requests in a minute for docker pulls badges and they're all for the same docker image we can make 1 request and then serve the other 100 from cache. If we get 101 requests in a minute for docker pulls badges and they're all for different images, we need to make 101 API calls. There is no way round it. We can cache those badges for a minute or a year, but fundamentally we still had to make those requests upstream at the point they came in to us.

**Comment by chris48s** [comment]
I Made another discovery.

This is not documented in either https://docs.docker.com/docker-hub/download-rate-limit/#other-limits or https://docs.docker.com/docker-hub/api/latest/#tag/rate-limiting but anecdotally, if I call the docker registry API with an auth token, `x-ratelimit-remaining` tells me I have a higher rate limit: It goes up to 600 reqs/minute.

So that's the good news.
The bad news is it isn't a completely straightforward auth (at least none of our existing [auth helpers](https://github.com/badges/shields/blob/83c22ccd5548843fa08b02db0c5c9077674ac4f8/core/base-service/auth-helper.js) cover it).

Its an OAuth dance, so we call https://hub.docker.com/v2/users/login/ with a username and either password or PAT first. Then that returns a time-limited (but fairly long-lived) JWT we can pass in a Bearer header for subsequent requests. That's a bit of a pain for us given we strive for stateless, but I think this does give us a path forward to obtaining a higher rate limit.

I've deployed another change increasing the max-age in the short term, but longer term I think implementing auth is the way forward. Docker is a popular/high traffic service. Even if the latest PR gets us under 180 reqs/minute in the short term, it won't last.

**Comment by chris48s** [comment]
quick snippet of how to do the auth with cURL

```
$ JWT=$(curl -s -d "username=<username>&password=<pat>" https://hub.docker.com/v2/users/login/ | jq -r .token)
$ curl --include "https://hub.docker.com/v2/repositories/library/ubuntu" -H "Authorization: Bearer ${JWT}"
```

You can make a PAT with public repo scope only. We should make one on an account that is completely separate from the credentials we use for pushing https://hub.docker.com/r/shieldsio/shields/ to DockerHub though.

![Screenshot at 2023-07-12 21-19-17](https://github.com/badges/shields/assets/6025893/9d854d6b-a1a6-453a-9913-5bdecc5ae7ed)

**Comment by chris48s** [comment]
I've made a start on a JWT auth helper to support this
