### ISSUE TITLE
automation to help with bug reports

### ISSUE THREAD

**Issue by chris48s** [badges/shields#9351]
:clipboard: **Description**

Usually if someone files a bug report, the first thing I do is use `npm run badge` locally to get some additional information.

It would be nice if we had a GitHub actions workflow that fires when a new issue is opened and does the following:

If the user filled in the "bug report" template **AND** filled in "shields.io" in the "Are you experiencing an issue with..." field **AND** filled in a URL in the "Link to the badge" field then...

- Extract the value from "Link to the badge" to `$URL`
- Spin up an environment
- Run `npm run badge $URL`
- Capture the output and post it as an issue comment in a code fence (make it clear this was posted by a bot)

It might be that we need to tweak the issue template yaml a bit to make this easier?

**Comment by calebcartwright** [comment]
That sounds like a non-trivial thing to do, but it would be _awesome_

**Comment by jNullj** [comment]
seems easy, assign me if you want, i can get it done.

**Comment by jNullj** [comment]
I am working on this and i got a question regarding the issue bug template.
The template adds the question label to new bug report, why don't we just use the bug label right away? does question means it is waiting to be confirmed as a bug?

I want to github workflow to get an indication that the issue is relevant using label to avoid running on all issues:
Which of the following is preferred?
1. Create a bot specific label, when the label is added trigger the workflow, remove the label before exit - allows manual trigger
2. Trigger only on issue creation when the question label is present - avoid changes to current template - no manual trigger
3. Trigger only on issue creation with a new dedicated label - avoid binding existing label to new feature - no manual trigger

**Comment by chris48s** [comment]
Yes those issues get raised as "question" to start with. We'll label it as a bug after triage if it actually is one.

Only `1_Bug_report.yml` applies the "question" label and users who aren't repo collaborators can't label issues. I think just using the "question" label is fine.

**Comment by jNullj** [comment]
I am almost done, but i found some issue regarding the requirement to put the test output in a comment.
Some outputs might be longer then github's limit of chars per comment. For example when trying to run this `npm run badge https://img.shields.io/docker/v/xuxiaoweicomcn/gitlab-runner-helper?sort=semver&versionPrefix=x86_64`

I could link to the GH actions that run the task instead. I might be able to output it to a file and link to it/upload it to the comment.
Let me know if you know another way of presenting the output and what you prefer

**Comment by chris48s** [comment]
I had not thought about that. I reckon if the output is too long, lets just post a link to the build as a starting point (as you've suggested). We can always tweak/improve this later.

**Comment by jNullj** [comment]
Here is an example.
![image](https://github.com/badges/shields/assets/15849761/0732434b-08fb-48b0-95a9-9712d7e77e19)
I am on the road, will PR once im home
