### ISSUE TITLE
Jitpack version badge displaying "invalid response data"

### ISSUE THREAD

**Issue by CoolDCB** [badges/shields#9366]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I am trying to get the following jitpack version badge for my jitpack build but am getting a grey badge displaying "invalid response data", I have not had this issue previously with other repos on jitpack so am a little confused why this one is buggy

### 🔗 Link to the badge

https://img.shields.io/jitpack/version/com.github.cooldcb/GardeningTweaks

**Comment by chris48s** [comment]
The API request we make for the JitPack badge is the latest successful build endpoint: https://docs.jitpack.io/api/#latest-build

For your package, https://jitpack.io/api/builds/com.github.cooldcb/GardeningTweaks/latestOk returns an `200 OK` with an empty object (which is why it is failing validation).

If I try another package, this works as expected
https://jitpack.io/api/builds/com.github.jitpack/maven-simple/latestOk

I'm not really that familiar with JitPack. Any ideas why we get this response? Maybe your project exists, but doesn't have any successful builds? If this is unexpected, this might be an issue with the upstream API.

**Comment by CoolDCB** [comment]
Ahh I see what you mean, I'll go ahead and make an issue in jitpack's github, one thing that might be relevant is that I deleted and reran the build a couple times under the same release name, I wonder if this affects it at all

**Comment by CoolDCB** [comment]
Issue has been resolved on jitpack's side, no further information was given unfortunately
