### ISSUE TITLE
Lemmy service badge

### ISSUE THREAD

**Issue by FireMasterK** [badges/shields#9367]
### 📋 Description

Lemmy - A link aggregator for the fediverse.

For a community, it may be helpful to show the number of subscribers, active users in a particular timeframe, etc.

Example: https://img.shields.io/badge/community-123%20subscribers-4c1

### 🔗 Data

Yes, the API docs are public at: https://join-lemmy.org/docs/contributors/04-api.html and https://join-lemmy.org/api/

For example, to get the subscribers count for `!piped@feddit.rocks`:
A request is made to https://feddit.rocks/api/v3/community?name=piped
The subscriber count can be gotten using this JSON path: `community_view.counts.subscribers`

### 🎤 Motivation

Lemmy is a good alternative to Reddit, built with the Fediverse in mind.

**Comment by chris48s** [comment]
As a point of clarification for anyone that wants to work on this: Lemmy is a federated rather than centralised service, so the instance URL we are querying will have to be a param to the badge.

From our perspective, it will look something like self-hosted JIRA or SonarCloud where there are lots of instances out there all implementing a common API interface but each instance is hosted on different infra with different config.
