### ISSUE TITLE
Add Freecharge company Badge

### ISSUE THREAD

**Issue by thisismemukul** [badges/shields#9371]
### 📋 Description

Freecharge is an Indian financial services company based in Gurgaon. It allows users to pay bills such as electricity, gas and telephone, as well as recharge mobile, broadband, DTH and metro cards. In addition, it enables the users to invest in mutual funds and get credit through Freecharge EMI
https://www.freecharge.in/

### 🔗 Data

https://www.freecharge.in/

### 🎤 Motivation

we can add freecharge badge to our github profile

**Comment by chris48s** [comment]
I'm going to close this because:

- Shields.io hosts integrations for services which are primarily used by developers or which are widely used by developers (see https://github.com/badges/shields/blob/master/CONTRIBUTING.md#badge-guidelines ). This service doesn't seem like it fits that profile.
- This issue doesn't include any indication of what dynamic data (e.g: a statistic or a metric) the badge would show. Although you've linked to a website, there is no information about a public API here.

If you just want a badge showing static text, it is already possible to make these https://github.com/badges/shields/blob/master/doc/static-badges.md
