### ISSUE TITLE
Adding a Bazel logo

### ISSUE THREAD

**Issue by sgammon** [badges/shields#9475]
Filing so there is a place to follow the discussion.

From #9474:

> To any future readers interested in the logo, at this point more discussion is needed but the door is still potentially open.

<hr />
<hr />

> > Could you please contribute the logo upstream?
> 
> @calebcartwright how is this not a no?

Because it doesn't say "no". If we were giving you a firm "no", we would've said so and closed the PR ourselves.

Again, in the context of P-Y's comment, it was not yet clear you'd already considered the SI route. This was a "hey let's start here" because that's our process.

> I really don't see what is "flippant" about my commentary. I don't know why you would ask for my commentary if you don't want it.

I'd say it's generally in bad taste to do things like informing a project maintainer that they are allowed to comment in the project they maintain and that they can open an issue themselves. Furthermore, phrases that start with the various variants of "respectfully", "with all do respect", "no offense", etc. are typically anything but, especially in digital communication forums between strangers.

Overall I feel there's a marked difference in the tone and choice of words between your comments on this thread and those of the maintainers, but I'm sure we have different perceptions on that front.

I followed up because I got the impression that you'd taken some level of umbrage at P-Y's comment, likely based on an incorrect interpretation of that comment, and that you in turn closed the PR prematurely.

I still feel that way, but we're all busy and I think it'd be futile to keep going back and forth here.

_Originally posted by @calebcartwright in https://github.com/badges/shields/issues/9474#issuecomment-1678255133_

**Comment by sgammon** [comment]
I'm really not trying to be disrespectful, @calebcartwright. I think you are misinterpreting my comments. I normally include prefixes like "_respectfully_" when I am trying to show that I am making an attempt to be respectful while confronting a topic of discussion; I don't know why these comments are being taken the way they are.

Closing the PR was my choice because I felt the comment from the maintainer meant that it should be contributed upstream. That's what the comment said.

Since you have left the door open to an issue, I've filed one here so I can track any future work toward a Bazel logo. I hope that's alright.

**Comment by sgammon** [comment]
(I'd just like to point out that you suggested multiple times in that thread that I file an issue, and that you asked me to clarify and I did. I don't know how to signal any harder that I am making every attempt to follow the rules. If this thread gets locked, I'm happy to give up, but I really will not know why.)

**Comment by calebcartwright** [comment]
No worries @sgammon it's all good and there's no hard feelings.

I locked the closed PR thread because the conversation had long since strayed from anything technical relative to what was being proposed or the specifics of the proposal.

You can send me a message on Discord (server info is on the project homepage) if there's anything else you'd like to say or discuss relative to PR comments, but I'm going to close this issue because I don't think a project's issue tracker/PR review process is a good place for such discourse.

> I'd just like to point out that you suggested multiple times in that thread that I file an issue

To be clear, I mentioned the potential for two separate issues:

* A new badge request for a version badge from Bazel Central Registry (https://github.com/badges/shields/issues/new?assignees=&labels=service-badge&projects=&template=3_Badge_request.yml)
* An issue to discuss the merits of potentially adding a bazel logo (and the reason for this was because the original PR had been closed and overloaded with text/content unrelated to that topic which made that PR a suboptimal location for that discussion on merits).

I've opened #9476 as I think internally we need to discuss strategy around if/when we might be willing to accept a new logo in general. It's up to you whether to create a new issue for either/both the two bazel-specific topics I've been referencing, as I won't be personally pushing for either myself.

If you do decide to create a new issue to track/discuss whether we should add the bazel logo specifically, I'd encourage keeping it framed around the "why" (e.g. specifically why SI and the custom logo feature aren't viable) and probably across some of the dimensions I noted in #9476 to make a more compelling case.

**Comment by sgammon** [comment]
@calebcartwright 

my intent was to create this issue under this potential you laid out:

> An issue to discuss the merits of potentially adding a bazel logo (and the reason for this was because the original PR had been closed and overloaded with text/content unrelated to that topic which made that PR a suboptimal location for that discussion on merits).

but i see you have closed this issue as well. frankly i am too confused to continue. good luck

**Comment by calebcartwright** [comment]
> my intent was to create this issue under this potential you laid out:

Well, I'd note that this issue hasn't achieved that in any shape or form. 

The whole point was to have a separate, clean discussion about the logo itself and making a case for why it should be added as opposed to continued commentary about comments. That hasn't happened yet, and this issue was a bad place for that from the outset given that you started it with a quote from a closed and locked discussion so that you could respond to that locked discussion.

You decided to characterize all of this as "meandering discussion" in https://github.com/badges/shields/issues/9476#issuecomment-1678505343, but yet you're the one that's been perpetuating that meandering even though I've been gently nudging you to stop and shift back to discussing the actual issue at hand.

Again, if you've got anything else you want to say to me on the "meandering" front you're welcome to message me in Discord and I'll respond when I can, but let's please stop this in our issue tracker as I don't intend to respond to this subject any more.

If you want to make the case for a bazel logo then please do so in a new issue starting from a clean slate leaving everything else behind.

**Comment by sgammon** [comment]
@calebcartwright

> Well, I'd note that this issue hasn't achieved that in any shape or form.

Okay. I'm sorry you feel that way.

> The whole point was to have a separate, clean discussion about the logo itself and making a case for why it should be added as opposed to continued commentary about comments

**That is this issue.** If you need me to file another because you are embarrassed about what you wrote, I will. I included my discussion points in the original PR, but you locked that so I can't comment there now. If you would like to respond to the idea that Bazel deserves a logo in Shields, why don't you do so here?

> You decided to characterize all of this as "meandering discussion"

You asked for my opinion and I gave it. It is meandering discussion which doesn't advance a Bazel logo on Shields.

> yet you're the one that's been perpetuating that meandering

You have written back to me, tagged me, and asked me several questions. I am not tagging you, I am not demanding that _you_ respond to these. It is merely an issue on a repo, man. You do have the option of leaving me alone at any time.

**There are other contributors and maintainers on this project.** If you write to me, I will respond, because you are a maintainer and I respect your role on this project.

> Again, if you've got anything else you want to say to me on the "meandering" front you're welcome to message me in Discord and I'll respond when I can

Thank you, but you've already made this offer. I have no interest in talking to you on Discord. I don't know why you are under the impression that I would _want_ to go chat with you on Discord after you've acted this way toward me. I _do_ have an interest in seeing a Bazel logo merged to Shields, because I am publishing packages to BCR.

> The path forward for potentially including a bazel logo is to have a fresh, structured conversation where folks can share why they think it should, or should not be added, and having a place to do so where they won't have to read through walls of unrelated text.

Thanks. Let me do so now. From my PR:

[Bazel](https://bazel.build/) is a popular open source build system by Google. It has some [pretty compelling adoption](https://bazel.build/community/users).

<details>
<summary>On the adoption page</summary>

- Adobe
- Asana
- Braintree
- Canva
- Databricks
- Dataform
- Dropbox
- Etsy
- Flexport
- Google
- Huawei
- Line
- LinkedIn
- Lucid
- Lyft
- Meetup
- Nvidia
- Pinterest
- Redfin
- Snap
- Spotify
- Stripe
- Tinder
- Twitter
- Two Sigma
- Uber
- VMware
- Wix
</details>

<details>
<summary>Open Source adoption</summary>

- Abseil
- Angular
- Dagger
- Envoy
- gRPC
- gVisor
- Jsonnet
- Kubernetes
- Selenium
</details>

I find the above companies and adopters of Bazel to be very compelling. There are multiple cases of two intensely competitive companies -- Uber and Lyft, for example -- adopting the same technology. This, to me, as a technologist who _does not work at either company_, signals that Bazel meets the standard proposed by Shields for inclusion in their logo set, specifically under this basis:

> In some cases we may also accept logo submissions directly. In general, we do this only when:
> We have a corresponding badge on the homepage, (e.g. the Eclipse logo because we support service badges for the Eclipse Marketplace). **We may also approve logos for other tools widely used by developers.**
> The logo provided in SimpleIcons is unclear when displayed at small size on a badge.

_(Emphasis mine)_

As I felt the badge met those requirements, I included in my PR a link to Bazel's adoption page. Personally, I would also say that the logo would be hard to recognize if contributed to SimpleIcons. This is because of the shape and layout of Bazel's logo, and their use of different shades of one color.

**Comment by sgammon** [comment]
There are other maintainers on this project. There are other contributors on this project. **I do not see any reason for you to keep following me around on this issue.**

Literally, it's just a Bazel badge. The issue is here to track when it is added or a decision is made not to add it. You or other maintainers can communicate this to me simply by closing the issue; there is no reason to tell me I'm a bad open source contributor etc etc.

I thanked you and the other devs on this project in my previous PR and issue, and I'll do so again. I really appreciate your hard work. I would simply ask that you write clear and simple contribution guidelines and then enforce them; I can't tell what's in your head ("I wish we didn't support these stupid custom logos") and so it should be written down.

I don't even necessarily disagree with you, for the record, I just wish the maintainers saw fit to enforce the contribution guidelines fairly on my PR.

**Comment by calebcartwright** [comment]
I'm not sure if I'm not clearly communicating the ask, but I've locked this as issue as well because the back and forth in the issue tracker has to stop.

This doesn't have anything to do with anyone feeling "embarrassed" about anything that's been said (all prior discussion is linked and no comments have been hidden). It's about having a structured and streamlined conversation about if/why/when a logo should be added that's separate from unrelated back and forth interpersonal noise (which is the entirety of this issue and the majority of your original PR)

This is simply to support a more streamlined and structured conversation because it's easier for anyone to participate and easier for everyone to read when they don't have to parse through walls of unrelated text.
