### ISSUE TITLE
The Testspace Test Results Badges is inaccessible

### ISSUE THREAD

**Issue by henry-hub** [badges/shields#9515]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The Testspace Test Results Badges is inaccessible

### 🔗 Link to the badge

https://img.shields.io/testspace/tests/swellaby/swellaby/main
![Testspace tests with custom labels](https://img.shields.io/testspace/tests/swellaby/swellaby/main)

**Comment by jNullj** [comment]
Hello @henry-hub and thank you for using shields and taking the time to open an issue.

While looking at the shield link you provided I noticed you might be missing the `metric` path parameter, as this is a required parameter this might be the cause of your issue.

Please take a look at the docs for this [shield here](https://shields.io/badges/testspace-tests)
Notice how the url format is `https://img.shields.io/testspace/:metric/:org/:project/:space` where metric should be one of the following: `[total, passed, failed, skipped, errored, untested]`

The log posted by the github actions bot also shows that:
```
 Response status code  🎯 
 404
 Handled error  🙅 
 NotFound: Not Found: org, project, or space not found
```

I also think that the project you specified, swellaby does not exist in the swellaby space. Please pick a project that exists at https://swellaby.testspace.com/ like: `swellaby:testspace-sample`, `swellaby:rusty-hook`, `swellaby:nyc-config` or `swellaby:dotfiles`

I will note that while testing this shield with the default example it worked for me in my local build but did not work on shields.io, So this might be related to an issue with the main deployment or the connection from it to testspace.com.
@chris48s Who can debug the shields.io deployment?

**Comment by henry-hub** [comment]
> Hello @henry-hub and thank you for using shields and taking the time to open an issue.
> 
> I think that the project you specified, swellaby does not exist in the swellaby space. Please pick a project that exists at https://swellaby.testspace.com/ like: , , or `swellaby:testspace-sample``swellaby:rusty-hook``swellaby:nyc-config``swellaby:dotfiles`
> 
> The log posted by the github actions bot also shows that:
> 
> ```
>  Response status code  🎯 
>  404
>  Handled error  🙅 
>  NotFound: Not Found: org, project, or space not found
> ```
> 
> I will note that while testing this shield with the default example it worked for me in my local build but did not work on shields.io, So this might be related to an issue with the main deployment or the connection from it to testspace.com. @chris48s Who can debug the shields.io deployment? Also the github workflow gets the correct response while the shields.io deployment gets inaccessible which does not seems to be right.

Thank you very much for your reply, sorry I used the wrong project, but I still have this problem when I use the existing project, like: `https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main` 
![Testspace tests with custom labels](https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main)
It is normal for me to try locally, is it possible that testspace.com restricts the use of the shields.io.

**Comment by jNullj** [comment]
I am not sure as this is my first time attempting to solve an issue that might be related to the shields.io operation, I suggest we wait for someone on the team with the expiriance and access to the shields.io host.
I marked the issue with what i belive is the correct label and i already pinged one of the team members that might be able to help us solve this.

**Comment by henry-hub** [comment]
thanks

**Comment by Aldaviva** [comment]
I have also been seeing this same issue recently, with previously-working badge URLs.

I think the issue is Testspace's API server refusing IPv6 connections.

When I ran the `badge-cli.js` script with the valid sample badge URL `https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main`, the result in an `ECONNREFUSED` error.
```text
% npm run badge "https://img.shields.io/testspace/tests/swellaby/swellaby%3Atestspace-sample/main"
 Request  🏹
 https://swellaby.testspace.com/api/projects/swellaby%3Atestspace-sample/spaces/main/results
{
  "headers": {
    "Accept": "application/json"
  }
}
 Handled error  🙅
 RequestError: connect ECONNREFUSED 2600:1f14:569:e000:d60:2c6a:8d0c:9502:443
    at ClientRequest.<anonymous> (file:///home/ben/projects/shields/node_modules/got/dist/source/core/index.js:792:107)
    at Object.onceWrapper (node:events:629:26)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16) {
  prettyMessage: 'inaccessible',
  cacheSeconds: undefined,
  response: undefined
}
```

On the same computer, I get a 200 response for this request using curl, but it needs to fall back from IPv6 to IPv4 to succeed.
```text
% curl -v -H "Accept: application/json" "https://swellaby.testspace.com/api/projects/swellaby%3Atestspace-sample/spaces/main/results"
*   Trying [2600:1f14:569:e000:d60:2c6a:8d0c:9502]:443...
* connect to 2600:1f14:569:e000:d60:2c6a:8d0c:9502 port 443 failed: Connection refused
*   Trying 54.202.124.205:443...
* Connected to swellaby.testspace.com (54.202.124.205) port 443 (#0)
...elided...
< HTTP/2 200
...elided...
```

If you force curl to only use IPv6 without allowing it to fall back to IPv4, you get the same connection refused error as Node.
```text
% curl -6 -H "Accept: application/json" "https://swellaby.testspace.com/api/projects/swellaby%3Atestspace-sample/spaces/main/results"
curl: (7) Failed to connect to swellaby.testspace.com port 443 after 34 ms: Couldn't connect to server
```

I have no idea if this was caused by a Testspace DNS change, a Testspace operational change, a Shields.io code change, or a Shields.io operational change.

**Comment by henry-hub** [comment]
I tried to deploy shields on my server, and I can access it normally
`https://badge.ihub.pub/testspace/tests/swellaby/swellaby:testspace-sample/main`

**Comment by Aldaviva** [comment]
This issue should be reopened because it's still broken in production:

https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main
![badge](https://img.shields.io/testspace/tests/swellaby/swellaby:testspace-sample/main)

Just because you don't have IPv6 doesn't mean it's fixed for everyone else.

**Comment by chris48s** [comment]
Yeah agreed. I can reproduce this in production and staging, but it works locally.

I haven't had a chance to confirm if it is ipv6 related or not yet. I think I'll need to spin up a review app with `TRACE_SERVICES=true` or set it on staging. Hopefully that will give me the logs to see what is happening. I'll try to get to this in the next couple of days.

**Comment by calebcartwright** [comment]
I'll add for awareness that someone from Testspace had contacted me about heavy API volume though it was due to me being the account owner of the projects/spaces they were seeing traffic from.

Based on the information that they shared it didn't seem the concerning traffic was coming from Shields (at least based on the request headers they were seeing), but it's possible they've implemented some protective mechanisms as a result.

Will share more with the Shields maintainers offline

**Comment by chris48s** [comment]
OK. I checked this on staging. I can confirm the error we have is also

```
RequestError: connect ECONNREFUSED 2600:1f14:569:e000:d60:2c6a:8d0c:9502:443
```

I don't know what the fix is off the top of my head, but I think we know the cause.

@Aldaviva - were you able to set your local env up to reproduce the issue? If so, any advice on doing so?

**Comment by Aldaviva** [comment]
I also note that `got` has a convenient [option to force the request's DNS lookup to use IPv4](https://github.com/sindresorhus/got/blob/main/documentation/2-options.md#dnslookupipversion), if you want to pass that in the `options` attribute of `_requestJson()`.

**Comment by Aldaviva** [comment]
FYI I [followed up with Testspace](https://github.com/testspace-com/support/discussions/30), and they identified and fixed the root cause. Now I am able to send HTTPS requests to Testspace domains using IPv6 only (at least in my very brief testing with curl).

I don't think anything else needs to be done with Shields.io at this point, but I just wanted to keep the folks here updated.
