### ISSUE TITLE
Branch not found for Fedora EPEL 9

### ISSUE THREAD

**Issue by avylove** [badges/shields#9589]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The following works as expected for EPEL 8

https://img.shields.io/fedora/v/python3-enlighten/epel8
![Fedora package](https://img.shields.io/fedora/v/python3-enlighten/epel8)

But this shows branch not found for EPEL 9

https://img.shields.io/fedora/v/python3-enlighten/epel9
![Fedora package](https://img.shields.io/fedora/v/python3-enlighten/epel9)

The branch is listed in [source](https://src.fedoraproject.org/rpms/python-enlighten/branches) and the package is available in the [mirror](https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/p/).

**Comment by chris48s** [comment]
We get our information for this badge from https://mdapi.fedoraproject.org/

That says we can get the list of all branches for which mdapi contains information can be found
at /branches

https://mdapi.fedoraproject.org/branches does not list `epel9`, so that probably explains that.

I don't think I can tell you any more that that though. I'd suggest opening an issue on https://github.com/fedora-infra/mdapi/

**Comment by avylove** [comment]
MDAPI seems to be a thin wrapper around other sources, so I created an issue for Fedora Infrastructure.
https://pagure.io/fedora-infrastructure/issue/11534

**Comment by avylove** [comment]
Resolved by Fedora Release Engineering
