### ISSUE TITLE
"custom badge inaccessible" but the data works

### ISSUE THREAD

**Issue by ljharb** [badges/shields#9659]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

https://img.shields.io/endpoint?url=https://github-actions-badge-u3jn4tfpocch.runkit.sh/ljharb/set-function-length says "custom badge inaccessible", but https://github-actions-badge-u3jn4tfpocch.runkit.sh/ljharb/set-function-length/main/475c87aa2f59b700aaed589d980624ec596acdcb returns JSON.

### 🔗 Link to the badge

https://img.shields.io/endpoint?url=https://github-actions-badge-u3jn4tfpocch.runkit.sh/ljharb/set-function-length

**Comment by chris48s** [comment]
When I looked at https://img.shields.io/endpoint?url=https://github-actions-badge-u3jn4tfpocch.runkit.sh/ljharb/set-function-length it showed `[github actions | passing]` so I just requested https://github-actions-badge-u3jn4tfpocch.runkit.sh/ljharb/set-function-length a bunch of times. Sometimes I got a 200 response with the body

```
{
  "schemaVersion": 1,
  "label": "github actions",
  "labelColor": "lightGrey",
  "message": "passing",
  "color": "success",
  "isError": true,
  "namedLogo": "github actions",
  "logoColor": "white",
  "style": "flat"
}
```

Sometimes I got a 500 error with the body

```
{
  "error": "socket hang up",
  "message": "ECONNRESET"
}
```

and sometimes I just never got a response.

That probably explains this. The endpoint badge caches the badge response for 5 mins, so if you hit one of those error cases once, that inaccessible badge gets cached for a bit.

I think this is an issue with either the code serving that endpoint or runkit itself.

**Comment by ljharb** [comment]
It's probably a bit of both. While I'll attempt to make it more reliable, since it's stateless, is there any way the badge response could be made to only cache successful responses?

**Comment by chris48s** [comment]
This concept of only caching "good" responses is something we have thought about before. It is not a completely outrageous idea, and it does make sense if you expect a small number of transient errors that resolve quickly.

The problem is, if you start getting errors that persist for long periods of time then that approach can become very problematic. If a popular service goes offline or has a major outage (which does happen), then we would suddenly and unexpectedly start processing a lot of traffic to serve the same error badges over and over, with every request hitting our origin rather than the cache.

Shields can only really operate at the scale we do on the budget we have because most of our traffic is served from downstream caches, rather than our own infrastructure.

That's why we set the same max age on the error badges that we do on the valid ones.

**Comment by ljharb** [comment]
@chris48s so you don't have any other suggestion for me? Perhaps the cache for "bad" responses could be drastically shorter than the cache for good ones?
