### ISSUE TITLE
[REQUEST] added badges style of the M3

### ISSUE THREAD

**Issue by whyakari** [badges/shields#9765]
:clipboard: **Description**

Hello, would be able to implement badges like M3 (Material You - Monet) in website? 
 - reference https://github.com/ziadOUA/m3-Markdown-Badges

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close because this isn't something we'll do.

Our badges are based on our [specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) and while we have added a couple other styles, we've also removed some and taken the position that we aren't going to add more.

It seems like this would be a reasonable thing to include on our [Awesome Badges](https://github.com/badges/awesome-badges) list though, so feel free to open a PR adding the m3 badges to that repo if you'd like!
