### ISSUE TITLE
403 responses from camo.githubusercontent.com

### ISSUE THREAD

**Issue by equiman** [badges/shields#9892]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Badges are working again in **GitHub** README files, but responses a 403 error on **npm** README.

GitHub - https://github.com/deinsoftware/swpm:
![image](https://github.com/badges/shields/assets/933393/822b8eac-7b11-41e9-bf84-3372f27334e9)

NPM - https://www.npmjs.com/package/swpm:
![image](https://github.com/badges/shields/assets/933393/43676f2c-8568-40c7-b63c-6998d8aa97fd)

### 🔗 Link to the badge

markdown badge on readme
```markdown
[![npm-version](https://img.shields.io/npm/v/swpm.svg?color=blue)](https://www.npmjs.com/package/swpm)
```

npm html element
```html
<a href="https://www.npmjs.com/package/swpm" rel="nofollow"><img src="https://camo.githubusercontent.com/2994fea994fae39fc744de21121c0af7249c97bfe4480afe6ada05b2de002326/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f7377706d2e7376673f636f6c6f723d626c7565" alt="npm-version" data-canonical-src="https://img.shields.io/npm/v/swpm.svg?color=blue" style="max-width: 100%;"></a>
```

**Comment by chris48s** [comment]
Hello. I'm seeing the same behaviour as you - lots of badges not showing in READMEs on NPM due to a 403 from camo.

This isn't an issue with shields though. The badges are being served fine from shields.io itself.

If you look at some projects that include images from elsewhere in their README on NPM, you'll notice that those images are broken too.

For example compare
https://www.npmjs.com/package/express?activeTab=readme
https://github.com/expressjs/express/blob/master/Readme.md
( https://i.cloudup.com/zfY6lL7eFa-3000x3000.png doesn't display on npm)

https://www.npmjs.com/package/passport?activeTab=readme
https://github.com/jaredhanson/passport/blob/master/README.md
( https://cdn.auth0.com/img/passport-banner-github.png doesn't display on npm)

You'll notice the banner images are broken for the same reason - it is a more general issue with images.

I'd suggest raising this issue with NPM or GitHub support. This camo proxy is not maintained by us.

Thanks

**Comment by chris48s** [comment]
Interestingly, the images do seem to be gradually re-appearing on NPM.

My guess is that there is a load of bad data in the cache and as the cached assets expire, the bad data is gradually being replaced with good.

**Comment by equiman** [comment]
Yes, I've checked again today and images are loading again.

![image](https://github.com/badges/shields/assets/933393/626b2e69-831c-49eb-85a0-f7b293f6c7f0)
