### ISSUE TITLE
`logoColor` param doesn't work for `git-hub-top-language`

### ISSUE THREAD

**Issue by SKY-ALIN** [badges/shields#9929]
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I tried to change color of the percentage text color for the following badge:

![GitHub top language](https://img.shields.io/github/languages/top/SKY-ALIN/space-drive-game?style=flat-square&logoColor=ffffff&color=90caf9)

Now it's black, but I'd like to change to white.

### 🔗 Link to the badge

https://img.shields.io/github/languages/top/SKY-ALIN/space-drive-game?style=flat-square&logoColor=ffffff&color=90caf9

**Comment by chris48s** [comment]
Hi. The `logoColor` param changes the colour of the logo. It is not doing anything because you are not using a logo.

So in this example:

- https://img.shields.io/github/languages/top/SKY-ALIN/space-drive-game?style=flat-square&color=90caf9&logo=rust
- https://img.shields.io/github/languages/top/SKY-ALIN/space-drive-game?style=flat-square&color=90caf9&logo=rust&logoColor=red

that param does something.

The color of the message text is non-configurable. We automatically set it based on the background to try and make the text readable.
