### ISSUE TITLE
extend github "commits since" badge --> count from latest release

### ISSUE THREAD

**Issue by tooomm** [badges/shields#993]
Right now you need to provide a fixed tag to count from.
Can we have "latest" there as well, so it automatically counts from that and resets on release?

For example: `https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/latest.svg`
instead having to updated the badge tag every time since it's hard linked:
`https://img.shields.io/github/commits-since/SubtitleEdit/subtitleedit/3.4.7.svg`

**Comment by paulmelnikow** [comment]
Neat idea! Would you like to open a pull request?

**Comment by tooomm** [comment]
I can't help with code, sry. :(

**Comment by jtmoon79** [comment]
**How do I use the _latest_ feature of the _commits since_ badge?**

Using URL `https://img.shields.io/github/commits-since/jtmoon79/goto_http_redirect_server/latest.svg` the badge did not resolve to something meaningful (only reads _no releases or repo not found_).
Things I tried:
- add tag and release `0.7.3` (this does resolve for URL `https://img.shields.io/github/commits-since/jtmoon79/goto_http_redirect_server/0.7.3.svg`)
- add tag and release `latest` that points to same commit as `0.7.3`.

Still the URL `.../latest.svg` is never useful.

[Project goto_http_redirect_server releases are here](https://github.com/jtmoon79/goto_http_redirect_server/releases).

**Comment by tooomm** [comment]
I think you have only tags in your repo, no releases @jtmoon79

**Comment by jtmoon79** [comment]
Thanks for the reply @tooomm .

> I think you have only tags in your repo, no releases

The project releases page counts 2 releases https://github.com/jtmoon79/goto_http_redirect_server/releases 🤔

**Comment by tooomm** [comment]
I can just tell that it works for me, but the release pages in the repo looks different: https://github.com/Cockatrice/Cockatrice/releases

--> ![](https://img.shields.io/github/commits-since/Cockatrice/Cockatrice/latest.svg)
`![](https://img.shields.io/github/commits-since/Cockatrice/Cockatrice/latest.svg)`

**Comment by jtmoon79** [comment]
> I can just tell that it works for me, but the release pages in the repo looks different:

Indeed!  I poked around briefly: it's a github oddity!
AFAICT, project _tags_ will also populate project _releases_ *_if there are no releases_*.  So just by adding tags, there appears to be releases.  But they are ... fake? ... releases.  They are something not quite releases.

Thanks for replying @tooomm

**Comment by calebcartwright** [comment]
I think the GitHub UX for releases is a fairly common source of confusion. I suspect this is because both tags and releases (if any exist) are listed in the default page, the "tags" tab filters down to releases-only but the "release" filters does not, not much visual distinction between the two especially for users that haven't worked with GH releases, etc.

For more info on the distinction: https://help.github.com/en/github/administering-a-repository/about-releases
